### ISSUE TITLE
en recette, la recherche de terrains d'immersion ne fonctionne pas. Liée manifestement à l'appel de l'API LBB -  géolocalisation ne semble pas fonctionner.

### ISSUE THREAD

**Issue by nathalie-reyre** [gip-inclusion/immersion-facile#1004]
_message: "Unhandled Error"
httpStatus: 401
message: "Request failed with status code 401"
method: "get"
path: "/partenaire/labonneboite/v1/company/?distance=100&longitude=2.3752&latitude=48.845&page=1&page_size=100&rome_codes=D1102&sort=distance"
request: {
  "path": "/v2/search",
  "method": "GET"
}
requestBody: "{}"
responseBody: "TypeAuth invalide ou non renseigné"
type: "Axios"
url: "https://api.peio.pe-qvr.fr/partenaire/labonneboite/v1/company/"

**Comment by nathalie-reyre** [comment]
Fonctionne avec le fix qui vient d'être fait (celui du 13/12 à 10h30)

**Comment by bbohec** [comment]
https://discord.com/channels/864451835553513474/1042365650359828480/1184880689468944414
