### ISSUE TITLE
Différences des données entre page stats et tdb inclusion connect PE

### ISSUE THREAD

**Issue by Jessicaceleste1** [gip-inclusion/immersion-facile#1012]
### :bug: Le problème
Voici la demande faite : 
![image](https://github.com/gip-inclusion/immersion-facile/assets/129732318/24804abc-4646-4382-ac53-24b4e5bab44f)

 j'ai vérifié pour mon département 77 : je suis sencée être rattachée à toutes les agences du 77 plus Bressuire d'une autre région, d'après mon tbd, il y a (modifié)
![image](https://github.com/gip-inclusion/immersion-facile/assets/129732318/28a6acbf-beab-4b70-aa80-cd3277fac672)

et d'après nos stats 

![image](https://github.com/gip-inclusion/immersion-facile/assets/129732318/9bed7d6f-476c-4d35-8646-028865bca0af)

**Comment by Jessicaceleste1** [comment]
https://discord.com/channels/864451835553513474/1042365650359828480/1184818107374653520

**Comment by Master-Touks** [comment]
Dashboard à vérifier : 
- https://metabase.immersion-facile.beta.gouv.fr/dashboard/4-tableau-de-bord-agence-embarque
- https://metabase.immersion-facile.beta.gouv.fr/dashboard/16-statistiques-immersion-facilitee
