### ISSUE TITLE
ETQ utilisateur, j'ai accès d'une part aux mesures d'impact d'IF et d'autre part à des infos macro sur les immersions conventionnées sur IF

### ISSUE THREAD

**Issue by nathalie-reyre** [gip-inclusion/immersion-facile#1015]
### :thinking: Contexte et problématique (et par qui est-ce remonté ?)

beaucoup de questions nous sont posées sur la durée moyenne d'une immersion, les publics que cela concerne, les métiers les plus sujets aux immersions. 
Nous exposons bien des données qui permettent de répondre à ces questions mais de façon peu évidente. Elles se trouvent noyées dans notre page de mesure d'impact. 
### :tada: Proposition de solution

Proposer deux pages distinctes : une consacrée à nos KPI et une consacrée aux données permettant d'éclairer sur les pratiques en matière d'immersion. 
Ces informations concernent d'une part les recherches et les mises en relation et d'autre part, les immersions conventionnées. 
Dans un premier temps, il faut réordonné ce qui est déjà proposé puis ensuite enrichir éventuellement ce qui concerne les pratiques.

**Comment by Master-Touks** [comment]
Draft Page V2: https://metabase.immersion-facile.beta.gouv.fr/dashboard/134-statistiques-immersion-facilitee-v2-draft 

Le draft ne correspond pas à la commande pour une raison : les infos doivent être splité en plusieurs tableaux.

**Comment by Master-Touks** [comment]
À faire 
- [ ] Page Impact Net
      - NPS
      - Nbre de convention signé au mois
      - Coût d'acquisition 

- [ ]  Page Business 
      - Le maximum d'info doit être filtrable par régions
      - Date mensuel par défaut
      - Les métiers conventionnés par régions
      - Terrain d'immersions (= Métier avec le plus d'offres)
      - Nbre d'immersion par bénéficiaire en moyenne (probablement à lier avec l'objectif de l'immersion)
      - Nbre de mise en relation par bénéficiaire (en moyenne, par mois ou trimestre ou année)
      - Occurences des secteurs d'activités le plus conventionné
      - Nbre de salariés
      - Garder nbre initié et validée (changer wording et expliquer par texte) [immersions conventionnées]
      - Corréler les immersions par typologie (age, objectifs, durées, …)
      - Retirer les mini stages de la page stats, faire un lien vers un dashboard ccI

**Comment by nathalie-reyre** [comment]
mes demandes d'amélioration 
**ne mettre qu'un CAC : celui d'une convention validée** (ce qui correspond à une immersion qu'on suppose réalisée)

**l'indicateur de conversion des entreprises immersives en entreprises accueillantes**, supprimer la jauge car pas très explicite et mettre à la place   le graphe qui permet de voir l'évolution dans le temps et qui indique l'objectif. Ce graphe s'appelle CVR et est perdu dans les CAC.

le graphe sur le % des conventions non validées est à repositionner avec les indicateurs sur les conventions et non avec le CAC

**Comment by Master-Touks** [comment]
Page business : https://metabase.immersion-facile.beta.gouv.fr/dashboard/148-business

Page Impact : https://metabase.immersion-facile.beta.gouv.fr/dashboard/85-indicateurs-cles-objectifs

**Comment by Master-Touks** [comment]
- [ ] Ajouter les CAC (prescripteur entreprises, entreprises accueillantes) 
- [ ]  Rétention des entreprises 
- [ ] KPI suivi sur les 6 prochains mois

Faire un point avec @nathalie-reyre et Arnaud pour les montrer nos pages et enclencher les revues tous les 2 mois.
