### ISSUE TITLE
UseCase de relance automatique de signature de convention par SMS

### ISSUE THREAD

**Issue by bbohec** [gip-inclusion/immersion-facile#102]
Tache planifiée > tous les soir

conditions d'enclanchement

statut : READY_TO_SIGN / PARTIALLY_SIGNED

QUID des conventions avec demandes de modif?

à moins de 72h ouvrés avant le démarrage de l’immersion

actions de relances possibles

72h > mail à tout le monde rappel de signature de convention

Wording specific Agence uniquement si statut IN_REVIEW

Si statut PARTIALLY_SIGNED | READY_TO_SIGN mail aux acteurs autre qu’agence

48h >- uniquement sur statut PARTIALLY_SIGNED | READY_TO_SIGN- mode SMS avec lien magique : aux personnes qui n’ont pas signé  si ils ont un portable  <Phase 2>- si un signataire qui n’a pas signé n’a pas de portable > mail à tout le monde (sauf agence) texte unique comme quoi il manque une signature et cette personne n’a pas de quoi recevoir un SMS

Alerte urgente convention en attente de revue prescripteur > uniquement 24 avant le démarrage de convention > notification agence par email <Uniquement IN_REVIEW>

stockage des actions de relance en base pour à minima analytics

Wording:

mail 72h

SMS 48h >> avec info du contact non signataire

mail 48h

**Comment by Hervelallemand974** [comment]
est-ce que l'envoi sms est différencié dans l'outbox ?
toutes les relances sont avec le topic "ConventionReminderRequired"
et Reminderkind = LastReminderForSignatories ou FirstReminderForSignatories
