### ISSUE TITLE
ETQ entreprise, sur la liste des résultats je souhaite apparaître sur une zone géographique plus étendue

### ISSUE THREAD

**Issue by cecile-dimarco** [gip-inclusion/immersion-facile#1026]
### :thinking: Contexte et problématique (et par qui est-ce remonté ?)

 les entreprises nous font remonter qu'elles souhaitent pourvoir être visible sur une couverture géographique plus large que celle dont dépend leur SIRET

https://discord.com/channels/864451835553513474/1186218671891283978

### :tada: Proposition de solution

Dupliquer plusieurs établissements avec le même SIRET sur différentes villes ou sur le formulaire proposer une choix de zone géographique ??

**Comment by nathalie-reyre** [comment]
@gip-inclusion/immersion-facilitee-dev  il faudrait étudier la faisabilité tech avant qu'on attaque le grooming. Le problème remonte de plus en plus souvent
