### ISSUE TITLE
Réduire les saisies de conventions Pôle emploi du back office - Gestion des erreurs de l'API PE

### ISSUE THREAD

**Issue by Hervelallemand974** [gip-inclusion/immersion-facile#103]
Toutes les conventions non peconnectées sont saisies par le back office

solution : utiliser l’api identité certifié de PE pour identifier le demandeur et permettre à l’api PMSMP de PE de les traiter en automatique

- [x] réunion avec api PE PMSMP
- [x] modification contrat d'interface
- [ ] tests puis mise en prod
- [x] gérer les erreurs / retours API

**Comment by Hervelallemand974** [comment]
Comment avoir accès aux conventions avec erreurs pour pouvoir les traiter manuellement ?

accès metabase par exemple

Description de la réponse

En cas d’erreur fonctionnel, le service retourne :

un code HTTP 400 en cas de requête erronée (paramètre obligatoire de type « query » absent)
un code HTTP 404 en cas d’élément non trouvé uniquement dans le cadre d’une recherche par identifiant unique

**Comment by bbohec** [comment]
réunion PE du 16/3 :
api identité certifié est requêtable avec le NIR uniquement.
une autre api qui pourrait faire le boulot n'est pas dispo en externe
l'equipe API PE va modifier le use case. IF transmet toutes les conventions (ajout de champs à voir) et l'API PMSMP PE va chercher l'individu en interne.
Reste également à voir le retour vers IF pour les individus non trouvés afin que l'équipe IF fasse la saisie.
Livraison toujours prévue pour mi-avril

**Comment by bbohec** [comment]
Reprise commentaire @nathalie-reyre  du 2/3/2023
---------------------------

côté PE, pas de dispo pour implémentation avant avril

**Comment by bbohec** [comment]
Reprise commentaire @Hervelallemand974 du 20/02/2023
-------------------------------------------

Dans le cadre de l’irritant « Information de validation à transmettre au CDE sur Objet3 », nous avons ce matin orienté la solution.
Nous allons réaliser une API dédiée (que nous exposerons via notre façade EX158 pour info) à ImFac que vous pourrez appeler, en passant par [Pe.io](http://pe.io/) ; nous vous retournerons le mail de l’agent CDE en charge du suivi de l’établissement.

1- Sauf erreur de ma part, cet appel d’API à notre EX sera réalisé après ou au moment du passage de la demande au statut « DEMANDE_A_ETUDIER» : une fois que le CDE signe (via lie lien fourni dans le mail), la demande passera au statut « DEMANDE_VALIDEE ».
2- Quel contrat d’interface prévoyez-vous ? (idem API Conseiller CDDE ?...)…parce qu’au plus simple, il nous suffirait a priori de l’identifiant de la demande pour retrouver le SIRET=>id_RCI=>Id Conseiller CDE

API Conseiller entreprise : On pourrait interroger cette API avec le SIRET lorsque la demande est soumise afin de récupérer l’adresse mail du conseiller entreprise. Ce qui nous permettrait de router les mails vers lui.
Questions métiers à rediscuter : est-ce qu’on fait ça pour l’objet 3 uniquement ? Est-ce qu’on fait quand même un mail à l’agence ? Est-ce qu’on fait quand même un mail au conseiller si DE Peconnecté ?

Contrat d’interface de l’API Conseiller Entreprise à discuter mais idem que API conseiller me semble bien

A mon avis, cela ne change pas notre contrat d’interface, car vous pouvez retrouver les infos chez vous. Il faut juste décrire les règles métiers pour les traiter chez vous (conventions saisies avec le code référent du conseiller entreprise au lieu du conseiller du DE).

Je bloque un point lundi 20 févier alors 

Sinon, pour l’api conseiller exposée par le DA157, l’id de la demande serait utile et plus simple pour nous, car le SIRET dans notre modèle de données est attachée à la demande (SIRET pouvant varier d’une demande à l’autre pour un même établissement).
Si on a l’id de la demande, on pourra récupérer plus facilement (car stockées) les infos sur l’agent à partir de notre domaine….à discuter ensemble

En attendant, si tu as le contrat d’interface de l’API conseiller qe vous utilisez pour les objets 1 et 2, je suis prenueur.

**Comment by bbohec** [comment]
Reprise commentaire @Hervelallemand974 du 13/02/2023
-----------------------

Il faudrait que vous documentiez le Contrat d’Interface avec ce nouveau champ idNationalDE chiffré dans l’espace partagé HedgeDoc (Documentation API pour diffusion des demandes de convention d’immersion - HedgeDoc ([incubateur.net](http://incubateur.net/)))

· Si vous pouvez par la même occasion modifier le statut « A_SIGNER » vers « DEMANDE_A_SIGNER » (cohérence avec les autres statuts)

**Comment by JeromeBu** [comment]
Voilà le format des erreurs que je compte enregistrer :

```json
{
        serviceName: 'PoleEmploiGateway.notifyOnConventionUpdated',
        httpStatus: 404,
        message: 'Ops, something is bad',
        params: { conventionId: 'a99eaca1-ee70-4c90-b3f4-668d492f7392' },
        occurredAt: 2023-05-19T13:44:35.701Z
 }
```
