### ISSUE TITLE
⚠️ CRAWLER en standby quand trop d'événements à gérer ⚠️

### ISSUE THREAD

**Issue by bbohec** [gip-inclusion/immersion-facile#1039]
### :bug: Le problème

Gros bug à gérer pendant les fêtes suite à l'augmentation de la quantité d'envoi de reminder.

Explication: l'augmentation des reminder fait qu'on a beaucoup d'event de notification non publiés d'un coup.
C'est l'instance crawler qui s'occupe de ses events comme d'hab.
On a donc une quantité d'event à gérer assez importante mais c'est ok vu que le crawler va les gérer 5 par 5 si mes souvenirs sont bon.

Le soucis >>> à un moment le crawler s'arrete sans broncher, pas de prod error et des logs qui semblent rien exposer de grave autre que les logs d'events / usecase / gateways classique, j'ai pas vu de log type erreur postgres ou de crash de l'instance, il n'y a juste plus de log à un moment >>> le crawler est en pause indéfiniment.

Ce qui fait qu'on a une pause dans la gestion des events de l'application complète 😔 
Le crawler se met en pause tout les ~400 events.

Pour relancer la gestion, il faut restart l'instance crawler dans scalingo et ça repart

Je recommande donc pour les congés de prioriser ce sujet et surtout en attendant sa résolution de surveiller en base la quantité d'évent non publiés du jour afin de relancer le crawler si c'est bloqué.

### :footprints: Étapes pour reproduire

Surveillez la quantité d'event non publiés du jour avec la requête suivante:
```
SELECT COUNT (*)
FROM "outbox"
WHERE status = 'never-published'
AND "occurred_at" >= '2023-12-22'
```

Si le nombre n'est pas à 0 et qu'il ne baisse pas tout seul alors il faut redémarrer le crawler de prod sur scalingo:
![image](https://github.com/gip-inclusion/immersion-facile/assets/58432308/3664fb43-87c4-4cc6-a3d9-229ee31d73d3)

### :dart: Comportement attendu

Le crawler n'a pas être en standby continu sans erreur alors qu'il reste des events jamais publiés

**Comment by bbohec** [comment]
https://discord.com/channels/864451835553513474/1042365650359828480/1187719549768966215

**Comment by celineung** [comment]
Investigation:
- Le crawler a l'air de fonctionner correctement depuis son redémarrage le 22 décembre.
- J'ai créé un script qui crée 5000 event dans la table outbox sur une review app, le crawler dépile bien tout 😕
