### ISSUE TITLE
ETQ que structure candidate pour être prescriptrice, je peux prendre connaissance de la convention de délégation de prescription dans le mail qui m'invite à compléter le quizz.

### ISSUE THREAD

**Issue by nathalie-reyre** [gip-inclusion/immersion-facile#1049]
héberger le doc de la convention de délégation de prescription sur clever cloud plutôt que sur le Drive. 
Le doc est ici : https://docs.google.com/document/d/1MyHmTqbzB52hDeg1wokZcCEe9Jrra6k_iXUTz2ts6xE/edit?usp=sharing

le mail est rédigé. Dès que le doc est hébergé sur clever cloud, me donner son url en commentaire afin que je mette à jour le template de mail qui est un template Brevo 
#88 | [Délégation] Envoi Quizz avec demande motivée

**Comment by JeromeBu** [comment]
Il faut donc un pdf qu'on pourra mettre sur clever ? car un google doc on ne peut pas. On peut mettre le pdf en question ici ?

**Comment by JeromeBu** [comment]
Voilà le PDF (qui est la version pdf du google doc mentionné ci dessous)



[CONVENTION DÉLÉGUANT LA PRESCRIPTION DE PMSMP - Google Docs - https___docs.google.com_document_d_1MyHmTqbzB52hDeg1wokZcCEe9Jrra6k_iXUTz2ts6xE_edit.pdf](https://github.com/gip-inclusion/immersion-facile/files/13840989/CONVENTION.DELEGUANT.LA.PRESCRIPTION.DE.PMSMP.-.Google.Docs.-.https___docs.google.com_document_d_1MyHmTqbzB52hDeg1wokZcCEe9Jrra6k_iXUTz2ts6xE_edit.pdf)

**Comment by nathalie-reyre** [comment]
Parfait ! je m'apprêtai  à l'inclure
