### ISSUE TITLE
ETQ candidat, je peux déclarer si je suis en situation de handicap

### ISSUE THREAD

**Issue by bbohec** [gip-inclusion/immersion-facile#105]

**Comment by nathalie-reyre** [comment]
lié au #91 + création d'un champ ad hoc (incidence en base)

**Comment by nathalie-reyre** [comment]
![Image](https://github.com/gip-inclusion/immersion-facile/assets/61510442/21414382-9a89-4233-bb4b-85fe522bff78)

**Comment by nathalie-reyre** [comment]
@clement-duport je crois que c'est toi qui voulais le faire. On en parle quand tu  veux/peux

**Comment by 3lodi3** [comment]
Je vous propose d'ajouter le champ et de déporter le texte dans l'aide pour éviter de surcharger le formulaire : https://www.figma.com/proto/O6MfTEZ1Ms8cKQHFjOYEA5/Site---UX-design?page-id=0%3A1&type=design&node-id=3-5372&viewport=1842%2C84%2C0.6&scaling=min-zoom&starting-point-node-id=3%3A5293

J'ai créé une page d'aide champ par champ que je vais compléter (https://aide.immersion-facile.beta.gouv.fr/fr/article/notice-formulaire-de-demande-dimmersion-xryn5j/), l'avantage c'est que dans crisp il y a des ancres sur chaque titre donc on peut facilement lier l'aide à un champ particulier du formulaire.
