### ISSUE TITLE
ETQ que agent PE en DR ou en DT, quand je m'inclusion connecte via la SSO PE, j'ai accès directement à un tableau de bord Région ou direction territoriale

### ISSUE THREAD

**Issue by nathalie-reyre** [gip-inclusion/immersion-facile#1065]
Nous avons désormais la liste des codes SAFIR attribués aux DT et aux DR. Nous savons également par ailleurs à quelle région ou quel département les agences sont rattachées. Il faudrait donc permettre aux agents dont le code SAFIR correspond à une DT ou une DR d'avoir directement accès au tableau de bord territorial ad hoc. 
VA : éviter d'avoir à les rattacher manuellement aux agences de leur territoire et ainsi faire gagner beaucoup de temps à celui que le fait.

**Comment by nathalie-reyre** [comment]
[DORA_DGDRDT (2).xlsx](https://github.com/gip-inclusion/immersion-facile/files/13844805/DORA_DGDRDT.2.xlsx)

fichier des codes SAFIR/DR et DT

**Comment by 3lodi3** [comment]
Voir si on peut plutôt passer par l'API agence via PE.io
KIckoff à prévoir

**Comment by 3lodi3** [comment]
Grooming mardi 30 janvier

**Comment by enguerranws** [comment]
Au final, on fait quoi sur ce sujet ? 
- soit en auto en se basant sur le début du code safir
- soit via une table de mapping DR/DT/code safir agence

**Comment by nathalie-reyre** [comment]
fichier DR/DT

[liste-DR-DT.csv](https://github.com/gip-inclusion/immersion-facile/files/14240901/liste-DR-DT.csv)

**Comment by nathalie-reyre** [comment]
[https://immersion.cellar-c2.services.clever-cloud.com/DR_DT_IF(3).numbers](url). fichier DR DT avec mails pour délégation de prescription
