### ISSUE TITLE
ETQ entreprise, j'ai accès à mon tableau de bord cf EPIC #753 : mettre en prod la fonctionnalité

### ISSUE THREAD

**Issue by nathalie-reyre** [gip-inclusion/immersion-facile#1066]
Modifier les entrées entreprises sur l'accueil et dans le menu : 
- Référencer ou modifier mon entreprise
- Remplir la demande de convention
- Piloter mon entreprise

**Comment by JeromeBu** [comment]
ca donnera ça :
<img width="1444" alt="image" src="https://github.com/gip-inclusion/immersion-facile/assets/22095555/254d8517-1625-4220-9de7-0d1e288bfceb">
