### ISSUE TITLE
Mise à jour des différents statuts disponibles en explication dans le tableau de bord

### ISSUE THREAD

**Issue by Jessicaceleste1** [gip-inclusion/immersion-facile#1073]
### :thinking: Contexte et problématique (et par qui est-ce remonté ?)

Les statuts disponibles sous les tableaux de bord pour expliquer les différents statuts ne sont pas à jour. 
De plus, ils sont toujours en anglais alors que maintenant nos filtres sont en français.

![image](https://github.com/gip-inclusion/immersion-facile/assets/129732318/a8eddc47-0034-4f2a-bb7d-88faddc5b5a1)

Annulée : Convention validée puis annulée
En brouillon ou demande de modification en cours : Demande initiée mais non envoyée ou demande en cours de modification
Obsolète : Demande abandonnée
Partiellement signée : En attente de signature du candidat ou de l'entreprise
Prête à signer : Demande envoyée en attente de toutes les signatures
Rejetée : Refuser par le prescripteur
Validée par le prescripteur : Convention validée (plus modifiable)
A validée par le conseiller : En attente de validation du conseiller

Légende en dessous du tableau de bord :)

**Comment by 3lodi3** [comment]
En fait il faudrait juste supprimer cette trad qui date de l'époque où on n'avait pas les statuts en toutes lettres dans le metabase.

**Comment by JeromeBu** [comment]
obsolète : abandonnée
