### ISSUE TITLE
Demande bouton accès direct en dernière page sur tbd

### ISSUE THREAD

**Issue by Jessicaceleste1** [gip-inclusion/immersion-facile#1074]
### :thinking: Contexte et problématique

Lorsque que l'on veut avoir accès aux données de la dernière page, il faut passer toutes les pages une par une. 

![image](https://github.com/gip-inclusion/immersion-facile/assets/129732318/6fd08c9c-949e-4056-8e6b-acc922b13479)

Avoir un bouton pour y accéder direct.

**Comment by 3lodi3** [comment]
ON n'a pas la main sur la pagination metabase, est-ce que ça peut se résoudre en filtrant les résultats plutôt ? @Jessicaceleste1
