### ISSUE TITLE
Afficher chacun des filtres possible sur le tbd

### ISSUE THREAD

**Issue by Jessicaceleste1** [gip-inclusion/immersion-facile#1077]
### :thinking: Contexte et problématique (et par qui est-ce remonté ?)

Depuis le tbd, tous les filtres des statuts de conventions sont possible uniquement si il y a des conventions dans ce cas. 

Ex : certains ne peuvent filtrer que sur 
![image](https://github.com/gip-inclusion/immersion-facile/assets/129732318/f56f8da7-7f8c-4731-89c8-b61da188fae0)

ou sur 

![image](https://github.com/gip-inclusion/immersion-facile/assets/129732318/4e405f2a-f426-46e2-a748-ed1be3a70250)

ou sur

![image](https://github.com/gip-inclusion/immersion-facile/assets/129732318/5821305f-5f80-4a7a-952e-3ae6102dc90b)

### :tada: Proposition de solution

il faudrait que tout le monde puissent tous les statuts de conventions visibles pour filtrer et qu'une donnée à zéro avec une phrase, vous n'avez pas convention "a valider par le conseiller" par ex
![image](https://github.com/gip-inclusion/immersion-facile/assets/129732318/8c9044ed-84d8-49cd-915a-144f6577ceb5)

**Comment by 3lodi3** [comment]
Dans quel but @Jessicaceleste1 ? Dans tous les cas on n'a pas la main sur le fonctionnement des filtres metabase

**Comment by Jessicaceleste1** [comment]
irritant ne remonte pas assez souvent et de toute façon nous n'avons pas la main sur les filtres
