### ISSUE TITLE
🚀 ETQ IF, je souhaite rapatrier l'expé no code : relance des mer restées sans réponse.R:1750 I:3 C:1 =5250

### ISSUE THREAD

**Issue by 3lodi3** [gip-inclusion/immersion-facile#1079]
### :thinking: Contexte et problématique (et par qui est-ce remonté ?)

cf epic #968 

#### Analyse XP no code existante

- 2 workflows N8N de fonctionnement identique (un pour relance à 3j, un pour relance à 7j)
  - Activation par tâche planifiée tout les jours ou tout les 2j
  - Récupération des discussions sans réponses depuis questions publiques Metabase:
    - https://metabase.immersion-facile.beta.gouv.fr/question/1210-mer-non-repondues-depuis-3-jours
    - https://metabase.immersion-facile.beta.gouv.fr/question/1239-mer-non-repondues-depuis-7-jours
  - Mise forme interne N8N pour la suite
  - Récupération des id de discussion ayant une relance désactivée dans une base airtable sur compte Pierre
  - Retrait des ID désactivés
  - Préparation en plus des infos de contact d'une URL qui permet d'ajouter la discussion dans la table Airtable de relance désactivée
  - Dépot FTP Pierre temporaire
  - Appel API Brevo pour ajout des contacts dans la liste (99 ou 101 en fonction du workflow)
- Automatisation Brevo
  - 2 listes de contact
  - 2 templates de mail
  - 2 automatisations à processus identique
    - lorsque chaque contact est ajouté
    - on rempli le template associé et on l'envoi avec les info de contact dont l'url de désinscription pour alimenter airtable
    - on retire le contact de la liste

### Proposition de solution @bbohec & @celineung 
- XP en place depuis septembre qui fonctionne, on a pas vraiment d'urgence hors le fait de rapatrier l'XP dans le code > on a le temps de réfléchir 😉 
- Stratégie envisagée : inclure l'expérience dans #1136
- Attendre que les expériences suivantes soient en place:
  - Tableau de bord entreprise qui liste les infos de discussions/MER
  - Vu de pilotage de discussion/MER en mode chat/historique des échanges pour avoir la possibilité d'ajouter ici des capacités d'action
- On peut ajouter une action de type active/désactiver les rappels et/ou la feature qui permet de clôturer automatiquement une MER de type "ne pas donner suite à la MER" afin d'avoir un process de fin de MER (et aussi d'ouvrir à une fin de MER différente qui serait de proposer la création d'une convention si le candidat et/ou l'entreprise le veulent 😉 ). Niveau donnée il nous faudra surement ajouter une donnée sur la discussion qui serait la date de dernière relance. Ensuite pour reprendre l'envoi de mail en interne il nous faudra une feature de relance planifiée qui prendra les discussions en cours qui ont une date de dernière relance qui date de plus de 3 jours pour pousser l'entreprise et/ou le candidat à aller au bout du processus de MER et pas uniquement les MER qui n'ont pas eu de première réponse.

A changer : 
- Modifier le contenu du mail : proposer de répondre via l'espace entreprise
- proposer de répondre tout de suite via l'email

https://my.brevo.com/camp/template/144/message-setup/app-smtp

**Comment by 3lodi3** [comment]
STAND BY en attenadant la feature des discussions dans le tdb entreprises #1120

**Comment by nathalie-reyre** [comment]
@clement-duport c'est fait non ? Si oui, tu peux fermer le ticket ?

**Comment by clement-duport** [comment]
@nathalie-reyre  non ça avait été mis en stand by en attendant l'integration des discussions dans le tdb entreprise

**Comment by nathalie-reyre** [comment]
Selon moi, ce ticket est soit à transformer en epic, soit à fermer car la gestion des conversations en prod

**Comment by bbohec** [comment]
Décision de reprendre l'XP no code N8N/Metabase/Brevo sans changement de comportement.

Relance si pas de réponse depuis 3 jours
Relance si pas de réponse depuis 7 jours

**Comment by bbohec** [comment]
Exemple de mail



![Image](https://github.com/gip-inclusion/immersion-facile/assets/58432308/fd500d50-2bb8-4de6-8060-32f02b582e02)

**Comment by nathalie-reyre** [comment]
@bbohec
