### ISSUE TITLE
ETQ bénéficaire, j'ai accès à des résultats d'entreprises qui existent. (Script de mise à jour d'établissements)

### ISSUE THREAD

**Issue by bbohec** [gip-inclusion/immersion-facile#108]

**Comment by nathalie-reyre** [comment]
Relancer la script de vérification du SIRET

**Comment by JeromeBu** [comment]
Est-ce qu'on peut détailler les données qu'on veut mettre à jour @nathalie-reyre ?

Je vois bien :
- si l'établissement est toujours ouvert
- si le naf à changé
- si le nom à changé ? 

En tout cas pour l'adresse, je pense qu'on ne met pas à jour, car les gens qui se sont inscrit chez nous ont pu la modifier, elle ne serai pas forcément là même que celle de l'api siret.

**Comment by nathalie-reyre** [comment]
ok pour tes propositions
