### ISSUE TITLE
Référencement des cookies utilisés sur IF - obligation réglementaire

### ISSUE THREAD

**Issue by 3lodi3** [gip-inclusion/immersion-facile#1083]
### :thinking: Contexte et problématique (et par qui est-ce remonté ?)

cf EPIC #958

**Comment by enguerranws** [comment]
J'ai utilisé un outil pour détecter à peu près tout ce qu'on a (sur la page stats comme ça, on voit également les cookies nécessaires à metabase) : https://cookie-script.com/quick-report?identifier=8a0c4efe077dce3626c752f6a70adb09

L'essentiel, c'est du Linkedin : je vais voir avec @PierreDeNantes à quoi ça nous sert (je ne me rappelle plus).
Sinon, 2 cookies pour Matomo, 1 metabase, 1 crisp.

**Comment by enguerranws** [comment]
Le tracking linkedin va être supprimé par @PierreDeNantes , ça va nous simplifier le boulot de recensement.

**Comment by enguerranws** [comment]
Pour préparer l'implem, un peu de doc : 
- changer le comportement de Matomo : https://developer.matomo.org/guides/tracking-consent
- utiliser le composant consentManager de react-dsfr avec une implem custom (de base, le dsfr utilise Eulerian) : https://components.react-dsfr.codegouv.studio/?path=/docs/components-consentmanagement--default

**Comment by enguerranws** [comment]
La solution DSFR proposée est pas mal : 



![Image](https://github.com/gip-inclusion/immersion-facile/assets/2190121/d370572a-aa5e-483e-b68b-ac6acd704f17)
