### ISSUE TITLE
modification wording PE en FT

### ISSUE THREAD

**Issue by Jessicaceleste1** [gip-inclusion/immersion-facile#1085]
### :thinking: Contexte et problématique (et par qui est-ce remonté ?)

wording a modifier : sans identifiants et avec identifiants France travail et modifier l'icone https://immersion-facile.beta.gouv.fr/demande-immersion

![image](https://github.com/gip-inclusion/immersion-facile/assets/129732318/a724a26d-de05-4af9-97c8-e0cc4fe6b93a)

**Comment by Jessicaceleste1** [comment]
page france travail connexion https://authentification-candidat.pole-emploi.fr/connexion/XUI/?realm=/individu&goto=https://authentification-candidat.pole-emploi.fr/connexion/oauth2/realms/root/realms/individu/authorize?response_type%3Dcode%26client_id%3DPAR_immersionfacile_049065783eb6e216586e6cda7e560658c7f57b43196d2552fae03dabd1fa4209%26realm%3D/individu%26redirect_uri%3Dhttps://immersion-facile.beta.gouv.fr/api/pe-connect%26scope%3Dapplication_PAR_immersionfacile_049065783eb6e216586e6cda7e560658c7f57b43196d2552fae03dabd1fa4209%2520api_peconnect-individuv1%2520api_peconnect-conseillersv1%2520api_peconnect-statutv1%2520individu%2520openid%2520profile%2520email%2520statut#login/

**Comment by Jessicaceleste1** [comment]
plus modification du wording complet : vous êtes inscrit à Pôle Emploi, la notion d'inscription ne convient, mais plutôt quelque chose qui exprime c'est PE/ FT qui gère votre convention, car, en réalité lorsqu'il s'agit de suivi délégué auprès d'un prestataire qui a une convention de délégation, il ne faut pas qu'il se PE connect, idem pour les structures d'accompagnement, car si PE connect, il ne peut pas choisir une autre structure que PE
![image](https://github.com/gip-inclusion/immersion-facile/assets/129732318/2aaac078-9d29-40e5-9e22-e8bcc4effa79)

**Comment by nathalie-reyre** [comment]
repérer toutes les mentions Pôle emploi sur IF et les modifier par France Travail

**Comment by NastassiaRodriguez** [comment]
Le wording officiel est : France Travail ( anciennement Pôle emploi ) @3lodi3

**Comment by nathalie-reyre** [comment]
le logo France Tavail connect n'existe pas encore.  On sera informés quand il sera dispo

**Comment by nathalie-reyre** [comment]
@celineung oui pour l'instant, ça reste Pôle emploi Connect. Le nom changera en même temps que le logo.
