### ISSUE TITLE
ETQ 'structure d'accompagnement, je ne dois pas pouvoir valider une demande de convention 

### ISSUE THREAD

**Issue by nathalie-reyre** [gip-inclusion/immersion-facile#1086]
### :bug: Le problème

Quand une convention  suivie par une structure d'accompagnement est modifiée (dans l'exemple, la convention a été modifiée par la structure d'accompagnement elle même),  la validation de la convention ne se fait plus par la structure prescriptrice mais par la structure d'accompagnement. 

### :footprints: Étapes pour reproduire
Cf convention 9c082c21-6bfc-4d0d-9297-4da05e0e3d86.  
Lien de validation définitive envoyé à la structure d'accompagnement cf https://metabase.immersion-facile.beta.gouv.fr/dashboard/102-notifications-email?filtrer_par_numero_de_convention=9c082c21-6bfc-4d0d-9297-4da05e0e3d86&filtre_de_date_des_mails=thismonth . 
La structure d'accompagnement est correctement référencée
Image
ID structure d'accompagnement : 7a12d2b4-b46e-431d-a5d1-71afd5b682a8

-->

### :dart: Comportement attendu

Le comportement attendu est envoi du lien de contrôle de l'éligibilité puis envoi du lien de validation à la structure prescriptrice . 
### Screenshots

![Uploading Capture d’écran 2024-01-09 à 18.42.46.png…]()

**Comment by celineung** [comment]
Thread Discord: https://discord.com/channels/864451835553513474/1194335679358971975

Lors du rapprochement d'un utilisateur d'une agence, ce dernier a toujours le rôle de valideur.
