### ISSUE TITLE
ETQ administrateur , je dois pouvoir modifier des structures prescriptrices ou d'accompagnement même si elles sont détectées comme doublon

### ISSUE THREAD

**Issue by nathalie-reyre** [gip-inclusion/immersion-facile#1089]
### :bug: Le problème

En BO, il n'est plus possible d'opérer des modifs sur certaines structures car elles sont détectées en doublon. On ne peut  les fermer ou changer des informations qu'en passant par la base.

Message d'erreur  "Désolé : nous n'avons pas été en mesure d'enregistrer vos informations. Veuillez réessayer ultérieurement
{ "errors": "Une autre agence du même type existe avec la même adresse" } --> la détection des doublons ne doit se faire qu'au moment du référencement de la structure."

### :dart: Comportement attendu
La détection des doublons ne doit se faire qu'au moment de la création d'une nouvelle structure, à l'étape d'enregistrement du formulaire de référencement. 
Dans le BO, je dois pouvoir modifier toutes les structures présentes sans que ne s'applique la vérification du doublon

**Comment by JeromeBu** [comment]
attention ici, c'est uniquement dans le cas d'un admin ? 
Car est-ce que tu veux autoriser qu'une agence qui fait une édition puisse créer un doublon à ce moment là ? 
(Je ne crois pas que les agences ait le droit d'édition pour l'instant, mais ca ne va pas trop tarder à venir)
