### ISSUE TITLE
ETQ candidat, je peux avoir accès aux infos données par LBB sur un établissement "tentez votre chance"

### ISSUE THREAD

**Issue by JeromeBu** [gip-inclusion/immersion-facile#109]
permettre aux utilisateurs d'accéder aux infos de contact et de mode de mise en relation que LBB a enregistré/entreprise proposée par l'algo. 
Conserver le lien vers la map google qui permet de localiser l'établissement. et ajouter un lien vers LBB pour les informations de contact.

**Comment by JeromeBu** [comment]
@3lodi3 pour comment on visualize ca dans les résultats de recherche ?

**Comment by 3lodi3** [comment]
@JeromeBu Si on veut garder strictement les cartes du DSFR, on peut faire ça : https://www.figma.com/proto/O6MfTEZ1Ms8cKQHFjOYEA5/Site---UX-design?page-id=325%3A50764&type=design&node-id=403-53897&viewport=537%2C95%2C0.62&scaling=min-zoom&starting-point-node-id=403%3A53897

En revanche je ne vois pas comment on peut lier vers 1 seule page entreprise sur le site LBB, je ne vois que des pages de résultats avec plusieurs entreprises où il faut en plus ouvrir l'accordéon pour voir le mode de contact. Est-ce que vous pouvez obtenir autre choses via l'API ?

**Comment by JeromeBu** [comment]
Voilà un exemple :

[Pour une recherche de Boulanger, au havre](https://immersion-facile.beta.gouv.fr/recherche?distance_km=10&latitude=49.4939&longitude=0.10797&place=Le%20Havre%2C%20Normandie%2C%20France&rome=D1102&romeLabel=Boulangerie%20-%20viennoiserie&sortedBy=distance&appellationLabel=Boulanger%20%2F%20Boulang%C3%A8re&appellationCode=11573)

On a parmis les résultats :

![Image](https://github.com/gip-inclusion/immersion-facile/assets/22095555/55b2f362-ce35-4987-8a80-472e76fb3e99)



Mais [Sur le site de la bonne boite](https://labonneboite.pole-emploi.fr/51476642700017/details?rome_code=D1102&utm_medium=web&utm_source=api__emploi_store_dev&utm_campaign=api__emploi_store_dev__immersionfacile), on a plus d'infos, un téléphone etc... (qu'on a pas avec l'API)



![Image](https://github.com/gip-inclusion/immersion-facile/assets/22095555/1a0ca5f6-46e6-461c-8577-416e8dc2d2e8)

**Comment by JeromeBu** [comment]
L'idée serait d'avoir un lien dans la petite card de résultat vers le site de LBB (sur l'entreprise concernée)

**Comment by 3lodi3** [comment]
Super si on peut avoir 1 page par entreprise, je propose de remplacer le bouton "tentez votre chance" par "localiser l'entreprise" et de lier vers la page directement (on a de nombreux retours utilisateurs sur ce texte de bouton qui n'est pas compris, donc autant le changer).

**Comment by JeromeBu** [comment]
pour moi pas de problème, on peut tout faire. Juste :
1. actuellement, sur ce bouton tentez votre chance on ouvre une modale
2. sur cette modal, il y a un lien vers google maps avec les données de l'entreprise

Est-ce qu'on fait sauter cette modale et on renvoie directement vers la bonne boite ? (et on supprime de fait la possibilité de cliquer sur le lien google maps)

Ou bien on garde le bouton "Tentez votre chance" et on ajoute le lien vers LBB à coté du lien google map ?

Je suis d'accord qu'avec le lien LBB , le lien vers google map perd de son intérêt puisque les infos se recoupent.

@nathalie-reyre pour info

**Comment by 3lodi3** [comment]
1. je propose d'enlever la modale où on trouve le bouton "localiser" et de le mettre directement dans la carte
2. on peut déjà aujourd'hui, sur toutes les cartes (tentez votre chance ou pas), cliquer sur l'adresse et ouvrir un lien gmaps -> on garde ce comportement. (à moins que ça change avec l'arrêt du stockage des résultats LBB ?)

**Comment by nathalie-reyre** [comment]
il faut expliquer le concept "tentez votre chance". Je suis ok avec le fait de supprimer le lien vers google map dès lors qu'on renvoie vers LBB qui en plus des coordonnées localise l'entreprise et qui donne un plus un lien vers Google.  On peut imaginer une pop up qui s'ouvre quand on survole le tag "tentez votre chance" et remplacer le wording du CTA "Tentez votre chance" par "Trouver les coordonnées de l'entreprise" si ça te semble plus clair @3lodi3

**Comment by JeromeBu** [comment]
Très rapidement j'ai pu changé comme ca :

<img width="623" alt="image" src="https://github.com/gip-inclusion/immersion-facile/assets/22095555/2ee99ed8-22fe-4428-ba79-7cd7935282e2">

avec dans la liste des résultats :

<img width="1274" alt="image" src="https://github.com/gip-inclusion/immersion-facile/assets/22095555/9280d8a9-6379-45c1-9ed0-9c54c88f1e24">


Je vous laisse me dire, si on vire la modale, si on renomme le bouton, etc...

**Comment by nathalie-reyre** [comment]
Pour l'instant, on part comme ça avec une modif du wording qui devient "**trouver le contact sur La Bonne Boite**" (wording identique dans la modale et sur la fiche). 
On recrée un ticket ad hoc pour revoir plus en détail le contenu de la fiche (lien vers LBB et accès aux conseils pour présenter la demande d'immersion).
