### ISSUE TITLE
Ajouter indicateur de NPS/difference sur les immersions avec IF et sans IF

### ISSUE THREAD

**Issue by Master-Touks** [gip-inclusion/immersion-facile#1090]
### :thinking: Contexte et problématique

Nous avons aujourd'hui le NPS qui est récupéré par Tally https://tally.so/r/nprlKZ et intégré automatiquement dans un [google sheet](https://docs.google.com/spreadsheets/d/1C05H_JR9gz_cBC2N7BZ17zlf9phrJ9qmaBikyKu9Sgo/edit?pli=1#gid=0) ce qui nous permet de le calculer simplement. 
Le besoin change et nous voulons l'intégrer dans un dashboard Metabase. 

### :tada: Proposition de solution

Pour se faire, est-ce possible d'intégrer le NPS dans une table Postgres afin de la récupérer et le calculer dans Metabase ?

**Comment by JeromeBu** [comment]
C'est en prod
