### ISSUE TITLE
Investigation tracking matomo supprimé sur les liens avec beaucoup de paramètres

### ISSUE THREAD

**Issue by 3lodi3** [gip-inclusion/immersion-facile#1098]
### Problème
Au clic sur ce genre de lien, le tracking matomo disparaît : https://immersion-facile.beta.gouv.fr/recherche?distanceKm=10&latitude=48.8535&longitude=2.34839&appellations[]=%7B%22romeCode%22%3A%22M1805%22%2C%22romeLabel%22%3A%22%C3%89tudes%20et%20d%C3%A9veloppement%20informatique%22%2C%22appellationCode%22%3A%2214153%22%2C%22appellationLabel%22%3A%22D%C3%A9veloppeur%20%2F%20D%C3%A9veloppeuse%20informatique%22%7D&sortedBy=distance&place=Paris%2C%20%C3%8Ele-de-France%2C%20France&mtm_campaign=campagne-semaine-numerique-2024&mtm_kwd=20231214_numerique

### Piste de solution

Si on peut garder les paramètres suivants qui permettent de tracker via matomo :
- mtm_campaign
- mtm_kwd

**Comment by enguerranws** [comment]
Bon, on ne va pas avoir le choix, il va falloir ajouter les params à la mano dans les définitions de type-route : ça fonctionne sur des pages normales, mais dès qu'on fait un push ou un replace (sur presque tous les forms) avec des params que type-route ne connait pas, ça crash.
