### ISSUE TITLE
ETQ Catherine Vautrin, j'admire mon nouveau logo sur IF

### ISSUE THREAD

**Issue by nathalie-reyre** [gip-inclusion/immersion-facile#1112]
### :thinking: Contexte et problématique

remaniement ministériel = logo du ministère à mettre à jour

  nouveau logo ici  https://travail-emploi.gouv.fr/IMG/logo/logo-travail-emploi.png

**Comment by 3lodi3** [comment]
https://zeroheight.com/248ec09c8/p/151c1f-logos/b/98907a
