### ISSUE TITLE
ETQ entreprise je vois clairement à quels candidats je dois répondre afin d'améliorer le taux de réponse des entreprises

### ISSUE THREAD

**Issue by 3lodi3** [gip-inclusion/immersion-facile#1118]
🚧 Epic

https://github.com/gip-inclusion/immersion-facile/issues/1136

### :thinking: Contexte et problématique

Le taux de réponse des entreprises aux demandes de mise en relation est trop faible (17% en janvier 2024).

### :tada: Proposition de solution

Afficher toutes les demandes de mer dans un tableau de bord propre à l'entreprise.
Dans un premier temps, un tdb metabase.

1è étape : tableau metabase
- date de la demande
- objet
- métier
- prénom candidat
- nom candidat
- email candidat
- téléphone candidat
- raison sociale entreprise ou enseigne
- SIRET
~~- type de stage~~

-> 1 ligne par mer

Au clic sur la ligne, on peut consulter les échanges (autre feature).

**Comment by bbohec** [comment]
![Image](https://github.com/gip-inclusion/immersion-facile/assets/58432308/41790950-c2ab-44b7-99f7-df34f22c1a35)
