### ISSUE TITLE
ETQ entreprise, je souhaite voir le détail des échanges avec les candidats à l'immersion

### ISSUE THREAD

**Issue by 3lodi3** [gip-inclusion/immersion-facile#1120]
### :construction: Epic
#1136 

### :thinking: Contexte et problématique

Suite de l'issue #1118.
En partant du tableau de bord entreprises, l'utilisateur peut accéder au détail des échanges avec le candidat = une discussion avec un ID.

### :tada: Proposition de solution

- Voir le contenu des discussions par date (suggestion des devs : UI messagerie type whatsapp pour anticiper la suite, quand on pourra échanger des messages directement dans IF).
- Bouton pour répondre au candidat - pour l'instant un mailto et par la suite une vraie réponse dans l'app IF (feature à part).

### :camera: Maquettes

Proto : https://www.figma.com/proto/6msAgGCn4id2P3OjI4NRxP/Site---UX-design-1er-semestre-2024?page-id=139%3A732&type=design&node-id=510-7213&viewport=-733%2C-892%2C0.07&t=JDeqdD6DPGPQOJXw-1&scaling=min-zoom&starting-point-node-id=510%3A6801&mode=design

Fichier pour dev : https://www.figma.com/file/6msAgGCn4id2P3OjI4NRxP/Site---UX-design-1er-semestre-2024?type=design&node-id=510%3A6801&mode=dev&t=2Vsy4JIeTdfKA262-1

**Comment by 3lodi3** [comment]
A préparer avec Asmaa pour le grooming du mardi 30 janvier

**Comment by 3lodi3** [comment]
prévoir les actions possibles par la suite :
- pré-remplir une demande de convention
- répondre négativement au candidat

**Comment by JeromeBu** [comment]
Dans l'ordre on peut faire :
1. visualisation de la discussion
2. possibilité d'envoyer un message
3. ajout des templates de réponse
4. ajout de la gestion de pièce jointes

**Comment by nathalie-reyre** [comment]
réponse d'Elo, ca lui va très bien
