### ISSUE TITLE
ETQ FAST, je veux pouvoir suivre l'impact sur l'augmentation net des immersions en France

### ISSUE THREAD

**Issue by Master-Touks** [gip-inclusion/immersion-facile#1123]
### :thinking: Contexte et problématique

Afficher le nombre d'immersion faites grâce à Immersion Facilité sur la page Stat publique.
Pour l'instant les résultats transites entre Tally.so et un google sheet depuis une intégration native. Nous aimerions automatisé l'affichage du résultat d'impact net directement dans metabase.

Le formulaire : https://tally.so/r/nprlKZ

### :tada: Proposition de solution

Suite à cela, nous aimerions créer un script qui va récupérer via un webhook les soumissions de formulaire, en temps réel, pour les stocker dans notre base de données Postgresql afin de pouvoir lire les soumissions directement depuis metabase et calculer le score d'impact net dans nos dashboards publiques.

**Comment by 3lodi3** [comment]
Coucou @Master-Touks on en a parlé ce matin, on avait déjà fait le ticket pour récupérer le Tally en fait !
