### ISSUE TITLE
Màj logos - supports print

### ISSUE THREAD

**Issue by 3lodi3** [gip-inclusion/immersion-facile#1133]
### :thinking: Contexte et problématique

Le logo et le nom de Pôle emploi ainsi que du Ministère du travail ont changé

### :tada: Proposition de solution

- Remplacer les logos du ministère du travail et de Pôle emploi sur les supports print sous InDesign
cf Elle peut présenter son travail effectué pour l’entretien

- Remplacer le wording "Pôle emploi" par "France Travail"

On a trois types de supports à mettre à jour :

les dépliants : https://drive.google.com/drive/folders/1EZ1lBpKVHZF_mIF8Hn9hPyLs8e9CFWhZ
les kakemonos : https://drive.google.com/drive/folders/1T7F-SQUVUpYJ1DiWMROqv4w7GcYeyWDL
les affiches : https://drive.google.com/drive/folders/15aH4mU1q1Jl-64T9WKygdLG2VsU_gLVk

**Comment by 3lodi3** [comment]
Pour Asmaa

**Comment by Jessicaceleste1** [comment]
les fiches mémos ? @NastassiaRodriguez https://drive.google.com/drive/u/0/folders/16sFygtzt6hPfHTzLHw8oMoarJsTPUupP
