### ISSUE TITLE
ETQ service com Plateforme de l'inclusion, je veux une com sur l'événement du 1er février sur IF

### ISSUE THREAD

**Issue by 3lodi3** [gip-inclusion/immersion-facile#1141]
Prévoir :
- illustration libre de droits - je vous conseille https://undraw.co/illustrations
- phrase de mise en avant (actuellement 77 caractères)
- lien de redirection (éventuellement tracké via une campagne matomo si vous voulez suivre le nb de clics, voir comment faire ici : https://www.notion.so/gip-inclusion/Matomo-IF-0630e07f59a5433db939bdce4b50a8a1?pvs=4)

**Comment by NastassiaRodriguez** [comment]
Ressources :

- Lien de redirection à tracker ( cf Elo ) : https://www.inclusion-demain.fr/
- Proposition de titre sur le badge : "Le rendez-vous incontournable des professionnels de l'inclusion"
- Date : Jeudi 01 février 2024

**Comment by Jessicaceleste1** [comment]
pas d'illustration proposée par contre peut être prévoir un code couleur genre event pro prescripteur, event ent, pb site

**Comment by Jessicaceleste1** [comment]
![image](https://github.com/gip-inclusion/immersion-facile/assets/129732318/8af73085-6f9e-489c-bf84-8d6279096288)

**Comment by NastassiaRodriguez** [comment]
> La phrase de mise en avant utilisée par les autres c'est :
> 
> L'inclusion aujourd'hui, les défis de demain (le titre) Le jeudi 01 février 2024, les professionnels de l'inclusion ont rendez-vous de 09h à 17h pour un événement en ligne incontournable.

c'est trop long pour le badge Jesse et pas compréhensible par l'usager

**Comment by NastassiaRodriguez** [comment]
Lien tracké : https://www.inclusion-demain.fr/?mtm_campaign=Badge-site-PDI&mtm_kwd=2024-01-badge-site-home-front cc @Master-Touks @3lodi3

**Comment by NastassiaRodriguez** [comment]
Pour illustration, prendre le logo de la communauté de l'inclusion https://www.inclusion-demain.fr/fr ( je le demande à la com )
