### ISSUE TITLE
ETQ ADMIN je ne vois plus les TDB agence

### ISSUE THREAD

**Issue by cecile-dimarco** [gip-inclusion/immersion-facile#1149]
### :bug: Le problème

Depuis ADMIN, dans l'onglet agence, je ne visualise plus le tableau de bord embarqué des agences

### :dart: Comportement attendu

 je devrais visualiser le TDB de l'agence

### Screenshots

![image](https://github.com/gip-inclusion/immersion-facile/assets/134716620/54a98b78-39d2-4543-bcaf-8fad3b47d6e3)

**Comment by JeromeBu** [comment]
Je ne reproduis pas ce problème sur la prod :



![Image](https://github.com/gip-inclusion/immersion-facile/assets/22095555/29b1ce25-d8d0-4959-b6b2-a57c348a8c8a)

**Comment by cecile-dimarco** [comment]
![image](https://github.com/gip-inclusion/immersion-facile/assets/134716620/9dd47f19-12be-473d-b473-af6bc7c1d157)

@JeromeBu c'est pas la même vue, celle-ci c'est les agences en attente de validation de référencement 
Pour être plus précise, c'est le TBD agence après avoir sélectionnée une agence dans éditer une agence

**Comment by bbohec** [comment]
@nathalie-reyre  @Master-Touks @cecile-dimarco vous avez la possibilité de retrouver le tableau de bord métabase et de nous donner son lien?
