### ISSUE TITLE
ETQ qu'admin , je peux "supprimer" une entreprise

### ISSUE THREAD

**Issue by nathalie-reyre** [gip-inclusion/immersion-facile#115]
depuis le back office avec un flag entreprise ce qui génère une suppression des données personnelles. On ne garde que le SIRET de l'entreprise. Gestion des événements + envoi d'un mail de confirmation lui indiquant ce qui a été supprimé et ce qu'on conserve et pourquoi on le conserve

**Comment by bbohec** [comment]
Atelier DEV
============

- Quand on supprime un establishment il ne faut pas oublier de supprimer le form_establishment
- Retirer le lian (fk) Siret de la table discussion comme ça si on supprime un établissement alors pas d'impact sur la discussion ou bien supprimer les discussion associées à l'étab en mode cascade? Et quid de l'anonymisation des discussions?
- penser à la donnée stockée dans immersion_contact qui est lié à la table de jointure etab par etab_immersion_contact

- comment c'est fait aujourd'hui à la main par le métier en base?

- mail de notif admin et/ou entreprise de la suppression effective

**Comment by nathalie-reyre** [comment]
Quid de l'échange avec Osiris ?

**Comment by JeromeBu** [comment]
D'un point de vu DB, il faut , dans l'ordre, mais de façon transactionnel, il faut  :

1. Supprimer les immersions_contact lié au siret
2. Supprimer le form_establishment
3. Supprimer l'establishment (cascade sur les offres )
