### ISSUE TITLE
ETQ entreprise, je peux référencer plusieurs fois un même établissement avec des localisations

### ISSUE THREAD

**Issue by nathalie-reyre** [gip-inclusion/immersion-facile#1153]
Aujourd'hui, chaque SIRET renvoie à une seule adresse. La visibilité de l'entreprise est contrainte par cette adresse unique.
Or nous avons de plus en plus d'entreprises qui ont un seul siret mais qui veulent être visibles dans d'autres lieux, souvent parce qu'elles ont des agences non immatriculée ou parce qu'elles recrutent des salariés en itinérance. 

Proposition de solution : ajouter des adresses supplémentaires à celle qui est indiquée dans la base SIREN. 
Chaque adresse ajoutée permet d'ajouter un lieu de recherche (même process que pour les métiers)

![Image](https://github.com/gip-inclusion/immersion-facile/assets/61510442/0c639b6d-19eb-4ca3-a06e-314b64ad65a6)

Parcours UX/UI
https://www.figma.com/proto/6msAgGCn4id2P3OjI4NRxP/Site---UX-design-1er-semestre-2024?page-id=6%3A303&type=design&node-id=6-1254&viewport=-526%2C-346%2C0.83&t=uqcpit0h4uGl9fof-1&scaling=min-zoom&mode=design

Proto validé par la personne qu'on a vue en test utilisateur le 1er fevrier (société villaflorale) : https://www.notion.so/gip-inclusion/Nouveau-parcours-r-f-rencement-entreprises-ddf924f2ffc84995a7f9ae5fa3d48b83?pvs=4

**Comment by JeromeBu** [comment]
ca mérite peut-être de passer par la prochaine séance de groming ce ticket... C'est assez impactant, et puis il faut définir une UX/UI pour la saisie, mais aussi pour la visualisation des résultats (avec les cas tordu, du genre : l'entreprise apprait 2 ou 3 fois sur le périmètre choisi dans la recherche, est-ce qu'on l'affiche 2 ou 3 fois ) ? etc....

**Comment by 3lodi3** [comment]
Grooming mardi 30 janvier

**Comment by 3lodi3** [comment]
Peut-être plutôt ajouter un select ville (le même que dans le moteur de recherche de notre annuaire) dans l'étape "Comment souhaitez-vous apparaître dans notre annuaire ?"
-> On garde 1 SIREN / Raison sociale / Adresse du siège pour les documents administratifs

**Comment by 3lodi3** [comment]
Pour l'instant, on ajoute un étape dans le form de référencement la possibilité d'ajouter plusieurs adresses pour apparaître sur ces localisations dans l'annuaire de recherche.

**Comment by 3lodi3** [comment]
Demander à @cecile-dimarco et @nathalie-reyre les contacts des entreprises qui ont remonté cette demande.

**Comment by nathalie-reyre** [comment]
UX préparée par Aasma cf figma
