### ISSUE TITLE
ETQ conseiller ou valideur, j'ai des droits différenciés sur le BO/agence

### ISSUE THREAD

**Issue by nathalie-reyre** [gip-inclusion/immersion-facile#1164]
Lors de validation des droits de l'utilisateur il faut sélectionner si l'utilisateur est conseiller ou valideur.

**Comment by JeromeBu** [comment]
ca donne ça

![Image](https://github.com/gip-inclusion/immersion-facile/assets/22095555/d09e8a26-cf95-4651-8208-fa59e1a86bb4)
