### ISSUE TITLE
ETQ utilisateur, je trouve le mail de la structure d'accompagnement et/ou de la struture prescriptrice dans la convention validée

### ISSUE THREAD

**Issue by nathalie-reyre** [gip-inclusion/immersion-facile#1177]
Afficher le 1er email de la liste pour : 
- structure accompagnante
- valideur + conseiller pour les agences à 2 niveaux
- valideur pour les agences à 1 niveau

**Comment by celineung** [comment]
@nathalie-reyre dans le cas où il y a plusieurs valideurs, on affiche tous les mails ?
