### ISSUE TITLE
ETQ France Travail, clarifier ma notification immersion déposée

### ISSUE THREAD

**Issue by cecile-dimarco** [gip-inclusion/immersion-facile#1206]
### :thinking: Contexte et problématique (et par qui est-ce remonté ?)

La notification immersion déposée indique que le conseiller référent reçoit également la notification, mais ce n'est pas le cas.
Cela induit en erreur les gestionnaires des boites mails agences qui pensent que le conseiller a eu l'info

### :tada: Proposition de solution

Voir la solution envisagée en pré-grooming avec Nath en commentaire

~~Soit supprimer la mention dans le mail, soit envoyer la notification au référent dès que la convention est initiée~~

https://discord.com/channels/864451835553513474/1201542258692984852

**Comment by 3lodi3** [comment]
Lorsqu'une convention est remplie avec les id France Travail du candidat : 

- [ ] On envoie la notif de demande déposée UNIQUEMENT au conseiller référent : "Convention - nouvelle convention à traiter par le conseiller FT lié"
- [ ] On n'envoie plus cette notif à l'agence : "Convention - nouvelle convzention à traiter par l'agence"
- [ ] On envoie la notif de convention SIGNEE par toutes les parties au conseiller réf + boite agence en backup (dans "Convention - entièrement signée à troiter par l'agence". Expliquer que c'est conseiller réf qui doit valider la demande en prio, et qu'elle est envoyée à l'agence en backup en cas d'absence).

**Comment by clement-duport** [comment]
Dans le cas où il n'y a pas de conseiller référent est ce qu'on envoie une notification à l'agence ou alors on n'en envoie à personne ?
