### ISSUE TITLE
Répondre à Diagoriente

### ISSUE THREAD

**Issue by 3lodi3** [gip-inclusion/immersion-facile#1209]
Guillaume Chérel <guillaume@diagoriente.beta.gouv.fr>
mar. 16/01, 09:21Vincent Sommé <vincent.somme@beta.gouv.fr>;Élodie Delaisement;Nathalie Reyre;
Boîte de réception
Bonjour à tous,
Nous avons déployé hier soir une nouvelle version du moteur de recherche avec un endpoint de feedbacks "/feedback/search". Si vous pouvez l'intégrer à votre UX, ça nous aidera à comprendre comment est utilisé le moteur et la pertinence des résultats pour le faire progresser. Le swagger contient des descriptions qui devraient vous aider à l'utiliser, mais n'hésitez pas à revenir vers nous si vous avez des questions.

Une conséquence est que nous avons protégé l'endpoint "/search/oplc/*" par authentification. Pour que vous puissiez continuer à le tester, je dois vous envoyer votre identifiant et mot de passe. Est-ce que l'un de vous à une clé GPG ou un autre moyen de communication sécurisé ?
On prépare aussi une interface web qui vous permettra de tester le moteur et de nous faire des retours plus facilement. On vous enverra le lien dès qu'il sera prêt.
À bientôt,
Guillaume

**Comment by JeromeBu** [comment]
Répondu le 02 février 2024, en proposant un moyen de nous transmettre la clé API
