### ISSUE TITLE
Lors de la relance des entreprises à 6 mois, les liens périment trop vite

### ISSUE THREAD

**Issue by nathalie-reyre** [gip-inclusion/immersion-facile#121]
La durée de validité des liens est de 48h, ce qui est trop court pour des mails de relance.

Il y a plusieurs possibilités pour fixer ca :

1. on allonge la durée (mais c'est pas forcément idéal)
2. le bouton devient un moyen de demander un lien de modification, et plus le mail de modification lui même
3. un message d'erreur explicite apparaît avec la possibilité de demander le renouvellement du lien magique. Peut être mieux que l'option 2 qui ajoute une étape supplémentaire pour accéder à sa fiche

**Comment by 3lodi3** [comment]
On rallonge la durée du lien à 1 semaine
