### ISSUE TITLE
Orienter l'utilisateur vers le bon choix de complétude de la convention

### ISSUE THREAD

**Issue by Jessicaceleste1** [gip-inclusion/immersion-facile#1218]
Update suite à la discussion du 13 maia vec @enguerranws 

prototype figma : https://www.figma.com/proto/rZtRL0ShjGKfdw43nMUPex/Site---UX-design-2nd-trimestre-2024?page-id=444%3A4204&type=design&node-id=3040-45678&viewport=445%2C168%2C0.13&t=JNW4FqLgCJ898T3k-1&scaling=min-zoom&starting-point-node-id=3040%3A45678&mode=design

fichier figma : https://www.figma.com/file/rZtRL0ShjGKfdw43nMUPex/Site---UX-design-2nd-trimestre-2024?type=design&node-id=444%3A4204&mode=design&t=zIcLfq5XpVPwgIWs-1

-> Pour les entreprises et prescripteurs, on accède directement au formulaire.
-> Pour les candidats, il y a une page intermédiaire avec les différents choix entre type de prescripteurs

### :thinking: Contexte et problématique

Il y a deux problématiques sur [cette page](https://immersion-facile.beta.gouv.fr/demande-immersion) : 
- Les entreprises qui ont leurs identifiants France Travail choisissent la 2è option et les remplissent sur la [page de connexion candidat FT](https://authentification-candidat.francetravail.fr/connexion/XUI/?realm=/individu&goto=https://authentification-candidat.francetravail.fr/connexion/oauth2/realms/root/realms/individu/authorize?response_type%3Dcode%26client_id%3DPAR_immersionfacile_049065783eb6e216586e6cda7e560658c7f57b43196d2552fae03dabd1fa4209%26realm%3D/individu%26redirect_uri%3Dhttps://immersion-facile.beta.gouv.fr/api/pe-connect%26scope%3Dapplication_PAR_immersionfacile_049065783eb6e216586e6cda7e560658c7f57b43196d2552fae03dabd1fa4209%2520api_peconnect-individuv1%2520api_peconnect-conseillersv1%2520api_peconnect-statutv1%2520individu%2520openid%2520profile%2520email%2520statut#login/)
- Les candidats inscrits à FT mais qui se font prescrire une immersion par une milo rentrent également leur identifiants PE et leur convention part chez leur conseiller FT au lieu de leur conseiller milo.

### :tada: Proposition de solution

Funnels créés : 
- sans ID FT 33% de conversion : https://matomo.inclusion.beta.gouv.fr/index.php?module=CoreHome&action=index&idSite=207&period=day&date=yesterday#?idSite=207&period=week&date=2024-04-21&category=Funnels_Funnels&subcategory=66
- avec ID FT 11% de conversion : https://matomo.inclusion.beta.gouv.fr/index.php?module=CoreHome&action=index&idSite=207&period=day&date=yesterday#?idSite=207&period=week&date=2024-04-21&category=Funnels_Funnels&subcategory=67

Tester un nouveau parcours et voir si les taux de conversion sont améliorés :
- Depuis le menu candidat -> renvoi aux choix candidats
- Depuis le menu entreprise -> accès direct au form
- Depuis le menu prescripteurs -> accès direct au form
- Ajout d'un lien d'accès rapide en header -> renvoi au choix persona

### :camera: Maquettes

Proto : https://www.figma.com/proto/rZtRL0ShjGKfdw43nMUPex/Site---UX-design-2nd-trimestre-2024?page-id=444%3A4204&type=design&node-id=3040-45678&viewport=765%2C216%2C0.25&t=SzvMjVEFIyvgFJIN-1&scaling=min-zoom&starting-point-node-id=3040%3A45678&mode=design

Fichier : 
https://www.figma.com/file/rZtRL0ShjGKfdw43nMUPex/Site---UX-design-2nd-trimestre-2024?type=design&node-id=444%3A4204&mode=design&t=5hnyyz84y1DklYGK-1

**Comment by Jessicaceleste1** [comment]
@SlimanCA @cecile-dimarco @Sylvieleb @NastassiaRodriguez

**Comment by Jessicaceleste1** [comment]
lien discord :https://discord.com/channels/864451835553513474/1042365650359828480/1202564700345466880

**Comment by 3lodi3** [comment]
Inverser les deux niveaux de texte et "je suis un candidat SUIVI par FT")

**Comment by nathalie-reyre** [comment]
@3lodi3 je propose un wording un chouia différent car on ne peut pas suggérer d'utiliser les ID Pe connect à la place de son titulaire. Il faut qu'on insiste sur le fait que le conseiller du candidat est exclusivement un conseiller France travail

**Comment by nathalie-reyre** [comment]
pour moi, on peut déjà faire ce que tu proposes en modifiant le wording et en ajoutant ces labels. Ca ne devrait pas trop prendre de temps et ça peut soulager pas mal le support

**Comment by 3lodi3** [comment]
Story de base (revue pour fusionner avec la problématique milo sur la même page)
### :thinking: Contexte et problématique (et par qui est-ce remonté ?)

Sur la page "remplir la convention" : https://immersion-facile.beta.gouv.fr/demande-immersion
Un candidat suivi par la mission locale mais inscrit chez FT, va cliquer sur "je remplis une convention avec mes identifiants FT" et ne pourra alors que sélectionner son agence FT et non sa mission locale qui doit porter sa convention. 
Ce problème se pose de façon récurrente : mission locale, SIAE, Cap emploi, Autres ..... dès lors que le candidat est inscrit à FT.

![image](https://github.com/gip-inclusion/immersion-facile/assets/129732318/0032d902-dfb7-4eb0-97d5-d3500d28d430)

Le problème est le même pour les jeunes en milo + FT cf #1424 

### :tada: Proposition de solution

Avoir un filtre dès lors que l'on clique sur remplir la demande de convention : 

![image](https://github.com/gip-inclusion/immersion-facile/assets/129732318/109b516d-2c62-4c62-97f2-19d06332866f)
La possibilité de choisir son département puis
La possibilité de choisir de quelle structure accompagne le candidat (même vue depuis entreprise, candidat ou prescripteur) via un menu déroulant. 
(soit 2 filtres)

Si l'on choisit n'importe quel autre prescripteur que FT : la page de la convention à compléter s'ouvre
Si l'on choisit FT une page s'ouvre afin d'inviter à s'identifier avec les identifiants FT qui permettent d'accélérer la démarche ou compléter la convention sans s'identifier. 

@3lodi3 
C'est une super proposition mais je crois que techniquement c'est compliqué (on en avait déjà parlé).
Donc je propose plutôt qu'on modifie le wording de la page pour voir si ça résout le problème + ajouter le logo FT : 
proto : https://www.figma.com/proto/6msAgGCn4id2P3OjI4NRxP/Site---UX-design-1er-semestre-2024?page-id=444%3A4204&type=design&node-id=444-4393&viewport=412%2C380%2C0.49&t=2Add03bnN4vwqkdj-1&scaling=min-zoom&mode=design

fichier dev : https://www.figma.com/file/6msAgGCn4id2P3OjI4NRxP/Site---UX-design-1er-semestre-2024?type=design&node-id=444%3A4204&mode=dev&t=2Vsy4JIeTdfKA262-1

logo FT en png et svg dispo sur le zeroheight : https://zeroheight.com/248ec09c8/p/151c1f-logos/b/98907a

**Comment by 3lodi3** [comment]
2è story fusionnée :
la question de l'identifiant FT est un vrai problème pour les MILOS : ETQ jeune inscrit à une milo et à FT, je n'ai pas la tentation de me FT connecter pour faire une demande de convention
[#1424](https://github.com/gip-inclusion/immersion-facile/issues/1424)

[Courrier - elodie.delaisement@beta.gouv.fr.pdf](https://github.com/gip-inclusion/immersion-facile/files/14801666/Courrier.-.elodie.delaisement%40beta.gouv.fr.pdf)

**Comment by NastassiaRodriguez** [comment]
@3lodi3 est-il possible ( dans cette MEP ou une autre ) de changer l'ordre par 1. je suis accompagné.e par une structure 2. Je suis accompagné par un conseiller FT ? Cette demande provient des MILOS, si elle n'est pas pertinente je ferais passer l'info. Merci à toi et à dispo pour en échanger 

![Image](https://github.com/gip-inclusion/immersion-facile/assets/103033764/cc6dd5a0-5611-433e-bb05-2992c0f5196d)
