### ISSUE TITLE
ETQ bizdev IF, je souhaite qu'une entreprise qui a fait une immersion via IF devienne entreprise accueillante

### ISSUE THREAD

**Issue by 3lodi3** [gip-inclusion/immersion-facile#123]
Dépendance : story #149 

**Proposition MVP :**  
A la date de fin d’immersion +24h : envoi d’un email qui dit “vous avez fini une immersion hier, voici le lien pour vous référencer → arrivée directement sur le site IF avec formulaire “Référencer mon entreprise” pré-rempli.  

**Template email :**  
https://my.brevo.com/camp/template/100/message-setup?editor=v6  

**Proposition avec parcours utilisateur + abouti :**  
À la date de fin d’immersion +24h : envoi d’un email qui dit “vous avez fini une immersion hier, voici le lien pour vous référencer → arrivée directement sur l'évaluation entreprise actuelle → puis arrivée directement sur le site IF avec formulaire “Référencer mon entreprise” pré-rempli (permet d’enlever le lien d'évaluation entreprise de l’email bilan actuel et de mettre le CTA bilan en gros)  À J+ 7, relance avec directement vers fiche entreprise pré-remplie à sur les entreprises non-inscrites en tant qu’entreprises accueillantes.

**Comment by 3lodi3** [comment]
Proposition MVP :  
A la date de fin d’immersion +24h : envoi d’un email qui dit “vous avez fini une immersion hier, voici le lien pour vous référencer → arrivée directement sur le site IF avec formulaire “Référencer mon entreprise” pré-rempli.  

Template email :  
https://my.brevo.com/camp/template/100/message-setup?editor=v6  Proposition avec parcours utilisateur + abouti :  À la date de fin d’immersion +24h : envoi d’un email qui dit “vous avez fini une immersion hier, voici le lien pour vous référencer → arrivée directement sur l'évaluation entreprise actuelle → puis arrivée directement sur le site IF avec formulaire “Référencer mon entreprise” pré-rempli (permet d’enlever le lien d'évaluation entreprise de l’email bilan actuel et de mettre le CTA bilan en gros)  À J+ 7, relance avec directement vers fiche entreprise pré-remplie à sur les entreprises non-inscrites en tant qu’entreprises accueillantes.

**Comment by bbohec** [comment]
@PierreDeNantes c'est déjà fait en NoCode?

**Comment by PierreDeNantes** [comment]
Absolument (désolé, pas vu le message)
