### ISSUE TITLE
ETQ admin, quand j'accède à une agence pour la modifier, un nouveau numéro de siret remplace le bon n° de siret

### ISSUE THREAD

**Issue by nathalie-reyre** [gip-inclusion/immersion-facile#1234]
### :bug: Le problème

 quand on sélectionne une agence pour la modifier (select par le nom), la fiche apparaît mais avec un siret qui n'est pas celui précédemment enregistré. Cela modifie le nom de la structure et son adresse

### :footprints: Étapes pour reproduire

 agence.'
2. Sélectionner une agence avec une recherche par le nom
3. Scroller sur la page --> le nom de l'agence ne correspond pas à celui recherché, l'adresse est différente, le siret également

### :dart: Comportement attendu

Pas de modif de SIRET, pas de modif de nom/nom déjà saisi/ pas de modif d'adresse

**Comment by celineung** [comment]
@nathalie-reyre est-ce que tu as toujours ce bug ?

**Comment by enguerranws** [comment]
@celineung C'est pas celui qu'on a corrigé la semaine dernière ? (cc: @nathalie-reyre)
