### ISSUE TITLE
Piloter depuis admin les structures avec le n° siret 

### ISSUE THREAD

**Issue by Jessicaceleste1** [gip-inclusion/immersion-facile#1244]
### :thinking: Contexte et problématique (et par qui est-ce remonté ?)

Les prescripteurs enregistrent plusieurs sites avec le même nom c'est très compliqué pour les retrouver et les modifier, si nous pouvions rechercher avec le siret cela serait beaucoup plus simple.

https://immersion-facile.beta.gouv.fr/admin/agencies

![image](https://github.com/gip-inclusion/immersion-facile/assets/129732318/533e3e75-82ea-4895-a399-59b326c0f09f)

### :tada: Proposition de solution

- [ ] Dans un premier temps, ajouter le filtre SIRET dans le tableau metabase
- [ ] Ensuite si possible ajouter la recherche par SIRET pour éditer une entreprise
- [ ] Préciser dans le form de référencement agence à quoi sert le nom : aux candidats + à eux-mêmes dans le tdb https://immersion-facile.beta.gouv.fr/ajouter-prescripteur

Maquette form de référencement :
proto : https://www.figma.com/proto/6msAgGCn4id2P3OjI4NRxP/Site---UX-design-1er-semestre-2024?page-id=441%3A597&type=design&node-id=441-4172&viewport=1736%2C1255%2C0.77&t=BTIndxSUZ3hKd8rS-1&scaling=min-zoom&mode=design

fichier pour dev : https://www.figma.com/file/6msAgGCn4id2P3OjI4NRxP/Site---UX-design-1er-semestre-2024?type=design&node-id=441%3A597&mode=dev&t=2Vsy4JIeTdfKA262-1

**Comment by 3lodi3** [comment]
- [ ] Dans un premier temps, ajouter le filtre SIRET dans le tableau metabase
- [ ] Ensuite si possible ajouter la recherche par SIRET pour éditer une entreprise

**Comment by JeromeBu** [comment]
Faire en sorte que le champs accepte les siret et les nom et fasse un autocomplete
