### ISSUE TITLE
ETQ prescripteur je me mélange dans le parcours de modif

### ISSUE THREAD

**Issue by 3lodi3** [gip-inclusion/immersion-facile#1250]
### :thinking: Contexte et problématique (et par qui est-ce remonté ?)

https://discord.com/channels/864451835553513474/1206965803241443359

### :tada: Proposition de solution

A cette étape :
![image](https://github.com/gip-inclusion/immersion-facile/assets/76998405/79e17a9c-9d18-48f9-8d09-123fe257a3e7)
h1 : Relancer les signataires manquants (vérifier selon l'étape d'avant)
Texte : enlever la 1è phrase "Dans ce cas... enregistrées."

**Comment by clement-duport** [comment]
La phrase a bien été retirée. Par contre la modification du titre de la modal est plus complex que prévue car liée au texte du bouton d'action. On décide donc de le repousser à la fin de l'itération.
