### ISSUE TITLE
ETQ Agence prescripteur je ne reçois pas de mail pour m'informer que une structure d'accompagnement vient de se référencer et m'a choisit comme structure prescriptrice

### ISSUE THREAD

**Issue by Jessicaceleste1** [gip-inclusion/immersion-facile#1263]
### :bug: Le problème

Lorsqu'une structure d'accompagnement s'enregistre sur notre site et choisi un prescripteur. Ce dernier ne reçoit pas de mail pour être informé qu'il va devoir valider les conventions de cette structure. 

### :dart: Comportement attendu

Voir avec Nath si une structure d'accompagnement peut être activée automatiquement, si oui le mail part, si non a définir quand il doit être envoyé soir lors de l'enregistrement soit lors de l'activation. 

Envoyer un mail auto à l'activation de la structure d'accompagnement.

**Comment by clement-duport** [comment]
@Jessicaceleste1  Quand t'auras le temps tu pourras me donner le wording pour le mail ?
