### ISSUE TITLE
Remplacer les PJ des mails de notification

### ISSUE THREAD

**Issue by NastassiaRodriguez** [gip-inclusion/immersion-facile#1269]

**Comment by NastassiaRodriguez** [comment]
_**Remplacer les pièces jointes envoyées via les notifications mail et/ou ajouter de nouvelles PJ**_ 

**Liens clever cloud :** 
**A. bénéficiaires :** https://immersion.cellar-c2.services.clever-cloud.com/Fiche memo-beneficiaire-immersionfacilitée2024.pdf
lien à supprimer : https://immersion.cellar-c2.services.clever-cloud.com/les_etapes_de_votre_demande.pdf
Important : vérifier que cette PJ n'est adressée qu'au bénéficiaire, le cas échéant ce mémo devra être revu 
**B. Entreprise accueillante :** https://immersion.cellar-c2.services.clever-cloud.com/Fiche memo-entreprise accueillante-immersion facilitee 2024.pdf 
à rajouter sur la notification "établissement référencement réussi 
**C. Prescripteurs :** https://immersion.cellar-c2.services.clever-cloud.com/Fiche-memo-prescripteur-générale-immersionfacilitée2024.pdf 
lien à supprimer : nouvelle convention - lien convention à traiter par le conseiller France Travail lié + nouvelle convention à traiter par l'agence + entièrement signée à traiter par le conseiller France Travail lié + entièrement signée à traiter par l'agence 
**D. Rôle des prescripteurs :** https://immersion.cellar-c2.services.clever-cloud.com/Fiche memo prescripteur-Role-des-prescripteurs-et-couverture-des risques-immersionfacilitee2024.pdf
à rajouter sur agence activée 


-> lien drive au besoin : https://drive.google.com/drive/folders/10dr2I0v0biXTpE1kUyQ6yI2Hgy_Eenwf

**Comment by NastassiaRodriguez** [comment]
@3lodi3 quel est ton avis sur ce mémo commun ? à mon sens on pourrais mettre les 2 PJ en 1 car vraiment en fonction de l'interlocuteur il faut une description des actions et peut être brander en mode  "guide IF" ?  comme un livret blanc qu'en penses tu ?

**Comment by 3lodi3** [comment]
@NastassiaRodriguez Oups j'vais pas vu :-) Oui carrément on peut mettre les deux si on n'envoie pas de PJ directement mais si on met juste un lien vers la PJ, sinon ça risque d'être lourd !
