### ISSUE TITLE
ETQ prescripteur je souhaite me référencer sur plusieurs départements

### ISSUE THREAD

**Issue by 3lodi3** [gip-inclusion/immersion-facile#1300]
### :construction: Epic

#1304 

### :thinking: Contexte et problématique

Aujourd'hui on autorise les doublons de SIRET par structure et cela pose des pb.
Voir le document très complet des bizdev : https://docs.google.com/presentation/d/1zeTiCyiPfV29D5T2mtKmobR7SfpigVs7cacGldizvnQ/edit?usp=sharing

### :tada: Proposition de solution

Changer le form de référencement prescripteur :
- par défaut le département lié à l'adresse est coché
- on permet d'ajouter d'autres départements que ceux liés à l'adresse

Concernant les agences dans ce cas : 
- on garde une seule agence ouverte, les autre passent en statut close.
- une fois que toutes les conventions liées aux agences "closed" sont finies, on les supprime.

6 mars :
- expliquer sur la fiche qu'on doit créer plusieurs fiches pour se référencer sur plusieurs départements/ pluisuers noms / plusieurs prescripteurs liés (pour les structures d'accompagnement).
- on peut personnaliser le nom (raison sociale) de façon plus explicite : "Indiquez le nom de la structure/organisme, qui apparaîtra lorsque les candidats saisiront une convention, et dans votre espace prescripteur."
- afficher une erreur si un user essaye de créer une fiche avec le même SIRET + le même nom en doublon.
- afficher dans l'idéal le nom des fiches déjà existantes pour 1 SIRET.

**Comment by JeromeBu** [comment]
Le back est dans le ticket : #1335

**Comment by JeromeBu** [comment]
à discuter sur la solution de select multiple
