### ISSUE TITLE
ETQ entreprise, je ne suis pas toujours exposée de la même façon dans les résultats de recherche

### ISSUE THREAD

**Issue by nathalie-reyre** [gip-inclusion/immersion-facile#1315]
### :thinking: Contexte et problématique (et par qui est-ce remonté ?)

 les résultats apparaissent de nouveau toujours dans le même ordre quand on lance une recherche métier + localisation  cf Boulanger + Paris + 10 km qqsoit le device utilisé 
<img width="1020" alt="Capture d’écran 2024-02-29 à 17 22 06" src="https://github.com/gip-inclusion/immersion-facile/assets/61510442/c2f51f10-ec90-45ff-b449-a49c13e832c3">

### :tada: Proposition de solution

Proposer un choix par défaut "par pertinence"  -> un nouveau bouton radio (et non "par proximité").

### Scoring : 
1. Taux de réponse aux mer. >> parmi toutes les MER d'une entreprise sur 1 an, on prend les échanges qui ont au moins une réponse de la part de l'entreprise. Ce taux est ajouté dans le score initial de l'offre. Si 100% alors +100 sur le score.
2. Est-ce que l'entreprise a déjà fait une immersion ? +10 points par immersion validée sur la dernière année

Rappel, chaque offre a un score affecté par défaut à 4.5

### Critère de succès : 
Augmentation du taux de réponse des entreprises.

**Comment by celineung** [comment]
suggestion: proposer une vue carte

**Comment by nathalie-reyre** [comment]
scoring et label à travailler en grooming le 26/03

**Comment by bbohec** [comment]
Backlog FAST >> https://trello.com/c/MuHskwqh/27-rating-des-ent-accueillantes

**Comment by bbohec** [comment]
![image](https://github.com/gip-inclusion/immersion-facile/assets/58432308/6c4aa44a-74ef-4cf5-9b61-8b0837203f6c)
![image](https://github.com/gip-inclusion/immersion-facile/assets/58432308/6132f6d2-fc9b-45fa-a150-3cda5febed67)
![image](https://github.com/gip-inclusion/immersion-facile/assets/58432308/04b530fd-743b-4b2f-a304-4cfa5edc3f88)
