### ISSUE TITLE
ETQ candidat je ne veux pas me décourager au fil des candidatures

### ISSUE THREAD

**Issue by 3lodi3** [gip-inclusion/immersion-facile#1317]
### :thinking: Contexte et problématique (et par qui est-ce remonté ?)

Les candidats se découragent car les entreprises ne leur répondent pas.

### :tada: Proposition de solution

Afficher sur la page de résultats de recherche le nombre moyen de mer candidats envoyées pour obtenir 1 réponse (si on peut le calculer via l'inbound parsing en se basant sur l'adresse mail candidat /ex).

https://www.figma.com/file/6msAgGCn4id2P3OjI4NRxP/Site---UX-design-1er-semestre-2024?type=design&node-id=1004%3A3770&mode=design&t=5ubc8ePH5wcYv6XP-1

![undraw_everywhere_together_re_xe5a(1)](https://github.com/gip-inclusion/immersion-facile/assets/76998405/c7397d22-57dc-4a11-8eaa-cce626643bc4)

**Comment by JeromeBu** [comment]
Donnée à cherché puis décider où on affiche ça précisément

**Comment by JeromeBu** [comment]
https://discord.com/channels/864451835553513474/1215323652049080330/1215323671732813934
