### ISSUE TITLE
TTU - ETQ prescripteur, j'ai le nombre d'heures et le nombre de bénéficiaires exacts dans le décompte pour la cotisation AT/MP

### ISSUE THREAD

**Issue by nathalie-reyre** [gip-inclusion/immersion-facile#1340]
### :bug: Le problème

le décompte des heures prend tous les statuts des demandes de convention 
cf 

![Image](https://github.com/gip-inclusion/immersion-facile/assets/61510442/638bd24c-bc6b-4885-b4a5-4ac0ce1dfbbb)

### :dart: Comportement attendu

il faut ne prendre en compte que la statut validé --> il ne devrait y avoir aucune heure comptabilisée pour cette structure

**Comment by Master-Touks** [comment]
Le lien du tableau : https://metabase.immersion-facile.beta.gouv.fr/dashboard/4-tableau-de-bord-agence-embarque
