### ISSUE TITLE
Création / édition d'agence dans redux

### ISSUE THREAD

**Issue by JeromeBu** [gip-inclusion/immersion-facile#1344]

**Comment by enguerranws** [comment]
Pour avoir une vue d'ensemble de ce qu'on a actuellement concernant les agences : 
- une slice agencyInfo : pour récupérer les infos publiques d'une agence (dont son adresse)
- une slice agencyAdmin : plusieurs choses relatives à l’administration des agences (récup des agences à review, edition, etc)
- plusieurs appels de gateway direct dans les composants `outOfReduxDependencies.agencyGateway` : ce serait eux qu'il faudrait passer dans redux et les regrouper avec agencyInfo (agency.slice.ts ?)
