### ISSUE TITLE
ETQ prescripteur je veux valider la convention rattachée à ma structure

### ISSUE THREAD

**Issue by cecile-dimarco** [gip-inclusion/immersion-facile#1389]
### :bug: Le problème

France Travail peut valider une convention d'une autre structure

### :footprints: Étapes pour reproduire

1. le bénéficiaire se pe connect 
2.  Le bénéficiaire initie sa convention 
3. Le bénéficiaire partage la convention (test fait avec Clément)
4. Le bénéficiaire modifie et sélectionne une Mission Locale ou APEC (par exemple) autre que FT comme structure d'accompagnement
5. La demande de convention est signée par les deux parties
6. La demande de convention est transmise pour validation à la structure sélectionnée (Mission Locale ou APEC) mais aussi au conseiller référent FT
7. Le référent France Travail valide la convention
8. La structure d'accompagnement sélectionnée découvre la validation de la convention 
9. Sur la convention, est indiquée, le nom du conseiller référent FT, et la structure prescriptrice (Mission Locale ou APEC) comme valideur
10. La convention n'apparaît que sur le TDB APEC ou Mission Locale et n'apparait sur le TDB France Travail

-->

### :dart: Comportement attendu

1. le bénéficiaire se pe connect 
2.  Le bénéficiaire initie sa convention 
3. Le bénéficiaire partage la convention
4. La structure d'accompagnement ne peut pas être modifiée 

### Screenshots

![image](https://github.com/gip-inclusion/immersion-facile/assets/134716620/9a1c834d-bdf0-4303-b745-0ead10350a73)
![image](https://github.com/gip-inclusion/immersion-facile/assets/134716620/8211da3b-8a85-4617-b581-4ed246db021a)
![image](https://github.com/gip-inclusion/immersion-facile/assets/134716620/5028e319-685a-4a23-87a0-8346856464e2)
![image](https://github.com/gip-inclusion/immersion-facile/assets/134716620/ebf494a8-c604-42d1-944e-4ddabdfd6aa2)

**Comment by nathalie-reyre** [comment]
Quand on se PE connect, il faut ne permettre que de sélectionner une agence FT y compris s'il y a une demande de modification ou un partage avec une pré sélection d'une agence de type différent.

**Comment by clement-duport** [comment]
On viens de faire un test et c'est déjà comme ça on ne peut pas sélectionner un agence autre que pole emploi quand on est PeConnect

**Comment by bbohec** [comment]
Test mise en situation.


# PE connecté
![image](https://github.com/gip-inclusion/immersion-facile/assets/58432308/9283278b-155c-4064-bc0b-62f6128a216f)
![image](https://github.com/gip-inclusion/immersion-facile/assets/58432308/b9de7361-ca66-405a-a251-10265e78d6ff)

# Non-PE connecté
![image](https://github.com/gip-inclusion/immersion-facile/assets/58432308/5f143ffb-9f2d-445a-abe7-c90ad13aa0c4)
![image](https://github.com/gip-inclusion/immersion-facile/assets/58432308/90cf4877-1f7a-4154-a4a7-1de0fdc38f97)
