### ISSUE TITLE
ETQ entreprise, quand je réponds à un candidat qui veut faire une immersion, je peux commencer une demande de convention avec des infos pré remplies concernant mon entreprise et le métier proposé

### ISSUE THREAD

**Issue by nathalie-reyre** [gip-inclusion/immersion-facile#1390]
Dans l'objectif d'augmenter la conversion entre mise en relation, réponse faite  et immersion, outiller les entreprises pour les inciter à répondre aux candidats. 
Leur permettre de générer rapidement une demande de convention avec tous les champs relatifs à l'entreprise pré complétée grâce aux informations que nous avons dans la fiche entreprise : siret,lieu de l'immersion, coordonnées du tuteur/signataire de la convention, métier choisi. tous les champs restent éditables.

**Comment by nathalie-reyre** [comment]
Possibilité de générer ces demandes de convention pré remplies depuis le tableau de pilotage des entreprises et depuis la conversation avec un candidat

**Comment by bbohec** [comment]
Dépend de #1408

**Comment by bbohec** [comment]
![Image](https://github.com/gip-inclusion/immersion-facile/assets/58432308/6cd19b97-e94d-475f-a00b-9706ed066434)



![Image](https://github.com/gip-inclusion/immersion-facile/assets/58432308/ee354d3e-2377-4e31-bd43-f6496ac56903)


![Image](https://github.com/gip-inclusion/immersion-facile/assets/58432308/6a3b6a44-7860-486c-a2d4-945ab1edc6ea)



![Image](https://github.com/gip-inclusion/immersion-facile/assets/58432308/700caac7-4baf-4ad9-90e4-c47335ccc50f)



![Image](https://github.com/gip-inclusion/immersion-facile/assets/58432308/5c7e0243-94e0-4970-8d93-1874f39b9192)

**Comment by bbohec** [comment]
Backlog FAST > https://trello.com/c/PpoXc2xZ/19-a-mettre-dans-le-backlog-github-pr%C3%A9remplir-la-convention-en-brouillon-avec-les-donn%C3%A9es-dune-mise-en-relation
