### ISSUE TITLE
ETQ entreprise, on me suggère un nombre max de mise en relation/semaine adapté à mes effectifs

### ISSUE THREAD

**Issue by nathalie-reyre** [gip-inclusion/immersion-facile#1391]
on n'affiche pas le nombre de mises en relation qu'on a défini par défaut. Sera affiché au moment des mises à jour/
Pour les entreprises qu'on a déjà chez nous, on ne touche pas pour l'instant

**Comment by JeromeBu** [comment]
c'est sur main, je ferme

**Comment by bbohec** [comment]
Backlog FAST > https://trello.com/c/ntEcAYsV/30-optimiser-le-nombre-de-mise-en-relations-avec-leffectif-de-lentreprise-ex-tpe-pme-5-max-semaine
