### ISSUE TITLE
ETQ entreprise ayant déjà accueilli en immersion, je me référence comme entreprise accueillante

### ISSUE THREAD

**Issue by nathalie-reyre** [gip-inclusion/immersion-facile#1393]
## Contexte

Les entreprises qui ont signé une demande de convention reçoivent un mail pour les inciter à se référencer comme entreprise accueillante. Le taux de conversion est bas (3,5%). 
Il faudrait l'augmenter. 
Test en modifiant le wording du mail. Ajouter peut être une relance supplémentaire.
Dépend de #1550 

## Maquettes

On commencerait à inaugurer l'onboarding entreprise avec la refonte de l'email "Establishment lead - premier rappel ".

Peut-on savoir quelle est la taille de l'entreprise en partant de son SIRET ?
Si oui, on propose deux emails distincts (à discuter ensemble)
1- petites entreprises : effectif moins de 50 personnes
2- autres : effectif supérieur ou égal à 50 personnes

1-
Objet : Merci d’avoir accueilli un candidat en immersion !
Phrase d'accroche : Participez à notre webinaire pour être accompagné sur vos futurs recrutements
Timing : 
https://www.figma.com/proto/rZtRL0ShjGKfdw43nMUPex/Site---UX-design-2nd-trimestre-2024?page-id=1107%3A1948&type=design&node-id=3067-7081&viewport=-307%2C175%2C0.5&t=AxVTWN6mhLwxSiDp-1&scaling=scale-down&starting-point-node-id=3067%3A7081&mode=design

2-
Objet : Merci d’avoir accueilli un candidat en immersion !
Phrase d'accroche : Participez à notre webinaire pour comprendre les avantages d'une politique Diversité et Inclusion
Timing : 
https://www.figma.com/proto/rZtRL0ShjGKfdw43nMUPex/Site---UX-design-2nd-trimestre-2024?page-id=1107%3A1948&type=design&node-id=3067-7255&viewport=-307%2C175%2C0.5&t=AxVTWN6mhLwxSiDp-1&scaling=scale-down&starting-point-node-id=3067%3A7081&mode=design

3-
Objet : Recrutez autrement avec l’immersion professionnelle 
Phrase d'accroche : Proposez une immersion sur notre site et découvrez de nouveaux talents !
Timing : 
https://www.figma.com/proto/rZtRL0ShjGKfdw43nMUPex/Site---UX-design-2nd-trimestre-2024?page-id=1107%3A1948&type=design&node-id=1134-281&viewport=-307%2C175%2C0.5&t=BwymOHhcnpJNGQGO-1&scaling=scale-down&starting-point-node-id=1134%3A281&show-proto-sidebar=1&mode=design

4-
Objet : Valorisez votre marque employeur avec l’immersion professionnelle
Phrase d'accroche : Proposez une immersion sur notre site et rendez vos équipes plus diverses !
Timing : 
https://www.figma.com/proto/rZtRL0ShjGKfdw43nMUPex/Site---UX-design-2nd-trimestre-2024?page-id=1107%3A1948&type=design&node-id=1137-721&viewport=-451%2C175%2C0.5&t=8BSAJbmH4dNlIQP2-1&scaling=scale-down&starting-point-node-id=1134%3A281&show-proto-sidebar=1&mode=design

### proto : 
https://www.figma.com/proto/6msAgGCn4id2P3OjI4NRxP/Site---UX-design-1er-semestre-2024?page-id=1107%3A1948&type=design&node-id=1134-281&viewport=-377%2C311%2C0.38&t=V9wuWjE1RzMBkMGu-1&scaling=scale-down&starting-point-node-id=1134%3A281&show-proto-sidebar=1&mode=design

### fichier : 
https://www.figma.com/file/6msAgGCn4id2P3OjI4NRxP/Site---UX-design-1er-semestre-2024?type=design&node-id=1134%3A281&mode=design&t=mXIOorYsst9Grw5w-1

**Comment by bbohec** [comment]
Dépend de #1550

Point d'attention > QUID des conventions anciennes qui n'ont pas le nombre d'employés de disponible?
