### ISSUE TITLE
ETQ qu'admin, je peux valider un accès à des BO d'agences sans donner les droits d'agir sur les demandes de convention

### ISSUE THREAD

**Issue by nathalie-reyre** [gip-inclusion/immersion-facile#1400]
de plus de demandes d'accès à un ou plusieurs BO de structures sont faites avec des mails qui prouvent que la personne  travaille bien pour la structure en question mais sans pour autant être présents parmi les mails des conseillers ou des valideurs de la structure. Il faudrait pouvoir créer un rôle neutre, d'observateur qui permet de voir les demandes de convention, d'en faire le pilotage mais sans avoir la main pour modifier le statut des conventions. C'est  un élément important de sécurité.

**Comment by nathalie-reyre** [comment]
#1619

**Comment by 3lodi3** [comment]
duplicate #1150
