### ISSUE TITLE
ETQ 'admin, j'ai 161 conventions à rattacher à une agence France travail, suite à la fusion entre 2 agences

### ISSUE THREAD

**Issue by nathalie-reyre** [gip-inclusion/immersion-facile#1401]
### :thinking: Contexte et problématique (et par qui est-ce remonté ?)

 fermeture de l'agence ID 733db4ba-01ce-4f6e-a144-1366d16045b0; il faudrait rattacher toutes les conventions de cette agence à l'agence 
d631bafc-a3da-4e5b-8123-fb0d59d67611

### :tada: Proposition de solution

une petite requete SQL serait bienvenue

**Comment by celineung** [comment]
modifications:
- mettre l'agence 733db4ba-01ce-4f6e-a144-1366d16045b0 au statut "closed" en DB
- rattacher toutes les conventions de 733db4ba-01ce-4f6e-a144-1366d16045b0 à d631bafc-a3da-4e5b-8123-fb0d59d67611
- rattacher les utilisateurs inclusions connectés de l'agence 733db4ba-01ce-4f6e-a144-1366d16045b0 à d631bafc-a3da-4e5b-8123-fb0d59d67611
