### ISSUE TITLE
ETQ inclusion connecté je peux avoir accès à plus de 100 agences

### ISSUE THREAD

**Issue by Jessicaceleste1** [gip-inclusion/immersion-facile#1421]
### :bug: Le problème

Message error pour se co a inclusion connect 

https://discord.com/channels/864451835553513474/867361056866435134/1216702112373936209

Certains utilisateurs IC sont liés à beaucoup d'agences.
Une utilisatrice a par exemple 170 agences.

Ces utilisateurs n'ont plus accès à leur TDB Metabase car l'url est trop longue:
![image](https://github.com/gip-inclusion/immersion-facile/assets/11294487/cd59b8f3-7cd1-4b1e-bff2-b4a19b9e3507)

**Comment by celineung** [comment]
Certains utilisateurs IC sont liés à beaucoup d'agences.
'emilie.soriaux@pole-emploi.fr' a par exemple 170 agences.

Ces utilisateurs n'ont plus accès à leur TDB Metabase car l'url est trop longue:
![image](https://github.com/gip-inclusion/immersion-facile/assets/11294487/cd59b8f3-7cd1-4b1e-bff2-b4a19b9e3507)
