### ISSUE TITLE
ETQ Entreprise, je peux connaitre l'état d'une mise en relation

### ISSUE THREAD

**Issue by bbohec** [gip-inclusion/immersion-facile#1444]
### :thinking: Contexte et problématique

Avoir pour chaque mise en relation l'état / étape du parcours de mise en relation afin de ne plus avoir d'état inconnu et un non-suivi des mises en relation qui reste un moyen d'atteindre à terme :
- un abandon de la démarche de mise en relation
- un accord pour conventionner un stage

### :tada: Proposition de solution

# Identifier les différentes étapes que pourrait avoir une mise en relation

Tableau : en cours
~~1. Initiée : premier contact par un candidat sans réponse de l'entreprise~~ (j'ai fusionné avec le statut 2 et ajouté le nombre d'échanges et la date de dernière réponse à côté)
2. Le candidat attend votre réponse :   dernier échange par un candidat
3. Vous attendez une réponse du candidat :  dernier échange par une entreprise
5. En cours de conventionnement : l'entreprise et/ou le candidat décident de lancer le parcours de conventionnement (la convention et la discussion sont liées ?) -> dépendant de la story #1697

Tableau : passé
4. Candidature refusée par l'entreprise : l'entreprise et/ou le candidat met fin à la démarche (avec une raison?) (pour l'instant j'ai mis refus par l'entreprise car c'est la seule action possible)
6. PAs de réponse récente de l'entreprise / du candidat : La mise en relation est restée Initiée / En attente trop longtemps (3 mois, 6 mois , ....) >> situation non souhaitée 

Ca donne ainsi une ouverture pour:
- de la statistique sur l'état des mises en relation
- le taux de conversion vers la convention
- une capacité de relance
- une définition plus fine du scoring des entreprises qui sont engagées

On ajoute une colonne statut au tableau metabase
On trie les résultats par statut cf plus haut
Voir comment on peut faire de la mise en forme sur metabase
Et/ou on fait plusieurs talbeaux metabase "en cours" et "archivé"

### :camera: Maquettes

proto : https://www.figma.com/proto/rZtRL0ShjGKfdw43nMUPex/Site---UX-design-2nd-trimestre-2024?page-id=3371%3A2208&node-id=3374-2210&viewport=-428%2C439%2C0.5&t=eo05rgydmgrryZX9-1&scaling=min-zoom&starting-point-node-id=3374%3A2210

fichier : https://www.figma.com/design/rZtRL0ShjGKfdw43nMUPex/Site---UX-design-2nd-trimestre-2024?node-id=3371-2208&t=BNGLrgtaTXTSrfht-1

**Comment by 3lodi3** [comment]
Lié à #1688
