### ISSUE TITLE
ETQ bizdev je veux mesurer le taux de transfo d'une entreprise qui a fait une convention, qu'on contacte pour devenir entreprise accueillante R  I:

### ISSUE THREAD

**Issue by Jessicaceleste1** [gip-inclusion/immersion-facile#1452]
### :thinking: Contexte et problématique (et par qui est-ce remonté ?)

dans la dernière MEP que nous automatisons maintenant une campagne mailing a toutes les entreprises qui réalisent des conventions sans s'être enregistrées dans le but de les inviter à s'enregistrer comme entreprises accueillantes, avons nous un moyen de mesurer le taux de transformation ?

**Comment by Jessicaceleste1** [comment]
idem que l'autre ticket, une discussion amorcée avec Jérome, donc voici le lien vers le thread discord 
https://discord.com/channels/864451835553513474/1021337221288177684/1212386529654214667

**Comment by bbohec** [comment]
#1393
