### ISSUE TITLE
ETQ bénéficiaire je n'arrive pas à compléter les champs de ma convention, c'est grisé

### ISSUE THREAD

**Issue by Jessicaceleste1** [gip-inclusion/immersion-facile#1462]
### :bug: Le problème

comportement remonté par la candidate : 
Je ne peux pas saisir mon adresse e-mail dans le formulaire de convention et cela bloque tout le processus. Impossible d'aller au-delà de 4 ou 5 caractères, le champ se grise et se bloque.

je lui ai demandé capture d'écran et lien de son formulaire : [](https://immersion-facile.beta.gouv.fr/demande-immersion?fedId=9c5c2bfa-384b-04b6-e053-0a0a88187d5c&fedIdProvider=peConnect&email=auroredelarue&firstName=AURORE&lastName=DE%20LA%20RUE&phone=&financiaryHelp=&emergencyContact=&emergencyContactPhone=&isRqth=false&birthdate=&agencyDepartment=&siret=&businessName=&businessAdvantages=&etFirstName=&etLastName=&etJob=&etPhone=&etEmail=&erFirstName=&erLastName=&erPhone=&erEmail=&immersionAddress=&immersionActivities=&immersionSkills=&sanitaryPreventionDescription=&workConditions=&dateStart=2024-03-28&dateEnd=2024-03-29&schedule=%7B%22totalHours%22%3A0%2C%22workedDays%22%3A0%2C%22isSimple%22%3Atrue%2C%22complexSchedule%22%3A%5B%7B%22date%22%3A%222024-03-28T00%3A00%3A00.000Z%22%2C%22timePeriods%22%3A%5B%5D%7D%2C%7B%22date%22%3A%222024-03-29T00%3A00%3A00.000Z%22%2C%22timePeriods%22%3A%5B%5D%7D%5D%7D
)
Effectivement lorsqu'on déroule la partie candidat c'est grisé

![image](https://github.com/gip-inclusion/immersion-facile/assets/129732318/4536a7f8-3b9f-4e7c-b8b3-2c5550dcac7e)

**Comment by celineung** [comment]
Lorsque l'on partage un lien de création de convention créé depusi Pe Connect:
- le mail n'est pas modificable
- après navigation sur le site, puis depuis le menu Candidats > Remplir la demande de convention: l'écran intermédiaire avec n'est plus affiché

**Comment by celineung** [comment]
Le champ email est volontairement désactivé dans les cas de partage de formulaire de convention créé à partir de PeConnect.
Cet email incorrect est donc celui fournit par PE.
