### ISSUE TITLE
Ajouter mtm_campaign sur les actions de mails (Brevo, interne IF)

### ISSUE THREAD

**Issue by enguerranws** [gip-inclusion/immersion-facile#1466]
https://trello.com/c/j9X43zoH/57-tracker-tous-nos-liens-mis-sites-externes-outil-ft-centre-daide

### :thinking: Contexte et problématique (et par qui est-ce remonté ?)

Actuellement, on envoi des mails d'incitation à action (mettre à jour l'entreprise, etc). Ces mails contiennent des CTA qui ne sont pas identifiés par un param `mtm_campaign`.

### :tada: Proposition de solution

Ajouter (côté templates Brevo et mails internes IF) ces params (avec une valeur pertinente) sur ces liens.
**à faire côté bizdev**
(nomenclature: https://www.notion.so/gip-inclusion/Matomo-acb07e148d9b4a1281a92e7924503674)

**Comment by Master-Touks** [comment]
- [ ] Page notion (Culture du CTA) : https://www.notion.so/gip-inclusion/Tracking-077b77e2be514affa8005d841ecfd3a5?pvs=4
- [ ] Accompagner l'équipe BizDev (Bi-weekly/Weekly/Monthly?)

**Comment by chaibax** [comment]
@NastassiaRodriguez  : peux donner la liste des emails ou il faut mettre un mtm_campaign, ici

**Comment by cecile-dimarco** [comment]
Liste des mails : 

Admin

Etablissement : suggestion MAJ / lien d'édition/ Mise en relation par mail

brevo

#116 template test Inclusion Connect nouveaux utilisateurs

#144[MER] Relance #2 (J+7) entreprises sans réponse

#139[MER] Relance entreprises sans réponse

**Comment by enguerranws** [comment]
Établissement - Suggestion de mise à jour -> transactionnel-etablissement-suggestion-mise-a-jour
Établissement - Lien d'édition -> transactionnel-etablissement-lien-edition

**Comment by Jessicaceleste1** [comment]
brevo, fait :)
