### ISSUE TITLE
NPS candidats et entreprises

### ISSUE THREAD

**Issue by 3lodi3** [gip-inclusion/immersion-facile#147]
Grooming du 11 mai 2023 :

Où afficher le NPS candidat / entreprise ?

→ Ou bien lien vers le NPS dans l’email de confirmation de signature (lien direct vers Tally).

→ Ou bien sur la page de confirmation d’enregistrement de signature.

→ Il faut pouvoir tracker le type d’utilisateur (candidat ou entreprise).

En dév : ajouter à l’email le lien vers le NPS avec les bons query params / et selon l’endroit choisi pour l’afficher, ajouter le NPS à une page existante

**Comment by 3lodi3** [comment]
https://www.notion.so/gip-inclusion/Atelier-NPS-candidats-et-entreprises-b3a0b6ee2cbb41b8a802572054df0146?pvs=4

**Comment by PierreDeNantes** [comment]
J'ai invité @celineung , @bbohec et @clement-duport sur Tally.
NPS candidat : https://tally.so/forms/nprlKZ/share
NPS Entreprises : https://tally.so/forms/wL9QbO/share

**Comment by enguerranws** [comment]
Après discussion avec @PierreDeNantes , on a un peu changé la formule (techniquement) : sur la page de convention validée, on aura qu'un NPS (le même pour tous les rôles) et on remonte à Tally le rôle dans les infos lors de la soumission (ça crée une nouvelle colonne role dans les enregistrements de Tally). 

Pour l'instant, le rôle n'est pas différencié (le magic link dans le mail ne le permet pas encore), mais c'est prévu par #574
