### ISSUE TITLE
ETQ entreprise, je peux rentrer n'importe quel n° de tel lors de mon enregistrement et idem dans admin pour nous 

### ISSUE THREAD

**Issue by Jessicaceleste1** [gip-inclusion/immersion-facile#1473]
### :bug: Le problème

Une entreprise peut indiqué un n° imcomplet de téléphone  ex  06303455 ou n'importe quoi ex : 7777 

### :dart: Comportement attendu

- [ ] On autorise les portables et fixes
- [ ] On autorise les numéros français et DOM ROM
- [ ] On autorise soit le format 10 chiffres soit le format international +33

### Screenshots

Bonnes pratiques UX

- Un champ avec sélecteur de pays / DOM ROM
- Formater le no pour permettre une relecture plus facile (ex 06 77 88 99 55 et pas 677889955)

ex : https://intl-tel-input.com/
Source ux planet https://uxplanet.org/phone-number-field-design-best-practices-23957cbd86d5

**Comment by JeromeBu** [comment]
Je retire ça des bug, pour mois c'est pas vraiment un bug. C'est connu, et c'est comme ça depuis presque 3 ans. Ca passe dans process normal. Je le mets en prêt à clarifier.
