### ISSUE TITLE
ETQ validateur d'agence PE à double niveau de validation, je ne peux pas valider une convention qui rattachée à un utilisateur PE Connecté avec conseillé référent

### ISSUE THREAD

**Issue by bbohec** [gip-inclusion/immersion-facile#1474]
### :bug: Le problème

[Une description claire et concise du problème observé](https://discord.com/channels/864451835553513474/1223260597911818300)

3 solutions:
- retirer les mails conseiller aux agences PE pour rester à 1 niveau de validation
- adapter le code pour que la situation PE connecté + agence PE soit autorisé pour validation directe sans passage par l'étape conseiller
- retirer la spécificité PE Connect / conseillé spécifique rattaché

**Proposition de Clément :** 

- [x] On vire les adresses mail conseiller concernées 
- [x] Vérifier que le bouton est bien présent sur les conventions qui posaient problème avant la suppression de l'email
- [ ] @nathalie-reyre  les prévient

**Comment by nathalie-reyre** [comment]
@clement-duport indique les agences FT concernées - on les passe à 1 niveau de validation @nathalie-reyre communique auprès des ELD concernées

**Comment by clement-duport** [comment]
j'ai supprimer les mails conseiller des agences PE qui était a double validation (18 agences concernée).
Requête jouée sur la db en prod : 
```
UPDATE "agencies"
SET "counsellor_emails" = '[]'::jsonb
WHERE CAST("counsellor_emails" AS text) ILIKE '%@%'
  AND "kind" = 'pole-emploi'
  AND "status" = 'active';
```
