### ISSUE TITLE
ETQ qu'agence qui n'est plus associée à une convention, je ne devrais pas pouvoir mettre à jour cette convention

### ISSUE THREAD

**Issue by enguerranws** [gip-inclusion/immersion-facile#1495]
2ème round du ticket #1471 : la partie update status de convention

## Description

Lorsque l'on appelle l'api pour modifier le status d'une convention, on ne se base que sur le rôle contenu dans le token. Or il se peut que la personne ayant accès à cette convention n'ait plus ce rôle et n'ait donc plus le droit de mettre à jour le statut de la convention.

## Solution 
Comme pour la #1471: vérifier que le hash du mail dans le token ait toujours le rôle spécifié dans le token

**Comment by nathalie-reyre** [comment]
@enguerranws on vient de voir ce ticket dans le vrac. Ca me semble assez touchy comme sujet . L'avais tu traité et on a juste oublié le ticket ? Sinon, à prendre en compte rapidement non ?

**Comment by bbohec** [comment]
J'ai l'impression que c'est un vieux sujet déjà réglé. A valider par la team convention pour le usecase de maj de conv.
