### ISSUE TITLE
atelier création de compte

### ISSUE THREAD

**Issue by bbohec** [gip-inclusion/immersion-facile#1498]
https://trello.com/c/KBSsCyJP/41-atelier-cr%C3%A9ation-de-compte-bonne-ou-mauvaise-id%C3%A9e-comment-faire

**Comment by enguerranws** [comment]
On prévoit un atelier ? 
Quels objectifs à viser à la fin de cet atelier ?

**Comment by enguerranws** [comment]
1. Uniformisation des JWT + atelier tech sur le modèle de données d'un compte utilisateur
2. Commencer par les utilisateurs BO ?
