### ISSUE TITLE
ETQ utilisateur, j'ai accès aux graphes du CAC à jour depuis la page budget

### ISSUE THREAD

**Issue by nathalie-reyre** [gip-inclusion/immersion-facile#1516]
### :thinking: Contexte et problématique (et par qui est-ce remonté ?)

--> la page budget https://immersion-facile.beta.gouv.fr/pages/budget permet de voir 3 graphes CAC prescripteur, CAC entreprise et CAC candidat. Mais on affiche des screens à date. La page n'est donc jamais à jour.

### :tada: Proposition de solution

 proposer une vue dynamique depuis Metabase. 
<img width="518" alt="Capture d’écran 2024-04-10 à 16 07 45" src="https://github.com/gip-inclusion/immersion-facile/assets/61510442/2e6dd28a-e0d8-4faa-8ca4-bca83f622566">

Créer une table avec les budgets reçu par IF depuis son arrivé dans le GIP et afficher le Coût produit IF sur la page pour que ce soit mis à jour régulièrement et facilement

**Comment by Master-Touks** [comment]
Étape 1 : 
- [ ] Créer la table 
- [ ] Créer le tableau metabase
- [ ] Intégrer le tableau dans la page budget
