### ISSUE TITLE
Ajouter un message sur la page de rattachement d'agences d'un user IC

### ISSUE THREAD

**Issue by celineung** [gip-inclusion/immersion-facile#1524]
### :bug: Le problème

Suite à la création de compte d'un utilisateur inclusion connect, on lui demande sur le front de préciser les agences auxquelles il est rattaché.
En parallèle, on récupère automatiquement ses agences via code Safir dans le back.

Finalement, sur le front lorsque l'utilisateur soumet les agences auxquelles il est rattaché, il peut avoir l'erreur suivante car dans le back il a déjà des agences:

![Image](https://github.com/gip-inclusion/immersion-facile/assets/11294487/1249567d-e52f-4900-8e41-ca1f61350468)

### :footprints: Étapes pour reproduire

1. Se connecter avec un compte inclusion connect avec un code safir qui a des agences
2. Une page de rattachement de agence s'affiche
3. Renseigner des agences
4. Soumettre le formulaire et constater le message d'erreur

### :dart: Comportement attendu

Ajouter un message du style "nous cherchons si vous avez des agences rattaché à votre code Safir, veuillez rafraichir cette page dans 10 secondes"

**Comment by JeromeBu** [comment]
Voilà la ce que ça donnera :

<img width="1292" alt="image" src="https://github.com/gip-inclusion/immersion-facile/assets/22095555/d4da4521-7397-49ef-a2b7-65f962a19057">
