### ISSUE TITLE
ETQ candidat, j'accède à des entreprises avec des données de contact à jour

### ISSUE THREAD

**Issue by nathalie-reyre** [gip-inclusion/immersion-facile#1529]
### :thinking: Contexte et problématique (et par qui est-ce remonté ?)

Suite à un mailing auprès de 41000 entreprises enregitrées chez nous, plus de 2000 mails sont remontés en hard bounce. On a la liste. C'est l'occasion rêvée pour faire le nettoyage de l'annuaire et éviter de proposer des entreprises dont les adresses mails ne sont pas à jour

### :tada: Proposition de solution

[4017262-6618ff6f793ca61e990f19bb-0f3PKU.csv](https://github.com/gip-inclusion/immersion-facile/files/14956911/4017262-6618ff6f793ca61e990f19bb-0f3PKU.csv)
 identifier les entreprises avec ces adresses mails pourries, les passer en non recherchables le temps d'essayer de mettre à jour leur mail. Puis supprimer définitivement celles qu'on n'a pas pu mettre à jour.

**Comment by Master-Touks** [comment]
Done ✅ UPDATE establishments
```
SET is_searchable = False,  max_contacts_per_week = 0
WHERE siret IN (
    SELECT
       e.siret
        , e.is_searchable
        , e.max_contacts_per_week
    FROM establishments_contacts ec
             LEFT JOIN establishments e ON ec.siret = e.siret
    WHERE ec.email IN (<renseigner les emails comme suit : 'example@francetravail.fr', 'test@example.org' >)
)
;
```
