### ISSUE TITLE
ETQ prescripteur mini stage CCI je veux pouvoir visualiser la classe fréquentée sur mon TDB

### ISSUE THREAD

**Issue by cecile-dimarco** [gip-inclusion/immersion-facile#1533]
### :thinking: Contexte et problématique (et par qui est-ce remonté ?)

La CCI a besoin de faire remonter des statistiques sur les classes fréquentées par les bénéficiaires des mini stages

### :tada: Proposition de solution

Pouvoir faire apparaître la classe du bénéficiaire dans le tableau de bord métabase

**Comment by cecile-dimarco** [comment]
@Master-Touks après un point avec la CCI le 10/09/2024, relance sur leur besoin d'évolution sur le tableau de bord. Faire apparaître :
- classe fréquentée
- RQTH
- Etablissement scolaire
- Code postal de l'établissement scolaire

**Comment by JeromeBu** [comment]
C'est fait, c'est dans le tableau de bord en prod
