### ISSUE TITLE
[SEO/UX/Accessibilité] ETQ de visiteur du site, je veux que les pages se chargent rapidement (7,5s aujourd'hui) R : 160000 I : 0,25 C: 80  = 32000

### ISSUE THREAD

**Issue by chaibax** [gip-inclusion/immersion-facile#1563]
Les temps de chargement des pages du site vitrine sont trop longs, en particulier sur mobile avec une connexion 4g, ou en tout cas ils sont perçu tel quel par Google : 

Source : https://pagespeed.web.dev/analysis/https-immersion-facile-beta-gouv-fr/io8nntt09s?form_factor=mobile
![Image](https://github.com/gip-inclusion/immersion-facile/assets/3593868/b5739034-13af-4e68-b3ff-9b6329a1cb7c)

Cela impact negativement le SEO,  mais aussi l'expérience utilisateur @3lodi3 

On a un First Contentful Paint a 7.6s . 
Cela est du au fait que pour servir une page statique (la home), vous utilisez la meme chose que pour les pages dynamique du site : une grosse lib javascript  https://immersion-facile.beta.gouv.fr/assets/main-45421d5c.js   

Script Evaluation = 4 369 ms

Pour info : 

![Image](https://github.com/gip-inclusion/immersion-facile/assets/3593868/616f7878-1958-4005-88d8-bf20dbec5793)

**Comment by chaibax** [comment]
![Image](https://github.com/gip-inclusion/immersion-facile/assets/3593868/37bb1a29-aadc-43aa-b018-a1ef1c558947)
![Image](https://github.com/gip-inclusion/immersion-facile/assets/3593868/9e038e14-089d-409b-9a1c-23d7dd09dca1)
![Image](https://github.com/gip-inclusion/immersion-facile/assets/3593868/a276e9ec-5b99-43e8-99c5-be97eed53615)

**Comment by JeromeBu** [comment]
on a lazy loader le swagger. On a déjà réduit de 30% le bundle. C'est pas encore top mais c'était un quick win



![Image](https://github.com/gip-inclusion/immersion-facile/assets/22095555/49d07725-8c47-4732-be9b-655fb9687c33)
