### ISSUE TITLE
ETQ agent support, suite à une erreur , quand orientation vers le bouton "contactez nous" avoir dans le mail envoyé au support le message d'erreur afin de permettre au support de prendre en charge plus rapidement le cas

### ISSUE THREAD

**Issue by Jessicaceleste1** [gip-inclusion/immersion-facile#1568]
### :thinking: Contexte et problématique

Nous avons eu une erreur 429, lors de son affichage sur l'écran de nos utilisateurs, le bouton contactez nous apparait, par conséquent, tout le monde nous a contacté, j'ai du investiguer avant de comprendre le contexte de cette erreur, ou elle apparait à quel moment

### :tada: Proposition de solution

Avoir une récap de l'erreur qui contextualise (page sur laquelle se trouve l'erreur) par défaut dans le mail lorsqu'ils cliquent sur contactez nous

**Comment by bbohec** [comment]
src/app/contents/error/textSetup.tsx

```
const contactUsButtonContent: ErrorButton = {
  kind: "secondary",
  label: "Contactez-nous",
  href: `mailto:${immersionFacileContactEmail}`,
  target: "_blank",
};
```
