### ISSUE TITLE
Préciser les champs activités/compétences sur le form de convention

### ISSUE THREAD

**Issue by 3lodi3** [gip-inclusion/immersion-facile#1580]
### :thinking: Contexte et problématique (et par qui est-ce remonté ?)

Le champ activité est cleui où le plus d'utilisateurs abandonnent le form
![Image](https://github.com/gip-inclusion/immersion-facile/assets/76998405/5734bac8-758d-4c37-a237-a0d565862833)

Les champs activités/compétences font perdre du temps aux utilisateurs.
![Image](https://github.com/gip-inclusion/immersion-facile/assets/76998405/f2375d94-c3a1-4be6-9a82-deff22352041)

### :tada: Proposition de solution

- Est-ce qu'on a besoin de séparer les deux ?
- Est-ce qu'on peut expliquer mieux ce champ comme dans la notice du cerfa papier : "Précisez les éléments clefs de la période, son contexte, les tâches confiées, les objectifs
assignés au bénéficiaire."

<img width="806" alt="Capture d’écran 2024-04-22 à 14 46 20" src="https://github.com/gip-inclusion/immersion-facile/assets/76998405/720ebcff-196c-4455-994c-d18ac60191c6">

**Comment by nathalie-reyre** [comment]
on garde bien les 2 champs. Mais on reprend l'explication du CERFA pour le champs activité
