### ISSUE TITLE
Tracker le formulaire de référencement entreprises sur matomo. R : 2000 I : 2 C:0,8 =3200

### ISSUE THREAD

**Issue by 3lodi3** [gip-inclusion/immersion-facile#1582]
### :thinking: Contexte et problématique (et par qui est-ce remonté ?)

Ce formulaire est en plusieurs étapes et ne remonte pas bien dans le module forms.
Or on a besoin d'avoir des données précises sur celui-ci pour l'améliorer.

### :tada: Proposition de solution

Tester en trackant chaque champ avec data-matomo-name ? https://fr.matomo.org/faq/form-analytics/how-do-i-track-a-multi-page-form-using-form-analytics/

**Comment by nathalie-reyre** [comment]
vérifier funnel dans le module formulaire
