### ISSUE TITLE
ETQ Analyst, je veux créer des dashboard interne directement via du code pour plus de flexibilité

### ISSUE THREAD

**Issue by Master-Touks** [gip-inclusion/immersion-facile#1587]
### :thinking: Contexte et problématique

Récemment nous avons eu de grosse lenteur sur Metabase et plusieurs fois j'ai eu des demandes sur dashboards interne à la plateforme pour des fonctionnalités qui n'étaient pas vraiment possible sur l'outil donc il a fallu trouver une solution de contournement. 

### :tada: Proposition de solution

Je voudrais pouvoir créer des tableaux via du code, qui permettrait d'intégrer les tableaux internes à IF directement dans le parcours utilisateur.

Identifier par quel tableau de bord commencer : tdb des conventions agences (se baser sur les remontées de l'xp 49 fin juin)

**Comment by nathalie-reyre** [comment]
système de pagination à créer ex nihilo. Quid du DSFR pour créer des tableaux de pilotage ? Utilisation de class utilitaires.

**Comment by bbohec** [comment]
Doublon avec #1672 ????
