### ISSUE TITLE
Synchroniser les listes de contacts avec Brevo

### ISSUE THREAD

**Issue by 3lodi3** [gip-inclusion/immersion-facile#1607]
### :thinking: Contexte et problématique (et par qui est-ce remonté ?)

Utiliser correctement les listes de contacts, attributs et segments Brevo (suite atelier FAST).
On peut commencer par la liste entreprises.

### :tada: Proposition de solution
- [ ] Créer les attributs nécessaires à l'onboarding entreprises cf : https://www.notion.so/gip-inclusion/dcd6a613f3b646ce8a57ffff1c698583?v=d1bfecb65a574b3ca8f01e2f5c3327ab&pvs=4
- [ ] Importer les contacts dans la liste entreprises : https://app.brevo.com/contact/list/id/114
- [ ] Automatiser la synchro ou créer une tâche manuelle récurrente ?
https://developers.brevo.com/docs/synchronise-contact-lists

**Comment by chaibax** [comment]
Via un CRON quotidien ou, via des events , si possible en priorité pour pouvoir lancer les premiers scenarii : 

![Image](https://github.com/gip-inclusion/immersion-facile/assets/3593868/4e3c71fc-7305-41e3-94f9-2508d435c617)

**Comment by chaibax** [comment]
Attention pour l'import en batch des entreprises deja présente : 
- check de la validité de ces emails
