### ISSUE TITLE
ETQ LES je veux suivre les conversions des entreprises qui s'engagent chez nous et font des immersions

### ISSUE THREAD

**Issue by Master-Touks** [gip-inclusion/immersion-facile#1610]
### :construction: Epic

Entre LES (Les Entreprises S'engagent) et Immersion Facilité, il y a un pont qui est créé dès l'inscription de celle-ci chez LES. 
L'objectif ici, est de pouvoir suivre les conversions dans un premiers temps et améliorer le parcours entre les deux plateformes.

### :thinking: Contexte et problématique

Jusqu'à présent (30.04.2024), un mail automatique était envoyé depuis le Brevo de LES en checkant les entreprises qui sont dites engagés chez nous et qui ne le sont pas chez LES. Aucun suivi de conversion n'avait été communiqué et donc nous voudrions commencer par cet axe avant d'attaquer l'optimisation

### :tada: Proposition de solution

Créer un tableau de bord Metabase avec le suivi depuis le lien contenant des mtm de tracking (mtm_campaign=emailing-les&mtm_kwd=Conversion-entreprises-post-engagement-lee). 

- [ ] Afficher les entreprises avec ces mtm
- [ ] Définir des règles pour le taux de conversion
Les règles à savoir si on compte comme conversion un délai maximum d'une semaine après que le lien a été envoyé ou plus si besoin
- [ ] Calculer un taux de conversions
- [ ] Ajouter des mtm sur le lien présent chez LES vers IF (https://immersion-facile.beta.gouv.fr/accueil-entreprises?mtm_campaign=les_pagehandicap_vers_immersion)
- [ ] Est-ce que les entreprises taggué LES font plus de conventions que les autres ?
Lien : 
- https://immersion-facile.beta.gouv.fr/accueil-entreprises

Prochaine étape : 
- [ ] Changer l'embed par une redirection vers le lien (https://lesentreprises-sengagent.gouv.fr/formulaire-immersions-professionnelles)

**Comment by Master-Touks** [comment]
- [] Rendre le logo LESE sur le site IF cliquable en posant un MTM pour qu'ils puissent suivre les conversion de notre site, vers leur site.
- [] intégrer le nouveau logo de LESE en png (si possible parce qu'en version dark, le logo change devient blanc).

**Comment by gargagif** [comment]
Déja couvert
