### ISSUE TITLE
ETQ équipe Annuaire des Entreprises - ajout d’un `mtm_campaign` pour l’API de recherche d’entreprise

### ISSUE THREAD

**Issue by XavierJp** [gip-inclusion/immersion-facile#1611]
### :thinking: Contexte et problématique (et par qui est-ce remonté ?)

Nous souhaiterions tracker plus finement les utilisations de notre API Recherche d’Entreprises. 

### :tada: Proposition de solution

Pourriez-vous ajouter `mtm_campaign=immersion-facilite` à la fin de l’url ?

https://github.com/gip-inclusion/immersion-facile/blob/524a2d30ee7dabd61269daef0b30b3917556e60f/back/src/domains/core/sirene/adapters/AnnuaireDesEntreprisesSiretGateway.routes.ts#L62

Les stats apparaitront ici dans la partie `Campagne` :
https://stats.data.gouv.fr/index.php?module=CoreHome&action=index&idSite=294&period=range&date=previous30#?period=day&date=2024-04-30&idSite=294&category=Referrers_Referrers&subcategory=Referrers_WidgetGetAll

**Comment by JeromeBu** [comment]
pour info @XavierJp ça vient de partir en prod, tiens nous au courant que tu le vois bien dans votre matomo

**Comment by XavierJp** [comment]
Vu dans les stats ! https://stats.data.gouv.fr/index.php?module=CoreHome&action=index&idSite=294&period=range&date=previous30#?idSite=294&period=range&date=previous30&category=Referrers_Referrers&subcategory=Referrers_Campaigns

(chiffres à multiplier par 100)
