### ISSUE TITLE
ETQ que antenne de la mission locale de Paris, je suis référencée avec le siret de la milo de Paris mais mon nom et mon adresse restent ceux indiqués lors du référencement

### ISSUE THREAD

**Issue by nathalie-reyre** [gip-inclusion/immersion-facile#1617]
I Milo ne reconnait pas les SIRET dans antennes des missions locales. De ce fait, toutes les conventions initiées à Paris par les antennes sont en erreur. 
La seule solution possible est de modifier le siret et de leur attribuer le siret de la mission locale de PARIS :  53132862300149
Attention à l'effet de bord : le changement de siret va automatiquement modifier le nom et l'adresse de l'antenne. Or nous voulons conserver le nom et l'adresse pré-existants. Vérif  de cet effet de bord faite en staging

**Comment by nathalie-reyre** [comment]
donne aux devs la liste ds siret à modifier / Script SQL à écrire

**Comment by chaibax** [comment]
Hello @nathalie-reyre , en quoi c'est lié a une action FAST vu au kickoff, ou ajouté pendant notre rituel fast sur le tableau FAST trello : https://trello.com/b/18KYeyer/kickoff-fast-if ?

**Comment by nathalie-reyre** [comment]
@chaibax cible missions locales : ça va permettre à la mission locale de Paris de conventionner via IF : gros volumes en perspective
