### ISSUE TITLE
ETQ admin je veux retrouver une convention rapidement depuis crisp

### ISSUE THREAD

**Issue by cecile-dimarco** [gip-inclusion/immersion-facile#1620]
### :bug: Le problème

Le lien qui renvoie vers le pilotage admin dans crisp n'est plus actif avec la connexion inclusion connect 

ex : https://immersion-facile.beta.gouv.fr/pilotage-convention-admin?conventionId=12e8c4ba-bb1c-48e5-85ac-ccc94cbb8a18

### :dart: Comportement attendu

En cliquant sur le lien je devrais accéder au pilotage de la convention dans admin 

### Screenshots

![Image](https://github.com/gip-inclusion/immersion-facile/assets/134716620/7f590dc4-e942-448f-a690-cb15daeabfb2)

![Image](https://github.com/gip-inclusion/immersion-facile/assets/134716620/60c8ff95-d345-42ec-8bb1-3947e58c075f)

**Comment by JeromeBu** [comment]
Je viens de faire l'essai. Et le lien fonctionne correctement. Le problème est surement différent :

je suspect que la connection n'est valable que 1h. Et il faut donc qu'on fasse en sorte que pour les admin la connection dure plus longtemps.
