### ISSUE TITLE
FIX : ETQ  admin ou prescripteur, quand je veux rendre une convention obsolète, la modale qui s'ouvre a un wording qui peut prêter à confusion car il correspond au cas d'une  modification demandée

### ISSUE THREAD

**Issue by nathalie-reyre** [gip-inclusion/immersion-facile#1624]
![Image](https://github.com/gip-inclusion/immersion-facile/assets/61510442/ae3e8559-6ab2-4d5f-b9cc-320941e061ba)

supprimer cette première modale pour que la suivante s'ouvre directement  cf

![Image](https://github.com/gip-inclusion/immersion-facile/assets/61510442/37d2a5ee-b9a6-476a-83ae-97e8ced0d648)

éventuellement, insérer dans cette modale la possibilité de relancer un signataire manquant  cf

![Image](https://github.com/gip-inclusion/immersion-facile/assets/61510442/78b9f030-7e8b-4259-be4e-9f02c8530a2b)

**Comment by 3lodi3** [comment]
duplicate #1634
