### ISSUE TITLE
ETQ candidat, je transmets à l'entreprise un message qualifié lors de la mise en relation

### ISSUE THREAD

**Issue by nathalie-reyre** [gip-inclusion/immersion-facile#1628]
### :construction: Epic

Permettre aux entreprises de suivre les mise en contact (sur un tdb) pour améliorer leur taux de réponse
[#1136](https://github.com/gip-inclusion/immersion-facile/issues/1136) 

### :thinking: Contexte et problématique

 des entreprises ne répondent pas aux candidats car le message transmis lors de la mise en relation leur donne l'impression qu'elles vont perdre du temps "mon temps est précieux même si l'immersion, c'est gratuit..."
Les entreprises attendent un message plus qualifié avec un certain nombre de renseignements. 
Les candidats ne sont pas tous en position de rédiger eux mêmes ce message. 
Nous pouvons leur faire compléter un message pré formaté afin que les entreprises aient accès à un minimum d'informations nécessaires pourqu'elles puissent leur apporter une première réponse

### :tada: Proposition de solution

**Récupérer les informations nécessaires afin de compléter le message transmis aux entreprises**

1/ dates de l'immersion
2/ objectif recherché de l'immersion/parcours du candidat
sélectionner un objectif/parmi différents proposés et une option autre avec obligation de compléter un descriptif si cette option est choisie
3/ préciser niveau d'expérience du candidat/vie professionnelle (et non par rapport au métier découvert)(débutant, junior, expérimenté, très expérimenté)
4/ coordonnées du candidat
5/ champs libre pour saisie texte personnalisé si besoin (notamment si prise de contact pour stage autre qu'une immersion pro et pourquoi avoir choisi cette entreprise particulièrement)

**Modifier texte de mise en relation afin d'y intégrer ces informations de manière très précise et de rappeler en qqs mots ce qu'est une immersion.** 

Option : 
Intégrer un module d'IA générative pour créer un message personnalisé ?

Les entreprises se plaignent de ne pas avoir suffisamment de renseignements pour pouvoir répondre aux candidats. Il faudrait a minima les dates prévues de l'immersion, préciser dans quel parcours se situe le candidat (je suis à la recherche d'un emploi, je compte me former à ce métier, j'en suis au premier stade de ma réorientation et je veux en savoir plus sur ce métier), si le candidat a déjà eu une/des expériences professionnelles ou s'il est entrant sur le marché du travail...

- [ ] Plus de champ message libre
- [ ] Dates d'immersion en optionnel (quel format ?) ou option "Je suis flexible" champ texte style "2 semaines en juin"
- [ ] Les anciennes mer : le champ est rempli par "je suis flexible"
- [ ] Reformuler les objectifs : je suis à la recherche d'un emploi, je compte me former à ce métier, j'en suis au premier stade de ma réorientation et je veux en savoir plus sur ce métier
- [ ] Coches avec choix sur l'xp de la personne (si le candidat a déjà eu une/des expériences professionnelles ou s'il est entrant sur le marché du travail...) + champ texte libre pour préciser

### :camera: Maquettes

proto : https://www.figma.com/proto/rZtRL0ShjGKfdw43nMUPex/Site---UX-design-2nd-trimestre-2024?page-id=3256%3A6913&node-id=3258-6963&viewport=-334%2C-64%2C0.45&t=N4LuqPJgbjbgW1Sl-1&scaling=min-zoom

fichier figma : https://www.figma.com/design/rZtRL0ShjGKfdw43nMUPex/Site---UX-design-2nd-trimestre-2024?node-id=3258-6963&t=SkicKgTaAhDEUgO9-1

**Email "Etablissement - mise en relation par email"** 

Objet : POTENTIAL_BENEFICIARY_FIRST_NAME POTENTIAL_BENEFICIARY_LAST_NAME vous contacte pour une demande d'immersion sur le métier de APPELLATION_LABEL

Corps :
Bonjour CONTACT_FIRST_NAME CONTACT_LAST_NAME,

Un candidat souhaite faire une immersion dans votre entreprise BUSINESS_NAME (BUSINESS_ADDRESS).

Immersion souhaitée : 
- Métier : APPELLATION_LABEL.
- Dates d’immersion envisagées : du 10 au 24 juin.
- But de l'immersion : Je suis à la recherche d'un emploi / Je compte me former à ce métier / J'en suis au premier stade de ma réorientation et je veux en savoir plus  sur ce métier.

Profil du candidat : 
- Je n’ai jamais travaillé / J’ai déjà une ou plusieurs expériences professionnelles, ou de bénévolat.
- Expériences et compétences : "textarea".

CTA : Écrire au candidat	

Ce candidat attend une réponse, vous pouvez :

- répondre directement à cet email, il lui sera transmis (vous pouvez également utiliser le bouton "Écrire au candidat" ci-dessus)

- en cas d'absence de réponse par email, vous pouvez essayer de le contacter par tel : POTENTIAL_BENEFICIARY_PHONE

Vous pouvez préparer votre échange grâce à notre [page d'aide](https://immersion-facile.beta.gouv.fr/aide/article/etudier-une-demande-dimmersion-professionnelle-1ehkehm/).

Bonne journée,
L'équipe Immersion Facilitée

**Comment by 3lodi3** [comment]
- [ ] Template d'email à jour à rédiger
- [ ] Bizdev à prévenir
- [ ] articles d'aide helpdesk à modifier

**Comment by enguerranws** [comment]
@nathalie-reyre on supprime le champ pour renseigner un CV en ligne (ou lien linkedin) ?

**Comment by nathalie-reyre** [comment]
@enguerranws vaut mieux le laisser pour l'instant

**Comment by enguerranws** [comment]
@nathalie-reyre j'ai l'impression que ce ticket ne concerne que la MER par email (et ne doit pas impacter les formulaires de mise en relation téléphone et en personne), tu me confirmes ?
