### ISSUE TITLE
Remplacer l'article helpdesk no 3 mis en avant dans le footer

### ISSUE THREAD

**Issue by 3lodi3** [gip-inclusion/immersion-facile#1630]
### :thinking: Contexte et problématique (et par qui est-ce remonté ?)

L'article no 3 pointe vers un lien mort.

![Image](https://github.com/gip-inclusion/immersion-facile/assets/76998405/30592310-0d80-4204-82d9-558f60438e62)

### :tada: Proposition de solution

Le remplacer par :

Titre bleu : Comment signer ma convention ou envoyer un lien de signature ?

Texte : Vous ne retrouvez pas le mail permettant de signer votre convention : voici comment faire pour signer votre convention.

URL : https://aide.immersion-facile.beta.gouv.fr/fr/article/comment-signer-ma-convention-ou-envoyer-un-lien-de-signature-125bxxd/

**Comment by clement-duport** [comment]
@3lodi3 

J'ai modifier le texte que tu avais fourni dans la carte pour garder le même principe que pour les autres cartes.
C'est-à- dire que le texte correspond au texte de l'article du helpdesk.

ça donne ça : 

![Image](https://github.com/gip-inclusion/immersion-facile/assets/104081060/6f39c02d-8cac-4a23-8b8e-b3279e6d3bde)
