### ISSUE TITLE
Email de relance prescripteur : remettre le lien magique

### ISSUE THREAD

**Issue by 3lodi3** [gip-inclusion/immersion-facile#1633]
### :thinking: Contexte et problématique (et par qui est-ce remonté ?)

lorsqu'un prescripteur envoie une relance à un signataire, le mail ne contient pas le lien magique de signature électronique

![Image](https://github.com/gip-inclusion/immersion-facile/assets/76998405/9ce37cdf-db0d-43c2-8da2-b6fe3155433f)

Contexte : résoudre les 40% de tickets liés au lien de signature (signature, modif, renouvellement)
https://docs.google.com/presentation/d/1yFDutqnM4QPtjO03C6gaFwo0jWNgNilxywqopVxDoCI/edit#slide=id.p

### :tada: Proposition de solution

![Image](https://github.com/gip-inclusion/immersion-facile/assets/76998405/bedc92bf-c1f1-4508-a7f0-d6cbe218e5c9)

**Comment by gargagif** [comment]
Obsolète ? cf #2179

**Comment by gargagif** [comment]
Remplacé par #2179
