### ISSUE TITLE
ETQ prescripteur je veux voir les conventions des structures d'accompagnement dans mon tableau de bord

### ISSUE THREAD

**Issue by Sylvieleb** [gip-inclusion/immersion-facile#1638]
### :bug: Le problème

Les prescripteurs qui portent des structures d'accompagnement ne voient pas dans leur tableau de bord les conventions de ses structures à valider. 
Pour valider les conventions les prescripteurs doivent le faire depuis un mail que nous leur envoyons. 
Ce mail n'est pas toujours vu car, si le prescripteur nous écoute, il gère ses conventions à l'aide du tableau de bord.

### :footprints: Étapes pour reproduire

<!-- Étapes pour reproduire le comportement:
La structure d'accompagnement = Resto Bistro Coop de Maurepas Pépites!
Le prescripteur = Agence France Travail Rennes Nord

1. La structure d'accompagnement reçoit un mail pour rendre éligible la convention
2. La structure d'accompagnement rends éligible la convention
3. un mail est envoyé au prescripteur pour prévenir qu'il faut étudier la convention
4. la convention n'est pas visible dans le tableau de bord du prescripteur
5. si le prescripteur gère les conventions uniquement avec le tableau de bord il ne verra jamais cette convention

### :dart: Comportement attendu

Les conventions portées par une structure d'accompagnement sont visibles dans le tableau de bord du prescripteur.
Le prescripteur peut valider la convention depuis le tableau de bord une fois que la structure d'accompagnement l'a rendue éligible

### Screenshots
![FireShot Capture 018 - PMSMP_ Immersion Facile - immersion-facile beta gouv fr](https://github.com/gip-inclusion/immersion-facile/assets/156312559/56d03ff9-5824-48e4-8829-e1ce1b802a79)

![FireShot Capture 019 - Admin_ validation d'agence - PMSMP_ Immersion Facile_ - immersion-facile beta gouv fr](https://github.com/gip-inclusion/immersion-facile/assets/156312559/d4746883-3172-4442-8c56-9021cc84a4fd)

**Comment by bbohec** [comment]
Dans le TBD metabase convention pour agences, si l'agence rattachée à la convention est elle aussi rattachée à une autre agence (prescriptrice) alors il faut la rendre disponible pour l'utilisateur qui a des droits sur cette agence afin qu'il puisse la voir et la piloter pour pouvoir la valider sans utiliser le lien magique de validation

**Comment by bbohec** [comment]
Question Metabase à review avant de remplacer la question dans le tableau de bord convention prescripteur.
https://metabase.immersion-facile.beta.gouv.fr/question/1697-build-view-conventions-avec-droits-agence-accompagnatrice

Choisir un userId qui a des droits sur des agences en direct ou bien qui est validateur sur une agence qui a une agence accompagnatrice. L'agence accompagnatrice a un colonne `refers_to_agency_id` qui pointe sur l'agence qui doit porter les droits validateurs.
