### ISSUE TITLE
Erreur sur les coordonnées de l'entreprise

### ISSUE THREAD

**Issue by 3lodi3** [gip-inclusion/immersion-facile#1640]
### :bug: Le problème

Erreur dans l'accordéon "Coordonnées de l'entreprise" sur le form demande de convention alors qu'aucun champ n'est en erreur à l'intérieur.

### :footprints: Étapes pour reproduire

Étapes pour reproduire le comportement:
1. Aller sur https://immersion-facile.beta.gouv.fr/demande-immersion?email=&firstName=&lastName=&phone=&financiaryHelp=&emergencyContact=&emergencyContactPhone=&isRqth=false&birthdate=&agencyDepartment=&siret=&businessName=&businessAdvantages=&etFirstName=&etLastName=&etJob=&etPhone=&etEmail=&erFirstName=&erLastName=&erPhone=&erEmail=&immersionAddress=&immersionActivities=&immersionSkills=&sanitaryPreventionDescription=&workConditions=&dateStart=2024-05-17&dateEnd=2024-05-18&schedule=%7B%22totalHours%22%3A0%2C%22workedDays%22%3A0%2C%22isSimple%22%3Atrue%2C%22complexSchedule%22%3A%5B%7B%22date%22%3A%222024-05-17T00%3A00%3A00.000Z%22%2C%22timePeriods%22%3A%5B%5D%7D%2C%7B%22date%22%3A%222024-05-18T00%3A00%3A00.000Z%22%2C%22timePeriods%22%3A%5B%5D%7D%5D%7D#
2. Cliquer sur Coordonnées de l'entreprise
3. Cliquer dans le champ SIRET
4. Il y a l'erreur 'Erreur' sur l'accordéon Coordonnées de l'entreprise

4. bis : même comportement rencontré par une utilisatrice qui avait mis un SIRET valide dans le champ mais qui avait tardé à valider le formulaire (plusieurs jours)
-> le champ SIRET a été reconnu, les champs raison sociale et adresse remplis, puis le champ SIRET est passé en erreur.

### :dart: Comportement attendu

Il ne devrait pas y avoir d'erreur juste parce qu'on est entré puis sorti du champ ou qu'on a attendu avant de valider le form.

### Screenshots

Cas 1
![Image](https://github.com/gip-inclusion/immersion-facile/assets/76998405/5dff9022-2f8b-4f1c-89d7-aa5dcd26549b)

Cas 2

![Image](https://github.com/gip-inclusion/immersion-facile/assets/76998405/dc7d72e2-f337-4c4f-8d88-a073b3c728b7)

![Image](https://github.com/gip-inclusion/immersion-facile/assets/76998405/f9524b92-d8b1-4ab8-adf8-71d731f8a9c2)

**Comment by enguerranws** [comment]
En suivant les instructions données, on arrive pas à reproduire le problème, je passe en stand-by.

**Comment by clement-duport** [comment]
Je supprime, on recréera si le problème ce présente à nouveau
