### ISSUE TITLE
Relances SMS avec téléphones mobiles DOM/TOM

### ISSUE THREAD

**Issue by bbohec** [gip-inclusion/immersion-facile#165]

**Comment by bbohec** [comment]
Tu peux me mettre tes observations @Hervelallemand974 ici

**Comment by Hervelallemand974** [comment]
**_Indicatif international SMS_** 

Il existe un moyen très simple de connaître l'origine géographique de votre correspondant en regardant les 4 premiers chiffres de son numéro. Voici les indicatifs correspondant au DOM et aux collectivités territoriales.

0639 : vous téléphonez à Mayotte => remplacer 33 par 269
0690 ou 0691 : vous téléphonez en Guadeloupe => remplacer 33 par 590
0694 : vous téléphonez en Guyane => remplacer 33 par 594
0696 ou 0697 : vous téléphonez en Martinique => remplacer 33 par 596
0692 ou 0693 : vous téléphonez à la Réunion => remplacer 33 par 262

**Comment by bbohec** [comment]
Tests:
Mayotte  => l'indicatif semble pas bon, remplacé par 262 identique La Réunion
Guadeloupe => OK
Guyane => OK
Martinique => Soft bounce sur le numéro de test
La Réunion => to do
