### ISSUE TITLE
Activation recherche par scoring par défaut dans la page recherche R:24000 I: 3 C: 0,25 = 18 000

### ISSUE THREAD

**Issue by bbohec** [gip-inclusion/immersion-facile#1656]
https://trello.com/c/MuHskwqh/27-rating-des-ent-accueillantes

La recherche par scoring est disponible en API mais elle n'est pas en place pour dans l'interface de la recherche par défaut suite à la problématique de performance/crash rencontrée lors de la MEP de #1315 .
Un fix a été déployé mais on a pas réactivé la recherche par scoring par défaut pour voir si ça a un impact et si on tient niveau perf/stabilité d'IF.

**Comment by nathalie-reyre** [comment]
test de charge à faire manuellement via l'API. Feature flag à ajouter pour neutraliser le mode par scoring si besoin

**Comment by bbohec** [comment]
Ajouter un feature flag + faire un test de charge manuel ou auto

**Comment by bbohec** [comment]
https://github.com/gip-inclusion/immersion-facile/tree/main/__tests__/load

**Comment by nathalie-reyre** [comment]
faire un ticket de bug sur la perfo
