### ISSUE TITLE
Nurturing: Envoyer email de nurturing puis tracker le taux de lecture/clics/visitent des mails aux entreprises & aux candidatis

### ISSUE THREAD

**Issue by bbohec** [gip-inclusion/immersion-facile#1674]
https://trello.com/c/ZV4TfDMJ/50-nurturing-envoyer-email-de-nurturing-puis-tracker-le-taux-de-lecture-clics-visitent-des-mails-aux-entreprises-aux-candidatis

**Comment by chaibax** [comment]
C'est pas du produit, on pourra faire ca de facon autonome via Brevo, je close
