### ISSUE TITLE
ETQ entreprise, j'ai des messages pré-formatés pour répondre aux candidats plus rapidement

### ISSUE THREAD

**Issue by 3lodi3** [gip-inclusion/immersion-facile#1688]
### :thinking: Contexte et problématique

Les entreprise ne répondent pas assez aux candidats (17% de taux de réponse)

### :tada: Proposition de solution

Proposer des réponses rapides au candidat en passant par un mailto :
- réponse libre
- demande de convention pré-remplie
- refus de la candidature : pour pouvoir transformer ce refus en statut de mer, on utilisera pas un mailto mais un formulaire pour choisir le motif de refus dans une modale (côté entreprise) > sauvegarde le refus + transmet l'email au candidat.

Choix possibles pour le motif de refus :
- l’entreprise estime ne pas être en capacité de vous aider dans votre projet professionnel,
- l’entreprise traverse une période chargée et n’a pas le temps d’accueillir une immersion.
- Autre + champ libre

### :camera: Maquettes

proto : https://www.figma.com/proto/rZtRL0ShjGKfdw43nMUPex/Site---UX-design-2nd-trimestre-2024?page-id=3371%3A2208&node-id=3374-2210&viewport=-294%2C341%2C0.5&t=WOn15qc6rPe2miKo-1&scaling=min-zoom&starting-point-node-id=3374%3A2210

fichier : https://www.figma.com/design/rZtRL0ShjGKfdw43nMUPex/Site---UX-design-2nd-trimestre-2024?node-id=3371-2208&t=BNGLrgtaTXTSrfht-1

**Comment by 3lodi3** [comment]
Lié à #1444

**Comment by JeromeBu** [comment]
Cette issue concerne uniquement les boutons pour envoyer les emails, avec des texts prérempli. 

Il n'y a pas de gestion de status à faire ici. 
C'est l'object d'une autre issue :

**Comment by enguerranws** [comment]
J'ai un doute sur le contenu du mail proposé à l'entreprise qui accepte la candidature et propose au bénéficiaire de compléter la convention : on parle et on signe en tant qu'IF, alors que c'est supposé être un message de l'entreprise au bénéficiaire ?

**Comment by enguerranws** [comment]
Il faut qu'on gère le statut pour le refus de la candidature (usecase back pour sauvegarder refus + justification).

**Comment by nathalie-reyre** [comment]
ticket #1800 traité en même temps que celui-ci
