### ISSUE TITLE
ETQ prescripteur, je veux savoir si ma convention est bien arrivée dans les applications tierces (PART 1)

### ISSUE THREAD

**Issue by 3lodi3** [gip-inclusion/immersion-facile#1689]
### :thinking: Contexte et problématique (et par qui est-ce remonté ?)

ETQ prescripteur je ne sais pas si ma convention est bien arrivée dans DUNE, MILO etc.

### :tada: Proposition de solution

Afficher la date/heure de synchro + l'application tierce + type erreur 

Ajouter en gros : si vous avez synchronisé la convention et qu'elle est toujours en erreur, le problème vient de l'application tierce + mailto vers le support concerné.

- [ ] Faire la question qui donne le tableau des conventions en erreur sur la prod et pas la db nightly

### Maquette
https://www.figma.com/proto/rZtRL0ShjGKfdw43nMUPex/Site---UX-design-2nd-trimestre-2024?page-id=3514%3A3886&node-id=3514-3887&viewport=467%2C169%2C0.25&t=iuJf32KuV5Nin2qj-1&scaling=min-zoom&content-scaling=fixed

**Comment by 3lodi3** [comment]
lié à #1805

**Comment by nathalie-reyre** [comment]
création d'un tableau du flux avec filtres erreur/succès et historique des évenements.

**Comment by nathalie-reyre** [comment]
travail de renommage de la table saved errors

**Comment by clement-duport** [comment]
- [ ] Stocker les appels en succès et pas seulement les erreurs
- [ ] renomer saved error en partner_broadcasts 
- [ ] remonter dans le tbd seulement le dernier élément pour chacune des conventions
- [ ] rajouter un filtre métabase pour filtrer les convention en erreurs
- [ ] changer le wording des tab dans le tdb agence
- [ ] rajouter la date de synchro avec nom de l'application tiers
