### ISSUE TITLE
ETQ que nouvelle entreprise, je dois m'inscrire sans pwd avant  de déposer une 1e offre, référencer mon entreprise, ou signer une  premiere convention  R:21000 I:2 C:0,8 = 33600

### ISSUE THREAD

**Issue by chaibax** [gip-inclusion/immersion-facile#1692]
FAST 
cc @3lodi3 
### :thinking: Contexte et problématique

Aujourd'hui, il y a plusieurs parcours possibles pour signer une convention, référencer son entreprise, avoir accès à son espace, ou déposer une 1e offre. 

On peut le faire avec en ouvrant un compte (avec inclusion connect), ou pas . 

### :tada: Proposition de solution

Il faut s'inscrire pour déposer une 1e offre, référencer son entreprise, ou signer une convention :  
On peut s'inscrire avec un magique link 

Ensuite, dans son espace entreprise, on peut faire les actions clefs : 
- déposer une 1e offre s'il n'y a pas d'offre sur le site 
- modifier ses offres si on a déjà des offres , ou eéchanger avec un candidat
- signer une convention  dans tous les cas 

### :camera: Maquettes

flows entreprise : https://www.figma.com/proto/rZtRL0ShjGKfdw43nMUPex/Site---UX-design-2nd-trimestre-2024?page-id=3259%3A10514&node-id=3260-1102&viewport=-950%2C297%2C0.5&t=pS4eOwxmQxXEGJMI-1&scaling=min-zoom

**Comment by 3lodi3** [comment]
@nathalie-reyre on a fait un mix des deux : on propose une action mais on demande au moins l'email avant d'avancer dans le formulaire, ce qui nous permet de le valider et d'éviter tous les problèmes liés à la délivrabilité, sans rentrer dans la lourdeur d'une création de compte avec mot de passe. On en discute demain avec tout le monde.

**Comment by gargagif** [comment]
Obsolète pour les entreprises, à adapter au parcours candidat
