### ISSUE TITLE
ETQ qu'utilisateur connecté; je veux rester connecté le plus longtemps possible  R :16000 I:0,5 C:100 =8000

### ISSUE THREAD

**Issue by chaibax** [gip-inclusion/immersion-facile#1694]
FAST

### :thinking: Contexte et problématique

ETQ qu'entreprise on ne sait pas tooujours avec quel email on a fait tel ou tel action sur le site, et parfois , on ne connais pas son pwd
### :tada: Proposition de solution

Comme sur jeveuxaider.gouv.fr on est connecté le plus longtemps possible sur le site (max life time pour le cooke de session de connexion)

**Comment by nathalie-reyre** [comment]
A discuter avec les devs. Pas sécure en termes de sécu à mon sens
