### ISSUE TITLE
Lier une convention initiée à partir d'une mise en relation par les ID de la mer et de la convention

### ISSUE THREAD

**Issue by 3lodi3** [gip-inclusion/immersion-facile#1697]
### :thinking: Contexte et problématique (et par qui est-ce remonté ?)

On ne peut pas connaître le taux de conversion mer -> convention + toutes les métriques associées (nombre d'échanges, temps entre mer et convention...) 

### :tada: Proposition de solution

Lorsqu'on crée une convention à partir d'un mer (événement : READY_TO_SIGN), fournir l'ID de la mer pour gardent le liant mer - convention.
On ne change rien au cycle de validation de la convention, mais on peut avoir une info additionnelle : cette convention est liée à une mer ID XXX.

**Comment by nathalie-reyre** [comment]
pour bien comprendre @3lodi3  quand une convention est créée par l'entreprise à partir d'une conversation ?
