### ISSUE TITLE
ETQ admin, je peux choisir le niveau d'alerte du bandeau  lorsque les admins souhaitent diffuser un message

### ISSUE THREAD

**Issue by Jessicaceleste1** [gip-inclusion/immersion-facile#1703]
### :thinking: Contexte et problématique (et par qui est-ce remonté ?)

ETQ utilisateurs, je ne veux pas avoir de bandeau rouge lorsque les admins souhaitent diffuser un message.

### :tada: Proposition de solution

Avoir la possibilité d'avoir une autre couleur en fond, ou un autre style de bandeau plus doux.

L'idéal serait d'utiliser le composant "bandeau d'information importante" (dispo en bleu uniquement) -> https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/bandeau-d-information-importante

**Comment by nathalie-reyre** [comment]
besoin pour le 15/08
