### ISSUE TITLE
ETQ que prescripteur je ne comprends pas comment c'est possible de recevoir une demande de convention antidatée

### ISSUE THREAD

**Issue by Jessicaceleste1** [gip-inclusion/immersion-facile#1715]
### :thinking: Contexte et problématique (et par qui est-ce remonté ?)

Dans ce cas d'espèce, le DE a initialisé seule une convention d'immersion  le 17/05 dernier pour un démarrage le 13/05 et une fin prévue le 17/05. Il a réalisé l'immersion sans la validation de l'entreprise ni celle de son AFT (Lisieux)
Le site IF a donc techniquement autorisé l'initialisation d'une convention d'immersion rétroactivement alors qu'AUDE DE/MAP ne le permet pas. IF devrait également être bloquant.

Or le DE ne peut pas ignorer que sa convention doit être validée pour la  démarrer comme le précise le site

Il est obligatoire d'avoir une convention validée pour démarrer une immersion.

Peut être conviendrait il  de préciser : validée par la structure d'accueil et le structure d'accompagnement pour renforcer l'alerte;
Pour ma part , je conclurai au refus de la convention d'immersion compte tenu du contexte 

### :tada: Proposition de solution

Avoir un système de blocage à minima par ex 48h d'antidate max dans ce cas demande le 17 pour un démarrage le 13....

**Comment by nathalie-reyre** [comment]
il faudrait même n'autoriser ce type de création qu'aux prescripteurs/agences d'accompagnement (mais cela sous tend la création d'une demande de convention tagguée en fonction de qui la crée)

**Comment by gargagif** [comment]
Couvert par #1698
