### ISSUE TITLE
ETQ personne inclusion connecté, je ne suis pas sensé prendre d'erreur de redirection

### ISSUE THREAD

**Issue by JeromeBu** [gip-inclusion/immersion-facile#1717]
### :bug: Le problème

On a régulièrement des erreurs d'inclusion connect.

### :footprints: Étapes pour reproduire

Souvent c'est quand on reviens sur le site après plusieurs heure. On se retrouve déconnecté de Inclusion connect et on prend ce message bizarre (voir les screen shots)

### :dart: Comportement attendu

On ne devrait pas avoir ces erreurs

### Screenshots

<img width="1146" alt="image" src="https://github.com/gip-inclusion/immersion-facile/assets/22095555/b30e9fe9-4e73-4621-b898-49d6e4d7fa40">

**Comment by JeromeBu** [comment]
autre cas : on charge la page et on tombe direct là dessus : 
<img width="1304" alt="image" src="https://github.com/gip-inclusion/immersion-facile/assets/22095555/fa6704a3-6380-4c66-acb8-5a8d6d0232a6">

**Comment by enguerranws** [comment]
Investigation : 
- après plusieurs tests d'invalidation du payload en local storage
- si on créé un token avec une expiration courte (voire déjà expirée)
- on déclenche la mécanique de redirection

Cette mécanique est pratique dans le cas où on déclenche à la main la demande de déconnexion, mais il faudrait la distinguer de l'expiration du token inclusion connect pour proposer un autre comportement. 

Je ne sais pas pourquoi c'est apparu récemment par contre.
