### ISSUE TITLE
ETQ DRH france travail, j'ai besoin de suivre les agences entreprises accueillantes

### ISSUE THREAD

**Issue by Jessicaceleste1** [gip-inclusion/immersion-facile#1720]
### :construction: Epic

Possible d'avoir un 2ND  tableau de bord france travail agences entreprises accueillantes : https://metabase.immersion-facile.beta.gouv.fr/dashboard/139-tdb-agences-ft-enregistrees-comme-entreprises-accueillantes ou les 2 fusionnés, identique à celui de La Poste : https://metabase.immersion-facile.beta.gouv.fr/dashboard/105-suivi-la-poste

### :thinking: Contexte et problématique

Besoin d'augmenter le nombre d'entreprises accueillantes sur nos métiers en tension et celui de conseiller en insertion professionnelle en est un.

**Comment by nathalie-reyre** [comment]
il faut qu'on répertorie tous les différents tableaux de bord qui ont été crées pour suivre tel ou tel groupe (@antoineferrierbeta @Jessicaceleste1 @NastassiaRodriguez @SlimanCA )

**Comment by Jessicaceleste1** [comment]
pour ma part, j'utilisais la poste et maintenant que FT, j'ai vite fais créer les autres qui se trouve ici : 
il faudrait faire un cumul des 2 board de la poste et de FT https://metabase.immersion-facile.beta.gouv.fr/collection/166-suivi-referencement-entreprises-accueillantes

**Comment by NastassiaRodriguez** [comment]
> il faut qu'on répertorie tous les différents tableaux de bord qui ont été crées pour suivre tel ou tel groupe (@antoineferrierbeta @Jessicaceleste1 @NastassiaRodriguez @SlimanCA )
Voici le lien où tous nos tableaux sont recensés 
https://metabase.immersion-facile.beta.gouv.fr/dashboard/188-menu-recherche-entreprise?tab=10-page-2
