### ISSUE TITLE
Mettre à jour les données métiers en base par celles du ROME 4

### ISSUE THREAD

**Issue by 3lodi3** [gip-inclusion/immersion-facile#1723]
### :thinking: Contexte et problématique

Il nous manque des codes dans le ROME 3

### :tada: Proposition de solution

Passer au référentiel ROME 4
Il faut un script pour màj les données

**Comment by enguerranws** [comment]
1 - s'assurer que la structure / nomenclature est identique (changement de données)
2 - l'injecter via un fichier (csv) dans notre db pour mettre à jour nos données (public_appellations_data, etc)

**Comment by celineung** [comment]
Docs Rome 4: https://www.data.gouv.fr/fr/datasets/repertoire-operationnel-des-metiers-et-des-emplois-rome/#/community-resources

**Comment by enguerranws** [comment]
Info : Rome 3 coupé en novembre.

**Comment by celineung** [comment]
API : https://francetravail.io/compte/applications/2428

**Comment by celineung** [comment]
```
curl --request GET \
  --url 'https://api.francetravail.io/partenaire/rome-metiers/v1/metiers/appellation?champs=libelle,code,metier(code,libelle)' \
  --header 'Accept: application/json' \
  --header 'Authorization: Bearer your_token' 
```
