### ISSUE TITLE
Identifier les mauvais emails en base / campagnes

### ISSUE THREAD

**Issue by enguerranws** [gip-inclusion/immersion-facile#1729]
### :bug: Le problème

Nous envoyons des mails à des adresses dont on ne peut s'assurer de la qualité.
Ça pose plusieurs soucis : 
- une campagne, envoyée en one-shot produit 2300 hardbounce d'un coup : cela peut engendrer des réactions de la part des serveurs de réception qui, vu que c'est sur un délai court, pourrait prendre ça comme une tentative de spam et nous flagger comme spammeur pour toutes les adresses de leur serveur
- idem mais avec moins de volume pour les scripts auto (reminders, etc)
- au niveau fonctionnel (au niveau transactionnel) et pour le métier, on a des entreprises en base avec un mail qui ne fonctionne pas

### Que peut-on faire ?

1. identifier les mails qui n'existent pas. Ex: Brevo peut nous retourner le code `USER` pour un hardbounce concernant un utilisateur inconnu sur le serveur (= mail qui n'existe pas)
2. nettoyer nos listings de campagnes d'emailing
3. faire le lien entre ces mails et les entreprises qu'on a en base et en proposer une vue (metabase ?)

Utiliser le webhook de brevo pour récupérer les emails en hard bounce et en faire une vue metabase

**Comment by enguerranws** [comment]
En jouant avec l'API Brevo `https://api.brevo.com/v3/smtp/blockedContacts` , voici un csv contenant les mails flaggés en hard bounce par Brevo depuis le 1er janvier 2022.

[suspicious-emails.csv](https://github.com/gip-inclusion/immersion-facile/files/15485130/suspicious-emails.csv)

A prendre avec des pincettes : à ce stade, on ne connait pas la raison du bounce, mais ce sont des mails suspects.

**Comment by enguerranws** [comment]
J'ai joué avec l'API `https://developers.brevo.com/reference/getemaileventreport-1` en requetant tous les événements hard bounce sur les 90 derniers jours et j'ai mis ça dans un json. Les `reason` sont intéressants : à part hotmail qui nous renvoie simplement "hard bounce" (lien de [quelqu'un qui a un problème similaire](https://answers.microsoft.com/en-us/outlook_com/forum/all/emails-keep-bouncing-back-when-sent-to-hotmailcom/9e076877-43fc-4c44-9458-48168c7266b9)) (sur la période, ça représente 2-3 éléments je crois), le reste est bien qualifié : adresse qui n'existe pas, problème de config sur serveur de reception, etc.

[hard-bounce-data.json](https://github.com/gip-inclusion/immersion-facile/files/15486967/hard-bounce-data.json)

**Comment by JeromeBu** [comment]
Concrètement :
Est-ce que c'est dans cette issue qu'on se branche aux webhooks de Brevo pour récupérer les status dans chaque notif envoyé ? 

@enguerranws

**Comment by nathalie-reyre** [comment]
Un ticket à créer pour mettre à jour les mails contact des entreprises inscrites chez nous
