### ISSUE TITLE
ETQ utilisateur et acteur d'une demande de convention, je reçois un mail spécifique pour m'informer que la demande de convention a été modifiée par un autre acteur et que je dois la signer de nouveau

### ISSUE THREAD

**Issue by nathalie-reyre** [gip-inclusion/immersion-facile#174]
- création d'un nouvel événement : notification signature après modification
- création d'un nouvel template d'email
- Wording du nouveau template

**Bonjour [acteur concerné], 
La demande de convention pour l'immersion de [name_beneficiary] au sein de [establishement] vient d'être modifiée.

Action attendue  : 
Vérifiez  si qui a été modifié vous convient. 
Si c'est la cas,  confirmeZ votre accord en signant de nouveau cette demande. 
Si la modification ne vous convient pas, vous pouvez relancer des modifications.

Bouton (relire et signer la demande de convention).**

Bien cordialement, 

L'équipe d'Immersion Facilitée

**Comment by bbohec** [comment]
Exemple du rendu du mail.

![image](https://github.com/gip-inclusion/immersion-facile/assets/58432308/569e5d58-670e-4a6f-85ab-27db37b353a7)
