### ISSUE TITLE
[EPIC] Ne plus afficher le broadcast des conventions en succès dans le tableau Metabase des conventions en erreur

### ISSUE THREAD

**Issue by celineung** [gip-inclusion/immersion-facile#1746]
### :thinking: Contexte et problématique (et par qui est-ce remonté ?)

Actuellement dans le tableau Metabase des conventions en erreur, nous remontons la dernière erreur qui a eu lieue pour l'envoi d'une convention, même si cet envoi a pu se faire correctement plus tard.

Elle apparait toujours dans le tableau de bord comme une convention en erreur alors que ce n'est plus le cas.

Les prescripteurs doivent marquer la demande comme traitée pour l'enlever de ce tableau.

### :tada: Proposition de solutions

--> A partir de ces propositions, on peut construire la vue view_conventions_errored pour ne récupérer que les conventions toujours en échec aujourdh'ui.

US  : 
- bouton relancer la convention sur l'espace prescripteur
<img width="1275" alt="Capture d’écran 2024-06-18 à 10 45 49" src="https://github.com/gip-inclusion/immersion-facile/assets/76998405/036269c5-5860-465c-8ac2-69580e10b173">

- ne pas faire apparaître les conv en erreur si elles ont eu un succès derrière
- stocker les appels en succès et pas seulement les erreurs

**Comment by nathalie-reyre** [comment]
pour moi, il faut les  3 ensemble pour proposer une solution parfaite. En effet, si un conseiller I Milo créée un établissement dans I Milo alors que la demande de convention est déjà créée, la convention ne pourra remonter dans I  Milo que si on rejoue l'appel API. 
Suggestion de Ben sur la proposition 3 : limiter la possibilité de lancer une synchro/convention pour un temps donné afin de réduire le retour à la  synchronisation compulsive
