### ISSUE TITLE
ETQ victor, j'ai accès à des données d'un tableau de bord metabase via l'API de metabase

### ISSUE THREAD

**Issue by JeromeBu** [gip-inclusion/immersion-facile#1748]
Il avait été envisagé une connection via l'API metabase mais finalement après discussion avec @vperron on préfère partir sur un développement de point API custom.

**Comment by vperron** [comment]
Après discussion avec @JeromeBu il en ressort que:
- Metabase ne permet de limiter les droits des API Token qu'à des tables ou vues SQL spécifiques
- Il faudrait donc développer une vue spéciale rien que pour cette usage
- Il est au final plus pérenne et solide de coder une API proprement qui permettra de restreindre l'usage, l'accès et d'avoir des stats.

Une session de pair programming est à prévoir semaine 24.

**Comment by JeromeBu** [comment]
N'hésite pas à préciser le contrat qui t'intéresse dans cette issue. Si j'en crois la vue metabase que tu avais faites il te faudrait un truc du genre :

```ts
type Establishment = {
  siret: string,
  name: string,
  numberOfConventions: number,
}

// La réponse de l'API serait du type :

type ApiResponse = {
  data: Establishement[],
  pagination: {
       totalRecords: 100,
       currentPage: 1,
       totalPages: 10,
       nextPage: 2,
       prevPage: null
  }
}

```
