### ISSUE TITLE
ETQ prescripteur, je dois pouvoir modifier moi -même une demande de convention

### ISSUE THREAD

**Issue by nathalie-reyre** [gip-inclusion/immersion-facile#1762]
### :bug: Le problème

Quand un prescripteur (ou un conseiller) demande à faire une modification , il ne peut pass se désigner comme destinataire de le demande de modification s'il accède à la convention via le tableau de bord.

Par contre, il peut le faire s'il accède via le lien magique
### :dart: Comportement attendu

Permettre de se (conseiller ou valideur) choisir pour recevoir le lien de modification et pouvoir ensuite faire la modification avant de  la renvoyer en signature

### Screenshots

![Capture d’écran 2024-06-04 à 22 44 11](https://github.com/gip-inclusion/immersion-facile/assets/61510442/a4ba7690-a851-4b9d-ae3d-df88fbc6b4df)
![Capture d’écran 2024-06-04 à 22 54 42](https://github.com/gip-inclusion/immersion-facile/assets/61510442/796e4581-39d8-4954-95a0-4ef5a8efd240)

**Comment by celineung** [comment]
@nathalie-reyre tu as dû faire la manipulation en étant inclusion connecté admin.
Si tu refais avec un utilisateur counsellor ou validator non admin, tu auras l'option "vous-même" dans la liste déroulante.

**Comment by nathalie-reyre** [comment]
c'était remonté par des prescripteurs eux mêmes .

**Comment by clement-duport** [comment]
closed by #1794
