### ISSUE TITLE
ETQ que RH Grand compte, je peux suivre l'enregistrement et les conventions des mes structures

### ISSUE THREAD

**Issue by Jessicaceleste1** [gip-inclusion/immersion-facile#1765]
### :thinking: Contexte et problématique (et par qui est-ce remonté ?)

Lors d'un webinaire dédié aux entreprises grand compte le 25 juin, je vais les inviter à enregistrer toutes leurs structures comme entreprise accueillante. Je vais les accompagner dans la création de leur page en les aidant à compléter le tableau pour un import en masse lors de rdv en one to one. Notre proposition de service actuel c'est d'avoir une page dédiée, tout comme je le fais pour "La poste" il faudrait que pour chaque page dédiée, nous puissions donner aux RH la possibilité de suivre les enregistrements de leur site et la réalisation des conventions. 

### :tada: Proposition de solution

Avoir un tableau de bord que l'on puisse partager avec un lien public similaire à celui de la poste : https://metabase.immersion-facile.beta.gouv.fr/collection/167-la-poste, pour chacune des entreprises qui ont une page dédiée.

Voici la liste des entreprises qui ont une page dédiée (attention pas besoin de faire un board par entreprise ayant une page dédiée, car ces dernières n'ont pas exprimé le besoin) l'idée est d'avoir un tableau et que ensuite, @Master-Touks me forme pour me montrer comment dupliquer ce tableau pour chacune des entreprises qui aura une page dédiée.

https://metabase.immersion-facile.beta.gouv.fr/question/1632-groupes-dentreprises-avec-une-page-sur-if

**Comment by nathalie-reyre** [comment]
cf ticket #1720
