### ISSUE TITLE
Création de droits pour les entreprises (cf ticket prescripteur #1709) R:120000 I:1 C:0,5 = 60000

### ISSUE THREAD

**Issue by nathalie-reyre** [gip-inclusion/immersion-facile#1770]
Contexte actuel :  on accède à l'espace entreprise si un mail est identifié comme mail de discussion (mail saisi dans le form establishment)--> permet d'accéder aux discussions adressées au mail de contact actif
email de contact de la fiche établissement --> accéder à la fiche entreprise pour la  modifier
email responsable signataire d'une convention --> accès à la convention
email tuteur --> accès à la convention mais ne peut pas la signer.
Les mails en copie ne sont pas utilisés pour accéder à l'espace

Problématique actuelle : 
accès au compte non corrélé au siret de l'établissement -  pas de rôle de responsable de l'espace qui pourrait ajouter ou retirer des accès et superviser l'ensemble de l'activité de l'entreprise.

Rôles de convention : 
- signataire convention
- tuteur de convention

Des rôles/espace  entreprise : 
- responsable d'établissement (SIRET) -> peut affecter des droits aux autres
- contact /métier si l'entreprise souhaite différencier les contacts en fonction des métiers -(revoir process de création de la fiche entreprise)
- Rôle de lecture seule (viewer)

**Comment by Jessicaceleste1** [comment]
A prendre en compte 

ETQ responsable légal d'entreprise et gestion via le tbd, si on change le représentant légal, plus accès à l'historique des demandes

exemple siret : 13000548125389 avait pour représentant légal une boite mail générique : apechambery.73014@pole-emploi.fr
ils ont été modifier leur fiche étab, (car avec inclusion connect en tant que agent FT plus possible d'accéder avec des boites mails générique)
du coup, ils ont mis myriam.chene@francetravail.fr
il faudrait que l'historique des MER soit rattaché au siret et non au contact, vu qu'ils peuvent changer le représentant légal de l'entreprise, exemple, si le directeur est remplacé dans l'entreprise il n'aura plus accès à l'historique
