### ISSUE TITLE
ETQ admin, je ne peux pas ouvrir l'agence  9037fb28-ff06-4f19-9787-a0da261b6e8f car message d'erreur = email manquant

### ISSUE THREAD

**Issue by nathalie-reyre** [gip-inclusion/immersion-facile#1778]
### :bug: Le problème

Création le 11 juin de l'agence 9037fb28-ff06-4f19-9787-a0da261b6e8f avec saisie d'emails validateur et emails conseillers. Pas possible de l'ouvrir en BO pour la traiter. Erreur  = Désolé : nous n'avons pas été en mesure d'enregistrer vos informations. Veuillez réessayer ultérieurement
Shared-route schema 'responses' was not respected in adapter 'axios'. Received status: 200. Handled statuses: 200. Route: GET /admin/agencies/:agencyId Issues: validatorEmails: Vous devez renseigner au moins un email
pblm lié au fait qu'il y avait doublon entre les mails conseiller et les mails valideur.
### :dart: Comportement attendu : prise en compte des mails enregistés même en cas de doublon entre valideur et conseiller (ou rendre dépot de la structure impossible)

cf ticket #1816

**Comment by celineung** [comment]
@nathalie-reyre En prod cette agence est déjà rejetée. 
J'ai aussi testé l'édition: pas de problème non plus.
Que veux-tu dire par "ouvrir l'agence" ?

**Comment by nathalie-reyre** [comment]
j'avais traité ces agences en allant en base modifier les droits pour avoir au moins un validateur.
Manifestement le problème  a eu aujourd'hui (le20/06) un impact pour choisir un prescripteur à qui transmettre la convention

**Comment by 3lodi3** [comment]
closing in favor of #1816
