### ISSUE TITLE
pas de dénomination sociale affichée pour le siret 57578002800016

### ISSUE THREAD

**Issue by celineung** [gip-inclusion/immersion-facile#1791]
### :bug: Le problème

Sur le formulaire de création de convention, la dénomination sociale ne se rempli pas pour ce siret 57578002800016:

![Image](https://github.com/gip-inclusion/immersion-facile/assets/11294487/c40cc4c4-750b-4327-958c-ea0500a24bd2)

Or dans l'annuaire des entreprises, le nom est SICAL:

![Image](https://github.com/gip-inclusion/immersion-facile/assets/11294487/d3f4ea0f-ad7e-47c8-948b-51a4b09fcec2)

### :footprints: Étapes pour reproduire

1. Aller sur "remplir une demande de convention"
2. Dans la partie "3. Coordonnées de l'entreprise", saisir le siret: 57578002800016
3. Constater que la raison sociale de l'établissement ne se pré rempli pas.

### :dart: Comportement attendu

La raison sociale soit automatiquement rempli SICAL pour le siret 57578002800016.

**Comment by bbohec** [comment]
La raison sociale remonte maintenant
