### ISSUE TITLE
Rattacher manuellement un utilisateur IC ou non IC à une agence en tant qu'admin IF

### ISSUE THREAD

**Issue by 3lodi3** [gip-inclusion/immersion-facile#1799]
### :construction: Epic

#1619 

### :thinking: Contexte et problématique

En tant qu'admin, je peux ajouter des utilisateurs rattachés à une agence/prescripteur.

### :tada: Proposition de solution

1. Je peux renseigner un email : 
  - soit l'email est rattaché à un compte IC
  - soit l'email n'est pas rattaché à un compte IC

2. Je sélectionne le ou les rôles (par défaut, pas de rôle).

Dans les deux cas les utilisateurs sont rattachés à l'agence.

La seule différence, c'est qu'on aura pas le nom / prénom des users sans compte IC.

### :camera: Maquettes

proto : https://www.figma.com/proto/rZtRL0ShjGKfdw43nMUPex/Site---UX-design-2nd-trimestre-2024?page-id=3285%3A1202&node-id=3521-4082&viewport=-945%2C-8396%2C1&t=umAsOljnHcjjVvUz-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=3521%3A4082

fichier : https://www.figma.com/design/rZtRL0ShjGKfdw43nMUPex/Site---UX-design-2nd-trimestre-2024?node-id=3285-1202&t=La3EszP2zNI3Zwr6-1

**Comment by clement-duport** [comment]
Si l'utilisateur n'est pas inclusion connecter il doit obligatoirement recevoir les notifs
