### ISSUE TITLE
Gestion des statuts de mise en relation

### ISSUE THREAD

**Issue by JeromeBu** [gip-inclusion/immersion-facile#1800]
Le but est d'avoir une statut pour les mise en relation.

2 statuts facilement identifiable :
- si on utilise le bouton de reponse : rejeter la mise en relation, on peut marquer la discussion comme "rejected". Attention dans ce cas, le "mailto" ne vas plus suffire. On va être obliger d'avoir un formulaire, pour envoyer explicitement le rejet au backend. On transmettra quand même un mail, mais on aura l'info du refus.

- si une convention est créer à partir d'une discussion, on peut considérer que la mise en relation à abouti à une convention, et est donc en "accepted"

**Comment by nathalie-reyre** [comment]
traité via #1688

**Comment by nathalie-reyre** [comment]
traité via https://github.com/gip-inclusion/immersion-facile/issues/1688
