### ISSUE TITLE
ETQ precripteur je ne souhaite pas faire apparaître les conventions en erreur si elles ont eu un succès derrière

### ISSUE THREAD

**Issue by 3lodi3** [gip-inclusion/immersion-facile#1803]
### :construction: Epic

#1746 

### :thinking: Contexte et problématique

Les conventions qui ont été en erreur apparaissent toujours dans le tableau des conventions en erreur même si elles ne sont plus en erreur, cela fausse le suivi côté prescripteur.

### :tada: Proposition de solution

Ne plus afficher les conventions qui ont été en erreur puis en succès dans le tableau des conventions en erreur.

**Comment by nathalie-reyre** [comment]
Convention n'apparaît plus en erreur si elle est en succès au moment d'un appel
