### ISSUE TITLE
ETQ prescripteur je souhaite pouvoir synchroniser manuellement le tableau des conventions en erreur

### ISSUE THREAD

**Issue by 3lodi3** [gip-inclusion/immersion-facile#1805]
### :construction: Epic

#1746 

### :thinking: Contexte et problématique

Parfois il suffit de relancer une synchro manuelle pour résoudre certaines erreurs ?

### :tada: Proposition de solution

Ajouter le date et heure de dernière synchro et un bouton "Synchroniser" dans l'onglet conventions en erreur.

### :camera: Maquettes

https://www.figma.com/proto/rZtRL0ShjGKfdw43nMUPex/Site---UX-design-2nd-trimestre-2024?page-id=3514%3A3886&node-id=3514-3887&viewport=467%2C169%2C0.25&t=iuJf32KuV5Nin2qj-1&scaling=min-zoom&content-scaling=fixed

**Comment by nathalie-reyre** [comment]
Proposition de @JeromeBu : en faire une fonctionnalité intégrée au code et non à lancer via metabase. 
Avec metabase --> nouvel événement non historisé et dont on ne connait pas l'origine et risque d'intrusion dans la base (cheval de Troie).
Dans le code : Un accès en bo admin en secours mais avant tout un accès/BO prescripteur pour donner la responsabilité à chaque prescripteur dont le SI est interconnecté avec IF de rejouer lui même les conventions. Historisation et identification de celui qui a lancé les nouveaux appels API.
En //, demande aux DSI concernées de conserver leurs logs car se reposent exclusivement sur nous et surcharge le support.

**Comment by 3lodi3** [comment]
lié à #1689

**Comment by JeromeBu** [comment]
Dans cette issue, on se concentre sur les admin. 

Le but est de faire apparaitre un bouton "Rediffuser aux partenaires", dans le page de validation de convention. Ensuite on selectionne le partenaire concerné, et ça déclenche une diffusion de la convention.
