### ISSUE TITLE
Modification de l'adresse email d'un utilisateur non IC

### ISSUE THREAD

**Issue by 3lodi3** [gip-inclusion/immersion-facile#1809]
### :construction: Epic

#1619 

### :thinking: Contexte et problématique

En tant que admin je peux modifier l'adresse email d'un utilisateur sans compte IC

### :tada: Proposition de solution

Dans la fiche utilisateur d'un profil non IC, je peux modifier l'email.

Note : ce n'est pas possible pour les utilisateurs  IC, dans ce cas l'utilisateur doit modifier son email lui-même via IC.

### :camera: Maquettes

proto : https://www.figma.com/proto/rZtRL0ShjGKfdw43nMUPex/Site---UX-design-2nd-trimestre-2024?page-id=3285%3A1202&node-id=3521-4082&viewport=-945%2C-8396%2C1&t=umAsOljnHcjjVvUz-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=3521%3A4082

fichier : https://www.figma.com/design/rZtRL0ShjGKfdw43nMUPex/Site---UX-design-2nd-trimestre-2024?node-id=3285-1202&t=La3EszP2zNI3Zwr6-1

**Comment by clement-duport** [comment]
Ici on veut créer une page de pilotage d'utilisateur dans laquelle on aura ses information préférence etc 
Dans ce ticket on créer la page et avec les infos du user (email nom prénom et inclusion connect oui/non)
Si l'utilisateur est IC Connect on ne peut pas modifier ses info, si il ne l'est pas on peut .

Les autre feature de cette page seront développer dans les autres tickets
