### ISSUE TITLE
Modification des préférences de notification d'un utilisateur par l'admin IF

### ISSUE THREAD

**Issue by 3lodi3** [gip-inclusion/immersion-facile#1810]
### :construction: Epic

#1619 

### :thinking: Contexte et problématique

En tant que admin je peux gérer les préférences de notifs des utilisateurs

### :tada: Proposition de solution

Dans l'admin je peux  : 
- [ ] voir les préférences de notifs des utilisateurs
- [ ] les changer (OUI/NON pour chaque agence)

Exception : l'admin ne peut pas désactiver les notifications d'un utilisateur non IC.

### :camera: Maquettes

proto : https://www.figma.com/proto/rZtRL0ShjGKfdw43nMUPex/Site---UX-design-2nd-trimestre-2024?page-id=3285%3A1202&node-id=3521-4082&viewport=-945%2C-8396%2C1&t=umAsOljnHcjjVvUz-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=3521%3A4082

fichier : https://www.figma.com/design/rZtRL0ShjGKfdw43nMUPex/Site---UX-design-2nd-trimestre-2024?node-id=3285-1202&t=La3EszP2zNI3Zwr6-1

**Comment by clement-duport** [comment]
ici on veut voir et pouvoir modifier les préférences de notifs des utilisateurs dans la page pilotage utilisateur précédemment crée

**Comment by clement-duport** [comment]
close in favor of #2124
