### ISSUE TITLE
Supression d'un utilisateur IC ou non IC par l'admin IF

### ISSUE THREAD

**Issue by 3lodi3** [gip-inclusion/immersion-facile#1811]
### :construction: Epic

#1619 

### :thinking: Contexte et problématique

En tant qu'admin, je peux supprimer des utilisateurs rattachés à une agence/prescripteur.

### :tada: Proposition de solution
Je supprimer un utilisateur en tant qu'admin

- [ ] Si l'utilisateur n'a pas de compte IC : on supprime son adresse email de toutes les agences auxquelles il est rattaché
- [ ] Si l'utilisateur a un compte IC : on supprime le lien du compte IC avec les agences 

Note : il y a une double validation lors de la suppression

### :camera: Maquettes

proto : https://www.figma.com/proto/rZtRL0ShjGKfdw43nMUPex/Site---UX-design-2nd-trimestre-2024?page-id=3285%3A1202&node-id=3521-4082&viewport=-945%2C-8396%2C1&t=umAsOljnHcjjVvUz-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=3521%3A4082

fichier : https://www.figma.com/design/rZtRL0ShjGKfdw43nMUPex/Site---UX-design-2nd-trimestre-2024?node-id=3285-1202&t=La3EszP2zNI3Zwr6-1

**Comment by clement-duport** [comment]
Ici on veut pouvoir supprimer un utilisateur depuis la page pilotage utilisateur.
Lors de la suppression on supprime ses rattachement à tout les agence (Est ce qu'on le supprime de lq table user ???)
