### ISSUE TITLE
Validation d'un utlisateur IC etq admin if

### ISSUE THREAD

**Issue by 3lodi3** [gip-inclusion/immersion-facile#1814]
### :construction: Epic

#1619 

### :thinking: Contexte et problématique

En tant qu'admin, je peux valider des utilisateurs IC qui ont demandé à être rattachés à une agence/prescripteur.

### :tada: Proposition de solution

Dans mon talbeau des utilisateurs, je vois les utilsiateurs avec le tag "A valider"
je clique sur modifier > je peux soit : 
- Choisir un rôle pour l'utilisateur et le valider
- Supprimer l'utilisateur

### :camera: Maquettes

proto : https://www.figma.com/proto/rZtRL0ShjGKfdw43nMUPex/Site---UX-design-2nd-trimestre-2024?page-id=3285%3A1202&node-id=3521-4082&viewport=-945%2C-8396%2C1&t=umAsOljnHcjjVvUz-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=3521%3A4082

fichier : https://www.figma.com/design/rZtRL0ShjGKfdw43nMUPex/Site---UX-design-2nd-trimestre-2024?node-id=3285-1202&t=La3EszP2zNI3Zwr6-1

**Comment by nathalie-reyre** [comment]
on garde le fonctionnement actuel de la liste déroulante des utilisateurs à valider. Ajouter tous les rôles possible
