### ISSUE TITLE
Gestion des agences de rattachement utilisateur etq admin IF

### ISSUE THREAD

**Issue by 3lodi3** [gip-inclusion/immersion-facile#1815]
Pré-requis :
- Refacto droits utilisateurs #2342 
- Création en lecture seule de la page utilisateurs (cf Jérôme)

### :construction: Epic

#1619 

### :thinking: Contexte et problématique

En tant qu'admin, je peux gérer les agences de rattachement d'un utilisateur IC ou non IC

### :tada: Proposition de solution

Dans la fiche profil de l'utilisateur, je peux ajouter ou supprimer des agences de rattachement.

Exception : je ne peux pas supprimer la dernière agence avant d'en ajouter une nouvelle.

### :camera: Maquettes

- [ ] [Page profil pour le super admin / l'administrateur de l'organisme](https://www.figma.com/proto/HYZpBJRGvsvCLTLcbWa9TC/Espace-personnel?page-id=0%3A1&node-id=1-6164&node-type=frame&viewport=211%2C1015%2C0.5&t=7S0FTX3NLYxhwgyp-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=11%3A3935)

[Fichier figma](https://www.figma.com/design/HYZpBJRGvsvCLTLcbWa9TC/Espace-personnel?node-id=1-6164&t=RwY5KGB3wZUI7Itx-1)

**Comment by gargagif** [comment]
Proposition : conserver le fonctionnement avec une modale (ISO page agence) plutôt que menu déroulant. A valider avec @3lodi3 avant d'attaquer le dev

**Comment by gargagif** [comment]
Recette OK en staging :
- Admin OK
- Validateur OK, ne peut pas se retirer les notifications si seul validateur de l'agence à les recevoir
- Prévalidateur OK, ne peut pas se retirer les notifications si seul validateur de l'agence à les recevoir
