### ISSUE TITLE
ETQ 'qui?', un titre court svpEtq Prescripteur depuis mon tableau de bord lorsque je pilote une convention et que je fais retour, tous mes filtres sautent, je dois tous les remettre pour retrouver de nouveau mes conventions à traiter

### ISSUE THREAD

**Issue by Jessicaceleste1** [gip-inclusion/immersion-facile#1818]
### :thinking: Contexte et problématique (et par qui est-ce remonté ?)

Etq Prescripteur depuis mon tableau de bord lorsque je pilote une convention (copier coller un n° de convention et cliquer sur piloter la convention) et que je fais retour, tous mes filtres sautent, je dois tous les remettre pour retrouver de nouveau mes conventions à traiter

### :tada: Proposition de solution
suggestion d'amélioration, soit avoir un bouton retour qui permet de conserver ses filtres initiaux, soit lorsque l'on clique sur piloter la convention, ça l'ouvre dans un nouvel onglet

**Comment by nathalie-reyre** [comment]
toujours d'actu avec le clic sur l'ID de convention ?

**Comment by Jessicaceleste1** [comment]
résolu, ça ouvre une nouvelle page pour consulter la convention, je clôture le ticket

**Comment by Jessicaceleste1** [comment]
résolu

**Comment by Jessicaceleste1** [comment]
pour ma part, j'utilisais la poste et maintenant que FT, j'ai vite fais créer les autres qui se trouve ici : 
il faudrait faire un cumul des 2 board de la poste et de FT https://metabase.immersion-facile.beta.gouv.fr/collection/166-suivi-referencement-entreprises-accueillantes
