### ISSUE TITLE
Pas de suggestion d'adresses dans le composant de sélection d'adresses

### ISSUE THREAD

**Issue by celineung** [gip-inclusion/immersion-facile#1819]
### :bug: Le problème

Sur le composant input d'adresse, il n'y a pas d'adresse suggéré pour "17 rue lamartine" alors qu'il y en a sur OpenCage.

### :footprints: Étapes pour reproduire

Sur la page d'ajout d'un nouveau prescripteur, saisir l'adresse "17 rue lamartine".

![Image](https://github.com/gip-inclusion/immersion-facile/assets/11294487/eb732a13-fc3e-4bb3-9d35-c2463853244a)

### :dart: Comportement attendu

Il devrait y avoir des propositions d'adresses car OpenCage en proposent :
![Image](https://github.com/gip-inclusion/immersion-facile/assets/11294487/882010ec-6b89-4ab6-882d-7f8ddde4b526)

**Comment by celineung** [comment]
Pour décider si les adresses d'Opencage remontent en suggestion chez nous, les adresses passent par la fonction `HttpAddressGateway.#featureToAddress` et sont filtrées si la fonction retourne undefined.

Dans notre exemple d'adresse "17 rue lamartine", departmentCode est undefined car departmentName = 'Occitanie'.
```ts
const departmentCode =
      departmentName &&
      getDepartmentCodeFromDepartmentNameOrCity[departmentName];
```

departmentCode étant undefined => `HttpAddressGateway.#featureToAddress` est undefined => pas de suggestion sur l'input d'adresses

**Comment by enguerranws** [comment]
Je reprends le sujet, je pense qu'il y a 2 choses : 
- OpenCage qui a peut être mis à jour ses données, il faut checker que tout est toujours à la bonne place et que notre façon de récupérer le département est toujours d'actualité
- le screenshot que tu montres, ça ne vient du souci qu'on dispatch au change et que selon les copier-collers, le fait qu'on ne vide pas la valeur dans l'état local, l'événement n'est pas déclenché 

![Image](https://github.com/gip-inclusion/immersion-facile/assets/2190121/48e0cc32-4b56-4b86-b2a6-749ecd08d7ce)

**Comment by enguerranws** [comment]
Pour le souci côté données OC, voilà l'exemple sur 17 rue lamartine : 
- 10 résultats trouvés par OC
- 7 remontent de notre côté

Pour les 3 qui restent : 

```
[
      {
        region: 'France métropolitaine',
        postcode: '94500',
        county: 'France métropolitaine',
        house_number: '17',
        road: 'Rue Lamartine',
        town: 'Champigny-sur-Marne'
      },
      {
        region: 'France métropolitaine',
        postcode: '94400',
        county: 'France métropolitaine',
        house_number: '17',
        road: 'Rue Lamartine',
        suburb: 'Coteau - Malassis',
        town: 'Vitry-sur-Seine'
      },
      {
        region: 'France métropolitaine',
        postcode: '54230',
        county: 'Grand Est',
        house_number: '17',
        road: 'Rue Lamartine',
        state: 'Grand Est',
        state_code: 'GES',
        village: 'Neuves-Maisons'
      }
    ]
```

Avec cette donnée là, impossible de trouver un département, donc on les exclu.

Ceci dit, ce problème arrive et je vais ouvrir un ticket chez OpenCage, mais ce problème exclu quelques résultats, il ne vide pas complètement les suggestions d'adresses. 

Par contre, le problème d'événement qui n'est pas dispatch fait que la requête ne part pas du tout et il faut le régler.
