### ISSUE TITLE
Email en spam chez ALTOSPAM

### ISSUE THREAD

**Issue by bbohec** [gip-inclusion/immersion-facile#1824]
### :bug: Le problème

![image](https://github.com/gip-inclusion/immersion-facile/assets/58432308/740ed7d4-0347-427a-bfb7-c40b248330b9)

Retour de la part de ALTOSPAM

>Au vue de la solution d'envoi et des en-têtes présentes dans votre mail, il nous sera impossible de ne pas vous classifier comme mass mailing.
>
>Vos mails sont envoyés par une solution reconnue pour ses mass mailing qui est brevo.
>Vos mails contiennent les en-têtes "list-unsubscribe", "list-unsubscribe-post", "x-mailin-eid" et "x-sib-id" typique des mass mailing
>
>L'analyse de votre domaine montre que votre DMARC n'est pas du tout sécurisé; En effet sa politique "p=none" autorise n'importe quel domaine à usurper votre From (https://www.altospam.com/actualites/expediteurs-et-destinataires-des-mails/).
>Cependant comme votre SPF "v=spf1 include:_spf.alwaysdata.com ~all" n'autorise pas l'IP "172.246.17.118"  comme serveur légitime pour votre domaine, vous ne pouvez pas sécuriser votre DMARC.
>
>Je vous invite donc à supprimer ces en-têtes de vos mails, à mettre à jours votre SPF avec l'ensemble des serveurs légitimes pour émettre des mails pour votre domaine et à sécuriser votre DMARC avec une politique au moins "p=quarantine" au mieux "p=reject".

- [x] revoir la confir DMARC/SPF
- [x] voir avec Brevo / API email Transactionnel si on ne peut pas retirer les header qui rend nos mail transac comme des mail market

**Comment by nathalie-reyre** [comment]
Support Brévo contacté par mes soins (ticket) le 21/06 PM

**Comment by nathalie-reyre** [comment]
@bbohec réponse de Brevo Afin de répondre au mieux à leurs préconisations, je vous invite à effectuer les deux actions suivantes :
 
Je vous invite d'abord à ajouter l'IP "172.246.17.118" à vos enregistrements SPF pour autoriser ce serveur comme émetteur légitime pour notre domaine.
 
Vous pouvez aussi modifier votre politique DMARC de "p=none" à "p=quarantine" en ajustant l'enregistrement chez votre hébergeur de domaine.
 
Je vous invite donc à réaliser ces modifications et à nous en informer. N'hésitez pas à revenir vers moi pour confirmer que tout fonctionne correctement ou à rouvrir ce ticket si nécessaire. Je reste à votre disposition.

**Comment by enguerranws** [comment]
Pour faciliter le debug, je me suis envoyé un mail via l'API Brevo pour checker les headers du mail : 

```
To: <enguerranweiss@gmail.com>
X-sib-id: V3IHxufqThpkAMVBOOMXombea5ojf7je2xwP3x9IhPPGka-LqOmTQ2O3zdAS5L5gCgUSw-sW2JQpmTrpULVp9dGihB1nN5Xw_7DuB9cbHrZXa0pBzb5aEQwfiyI_1ChLhbVFOt2hMnxG4PY-RvaOF297btY5qZQkULksi2Q0eAbG-bS_9N8
Message-Id: <202407241013.80004153951@smtp-relay.mailin.fr>
Reply-To: Bob <bob@fake.mail>
List-Unsubscribe-Post: List-Unsubscribe=One-Click
From: Bob <bob@143725570.t-sender-sib.com>
List-Unsubscribe: <https://r.email.immersion-facile.beta.gouv.fr/tr/un/li/91iZOjLYGajF95WDCCj35k68_A55Gvvc8Lbr1GGXwsekkdAIoSAVxF5Jxvzg64zO3J82FIYlW551ohaNtqro98hG08bsKfuZoHv-x8fAgXUuBbKGpKDyvqWFZ6Wexb67KPEZBE5KVlTx2Nqh1BWCd4QOQ6EG8lx_06BnMQAEtVPL18FnlSd_8g6Y6c-L80QxKhk2YBa7XjYk934c1k8G4H4LP4vlydyw66Fge2JntznzzZTb3Mh_wu2O>
X-CSA-Complaints: csa-complaints@eco.de
X-Mailin-EID: MTQzNzI1NTcwfmVuZ3VlcnJhbndlaXNzQGdtYWlsLmNvbX48MjAyNDA3MjQxMDEzLjgwMDA0MTUzOTUxQHNtdHAtcmVsYXkubWFpbGluLmZyPn5lbWFpbC5pbW1lcnNpb24tZmFjaWxlLmJldGEuZ291di5mcg%3D%3D
Date: Wed, 24 Jul 2024 10:13:27 +0000
Subject: Pour action :
  signez votre demande de convention
Origin-messageId: <202407241013.80004153951@smtp-relay.mailin.fr>
Feedback-ID: 172.246.17.118:4017262_-1:4017262:Sendinblue
X-Api-Version: v3
Content-Type: multipart/mixed; boundary=baa11a5dcad91690613963c5b4d438345bb9ac79e9d4ce2f426ccbd623e6
Mime-Version: 1.0
```

Les headers concernés : x-sib-id, List-Unsubscribe-Post, List-Unsubscribe.

De ce que je vois dans l'API Brevo, on ne peut que définir des headers custom, on ne peut pas remplacer ceux-là : https://developers.brevo.com/reference/sendtransacemail

Il faudrait demander au support Brevo.

**Comment by enguerranws** [comment]
Config avant modif : 

- root : v=spf1 include:_spf.alwaysdata.com ~all
- email : v=spf1 include:spf.sendinblue.com mx ~all

- v=DMARC1; p=none; rua=mailto:rua@dmarc.brevo.com
- v=DMARC1; p=none; sp=none; rua=mailto:dmarc@mailinblue.com!10m; ruf=mailto:dmarc@mailinblue.com!10m; rf=afrf; pct=100; ri=86400

Les changements ont été faits et vérifié via mxtools. La politique appliquée est reject (le mail se fera renvoyer par le serveur de reception).

Indicateurs : 

Sur juin 2024 : 
- 452 320 envois
- 0.89% en bounce (soft et hard) - 4046

A voir l'évolution sur aout 2024

**Comment by enguerranws** [comment]
Reste à suivre la demande concernant les headers de mail côté Brevo avant de clôturer ce ticket.

**Comment by bbohec** [comment]
Retour Brevo qui indique qu'il n'est pas possible pour eux de revoir leurs headers pour les mails transactionnels



![Image](https://github.com/user-attachments/assets/30bfbccd-cfaf-4a8d-aee3-dd5f3bcc0584)

**Comment by bbohec** [comment]
Feedback envoyé à Altospam


> Bonjour,
> 
> Nous avons pu avancer dans l'applications des bonnes pratiques que vous nous avez conseillé pour nos emails transactionnels.
> 
> - Nous avons revu notre configuration DMARC/SPF afin de spécifier notre IP et une politique "reject".
> - Nous avons contacté Brevo au sujet des headers. Il ce trouve qu'ils ne proposent pas la possibilité de retirer les headers "list-unsubscribe", "list-unsubscribe-post", "x-mailin-eid" et "x-sib-id" même pour des emails transactionnels au travers de leur solution.
> 
> D'après ces éléments, pourriez-vous nous indiquer si la configuration DMARC/SPF peut suffire à autoriser nos emails transactionnels?
>
> Cordialement,
> L'équipe Immersion Facilitée.

**Comment by jbuget** [comment]
D'après ce que je lis [ça](https://mailtrap.io/blog/list-unsubscribe-header/) et [là](https://www.cloudflare.com/fr-fr/learning/privacy/what-is-the-can-spam-act/), ceci explique pourquoi Brevo _ne peut pas_ supprimer ces headers. D'après le CAN SPAM Act (loi US 🇺🇸), ils sont obligés de permettre à leurs users de pouvoir se désinscrire de communications indésirées. Et Brevo, semble suivre un standard de facto (dont je n'ai pas cherché le nom) qui stipule d'intégrer les fameux headers problématiques.

**Comment by enguerranws** [comment]
Je clos après avoir discuté avec @jbuget
