### ISSUE TITLE
ETQ Entreprise, je ne reçoit pas l'email de bilan

### ISSUE THREAD

**Issue by bbohec** [gip-inclusion/immersion-facile#1826]
### :bug: Le problème

Situation pour la convention f30aa250-238f-4b67-be9a-3f7678a11723
La convention a comme dates: 10/06/2024 | 14/06/2024

Pas de mail dans brevo.

Normalement je devrait voir une notif chez nous mais ce n'est pas le cas:
![image](https://github.com/gip-inclusion/immersion-facile/assets/58432308/20efb0d6-ea35-4a26-b71b-9cbff23fa386)

Les scripts de mail de bilan fonctionnent tout les jours à ~20:57:12.450Z

Je soupçonne un problème de query pour

``` typescript
    const now = this.#timeGateway.now();
    const yesterday = subDays(now, 1);
    const conventions =
      await uow.conventionQueries.getAllConventionsForThoseEndingThatDidntGoThrough(
        yesterday,
        "EmailWithLinkToCreateAssessmentSent",
      );
```

**Comment by 3lodi3** [comment]
Est-ce que c'est parce que la date de fin tombe un vendredi ?

**Comment by clement-duport** [comment]
je viens d'enquêter vite fait, le script s'execute bien tout les jours mais pas les samedis.   ????
