### ISSUE TITLE
ETQ entreprise, je peux définir le nombre max de mises en relation/4 semaines Score : 5000

### ISSUE THREAD

**Issue by 3lodi3** [gip-inclusion/immersion-facile#1838]
### :thinking: Contexte et problématique (et par qui est-ce remonté ?)

Cf retour d'Arnaud Denoix -> Pour info, j'ai modifié les paramètres pour ne plus recevoir de candidat pour cause de trop nombreuses demandes non pourvues ou en cours d'étude. 

Le plafonnement du nombre de demande à la semaine ne correspond pas à notre capacité d'accueil (le flux traitable est plutôt 1 par mois si l'on veut répondre à tout le monde et parfois positivement) - du coup j'ai coché "non" et on n'apparaitra plus avant novembre. 

### :tada: Proposition de solution

Passer la plage de plafonnement des mer plutôt sur 1 mois au lieu d'1 semaine.

Reach : 10 000
Impact : 1
Confidence : 0,5

Points d'attention
- [x] tâche planifiée markEstablishmentsAsSearchableWhenMaxContactsAllows à configurer en mode 28 jours au lieu de 7
- [x] AJOUT Attribut Brevo ENT_MAX_CONTACTS_PER_MONTH
- [ ] SUPPRESSION POST MEP Attribut Brevo ENT_MAX_CONTACT_PER_WEEK 
- [ ] Revoir les configs Matomo qui utiliseraient les ids suivants:
```
im-form-create-establishment__max-contact-per-week
im-form-create-establishment__max-contacts-per-month

im-form-create-establishment__max-contact-per-week-when-available
im-form-create-establishment__max-contacts-per-month-when-available

im-form-edit-establishment__max-contact-per-week
im-form-edit-establishment__max-contacts-per-month

im-form-edit-establishment__max-contact-per-week-when-available
im-form-edit-establishment__max-contacts-per-month-when-available

im-form-manage-establishment-admin__max-contact-per-week
im-form-manage-establishment-admin__max-contacts-per-month

im-form-manage-establishment-admin__max-contact-per-week-when-available
im-form-manage-establishment-admin__max-contacts-per-month-when-available

im-form-manage-establishment-admin__max-contact-per-week-value
im-form-manage-establishment-admin__max-contacts-per-month-value
```

**Comment by nathalie-reyre** [comment]
pour celles dont l'effectif n'est pas connu, limiter le max à 12/mois @bbohec car le plus souvent, ce sont de petites entreprises
