### ISSUE TITLE
[EPIC] ETS que Chambre consulaire  mini-stage , des évolutions de wording + ajout de champs libre en mode optionnel (afin de ne pas mettre en erreur les anciennes conventions) à discuter en grooming

### ISSUE THREAD

**Issue by bbohec** [gip-inclusion/immersion-facile#1848]
**Référencement prescripteur :** modifier  

![Image](https://github.com/user-attachments/assets/02ce2468-b134-419c-a188-2138d0395a6f)

par Chambres consulaires (mini-stage/stage de découverte)

**Formulaire  de demande de convention** - 
**Choix du prescripteur **- modifier 

![Image](https://github.com/user-attachments/assets/b1235c00-fb20-423d-883d-e2f37ebee73e)

par un wording qui permet de comprendre que c'est en fonction du secteur d'activité du stage qu'on choisit la chambre consulaire ad hoc (je n'ai pas encore trouvé le bon wording) ou créer une url/chambre consulaire ? 

Certaines régions sont financées par le FSE : elles doivent certifier que le jeune qui fait une immersion réside bien dans la région ad hoc --ajouter un champ de saisie d'adresse optionnelle au niveau des coordonnées du jeune; 
Indiquer dans le wording que cette donnée est nécessaire dans la région ARA. 

**Wording à ajouter  à la modale de signature du candidat.**  "Les étudiants ne sont pas soumis aux périodes de vacances scolaires mais ne doivent pas avoir de cours ou d’examen sur la période de stage. En signant cette convention, le bénéficiaire atteste être libéré de toutes obligations étudiantes pendant la période de stage (ni cours, ni examen)."  Mettre en gras la dernière phrase (les étudiants peuvent faire des mini-stages en dehors de vacacances scolaires officielles s'ils n'ont pas de cours programmés. Les CCI doivent avoir la preuve que les étudiants respectent ce cadre).

**Lieux et horaires** :
Premier pavé : Lui mettre un titre en gras Période et durée de stage

Pavé Assurances : Mettre en gras les signataires de la convention s’engagent à avoir une couverture d’assurance nécessaire

Horaires : Si le jeune a moins de 15 ans, il ne doit pas dépasser 30h, modifier le blocage en fonction de l’âge (35h pour les autres)

**Détails du stage **
: Ajouter un pavé d’information avec pour titre en gras Déplacements sous la question Conditions de travail, avec le message suivant : Les déplacements dans le cadre du stage ne sont pas interdits tant qu’ils se font en présence et sous la responsabilité du tuteur et pendant les horaires prévus à la convention.

**Validation **: Ajouter un message au moment de la validation : Attention ! Vérifiez que tous les éléments soient bien intégrés au formulaire. En cas de demande de modification après validation, tous les signataires devront signer à nouveau la convention.

**Convention**
Logo (ci-joint) : utiliser le même sur toutes les conventions.
Il manque le numéro Siret et la ville de l'entreprise, ainsi que la classe et l’établissement du jeune
Une mise en forme à revoir avec des retours à la ligne à faire :
Après chaque titre d’article :
Article 1 - Objet
Article 2 – Modalités particulières
Article 3 – Organisation
…
Avant le titre II (Dispositions particulières), actuellement inclus dans l’article 10

**Modif logo CCI **pour avoir un seul et même logo pour toutes les CCI (annule et remplace les logos actuellement utilisés). Logo versé sur clever cloud :https://immersion.cellar-c2.services.clever-cloud.com/POA.jpg

@Master-Touks vérifier le tableau de bord CCI. Apparemment, limite d'affichage à 1000 conventions ?
en attente ciblage support grâce à formulaire d'entrée pour les renvoyer vers support CCI/région

NB 

Modification : Donner la possibilité au prescripteur CCI de renvoyer le lien de modification pour le cas où les destinataires n’auraient pas reçu le mail permettant de modifier la convention (a minima sur même principe que lien de signature) Une suggestion pour tous les types de prescripteur ?  A discuter de ce qui est faisable avec Elo 
Liens externes : Raccrocher le formulaire mini-stage à la plateforme un jeune une solution - Contacter Laurent Ingout (Nathalie)
Moteur de recherche : En lien avec le point précédent, avoir accès pour les jeunes à un moteur de recherche leur permettant de trouver une entreprise accueillante (ou avec une offre) --> API de recherche intégrée par les CCI

**Comment by nathalie-reyre** [comment]
découper en plusieurs tickets et les passer dans prêt à dev
