### ISSUE TITLE
ETQ que candidat qui reçoit un partage de convention, je lis pôle emploi au lieu de FT

### ISSUE THREAD

**Issue by Jessicaceleste1** [gip-inclusion/immersion-facile#1854]
### :thinking: Contexte et problématique (et par qui est-ce remonté ?)

sur la page de partage de convention, mauvais wording : 
https://immersion-facile.beta.gouv.fr/demande-immersion?email=&firstName=&lastName=&phone=&financiaryHelp=&emergencyContact=&emergencyContactPhone=&isRqth=false&birthdate=&agencyDepartment=&siret=&businessName=&businessAdvantages=&etFirstName=&etLastName=&etJob=&etPhone=&etEmail=&erFirstName=&erLastName=&erPhone=&erEmail=&immersionAddress=&immersionActivities=&immersionSkills=&sanitaryPreventionDescription=&workConditions=&dateStart=2023-08-02&dateEnd=2023-08-03&schedule=%7b%22totalHours%22:0,%22workedDays%22:0,%22isSimple%22:true,%22selectedIndex%22:0,%22complexSchedule%22:%5b%7b%22date%22:%222023-08-02T00:00:00.000Z%22,%22timePeriods%22:%5b%5d%7d,%7b%22date%22:%222023-08-03T00:00:00.000Z%22,%22timePeriods%22:%5b%5d%7d%5d%7d

A modifier le lien cliquable : [Ou continuer avec mes identifiants Pôle emploi (candidats inscrits à Pôle emploi)](https://immersion-facile.beta.gouv.fr/api/login-pe-connect)

### :tada: Proposition de solution

 modifier le wording ![Image](https://github.com/user-attachments/assets/ad4d255d-26a6-4ada-a1d4-151b8ac2dd49)

**Comment by nathalie-reyre** [comment]
tout petit ticket
