### ISSUE TITLE
ETQ entreprise, je ne peux pas répondre à un candidat parce que le champ Business Name est vide 

### ISSUE THREAD

**Issue by nathalie-reyre** [gip-inclusion/immersion-facile#1866]
### :bug: Le problème

 Erreur au moment de répondre à un candidat par l'espace entreprise 
![Capture d’écran 2024-07-05 à 11 58 06](https://github.com/gip-inclusion/immersion-facile/assets/61510442/312caa9f-cf77-4f47-aa44-1c9e3c7fc597)

 en base,  on a actuellement des discussion qui n'ont pas de business name
Sur 348 510 discussion en base
16 066 discussions ont un business name vide
Situation qu'on a depuis fin 2022
![Capture d’écran 2024-07-05 à 12 16 31](https://github.com/gip-inclusion/immersion-facile/assets/61510442/d11a6490-16cb-41ab-b453-435f0ad89c1e)

pourquoi on a ce champ à vide ? 
ça ne devrait pas arriver

 première fois qu'on nous signale l'erreur car c'est les premières fois que les entreprises  accèdent à la discussion par API
avant c'était juste des échanges de mail par inboundparsing

Ce qui est rassurant
Aucun établissement n'a de nom à vide
Par contre concernant le customized name des établissements:
1576 à vide
33 966 à NULL
17945 non vide et non null
13000548112502 qui est l'agence FT de marseille à le champs customized name à vide
Ces 1576 devraient avoir customized name à NULL

-->

### :dart: Comportement attendu

Pas de champ business name vide dans la table discussion
Pas d'établissement avec le champ customized name vide. Par défaut, doit être à null

### Screenshots

cf ci dessus

- [ ] MAJ à la main des discussions sans business name restantes

**Comment by bbohec** [comment]
Certaines discussions ne peuvent pas avoir de SIRET à partir de la migration car les entreprises ont étés supprimé.

Identifier les discussion sans business name:
``` sql
SELECT DISTINCT siret
FROM discussions
WHERE TRIM(business_name) = ''
```

Il y a ~400 discussions dans cette situation pour ~80 Sirets, il faudra les MAJ à la main
