### ISSUE TITLE
[EPIC] Messages d'erreur compréhensibles dans le front

### ISSUE THREAD

**Issue by nathalie-reyre** [gip-inclusion/immersion-facile#1876]
plusieurs sujets à traiter par les devs.
cf les tickets #1868  #1568 #1730 et #1739 
Impact : support moins sollicité car les utilisateurs peuvent comprendre comment remédier par eux-mêmes au problème. Si le support est sollicité, gain de temps car l'erreur est transmise en étant contextualisée au support.

abordé lors de l'ADR du 9/07

**Comment by JeromeBu** [comment]
à merger colturé quand #1730  et #1739 seront mergés
