### ISSUE TITLE
Investiguer : certains envois de mails prescripteur ne partent pas

### ISSUE THREAD

**Issue by enguerranws** [gip-inclusion/immersion-facile#1881]
### :bug: Le problème

Certains utilisateurs (prescripteurs) se plaignent de ne pas recevoir tous les mails. Ils reçoivent : 
- les mails de modification de convention
- les mails de validation de convention 

Mais, par exemple, ils ne reçoivent pas les mails de notification lors de la soumission d'une nouvelle convention qui les concernent.

@Sylvieleb a testé de régler le souci en faisant la manip suivante : 
- dans l'admin, éditer l'agence concernée pour supprimer le mail validateur concerné
- elle soumet la modif
- elle rajoute le même mail et soumet
- l'utilisateur a soumis une convention bidon, et a bien reçu le mail de notif

**Comment by JeromeBu** [comment]
besoin de screen shot et d'un exemple concret avec des id d'agence/ utilisateurs

**Comment by Master-Touks** [comment]
@Sylvieleb, est-ce que tu rajouter des screenshot, cf le commentaire de Jérôme au dessus, stp ?

**Comment by celineung** [comment]
vu avec @Sylvieleb : je cloture car on ne se souvient plus des détails du ticket
on re-créera si besoin plus tard
