### ISSUE TITLE
ETQ agent d'une agence prescriptrice ic connecté je veux voir dans mon tableau de bord les convention avec structure d'accompagnement pour laquelle mon agence est l'agence préscriptrice de cette convention

### ISSUE THREAD

**Issue by clement-duport** [gip-inclusion/immersion-facile#1884]

**Comment by clement-duport** [comment]
- Faire apparaitre ces conventions dans le tableau de bord 
- donner le droit de valider ces convention via le tdb si l'agence accompagnatrice a pré valider

**Comment by nathalie-reyre** [comment]
rendre très visible le fait que  les conventions sont des conventions issues d'une structure d'accompagnement (agence enfant)
