### ISSUE TITLE
Optimisation des résultats métiers diagoriente par scoring des proposition

### ISSUE THREAD

**Issue by bbohec** [gip-inclusion/immersion-facile#1889]
### :thinking: Contexte et problématique (et par qui est-ce remonté ?)

Suite à discussion avec Diagoriente, il s'avère que les propositions de métier ont un scoring établi par diag.
Or on n'utilise pas ce scoring pour trier les propositions les plus pertinentes.
Actuellement on prend juste les 5 premières.

### :tada: Proposition de solution

Check de l'API diag pour récupérer le scoring des propositions et trier par le meilleur scoring les propositions avant de prendre les 5 premières.

**Comment by nathalie-reyre** [comment]
hyper pertinent ! Prévoir un autre ticket avec la route retour

**Comment by nathalie-reyre** [comment]
@bbohec
