### ISSUE TITLE
ETQ prescripteur FT et iMilo, je peux resynchro une convention

### ISSUE THREAD

**Issue by celineung** [gip-inclusion/immersion-facile#1891]

**Comment by nathalie-reyre** [comment]
fonctionne  déjà pour les admins.

**Comment by nathalie-reyre** [comment]
contraintes techniques :  liste de prescripteurs pas communiquable telle quelle aux autres prescripteurs . Adapter ce qui est récupéré pour les admins .
Limiter le nombre de resynchro avec un quota max / heure --> éviter le spammage

**Comment by celineung** [comment]
possible pour conseillers et valideurs

**Comment by celineung** [comment]
quota: 1 toute les demi-journées
