### ISSUE TITLE
ETQ Entreprise, certaines informations ne sont pas mises à jour dans ma fiche entreprise quand je l'édite

### ISSUE THREAD

**Issue by bbohec** [gip-inclusion/immersion-facile#1895]
### :bug: Le problème

 **Suite à analyse, les données sont à jour dans la DB mais le dashboard BackOffice Entreprises IF et la vue utilsée view_establishment ne sont pas à jour en temps réel, mais ça vaut le coup de check au niveau des tests qu'on met bien à jour toutes les props**

- Si la **raison sociale** remontée par l'API Siret change et qu'on valide le form, l'ancienne raison sociale est conservée (la nouvelle raison sociale esty bien présente dans l'appel API d'édition, c'est un soucis côté back)
- Si l'entreprise est en **mode tout public** et qu'on la change en public non scolaire et qu'on valide le form, le mode tout public est conservé (l'appel API indique bien public non scolaire, c'est un soucis côté back)

### :footprints: Étapes pour reproduire

![image](https://github.com/user-attachments/assets/82360089-6816-4b93-9e83-2088fe8e32f8)
![image](https://github.com/user-attachments/assets/6f12bcd6-6e1d-495a-96b0-7f9bea1b925f)
![image](https://github.com/user-attachments/assets/d3b2b394-d2e0-4619-bc2d-3629a482adcb)

### :dart: Comportement attendu

Il faudrait un ensemble de test back qui couvre la modification de l'ensemble des infos d'une entreprise hors son SIRET pour bien valider que toutes les infos sont bien changées.

A tester au niveau de :
- FormEstablishment Use Case
- FormEstablishment PG Repo
- EstablishmentAggregate Use Case
- EstablishmentAggregate PG Repo

Ce sujet d'info d'entreprise non modifié est constant depuis un bon moment, il est maintenant temps de le résoudre une bonne fois pour toutes.

**Comment by enguerranws** [comment]
@bbohec Il faudrait qu'on pense à compléter les tests côté Playwright aussi
