### ISSUE TITLE
Rattraper les mails de bilans qui n'ont pas été envoyés

### ISSUE THREAD

**Issue by celineung** [gip-inclusion/immersion-facile#1912]
Concernant le problème d'envoi des mails de bilan il y a quelques jours (https://github.com/gip-inclusion/immersion-facile/pull/1902) on l'a corrigé mais on n'a pas rattrapé les anciens mails qui ne sont pas partis.

Une personne au support nous demande pourquoi elle n'a pas reçu de mail de fin d'immersion.

**Comment by nathalie-reyre** [comment]
Renvoyer les bilans des immersions finies en juillet
