### ISSUE TITLE
ETQ agent france travail quand je crée mon compte inclusion connect en cliquant sur connexion agent france travail on me demande de me rattacher à une agence

### ISSUE THREAD

**Issue by Jessicaceleste1** [gip-inclusion/immersion-facile#1971]
### :bug: Le problème

ETQ agent france travail quand je crée mon compte inclusion connect en cliquant sur connexion agent france travail on me demande de me rattacher à une agence

Lorsqu'un agent clique sur connexion agent france travail pour accéder à son espace la première fois, nous interrogeons FT pour connaitre à quelle agence il est rattaché et normalement, ça devrait le rattacher automatiquement, cependant dans certain cas, ça ouvre la page leur demandant de choisir leur agence de rattachement.
1er exemple : DUGUIN Yannick : jy.duguin@francetravail.fr

**Comment by Jessicaceleste1** [comment]
convers discord : https://discord.com/channels/864451835553513474/1042365650359828480/1265632764187644104

**Comment by clement-duport** [comment]
c'est par ce que dans certain cas on ne reçoit pas le code safir ce qui fait qu'on ne pas pas rattacher le conseiller a ses agences automatiquement
