### ISSUE TITLE
Changer le wording de la modale validateur/rendre éligible

### ISSUE THREAD

**Issue by Sylvieleb** [gip-inclusion/immersion-facile#2018]
### :thinking: Contexte et problématique (et par qui est-ce remonté ?)

Les personnes qui pré-valident et qui valident les conventions ne sont pas toujours des conseillers

### :tada: Proposition de solution

 

Modifier le wording 
Remplacer "Nom du conseiller qui marque la demande" et "Prénom du conseiller qui marque la demande"
Par

En 1 étape 
"Nom de la personne qui valide la demande" et "Prénom de la personne qui valide la demande"

En 2 étapes
- Prévalider "Nom de la personne qui pré-valide la demande" et "Prénom de la personne qui pré-valide la demande"
- Valider la demande "Nom de la personne qui valide la demande" et "Prénom de la personne qui valide la demande"
- Titre de la modale : "Pré-valider la demande"

![Image](https://github.com/user-attachments/assets/aa5325d3-e353-4732-9762-540832f1197e)

(attention : le screen n'est pas à jour au niveau du wording "pré-valider")

**Comment by gargagif** [comment]
Recette OK
