### ISSUE TITLE
ETQ que utilisateur qui va faire /accueillir un mini stage dans le domaine agricole, , j'ai accès directement au formulaire qui sera adressé à une chambre d'agriculture

### ISSUE THREAD

**Issue by nathalie-reyre** [gip-inclusion/immersion-facile#2021]
### :construction: Epic

 EPIC #1848 

### :thinking: Contexte et problématique

La chambre d'agriculture va utiliser le formulaire de convention de mini stage. Il faut que les utilisateurs (secteur agricole) puissent l'adresser sans avoir à confondre avec la CCI et à terme la CMA

### :tada: Proposition de solution

une url en propre   par ex :  https://immersion-facile.beta.gouv.fr/demande-mini-stage/chambre-agriculture 
cela permettra d'ouvrir le formulaire avec en choix du prescripteur que des chambres d'agriculture  comme c'est fait actuellement pour les CCI

**Comment by 3lodi3** [comment]
Liste des chambres d'agriculture : https://annuaire-entreprises.data.gouv.fr/entreprise/chambres-d-agriculture-france-180070047?terme=&page=1#etablissements

**Comment by JeromeBu** [comment]
On propose de changer un peu cette story. Voilà les étapes dans lesquels on pourrait faire les choses :

- ajouter les types de prescripteurs "Chambre d'agriculture" et "Chambre des métiers de l'Artisanat" (CMA)
- rendre possible à ces prescripteurs de se référencer (dans le front)
- ces prescripteurs seront des prescripteurs de mini-stage et non d'immersion
- dans le formulaire des conventions de mini-stage, les chambre d'agricultures et les CMA doivent apparaitre, comme les CCI
