### ISSUE TITLE
ETQ candidat pour un mini stage,   je peux indiquer mon adresse dans le formulaire du mini-stage

### ISSUE THREAD

**Issue by nathalie-reyre** [gip-inclusion/immersion-facile#2023]
### :construction: Epic

#1848 

### :thinking: Contexte et problématique

Certaines CCI ont un co financement FSE et doivent apporter la preuve que les jeunes résident bien dans la région

### :tada: Proposition de solution

Ajouter un champ optionnel de saisie d"adresse (auto complete) dans la partie coordonnées du candidat. Une explication peut apparaître au survol du champ ou via icône d'information avec ce wording "si vous résidez en Auvergne Rhône Alpe, il est obligatoire de saisir votre adresse."

**Comment by 3lodi3** [comment]
Sinon un champ Adresse du candidat * obligatoire pour tous ?
Après le champ Date de naissance du candidat *

**Comment by nathalie-reyre** [comment]
> Sinon un champ Adresse du candidat * obligatoire pour tous ? Après le champ Date de naissance du candidat *

si c'est obligatoire, risque de mettre en erreur les anciennes demandes
