### ISSUE TITLE
ETQ utilisateur de la convention mini stage, quelques informations apparaissent de façon un peu plus visible

### ISSUE THREAD

**Issue by nathalie-reyre** [gip-inclusion/immersion-facile#2024]
### :construction: Epic

#1848 

### :thinking: Contexte et problématique

Modifications de forme sur le formulaire et sur le PDF 

### :tada: Proposition de solution

Lieux et horaires :
Premier pavé : Lui mettre un titre en gras Période et durée de stage 

![Image](https://github.com/user-attachments/assets/27f63059-0410-48ab-8f54-58fbd112ae5d)

Pavé Assurances : Mettre en gras les signataires de la convention s’engagent à avoir une couverture d’assurance nécessaire

![Image](https://github.com/user-attachments/assets/0c6ab909-08e1-4ebe-8fe8-cef84078c6b3)

**Détails du stage **
: Ajouter un pavé d’information avec pour titre en gras **Déplacements **sous la question Conditions de travail, 
et wording  suivant : Les déplacements dans le cadre du stage ne sont pas interdits tant qu’ils se font en présence et sous la responsabilité du tuteur et pendant les horaires prévus à la convention.

![Image](https://github.com/user-attachments/assets/72e56a19-9484-4395-9123-1b1a2162dcae)

**Validation **: Ajouter un message au moment de la validation : **Attention ! Vérifiez que tous les éléments sont bien intégrés  et exacts. 
En cas de demande de modification après validation, tous les signataires devront signer à nouveau la convention.**

![Image](https://github.com/user-attachments/assets/e2c29f85-4215-4866-9844-f8786ad2f164)

(à mettre également sur formulaire PMSMP)

**Comment by clement-duport** [comment]
![Image](https://github.com/user-attachments/assets/b6863e9e-eb96-4cd9-bae9-a34165c99181)



![Image](https://github.com/user-attachments/assets/568f4617-c015-4eb3-834f-91cab096f0e2)



![Image](https://github.com/user-attachments/assets/f35cdae0-c1f1-4933-96f8-702099f962f1)
