### ISSUE TITLE
Résultats de recherche : nombres incohérents

### ISSUE THREAD

**Issue by ClementLmd** [gip-inclusion/immersion-facile#2028]
### :bug: Le problème

Lors d'une recherche d'entreprise sur la prod en renseignant métier + ville, le nombre de résultat varie de façon incohérente selon la distance maximum renseignée. 
Exemple, recherche pour le métier boulanger à Rouen : 
- distance maxi 5km : 78 résultats trouvés
- distance maxi 10km : 14 résultats trouvés

En revanche, nombres cohérents de 5 à 1km (78 -> 30 résultats) et de 50 à 10km (38 -> 14 résultats).

Autre point : lors d'une recherche en renseignant une ville uniquement (sans préciser le métier), le nombre de résultats varie légèrement (entre 1 et 10 résultats de différence) selon le filtre utilisé (pertinence / proximité / date de publication).

### :footprints: Étapes pour reproduire
1. Aller sur https://immersion-facile.beta.gouv.fr/recherche
2. Sélectionner le métier "Boulanger / Boulangère", la ville de "Rouen" et la distance maximum de 5km
3. Cliquer sur "Rechercher"
4. On trouve 78 entreprises : screenshot 1
5. On refait pareil avec une distance de 10km, on trouve 14 entreprises : screenshot 2

### :dart: Comportement attendu

On s'attendrait à avoir de moins en moins de résultats lorsqu'on réduit le périmètre de recherche.

### Screenshots

 
screenshot 1 : 
![Image](https://github.com/user-attachments/assets/8858f8c6-82ab-4f66-b038-2e2863526ca6)

screenshot 2 :
![Image](https://github.com/user-attachments/assets/e10c8041-6499-413f-a21f-a0a5696d485d)

**Comment by JeromeBu** [comment]
On cloture et on considère que ça sera géré avec la pagination. c'est du au fait qu'on complète les résultats avec La Bonne Boite quand on a moins de 10 résultats
