### ISSUE TITLE
Migration vers ProConnect.  Migration le 29/10

### ISSUE THREAD

**Issue by 3lodi3** [gip-inclusion/immersion-facile#2035]
# :construction: Epic
## :thinking: Contexte et problématique

Migration de Inclusion Connect vers Pro Connect à initier.

L'équipe de ProConnect est en effectif réduit cet été, et le sera encore plus début août
Je vous encourage vraiment à lancer au moins la démarche pour obtenir vos accès à la recette via ce formulaire : https://www.demarches-simplifiees.fr/commencer/demande-creation-fs-fca

Y a du délai sur la validation, donc il vaut mieux anticiper avant que le ticket soit dans votre sprint ! Sinon vous risquez de perdre du temps au moment où vous pensiez démarrer. 

 [Aide pour remplir le formulaire dispo dans le kit de dev](https://plateforme-inclusion.notion.site/Migration-vers-ProConnect-8e736334739b49219dac368d5d1768a4?pvs=4)

Documentation : https://plateforme-inclusion.notion.site/Migration-vers-ProConnect-8e736334739b49219dac368d5d1768a4

Si questions voir avec Sonia Perelroizen

# :tada: Proposition de solution

# Tactique de migration chez IF proposée
## 15 Aout > 15 Septembre
  - [x] Demander les comptes de service à Pro Connect - En attente des infos pro connect voir avec @celineung @clement-duport @enguerranws  ⚙️
  - [x] Modifier la gateway HttpInclusionConnectGateway en HttpOAuthGateway en la rendant paramétrable en fonction du feature flag en cours pour tapper soit sur Inclusion Connect soit sur Pro Connect. 
  - [x] Préparer un feature flag + évolution de la feature de connexion qui permet de switch entre la connexion Inclusion Connect ou Pro Connect. 
     - Il impactera le front pour le rendu de la connexion IC ou PC.
     - Il impactera le back pour choisir le hhtpClient et le check de sub
     - On va ajouter une colonne de sub Pro Connect en plus du sub Inclusion Connect qu'on va conserver temporairement le temps qu'on confirme la migration et assurer un rollback juste en changeant le feature flag.
     > Tout a été fait niveau adapters / business logic / tests .... voir PR il reste à revoir les urls du httpClient ProConnect et maj la gateway HttpOAuthGateway pour les urls login/logout en pro connect + variables d'env
     > Attention : 
     >  - nouvelle variable d'env pour Pro Connect Base URI
     >  - colonne users.external_id renommée avec migration en users.external_id_inclusion_connect (Pour les tableau de bord)
  - [x] Obtenir l'intégration Pro Connect front et l'implémenter. Pro Connect est en retard. La team Inclusion Connect va nous contacter dès qu'ils l'auront. Ce n'est pas bloquant pour nous car les URLs PC ou IC sont gérés par le back. Risque qu'on ne l'ai pas d'ici le 1er octobre. Le InclusionConnectButton a été modifié en OAuthButton pour avoir un mode InclusionConnect ou ProConnect (pas de CSS custom pour l'instant à terminer) ~50% fait  ⚙️
  - [x] Obtenir un exemple du CSV pour tester le script vers le 1er septembre (voir script mais attente retour Sonia) 
  - [x] Préparer le script d'ajout des sub PC liés à un sub IC chez nous à partir un CSV fourni en entrée et le tester avec le CSV. Script testé avec des données de fake CSV en local. Reste la partie lecture du CSV et confirmation du format  ~80% fait ⚙️
  - [x] Revoir les tableaux de bord métabase qui utilisent la colonne users.external_id
## vers le 15 Septembre
  - Obtenir le CSV de mapping sub de la part de la team Inclusion Connect et lancer le script
  -  Faire un test de bascule en soirée du feature flag pour tester un compte existant chez nous
     - Test idéalement prévu avec des membres IC, PC, IF et d'autres équipes produit pour constater les problèmes ou confirmer le bon fonctionnement
     - Tester un compte admin IF avec email classique beta.gouv par exemple : A DETERMINER
     - Tester un compte admin IF agent FT avec email utilisable pour Agent Connect au travers de Pro Connect : A DETERMINER
     - Tester un compte qui a des droits sur une entreprise (entreprise GIP Inclusion ?) : A DETERMINER
     - Situation attendue:
       -  pas de problématique dans la dynamique de connexion, voir si PC demande des infos lors de la première connexion pour alimenter une doc / article de support pour la communication utilisateur
       - conservation des droits (tableaux de bord prescripteur / entreprise / admin)
  -  repasser le feature flag en mode Inclusion Connect pour attendre la migration réelle
## vers le 1er Octobre (ou plus tard si migration reportée)
  - [x] Message d'annonce sur le site IF qu'on passe en Pro Connect
  - [x] Obtenir le CSV de mapping sub de la part de la team Inclusion Connect mis à jour et lancer le script à nouveau pour les derniers comptes créés entre le 15 sep et le 1er oct.
  - [x] Faire la bascule du feature flag pour passer en mode Pro Connect
  - [x] En cas de problématique majeur et de décision de rollback il suffit de passer le feature flag en mode inclusion connect

**Comment by Amaury** [comment]
Pas le bon Amaury...

**Comment by bbohec** [comment]
Retour inclusion connect

y a pas de réunion spécifique c'est juste eux entre eux où ils font le point le mardi pour distribuer les token

donc l'ideal c'est de remplir le formulaire démarches simplifiées comme indiqué dans la doc pour le transfert avant le mardi midi comme ça tu devrais avoir tes token le mardi soir (normalement)

**Comment by enguerranws** [comment]
Recencement des urls de redirection : 

**Intégration**

Redirection logout

http://localhost:3000
https://dev.immersion-facile.beta.gouv.fr
https://staging.immersion-facile.beta.gouv.fr


Redirection login

http://localhost:3000/admin
https://dev.immersion-facile.beta.gouv.fr/admin
https://staging.immersion-facile.beta.gouv.fr/admin

http://localhost:3000/tableau-de-bord-agence
https://dev.immersion-facile.beta.gouv.fr/tableau-de-bord-agence
https://staging.immersion-facile.beta.gouv.fr/tableau-de-bord-agence

http://localhost:3000/tableau-de-bord-etablissement
https://dev.immersion-facile.beta.gouv.fr/tableau-de-bord-etablissement
https://staging.immersion-facile.beta.gouv.fr/tableau-de-bord-etablissement


**Production**

Redirection logout

https://immersion-facile.beta.gouv.fr


Redirection login

https://immersion-facile.beta.gouv.fr/admin
https://immersion-facile.beta.gouv.fr/tableau-de-bord-agence
https://immersion-facile.beta.gouv.fr/tableau-de-bord-etablissement

**Comment by celineung** [comment]
Doc intégration ProConnect: https://github.com/numerique-gouv/agentconnect-documentation/blob/main/doc_fs/implementation_technique.md

**Comment by celineung** [comment]
Préparer un CSV pour pro-connect pour lier les sirets aux utilisateurs: https://github.com/gip-inclusion/immersion-facile/issues/2142

**Comment by clement-duport** [comment]
spec pour integration :

https://github.com/numerique-gouv/agentconnect-documentation/blob/fcdb49688a04fac68940dfec44bc248f95268467/doc_fs/bouton_proconnect.md

**Comment by enguerranws** [comment]
- [ ] Finir le script de migration
- [ ] Gérer la déconnexion si user IC et authentification ProConnect activée
- [ ] Gérer le state au logout (pour éviter les man-in-the-middle - celui de ongoingAuth)
- [ ] Refaire un export userId / siret pour Sonia
