### ISSUE TITLE
ETQ BizDev je veux avoir le nombre de salarié par nombre de convention

### ISSUE THREAD

**Issue by Master-Touks** [gip-inclusion/immersion-facile#2047]
### :thinking: Contexte et problématique

Nastassia a besoin de la tranche d'âge par convention faites... 

### :tada: Proposition de solution

Avoir le nombre de conventions par entreprise et comparé les tranches d'âges

**Comment by enguerranws** [comment]
Exemple : 
- il y a 3556 conventions réalisées pour la tranche 18-25 ans
