### ISSUE TITLE
ETQ entreprise, je souhaite recevoir des mises en relations plus qualifiées

### ISSUE THREAD

**Issue by 3lodi3** [gip-inclusion/immersion-facile#206]
Améliorer la mer par email suite aux [retours entreprises](https://www.notion.so/gip-inclusion/Enqu-te-entreprises-20mer-0conv-cd2edbc3b096405cb652cc3d7b5b0509?pvs=4).

- Changer le texte du message + ajouter le lien vers article d'aide crisp
- Ajouter un champ téléphone
- Ajouter un select sur l'objectif (3 objectifs déjà définis)

Figma : https://www.figma.com/proto/O6MfTEZ1Ms8cKQHFjOYEA5/Site---UX-design?page-id=325%3A50764&type=design&node-id=325-50767&viewport=-427%2C436%2C0.63&scaling=min-zoom&starting-point-node-id=403%3A53897

Sur l'email en vue "reçu" par l'entreprise -> Pas sure que les champs de perso "OBJET_IMMERSION" et "POTENTIAL_BENEFICIARY_PHONE" existent ou aient ce format, à voir. 

Suite au modification on va en profité pour mettre en place une v2 pour l'API de mise en contacte : https://github.com/gip-inclusion/immersion-facile/issues/287

**Comment by clement-duport** [comment]
@nathalie-reyre Dans le figma c'est le message du bénéficiaire, je me trompe peut-être, mais je pensais que les infos supplémentaires que l'on récupère lors de la demande de mise en relations(objectif de l'immersion, téléphone, cv) allaient être intégrées au mail reçu par l'entreprise.

**Comment by clement-duport** [comment]
L'immersion souhaitée {a pour objectif d'{IMMERSION_OBJECT} et} porte sur le métier de APPELLATION_LABEL dans votre entreprise BUSINESS_NAME.

**Comment by 3lodi3** [comment]
@clement-duport l'email est dans le figma aussi ! D'autre part je t'ai invité dans figma via ton email clement.duports@gmail.com pour que tu puisses copier-coller les textes des maquettes

**Comment by clement-duport** [comment]
@3lodi3 yep j'ai vus, je me suis appuyer dessus merci !

**Comment by clement-duport** [comment]
@3lodi3 @nathalie-reyre  concernant le champ objectif de l'immersion, Est ce qu'on veut qu'il soit obligatoire et si oui qu'est ce qu'on met comme valeur pour les ancienne mise en relation?

**Comment by clement-duport** [comment]
Suite au modification on va en profité pour mettre en place une v2 pour l'API de mise en contacte : https://github.com/gip-inclusion/immersion-facile/issues/287
