### ISSUE TITLE
L'adresse auto-remplie lors du référencement d'entreprise n'est pas celle fournie par l'annuaire des entreprises

### ISSUE THREAD

**Issue by celineung** [gip-inclusion/immersion-facile#2060]
### :bug: Le problème

Sur le siret [88155577500025](https://annuaire-entreprises.data.gouv.fr/etablissement/88155577500025), l'annuaire des entreprises indique cette adresse: BAT5 LES HIRONDELLES 501 RES SEMSAMAR QUARTIER D'ORLEANS.

Mais lorsque l'on colle ce siret dans notre formulaire de référencement d'entreprise, on a cette adresse qui n'est pas du tout au même endroit :

![Image](https://github.com/user-attachments/assets/7554cd39-24ba-4ba5-90e5-16effb3f9739)

### :dart: Comportement attendu

Pouvoir référencer cette entreprise avec la bonne adresse.

**Comment by celineung** [comment]
Leur demander de renseigner une adresse plus précise à la main

**Comment by celineung** [comment]
OK pour Saint Martin.
La solution: On leur demande de saisir simplement "97150 Saint martin" et de voir lors de leurs échanges avec le candidat pour une adresse plus précise.

**Autre problème**: l'adresse à Saint Barthélemy.

![Screenshot 2024-08-08 at 17 47 16](https://github.com/user-attachments/assets/e9c3b2d7-f142-4170-8f30-72ad59365636)

alors que l'adresse est trouvée sur Opencage:

![Screenshot 2024-08-08 at 17 54 16](https://github.com/user-attachments/assets/0bc1e759-03c0-47e7-a785-a84d28edb6b4)

**Comment by enguerranws** [comment]
Pour Saint Barthélémy, il faut l'ajouter dans le record de départements (address.dto.ts). On les a ajouté au fur et à mesure des demandes, et visiblement, il n'y a pas trop de demandes d'immersions à Saint Berthélémy
