### ISSUE TITLE
Espaces dans le param `place` sur la page de recherche

### ISSUE THREAD

**Issue by calummackervoy** [gip-inclusion/immersion-facile#2070]
### :bug: Le problème

En testant l'URL suivante : https://staging.immersion-facile.beta.gouv.fr/recherche?distanceKm=20&place=Aubervilliers%2C Île-de-France%2C France, j'ai noté qu'il y a des espaces ajouté sur le param `place` dans l'URL

Les espaces sont considerés "unsafe" dans le [RFC 1738](https://www.ietf.org/rfc/rfc1738.txt):

> The space character is unsafe because significant spaces may disappear and insignificant spaces may be introduced when URLs are transcribed or typeset or subjected to the treatment of word-processing programs

Principalement ça peut poser un problème sur la serialization des URLs partagées en ligne - par example sur gmail : 

<img width="721" alt="Screenshot 2024-08-08 at 14 31 09" src="https://github.com/user-attachments/assets/b5162bfc-a594-4c4e-a443-b6e46744c6ad">

### :footprints: Étapes pour reproduire

1. Lancer un recherche sur https://staging.immersion-facile.beta.gouv.fr/recherche
2. Préciser la ville `Aubervilliers, Seine-Saint-Denis, France`
3. l'URL générée inclut les espaces

### :dart: Comportement attendu

Je suggerais d'utiliser l'encoding avec `encodeURIComponent` de JS, qui va remplacer aussi des charactères dans les noms des régions comme Île de France... par example : https://staging.immersion-facile.beta.gouv.fr/recherche?distanceKm=20&place=Aubervilliers%2C%20%C3%8Ele%20de%20France%2C%20France

(À noter aussi qu'un changement qui rendre les URLs existantes invalides peut empêcher les utilisateurs existants, donc normalement c'est mieux de soutenir les anciennes URLs pendant un certain temps)

**Comment by enguerranws** [comment]
Merci pour ce retour @calummackervoy !
