### ISSUE TITLE
Mettre à jour la page budget (captures d'écran)

### ISSUE THREAD

**Issue by enguerranws** [gip-inclusion/immersion-facile#2086]
### :thinking: Contexte et problématique (et par qui est-ce remonté ?)

La page budget n'est pas à jour, on pourrait la rafraichir rapidement en mettant à jour les captures d'écrans et le texte, en attendant une version embed metabase.

**Comment by enguerranws** [comment]
@Master-Touks besoin d'aide sur ce ticket ?

**Comment by Master-Touks** [comment]
Oui je veux bien, j'avoue. Faut que je modifie le CAC pour apporter des ajouts au niveau prescripteur et entreprise puis je te dis. 
Merci @enguerranws

**Comment by Master-Touks** [comment]
@enguerranws à embed : https://metabase.immersion-facile.beta.gouv.fr/public/dashboard/dac7f422-0bca-411e-9dae-e2ca9701af8a
