### ISSUE TITLE
Bug sur l'âge minimum - à investiguer

### ISSUE THREAD

**Issue by enguerranws** [gip-inclusion/immersion-facile#2094]
Remontée du support : un bénéficiaire pour un mini-stage a entré la date de naissance 08/03/2009 et obtient un message d'erreur -> L'âge du bénéficiaire doit être au minimum de 10 ans.

**Comment by clement-duport** [comment]
J'ai tester en local et meme en prod pour être sure (je ne l'ai pas envoyer) et aucun problème avec cette date de naissance
