### ISSUE TITLE
ETQ candidat, le lien proposé depuis "mon espace" pour accéder à la fiche bilan est cassé

### ISSUE THREAD

**Issue by nathalie-reyre** [gip-inclusion/immersion-facile#2100]
### :bug: Le problème

impossible d'accéder à l'article du helpdesk sur le bilan (et au lien pour télécharger la fiche) depuis la page https://immersion-facile.beta.gouv.fr/tableau-de-bord-beneficiaire

### :dart: Comportement attendu

ouverture de l'article bilan :  

](https://aide.immersion-facile.beta.gouv.fr/fr/article/le-bilan-de-limmersion-1q9asij/)

**Comment by celineung** [comment]
doublon avec #https://github.com/gip-inclusion/immersion-facile/issues/2102
