### ISSUE TITLE
ETQ administrateur, je peux modifier une adresse mail invalide d'une agence non encore validée par une adresse mail d'un user inclusion connecté mais pas encore rattaché à une agence

### ISSUE THREAD

**Issue by nathalie-reyre** [gip-inclusion/immersion-facile#2107]
### :bug: Le problème

une structure a pu être créée avec un mail invalide (gamil.com-. En //, le responsable de la structure a créé son compte sur inclusion connect avec le mail valide (gmail.com).
Avant d'activer (ou de refuser) la structure, j'ai voulu corriger le mail en base pour que la notification par mail arrive bien; 
Impossible de corriger le mail 
cf :  ERROR: duplicate key value violates unique constraint "authenticated_users_email_key"
DETAIL: Key (email)=(opus.entreprise.insertion@gmail.com) already exists. 15:38:39. j'ai essayé de faire la modif dans la table où le mail parait (user ) requete SQL : ERROR: duplicate key value violates unique constraint "authenticated_users_email_key"
DETAIL: Key (email)=(opus.entreprise.insertion@gmail.com) already exists. 15:38:39 Requête SQL
UPDATE "users" SET
"id" = 'd669562d-3679-4f36-b4a5-c8dde0a765be',
"email" = 'opus.entreprise.insertion@gmail.com',
"first_name" = '',
"last_name" = '',
"created_at" = '2024-08-05 15:10:29.437416+00',
"updated_at" = '2024-08-05 15:10:29.437416+00',
"external_id" = NULL
WHERE "email" = 'opus.entreprise.insertion@gamil.com';

il se trouve qu'en effet un user existe bien avec le mail en gmail. C'est le responsable qui a activé inclusion connect et n'a pas pu demander le rattachement à sa structure puisque celle-ci est en stand by.

### :dart: Comportement attendu

1/le mail au moment de la création de la structure devrait être vérifié par emailable
2/ si un user existe déjà via inclusion connect, on doit pouvoir modifier le mail d'une structure en base même si le user n'est pas encore rattaché à la structure.

**Comment by bbohec** [comment]
Oubli de clôture de bug placé en production
