### ISSUE TITLE
ETQ admin, je peux en back office attribuer le rôle de viewer only à un utilisateur IC

### ISSUE THREAD

**Issue by nathalie-reyre** [gip-inclusion/immersion-facile#2109]

**Comment by celineung** [comment]
ETQ admin, lorsque je rapproche un utilisateur ic, je veux voir afficher la modale de gestion des rôles utilisateur au lieu d'avoir juste la dropdown avec les choix conseiller et valideur:

![Image](https://github.com/user-attachments/assets/99103062-a4f7-45b5-8ce2-5e7f2309b1e2)
