### ISSUE TITLE
ETQ entreprise, je réponds directement au candidat qui m'a contacté par l'intermédiaire d'IF

### ISSUE THREAD

**Issue by nathalie-reyre** [gip-inclusion/immersion-facile#211]
en cliquant sur répondre directement dans le mail reçu (formulaire de contact). La réponse de l'entreprise est stockée en base.

**Comment by nathalie-reyre** [comment]
doc SIB et stockage maison

**Comment by JeromeBu** [comment]
Il faut réviser le mail de mise en relation par mail initial.... Voici l'actuel :



![Image](https://github.com/gip-inclusion/immersion-facile/assets/22095555/c03cf66f-4ffb-412c-adbb-9b01e72bda6a)


Est-ce qu'on enlève le téléphone ? comme ca on peut tracker les réponses par mail uniqement ?

**Comment by JeromeBu** [comment]
Est-ce qu'on garde le boutton de réponse par mail ? Sachant qu'on peut répondre au mail, ca fonctionnera aussi

Et il faut sans doute revoir le wording

**Comment by enguerranws** [comment]
```
Ce candidat attend une réponse, vous pouvez : 
- répondre directement à cet email, il lui sera transmis 
- en cas d'absence de réponse par email, vous pouvez essayer de le contacter par tel : 06 21 54 87 12
```

**Comment by enguerranws** [comment]
![image](https://github.com/gip-inclusion/immersion-facile/assets/2190121/47afcce9-656d-45d1-8e44-f839df1ba70f)

**Comment by enguerranws** [comment]
![Capture d’écran 2023-06-30 à 10 17 06](https://github.com/gip-inclusion/immersion-facile/assets/2190121/9e813e7d-a773-44e6-8719-e9c2542ce711)
