### ISSUE TITLE
Ajouter le kind et la nature de l'agence (prescripteur ou structure d'accompagnement)

### ISSUE THREAD

**Issue by 3lodi3** [gip-inclusion/immersion-facile#2110]
### :thinking: Contexte et problématique

Le type d'agence n'est pas modifiable en admin.
La nature : prescripteur ou structure d'accompagnement n'est pas visible et cela pose un pb notamment côté support car les fonctionnements sont différents dans le parcours de signature électronique.

### :tada: Proposition de solution

- Ajouter le kind - modifiable
- Ajouter la nature (prescripteur ou structure d'accompagnement) - non modifiable
- Edit du 3 oct suite à échange avec Sylvie : faire apparaître le nom du prescripteur lié à la structure d'accompagnement

### :camera: Maquettes

https://www.figma.com/proto/rZtRL0ShjGKfdw43nMUPex/Site---UX-design-2nd-trimestre-2024?page-id=3285%3A1202&node-id=3448-14227&viewport=888%2C320%2C0.5&t=OXDcmAC9qgBVPuCw-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=3448%3A14227

**Comment by celineung** [comment]
en modification:
- supprimer les deux champs validateur/conseillers
- sur le tableau des users: avoir la possibilité de toujours mettre le role pré-valideur
