### ISSUE TITLE
Redirection non-anticipée sur un URL

### ISSUE THREAD

**Issue by calummackervoy** [gip-inclusion/immersion-facile#2112]
### :bug: Le problème

Sur les emplois, j'ai ajouté une fonctionnalité qui permet nos utilisateurs de trouver une immersion facilitée

l'URL que j'ai construit à cet effet marche bien dans le plupart des cas :

https://immersion-facile.beta.gouv.fr/recherche?distanceKm=20&latitude=48.912592&longitude=2.375613&sortedBy=distance&place=Aubervilliers%2C%20%C3%8Ele-de-France%2C%20France&mtm_campaign=les-emplois-recherche-immersion&mtm_kwd=les-emplois-recherche-immersion

Par contre pendant un test, on a trouvé que cet URL a été redirigé vers une recherche sur la service `Diagoriente`. Je ne sais pas si cette redirection est anticipée, sous certaines conditions ? C'est possible qu'il y a pas une anomalie ici

### :footprints: Étapes pour reproduire

Désolé je n'ai pas pu le reproduire de manière fiable. C'est possible que un cookie est impliqué car après j'ai redémarré mon navigateur le comportement est disparu

**Comment by gargagif** [comment]
Redirection correspond à un A/B test
