### ISSUE TITLE
ETQ adm, je n'arrive pas à voir correctement dans le BO les agences à valider

### ISSUE THREAD

**Issue by nathalie-reyre** [gip-inclusion/immersion-facile#2121]
### :bug: Le problème

le tableau de bord ne semble plus rattaché à la prod (alors que Jérôme l'avait rattaché en juillet) et surtout affiche un nombre très limité d'agences à valider et pas  forcément les dernières.
Les filtre par nom affiche bien l'ensemble des noms des structures mais quand on clique sur un nom, la structure ne s'affiche pas.
### :footprints: 
![Capture d’écran 2024-08-23 à 11 55 57](https://github.com/user-attachments/assets/5ade25da-5ba4-4140-a2e8-fce91d6083e8)

### :dart: Comportement attendu

tableau branché sur la prod et affichant toutes les structures à valider avec des filtres qui fonctionnent.

**Comment by celineung** [comment]
corrigé sur Metabase
