### ISSUE TITLE
ETQ entreprise, lorsque je veux répondre à une mer via mon espace perso, j'arrive directement sur la bonne page après m'être connecté avec Pro Connect

### ISSUE THREAD

**Issue by celineung** [gip-inclusion/immersion-facile#2125]
### :bug: Le problème

Lorsque j'accède à une discussion en tant que contact de l'entreprise mais que je suis pas inclusion connecté, j'ai ce message d'erreur au lieu d'avoir le bouton de connexion inclusion connect:

![Image](https://github.com/user-attachments/assets/74f209b6-5b6d-4016-abfd-5c8c784fb969)

Exemple sur la staging:
https://staging.immersion-facile.beta.gouv.fr/pilotage-mise-en-relation?discussionId=7f6b852b-8625-4659-ba14-9b9551aecbbd

### :dart: Comportement attendu

- Lorsque je clique sur https://staging.immersion-facile.beta.gouv.fr/pilotage-mise-en-relation?discussionId=7f6b852b-8625-4659-ba14-9b9551aecbbd, je voudrais être redirigée sur une page qui m'invite à m'inclusion connecter.
- Puis je voudrais être redirigé directement vers la bonne page : la discussion à laquelle on m'a demandé de répondre dans l'email de notif de mer.

**Comment by enguerranws** [comment]
Il faudrait regrouper ces URLs privées sous le même path (tableau-de-bord-entreprise/mise-en-relation/{id}), on profiterait du composant de route privée.
