### ISSUE TITLE
ETQ Admin j'ai la liste des utilisateurs a valider dans l'ordre alphabétique

### ISSUE THREAD

**Issue by Sylvieleb** [gip-inclusion/immersion-facile#2140]
### :thinking: Contexte et problématique

Je suis au téléphone avec un conseiller d'une agence
Je le guide dans son inscription sur inclusion connect
je veux le valider rapidement pour le guider vers la suite mais je mets du temps à le retrouver dans la liste 
### :tada: Proposition de solution

Avoir cette liste par ordre alphabétique

https://immersion-facile.beta.gouv.fr/admin/agencies
![image](https://github.com/user-attachments/assets/31074863-4821-45b8-b477-14a4387cf76d)

![image](https://github.com/user-attachments/assets/75ae78a9-b18d-4b45-958f-8cff35d69201)

**Comment by gargagif** [comment]
Après discussion avec Sylvie je clôture ce ticket : le besoin n'est plus d'actualité dans la mesure où ce sont désormais les admins d'agences qui vont gérer les utilisateurs depuis la page de l'agence, où il y a un tableau d'utilisateurs. Le champ mentionné dans le ticket n'a donc plus vocation à être utilisé.
