### ISSUE TITLE
Remplacer les placeholders par la description additionnelle sur les champs de saisie

### ISSUE THREAD

**Issue by mdamourette** [gip-inclusion/immersion-facile#2149]
### :thinking: Contexte et problématique (et par qui est-ce remonté ?)

Lors d'une intervention au support pour la saisie d'une convention, les utilisateurs pensaient que certains champs avec des placeholders étaient déjà remplis. Par conséquent, ils passaient à la suite sans y prêter attention.

### :tada: Proposition de solution

Il faudrait remplacer les placeholders par une description additionnelle (prévue dans le composant) afin de laisser le champ vide.

**Comment by gargagif** [comment]
déjà traité
