### ISSUE TITLE
Pas d'accusé de signature pour le dernier signataire

### ISSUE THREAD

**Issue by bbohec** [gip-inclusion/immersion-facile#215]

**Comment by bbohec** [comment]
![Image](https://github.com/gip-inclusion/immersion-facile/assets/58432308/3f997554-8810-4e26-b30c-38d6b35314ab)

**Comment by bbohec** [comment]
A discuter si c'est normal ou pas.

**Comment by 3lodi3** [comment]
Je pense que cela peut poser problème dans le cas où le conseiller tarde à valider la convention : l'usager n'aura pas l'info et ne pensera pas forcément à le relancer (ou pourrait presque ajouter un message à l'attention du candidat dans ce sens d'ailleurs, en remettant le contact du conseiller, sinon ça revient charger le support de notre côté).
