### ISSUE TITLE
ETQ Entreprises - Je souhaite accèder à une convention via mon espace perso

### ISSUE THREAD

**Issue by mdamourette** [gip-inclusion/immersion-facile#2151]
### :thinking: Contexte et problématique (et par qui est-ce remonté ?)
Plusieurs entreprises demandent au support comment accèder à leur convention via leur espace perso.

### :tada: Proposition de solution

Il faudrait pouvoir ouvrir directement la page de Pilotage d'une Convention depuis le tableau metabase en cliquant sur l'ID correspondant et enlever le champ de pilotage.

**Comment by gargagif** [comment]
Déjà traité
