### ISSUE TITLE
Gérer la vérification du state de ProConnect au login et logout

### ISSUE THREAD

**Issue by celineung** [gip-inclusion/immersion-facile#2164]
https://github.com/numerique-gouv/agentconnect-documentation/blob/main/doc_fs/implementation_technique.md

**Comment by nathalie-reyre** [comment]
A vérifier "find by state" ?

**Comment by mdamourette** [comment]
Test sur la staging ok ✅

**Test 1**
- Je suis connectée avec Inclusion Connect
- IF bascule sur Pro Connect
- Je suis bien déconnectée avec Inclusion Connect

**Test 2**
- Je suis connectée avec Pro Connect
- IF bascule sur Inclusion Connect
- Je suis bien déconnectée avec Pro Connect
