### ISSUE TITLE
Rendre cliquables les ID de convention / les ID de mer dans le tdb entreprise + prescripteurs si possible

### ISSUE THREAD

**Issue by 3lodi3** [gip-inclusion/immersion-facile#2165]
### :thinking: Contexte et problématique (et par qui est-ce remonté ?)

Le fait de copier-coller les ID de convention / mer pour les "piloter" est très mal compris par les entreprises qui abandonnent les parcours et génèrent des tickets support.

### :tada: Proposition de solution

Dans les espaces perso entreprise et prescripteur :
Rendre les ID des tableaux metabase dans les espaces perso cliquables pour ouvrir directement : 
- au clic sur ID de convention -> Page pilotage
- au clic sur ID de mer -> Page conversation

Supprimer le bloc "pilotage" sauf dans l'onglet "Conventions synchronisées" de l'espace prescripteur en attendant que tous les boutons soient migrés dans la page de pilotage.

**Comment by enguerranws** [comment]
- pour une discussion : https://immersion-facile.beta.gouv.fr/tableau-de-bord-etablissement/discussions?discussionId={id de la discussion}
- pour une convention : https://immersion-facile.beta.gouv.fr/pilotage-convention-inclusion-connect?conventionId={id de convention}

**Comment by Master-Touks** [comment]
Done ✅ 
(j'aurais besoin de vérifier que ce sont les bon tableaux)
