### ISSUE TITLE
bug sur la visibilité entreprise et le nb de contact max par mois

### ISSUE THREAD

**Issue by 3lodi3** [gip-inclusion/immersion-facile#2175]
### :bug: Le problème

Sur la prod j'ai créé une entreprise pour faire des tests.
Je me suis mise en visibilité cachée avec 1 contact max par mois.

Mais j'ai reçu une mer le 9 septembre alors que j'étais cachée et que j'avais déjà reçu une mer le 4 septembre.

### :footprints: Étapes pour reproduire

voir captures videos et photo dans discord : https://discord.com/channels/864451835553513474/1282617562840039466

### :dart: Comportement attendu

- Si je suis en visibilité cachée, je souhaite ne plus apparaître dans les résultats de recherche dès que je mets à jour ma fiche entreprise.
- Si je mets un nb de contact max par mois je ne souhaite plus recevoir de mer dès que ce nb est atteint et pour le mois en cours (ex : du 1er au 30 septembre).
- Bonus : je trouve que le fait de ne plus voir la visibilité que l'on a sélectionnée et les champs associés donne un effet "bug". Je pense qu'il faut laisser affichés les champs sélectionnés, suaf éventuellement si l'entreprise n'a pas été màj depuis longtemps, je fais un ticket dédié pour ces suggestions : #2176 

### Screenshots

voir captures videos et photo dans discord : https://discord.com/channels/864451835553513474/1282617562840039466

**Comment by ClementLmd** [comment]
Après investigation, il semblerait que cela fonctionne normalement : l'entreprise n'apparaît pas si elle est masquée (is_searchable=false) ou si son nombre de contact par mois est atteint.
Ticket repassé dans "à faire dans l'itération".

**Comment by enguerranws** [comment]
On arrive pas à reproduire le souci techniquement (les infos sont bien enregistrés, bien mises à jour et les résultats de recherche n'étaient plus visible dans la recherche).

Plusieurs choses à noter : 
- le comportement de la première question (oui / non) induit peut être en erreur
- il y a des résultats de recherches qui correspondent à d'anciens sirets (fermés) et qui peuvent aussi induire en erreur (la personne indique ne plus être dispo et elle voit un résultat de recherche obsolète correspondant à un vieux siret de la même boîte qui s'affiche) - ticket à créer
