### ISSUE TITLE
ETQ entreprise, quand je modifie mes paramètres de visibilité, je dois comprendre facilement ce que j'ai fait. 

### ISSUE THREAD

**Issue by 3lodi3** [gip-inclusion/immersion-facile#2176]
### :thinking: Contexte et problématique (et par qui est-ce remonté ?)

La visibilité entreprise se "remet à zéro" après qu'on l'aie choisie ce qui donne un effet bug.

### :tada: Proposition de solution

Laisser affichés les choix sélectionnés sauf si l'entreprise n'a pas màj son entreprise depuis xxx temps par ex :
- à l'envoi du mail de maj entreprise bi-annuel
- à l'expiration de la date de non disponibilité renseignée sur la fiche entreprise

Ex :
- entreprise non visible : https://www.figma.com/proto/Z7nwSYCDH32RlQOMfMns2w/Site---UX-design-3e-trimestre-2024?page-id=28%3A6683&node-id=562-227&node-type=frame&viewport=-554%2C402%2C0.5&t=AuPUbmOUDJHawvNz-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=28%3A7153
- entreprise visible : https://www.figma.com/proto/Z7nwSYCDH32RlQOMfMns2w/Site---UX-design-3e-trimestre-2024?page-id=28%3A6683&node-id=562-3299&node-type=frame&viewport=-1249%2C402%2C0.5&t=EJZ064DLOTwLvD3J-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=28%3A7153
- entreprise pas màj depuis xxx : https://www.figma.com/proto/Z7nwSYCDH32RlQOMfMns2w/Site---UX-design-3e-trimestre-2024?page-id=28%3A6683&node-id=562-3415&node-type=frame&viewport=-1249%2C402%2C0.5&t=EJZ064DLOTwLvD3J-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=28%3A7153

**Comment by enguerranws** [comment]
- modification de suggestion mise à jour (6 mois) : ajout d'un param dans l'url pour ne pas afficher les infos stockés dans le choix de dispo
- dans les autres cas, on affiche les choix renseignés
