### ISSUE TITLE
Améliorer l'expérience utilisateur lorsqu'on essaie de resynchroniser une convention qui a déjà été synchro il y a moins de 4h

### ISSUE THREAD

**Issue by 3lodi3** [gip-inclusion/immersion-facile#2184]
### :thinking: Contexte et problématique (et par qui est-ce remonté ?)

1. Le message d'erreur n'est pas clair.
2. La convention est synchronisée automatiquement à sa création, mais le bouton de synchro n'est pas désactivé.
https://discord.com/channels/864451835553513474/1281181364086902835

![Image](https://github.com/user-attachments/assets/2ef40e38-4b41-41bd-81dd-0e241edf29dd)

### :tada: Proposition de solution

 

https://github.com/user-attachments/assets/c1b71d8b-1a57-48fb-9dc0-3d0273e19695

**Contenu textuel (après création) :** "La convention a été synchronisée automatiquement à sa création le 05/09/2024 à 04h18. Vous pourrez la resynchroniser à nouveau dans 3 heures et 53 minutes."

**Contenu textuel (après synchro) :** "La convention a déjà été synchronisée le 05/09/2024 à 04h18. Vous pourrez la resynchroniser à nouveau dans 3 heures et 53 minutes."

Lien du proto Figma : https://www.figma.com/proto/Z7nwSYCDH32RlQOMfMns2w/Site-UX-design-3e-trimestre-2024?node-id=506-33&node-type=canvas&t=cBEYUz24iDWlEVcG-0&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=677%3A4840

**Comment by celineung** [comment]
@3lodi3 @mdamourette on va rajouter la modale, mais on se dit qu'il n'y a pas besoin de distinguer si la synchro a été automatique on non. Le message d'erreur serait donc toujours "La convention a déjà été synchronisée le 05/09/2024 à 04h18. Vous pourrez la resynchroniser à nouveau dans 3 heures et 53 minutes."

**Comment by mdamourette** [comment]
Ok parfait ça me va ! D'ailleurs je n'ai pas encore eu le temps de faire les maquettes, mais dans l'idée il faudrait éviter les messages d'alertes dans la barre d'action. Il faudrait donc, même quand ça réussit, afficher le message autrement. Mais je pourrais faire un autre ticket si besoin.
