### ISSUE TITLE
ETQ receveur de lien de partage de convention, je veux voir les infos correctes du bénéficiaire

### ISSUE THREAD

**Issue by celineung** [gip-inclusion/immersion-facile#2187]
### :bug: Le problème

Lorsque je clique sur un lien de partage de convention peConnecté, les infos utilisateurs sont stockées dans le local storage.
Mais lorsque je clique sur une autre convention qui m'a été partagée - qui n'est pas peConnectée, ce sont les informations du bénéficiaire de la 1ere convention qui sont affiché dans ce formulaire.

### :dart: Comportement attendu

Ne pas stocker dans le local storage les infos utilisateurs d'une convention qui m'est partagée. A discuter en équipe.

**Comment by ClementLmd** [comment]
Doublon #2122
