### ISSUE TITLE
Ajout d'un deuxième onglet dans le dashboard agence inclusion connecté, pour voir les conventions en erreur dans l'agence et pouvoir les corriger

### ISSUE THREAD

**Issue by JeromeBu** [gip-inclusion/immersion-facile#219]

**Comment by JeromeBu** [comment]
On peut peut-être agrandir un peu le text verticalement pour éviter le scroll :

<img width="1657" alt="image" src="https://github.com/gip-inclusion/immersion-facile/assets/22095555/b38cce38-007e-40d2-ad2c-a7f84149b30b">

**Comment by JeromeBu** [comment]
@3lodi3 si tu as des idées pour l'intégration . On partait sur des onglets

**Comment by 3lodi3** [comment]
Yes parfait !

**Comment by JeromeBu** [comment]
Taches à faire :

- [ ] ajouter des onglets. Par defaut, il n'y en aura qu'un
- [ ] si l'agence est de type pole emploi, alors afficher un 2ème onglet : Conventions en erreur
- [ ] prévoir la route backend pour récupéer le tableau métabase d'erreur sur l' agences connectés
- [ ] sur le nouvelle onglet, aller chercher le tableau metabase correspondant à l'agence et l'afficher
