### ISSUE TITLE
Dans l'admin, ajouter le nom de l'agence prescriptrice et rattacher dans un tableau spécifique tous les utilisateurs concernés (validateurs ou lecteurs)

### ISSUE THREAD

**Issue by 3lodi3** [gip-inclusion/immersion-facile#2190]
### :thinking: Contexte et problématique (et par qui est-ce remonté ?)

Actuellement, le tableau qui répertorie les utilisateurs sur une structure d'accompagnement affiche aussi les validateurs côté prescripteur lié.
On en devrait pas pouvoir changer le rôle de ces prescripteurs et on devrait les visualiser différemment.

D'autre part le comportement n'est pas le même selon les structures d'accompagnement, parfois seule l'adresse générique du prescripteur apparaît en validateur, parfois tous les utilisateurs du prescripteur sont validateurs :
![Image](https://github.com/user-attachments/assets/98a5e6f3-a9fc-4af1-ba96-f01147274ea3)
![Image](https://github.com/user-attachments/assets/3b42434d-2d8a-4210-9522-f57a696e11a4)

### :tada: Proposition de solution

Dans l'onglet "Utilisateurs" on va retrouver les utilisateurs de la structure d'accompagnement et en-dessous les utilisateurs de la structure liée en lecture seule. 

![utilisateurs](https://github.com/user-attachments/assets/b1832454-709f-43b3-be8c-047f66379f71)

**Lien Figma :** https://www.figma.com/proto/Z7nwSYCDH32RlQOMfMns2w/Site---UX-design-3e-trimestre-2024?node-id=862-601&node-type=frame&t=522Vgchmal5LgzfY-1&scaling=min-zoom&content-scaling=fixed&page-id=861%3A33&starting-point-node-id=862%3A601

**Comment by JeromeBu** [comment]
Voilà un aperçu de la nouvelle version pour les structures d'accompagnement :
![Image](https://github.com/user-attachments/assets/9d3ee0b1-6130-4d33-b96e-8e7c9e851655)



Et pour les prescripteurs (une agence qui ne réfère pas à une autre) :
![Image](https://github.com/user-attachments/assets/16a0a0eb-c42f-4625-8cf5-5a78120603b1)
