### ISSUE TITLE
ETQ France Travail, je veux recevoir les conventions d'autres types d'agences + voir les conventions

### ISSUE THREAD

**Issue by celineung** [gip-inclusion/immersion-facile#2196]
Demandes FT:

- Recevoir les conventions des types d'agences Cap Emploi, Mission local, Conseil départemental pour novembre + rattrapage des anciennes conventions validées des Conseil Départementaux => déjà traité

- Pouvoir appeler nos routes pour afficher une convention + générer les PDF des conventions (pour le 1er trimestre 2025)

- Envoyer le type "france-travail" au lieu de "pole-emploi"

**Comment by nathalie-reyre** [comment]
API FT OK -  reste à avoir le go côté juridique --> convention CHEOPS/FT/PDI en cours de signature. Quid CD ? Il faudra une convention également avec l'UNML

**Comment by gargagif** [comment]
Je clôture car doublon #1619
