### ISSUE TITLE
ETQ prescripteur mon espace n'affiche pas tous les filtres du tableau de bord

### ISSUE THREAD

**Issue by Jessicaceleste1** [gip-inclusion/immersion-facile#2219]
### :bug: Le problème

Depuis le tableau de bord prescripteur, les filtres "statut de la convention" et "candidat", ne s'affichent pas, ça mouline

**Comment by Jessicaceleste1** [comment]
lien discord : https://discord.com/channels/864451835553513474/1042365650359828480/1286598855852560454

**Comment by Master-Touks** [comment]
Solution envisagée et suggérée par @JeromeBu, créer un nouveau model de donnée pour les utilisateurs connectés.

**Comment by Master-Touks** [comment]
Problème partiellement résolu, en attente de savoir s'il y a des remontés utilisateur
