### ISSUE TITLE
ETQ que propect (entreprise), je peux accéder à la page accueil établissement même si j'ai un lien obsolète

### ISSUE THREAD

**Issue by nathalie-reyre** [gip-inclusion/immersion-facile#2242]
les flyers qu'on a en stock et qu'on diffuse lors des événementiels renvoie sur une url qui n'est plus active :  https://immersion-facile.beta.gouv.fr/etablissement.  Prévoir une redirection vers la home entreprise :  https://immersion-facile.beta.gouv.fr/accueil-entreprises

**Comment by enguerranws** [comment]
Redirection 301 à mettre en place
