### ISSUE TITLE
ETQ admin, je ne peux plus activer ou rejeter une agence

### ISSUE THREAD

**Issue by Jessicaceleste1** [gip-inclusion/immersion-facile#2249]
### :bug: Le problème

depuis admin, 
agence
je copie colle l'ID d'une structure pour l'activer ou la rejeter et lorsque je clique sur le bouton examiner une agence, rien ne se passe. 

![image](https://github.com/user-attachments/assets/1eba99d6-ea91-46cd-9d67-c4cfd5a8df50)

**Comment by clement-duport** [comment]
le problème venait d'une agence sans valideur, j'ai fait le fix en db
