### ISSUE TITLE
Corriger les liens vers le helpdesk sur le site

### ISSUE THREAD

**Issue by 3lodi3** [gip-inclusion/immersion-facile#2259]
### :thinking: Contexte et problématique (et par qui est-ce remonté ?)

Suite à la réorganisation du helpdesk les liens redirigeant vers des articles en dur sur le site sont morts.

### :tada: Proposition de solution

Remplacer les liens partout (app + automatisation + mail ?) où c'est nécessaire.

### Page https://immersion-facile.beta.gouv.fr/tableau-de-bord-beneficiaire

| Texte du lien | URL |
|--------|--------|
| [Je n'ai pas reçu la convention validée, que faire ?](https://immersion-facile.beta.gouv.fr/aide/article/je-nai-pas-recu-la-convention-validee-que-faire-1y3t9xw/) | Cell |
| [Comment signer ma convention ou envoyer un lien de signature ?](https://immersion-facile.beta.gouv.fr/aide/article/comment-signer-ma-convention-ou-envoyer-un-lien-de-signature-125bxxd/) | Cell |
| [Comment connaître l'état d'une demande de convention ?](https://immersion-facile.beta.gouv.fr/aide/article/comment-connaitre-letat-dune-demande-de-convention-1gbhxt4/) | Cell |
| [Quelles sont les étapes de signature de la convention ?](https://immersion-facile.beta.gouv.fr/aide/article/quelles-sont-les-etapes-de-signature-de-la-convention-17hf59q/) | Cell |
| [Guide de l’immersion](https://immersion-facile.beta.gouv.fr/aide/category/guide-de-limmersion-v19aod/) | Cell | 
| Cell | Cell | 

### Footer Home

| Texte du lien | URL |
|--------|--------|
| [Comment signer ma convention ou envoyer un lien de signature ?](https://immersion-facile.beta.gouv.fr/fr/article/comment-signer-ma-convention-ou-envoyer-un-lien-de-signature-si-je-nai-plus-le-lien-envoye-par-mail-125bxxd/) | Cell | 

### Recherche candidats

| Texte du lien | URL |
|--------|--------|
| [nos conseils pour vous démarquer](https://immersion-facile.beta.gouv.fr/aide/article/choisir-lobjet-et-rediger-un-email-de-motivation-pour-decrocher-une-immersion-xytzii/) | Cell | 

### Formulaire convention

| Texte du lien | URL |
|--------|--------|
| [nos conseils ici](https://immersion-facile.beta.gouv.fr/aide/article/je-nai-pas-de-structure-daccompagnement-et-je-veux-faire-une-immersion-1x15rdp). | Cell |
| [cela peut être utile au candidat et à l'entreprise](https://immersion-facile.beta.gouv.fr/aide/article/comment-remplir-la-demande-de-convention-xryn5j/#3-le-candidat-a-une-reconnaissance-travailleur-handicape-rqth-ou-equivalent-optionnel). | Cell |
| [Dans quelles situations puis-je faire une immersion pendant mon temps de travail ?](https://immersion-facile.beta.gouv.fr/aide/article/comment-remplir-la-demande-de-convention-xryn5j/#3-le-beneficiaire-est-actuellement-salarie-dune-entreprise-et-limmersion-va-se-derouler-pendant-le-temps-de-travail-habituel-optionnel) | Cell |
| Cell | Cell |
| Cell | Cell | 

-> Convention à refaire en staging pour voir si les liens de la page de confirmation sont cassés

### Footer Home prescripteurs

| Texte du lien | URL |
|--------|--------|
| [Puis-je faire une demande de convention avec une entreprise non inscrite sur le site ?](https://immersion-facile.beta.gouv.fr/aide/article/puis-je-faire-une-demande-de-convention-avec-une-entreprise-non-inscrite-sur-le-site-f9z742/) | Cell |
| [Le bénéficiaire, l'entreprise ou le prescripteur n'a pas reçu la convention à signer](https://immersion-facile.beta.gouv.fr/fr/article/comment-signer-ma-convention-ou-envoyer-un-lien-de-signature-si-je-nai-plus-le-lien-envoye-par-mail-125bxxd/) | Cell |

**Comment by celineung** [comment]
https://docs.google.com/spreadsheets/d/1RT3e3d38duiy0d5cgLaPvuToxLSJC_yJnqWYI2YlRXQ/edit?gid=215052152#gid=215052152
