### ISSUE TITLE
ETQ signataire d'une convention validée par l'agence FT de Beaune, de Montbard ou de Châtillon/seine (21), j'ai accès au support de bilan normal

### ISSUE THREAD

**Issue by nathalie-reyre** [gip-inclusion/immersion-facile#2261]
le support de bilan pour ces 3 agences est un Google doc avec accès verrouillé. c'est un support qui avait été créé pour le CD21 et qui n'a aucune raison d'être utilisé par France Travail. 
Il faut donc mettre à jour ces 3 agences avec le support de bilan normal hébergé sur Clever cloud et checker si d'autres agences FT présentent cette meme anomalie.

**Comment by JeromeBu** [comment]
suite à la dernière MEP, il y a la main pour le faire dans l'admin
