### ISSUE TITLE
Passage à l'API V2 de LBB

### ISSUE THREAD

**Issue by nathalie-reyre** [gip-inclusion/immersion-facile#2266]
### :thinking: Contexte et problématique (et par qui est-ce remonté ?)

mise en place de l’API V2 de La Bonne Boite à partir du 10 Avril 2024.
Cette nouvelle version a pour but de vous garantir la fraîcheur des données mises à jour mensuellement, ainsi que la fiabilité de vos informations.
Les données actuelles sur l’API V1 étant obsolètes, celle-ci sera désactivée le 12 novembre 2024.
Nous vous encourageons à migrer vers la V2 dès que possible afin de bénéficier de ses mises à jour régulière
### :tada: Proposition de solution

 migration  -  cf compte IF sur francetravail.io

**Comment by enguerranws** [comment]
Lié à #2254 : le passage à l'api v2 pourra peut être nous permettre de renvoyer des résultats plus cohérents aux utilisateurs (notamment les entreprises dont certaines succursales sont fermées mais apparaissent toujours côté LBB)

**Comment by enguerranws** [comment]
Notes sur le passage à la v2 :
- je ne trouve plus l'info de distance du résultat par rapport à la position recherchée
- il n'y a plus d'adresse non plus
- plus de rome label non plus
- d'autres champs ont été supprimés, moins importants

**Comment by enguerranws** [comment]
Après discussion, il semble que l'arrivée de la minimap va résoudre pas mal de souci.

Donc : 
- pas besoin d'affichage de distance sur les résultats
- si besoin, sur la page de single d'une offre, on ira chercher l'info de l'adresse (annuaire des entreprises ou opencage via les lat/lon).

**Comment by enguerranws** [comment]
Réglé : on est passé temporairement sur les accès / creds francetravail.io au lieu de qvr
