### ISSUE TITLE
Rendre tous les ID des tableaux Metabase cliquables

### ISSUE THREAD

**Issue by mdamourette** [gip-inclusion/immersion-facile#2284]
Pré-requis : #2363 

### :thinking: Contexte et problématique (et par qui est-ce remonté ?)

Le fait de rendre l'ID cliquable a grandement été apprécié des precripteurs et facilite la navigation.

### :tada: Proposition de solution

Que ce soit côté prescripteur ou admin IF, il faudrait rendre tous les ID cliquables.

**Pages concernées :** 
- [ ] Agences (admin) : Ouvrir la page le validation de l'agence au clic sur l'ID (on attent la page d'edition d'agence pour admin agence)
- [ ] Convention synchronisées (Prescripteurs) : Demande la création d'une page de pilotage -> Oui seulement si les actions spécifiques sont dispos sur la page des pilotage

**Comment by clement-duport** [comment]
Fait sur Metabase (Pas de PR liée)
