### ISSUE TITLE
Toujours utiliser les termes valider et pré-valider

### ISSUE THREAD

**Issue by mdamourette** [gip-inclusion/immersion-facile#2286]
### :thinking: Contexte et problématique (et par qui est-ce remonté ?)

Les termes "A valider par le prescripteur", "A valider par le conseiller", … ne sont pas compris. Les nouveaux rôles sont donc "Validateur" et "Pré-validateur".

### :tada: Proposition de solution

Dans les filtres Metabase, remplacer "A valider par le prescripteur" par "À valider" et "A valider par le conseiller" par "À pré-valider".
![filtres](https://github.com/user-attachments/assets/fe84da15-7115-40b3-8322-9ad84083d969)

**Comment by mdamourette** [comment]
<img width="755" alt="statut-metabase" src="https://github.com/user-attachments/assets/fb75cb58-ab2c-4ff0-80bc-50ec75a9bb8b">

**Problématique :** Le statut "IN_REVIEW" apparait toujours qu'il y ait des pré-validateur ou non. C'est le statut "ACCEPTED_BY_COUNSELLOR" qui est obtionnel. 

**Possibilité évoquée** : "IN_REVIEW" devient "À étudier"

**Comment by Master-Touks** [comment]
Un changement a été fait et un bug vient de mettre remonté !
