### ISSUE TITLE
[Demande de convention] Retirer tous les placeholders et remplacer par des descriptions additionnelles

### ISSUE THREAD

**Issue by mdamourette** [gip-inclusion/immersion-facile#2293]
### :thinking: Contexte et problématique (et par qui est-ce remonté ?)

Les placeholders sont contrastés pour respecter l'accessibilité mais certains de nos utilisateurs pensent que les champs sont déjà saisi. 

### :tada: Proposition de solution

Pour éviter la confusion, il faut remplacer les placeholders par une description additionnelle. 

**2. Informations sur le candidat**

- [x] - E-mail du candidat : "Cette adresse email sera utilisée dans le cadre de la signature de la convention d'immersion. Pensez à bien vérifier son exactitude. Format attendu : nom@exemple.com"
- [x] - Téléphone du candidat : "Renseignez de préférence un téléphone portable pour pouvoir signer la convention par SMS. Format attendu : (+33) 6 22 33 44 55"
- [x] - Aide matérielle : "Le candidat a-t-il besoin d'une aide matérielle pour réaliser l'immersion ? Par exemple : aide à la mobilité. Les aides sont soumises à des conditions de ressources. Renseignez-vous auprès de votre conseiller."
- [x] - Le candidat est-il majeur protégé ? : "Les majeurs protégés sont les personnes qui sont dans l'impossibilité de pourvoir seules à leurs intérêts en raison de l'altération de leurs facultés mentales ou corporelles de nature à empêcher l'expression de leur volonté."
- [x] - Prénom et nom de la personne à prévenir en cas d'urgence : "Ex : Jean Dupont"
- [x] - Téléphone de la personne à prévenir en cas d'urgence : "Format attendu : (+33) 6 22 33 44 55"
- [x] - E-mail de la personne à prévenir en cas d'urgence : "Format attendu : nom@exemple.com"
- [x] - Addresse de l'entreprise actuelle du candidat : Placeholder à retirer + attention à la faute sur le mot "Adresse" 
- [x] - Téléphone de l'entreprise actuelle du candidat : "Renseignez de préférence un téléphone portable pour pouvoir signer la convention par SMS. Format attendu : (+33) 6 22 33 44 55"
- [x] - E-mail du signataire dans l'entreprise actuelle du candidat : "Cette adresse email sera utilisée dans le cadre de la signature de la convention. Pensez à bien vérifier son exactitude. Format attendu : nom@exemple.com"

**3. Informations sur l'entreprise**

- [x] - SIRET de la structure d'accueil : "La structure d'accueil, c'est l'entreprise, le commerce, l'association ... où le candidat va faire son immersion. Format attendu : 362 521 879 00034"

**4. Lieu et heures de l'immersion professionnelle**

- [x] - Adresse du lieu où se fera l’immersion : "Ex : 35, Rue Édouard Danaux, 91220 Brétigny-sur-Orge"

**5. Détails de l'immersion professionnelle**
- [x] - Précisez les mesures de prévention sanitaire : "Ex : fourniture de gel, masques..."
- [x] - Intitulé du poste/métier observé pendant l’immersion : "Ex : employé libre service, développeur, boulanger..."
- [x] - Conditions de travail, propres au métier observé pendant l’immersion : "Ex : transport de marchandises longue distance pas de retour au domicile pendant 2 jours"
- [x] - Avantages proposés par l'entreprise : "Ex : navettes jusqu’au lieu de travail, paniers repas, hébergement..."
- [x] - Activités observées / pratiquées pendant l'immersion : "Précisez les éléments clefs de la période, son contexte, les tâches confiées, les objectifs assignés au candidat."
- [x] - Compétences/aptitudes observées / évaluées pendant l'immersion : "Ex : communiquer à l’oral, résoudre des problèmes, travailler en équipe..."

**Comment by gargagif** [comment]
Testé en staging : il manque juste une majuscule ici :
![image](https://github.com/user-attachments/assets/c7d20d24-ade9-470b-892a-68404e49f3f8)

Le reste est OK.
