### ISSUE TITLE
Préparer l'app pour le système de droits d'établissements

### ISSUE THREAD

**Issue by enguerranws** [gip-inclusion/immersion-facile#2299]
- [x] App mis à jour pour la nouvelle gestion des droits utilisateurs
- [x] Migration en base des contacts des établissements pour créer ou maj les utilisateurs (contact principal + contact en copie) et avoir les nouveaux droits d'entreprise
- [ ] Modification des tableaux de bord utilisateurs sur Metabase >> uniquement pendant/après la MEP

### Piste de reflexion

- table users__establishments (convertie depuis establishments__contacts ?)
- siret / userId / roles
- roles :
    - establishment-admin / establishment-contact
        - establishment-admin :
            - a accès aux conventions (en lecture)
            - a accès aux candidatures et peut y répondre
            - peut modifier la fiche entreprise
            - *pourra gérer les utilisateurs liés à son entreprise*
            - peut être signataire
        - establishment-contact :
            - a accès aux conventions (en lecture)
            - a accès aux candidatures et peut y répondre
            - peut être signataire
        - *signataire / tuteur* : seulement un utilisateur dont le mail match avec le représentant d’entreprise d’une convention

**Comment by enguerranws** [comment]
Plus gérer la migration : contact de l'entreprise => establishment-admin et copy emails => establishment-viewer

**Comment by nathalie-reyre** [comment]
permettra d'avoir plusieurs contacts/établissement

**Comment by celineung** [comment]
renommer "establishment-viewer" en "establishment-contact"

**Comment by nathalie-reyre** [comment]
recette OK 
establishment-admin :
a accès aux conventions (en lecture)
a accès aux candidatures et peut y répondre
peut modifier la fiche entreprise
pourra gérer les utilisateurs liés à son entreprise
peut être signataire
