### ISSUE TITLE
[Demande de convention] Il manque la précision dans le cas où il y a une protection individuelle

### ISSUE THREAD

**Issue by mdamourette** [gip-inclusion/immersion-facile#2307]
### :thinking: Contexte et problématique (et par qui est-ce remonté ?)

Dans le formulaire de convention à l'étape "Détails de l'immersion professionnelle", il y a la question "Un équipement de protection individuelle est-il fourni pour l’immersion ?", lorsque l'utilisateur sélectionne "Oui", rien ne se passe.

### :tada: Proposition de solution

Il faudrait rajouter un champ pour préciser de quoi il s'agit, comme c'est le cas dans le formulaire de Cerfa. N'afficher le champ de précision que si l'utilisateur clique sur "Oui" (à corriger aussi pour la question de la prévention sanitaire).

- "Précisez le ou les équipement(s) :"
- "Ex : gants, gilets, combinaisons, chaussures, casques, harnais de sécurité, protections auditives, ..."

<img width="679" alt="Capture d’écran 2024-10-09 à 10 31 25" src="https://github.com/user-attachments/assets/5f337312-24d1-41ad-b6d4-51a0bd3d8dee">

**Exemple dans le Cerfa :** 
<img width="483" alt="Capture d’écran 2024-10-09 à 10 32 11" src="https://github.com/user-attachments/assets/30741bf6-5b6a-4a66-b961-c327b7eba7d7">

**Comment by gargagif** [comment]
Il manque les infos de protection individuelle sur la vue de validation :
![image](https://github.com/user-attachments/assets/abfda25f-8963-48c7-beda-f3b0e8d390df)
Les autres vues sont OK

@clement-duport
