### ISSUE TITLE
[Demande de convention] Supprimer les étapes de fin de formulaire car elles sont en double

### ISSUE THREAD

**Issue by mdamourette** [gip-inclusion/immersion-facile#2308]
### :thinking: Contexte et problématique (et par qui est-ce remonté ?)

Les étapes à faire après l'envoi de la demande de convention sont présentes deux fois. Une fois à la fin de l'étape 5 et une fois avec la relecture de la demande.

### :tada: Proposition de solution

Retirer les étapes présentes à la fin de l'étape 5 : 
<img width="804" alt="Capture d’écran 2024-10-09 à 10 36 43" src="https://github.com/user-attachments/assets/06d73d90-005d-4a5a-a2f0-fb22a7eb3339">

Ne conserver que celles présentes après l'envoi de la demande : 
![Formulaire de convention success](https://github.com/user-attachments/assets/00a9eb85-cd29-48d7-a717-67df99e998cf)

En profiter pour ajouter les nouvelles illustrations et le fond de couleur 😊 
Le fond de couleur est nécessaire pour montrer qu'il y a des informations présentes sous la ligne de flottaison.

**Comment by JeromeBu** [comment]
La parte nouvelle illustration a été oubliée, elle passe dans un nouveau tickets :

- [ ]  intégrer les nouvelles illustrations sur la page de confirmation d'envoie de convention
