### ISSUE TITLE
[Demande de convention] Modifier les descriptions liées à chaque étape

### ISSUE THREAD

**Issue by mdamourette** [gip-inclusion/immersion-facile#2309]
### :thinking: Contexte et problématique (et par qui est-ce remonté ?)

Les descriptions liées à chacune des étapes du formulaire sont parfois vide ou parfois répète des informations déjà présentent dans des alertes.

### :tada: Proposition de solution

**Étape 1** 
Cette étape vise à identifier la structure qui accompagne le candidat dans son parcours d’immersion. Cela permet de garantir un suivi et que le candidat soit assuré pendant toute la durée de l’immersion.
Pour toute question, n’hésitez pas à contacter le conseiller du candidat.

**Étape 2**
Cette étape recueille les informations personnelles du candidat pour assurer le bon déroulement de l’immersion. Ces informations seront utilisées uniquement pour le suivi et la validation de la convention.
Assurez-vous que les informations saisies sont exactes, car elles seront utilisées pour les communications concernant la convention et pour la validation auprès de la structure d’accueil.

**Étape 3**
L’objectif de cette étape est de fournir les informations nécessaires sur la structure d’accueil (entreprise, collectivité, association, etc.) qui recevra le candidat en immersion. Ces informations permettent de faciliter la signature de la convention par la structure d’accueil.
Vérifiez les informations sur le tuteur, car il sera le point de contact principal pour l’organisation et la validation de l’immersion.

**Étape 4**
Définir précisément le lieu et les horaires de l’immersion permet de garantir la couverture du candidat pendant cette période.
Assurez-vous que ces informations sont exactes et reflètent les horaires réels de l’immersion, car elles sont essentielles pour la couverture du candidat et le suivi des allocations si applicable.
Pour toute question, contactez la structure d’accueil.

**Étape 5**
Cette étape vise à préciser les tâches et activités prévues lors de l’immersion, afin de s’assurer que le candidat tirera le meilleur parti de cette expérience.
 Consultez les conditions réglementaires applicables aux immersions pour vous informer sur les exigences légales.
 
**Lien du Figma :** https://www.figma.com/proto/Z7nwSYCDH32RlQOMfMns2w/Site---UX-design-3e-trimestre-2024?node-id=551-7147&node-type=frame&t=0odnIlCjUPjzRyui-1&scaling=min-zoom&content-scaling=fixed&page-id=550%3A1679&starting-point-node-id=551%3A7147

**Comment by gargagif** [comment]
Testé en staging : OK pour moi
