### ISSUE TITLE
Résultats de recherche format carte

### ISSUE THREAD

**Issue by 3lodi3** [gip-inclusion/immersion-facile#2314]
### :thinking: Contexte et problématique

Visualiser les résultats sur une carte pour éviter aux utilisateurs d'aller chercher l'adresse dans Google Maps.

### :tada: Proposition de solution

Visualisation format carte et/ou liste de cards.

### :camera: Maquettes

Todo

**Comment by enguerranws** [comment]
Déjà, mettre en place une minimap pour visualiser les résultats de recherche sur une carte (comme ils ont fait au [marché de l'inclusion](https://lemarche.inclusion.beta.gouv.fr/prestataires/)).

**Comment by enguerranws** [comment]
Pour tester : https://if-dev-front-pr2325.osc-fr1.scalingo.io/

**Comment by JeromeBu** [comment]
Il faut réviser le responsive (très moche sur mobile)

**Comment by mdamourette** [comment]
Chez moi (Chrome), les icônes sont cassées : 
<img width="408" alt="Capture d’écran 2024-10-16 à 09 41 22" src="https://github.com/user-attachments/assets/b9c137bf-3d52-4f6c-a906-cd0df9f668fd">

**Comment by 3lodi3** [comment]
![Image](https://github.com/user-attachments/assets/46a4215d-8347-4a4d-9e8c-4ed87f02eb51)

**Comment by 3lodi3** [comment]
> Chez moi (Chrome), les icônes sont cassées : <img alt="Capture d’écran 2024-10-16 à 09 41 22" width="408" src="https://private-user-images.githubusercontent.com/37290359/376942380-b9c137bf-3d52-4f6c-a906-cd0df9f668fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwNjQ4MTAsIm5iZiI6MTcyOTA2NDUxMCwicGF0aCI6Ii8zNzI5MDM1OS8zNzY5NDIzODAtYjljMTM3YmYtM2Q1Mi00ZjZjLWE5MDYtY2QwZGY5ZjY2OGZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE2VDA3NDE1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmNDVmOTRlMmE1OWFiMTgwNTkxMWUwZjUzMDQ1ODM2NDRlYzU4ZDIwYTZiMTgxYzk2OTYxOWM5NmZiN2IxM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tzDLVX_W_HxaW-qHwOrsT-uEbnS5yntYjl7sM7qx_ME">

Bizarre chez moi ça passe nickel : 

- MacOS Sonoma 14.6.1 (23G93)
- Chrome Version 130.0.6723.59 (Build officiel) (x86_64)
- Safari Version 18.0 (19619.1.26.111.10, 19619)
- Même Edge ^^ Version 129.0.2792.89 (Version officielle) (x86_64)

**Comment by mdamourette** [comment]
> > Chez moi (Chrome), les icônes sont cassées : <img alt="Capture d’écran 2024-10-16 à 09 41 22" width="408" src="https://private-user-images.githubusercontent.com/37290359/376942380-b9c137bf-3d52-4f6c-a906-cd0df9f668fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwNjQ4MTAsIm5iZiI6MTcyOTA2NDUxMCwicGF0aCI6Ii8zNzI5MDM1OS8zNzY5NDIzODAtYjljMTM3YmYtM2Q1Mi00ZjZjLWE5MDYtY2QwZGY5ZjY2OGZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE2VDA3NDE1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmNDVmOTRlMmE1OWFiMTgwNTkxMWUwZjUzMDQ1ODM2NDRlYzU4ZDIwYTZiMTgxYzk2OTYxOWM5NmZiN2IxM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tzDLVX_W_HxaW-qHwOrsT-uEbnS5yntYjl7sM7qx_ME">
> 
> Bizarre chez moi ça passe nickel - MacOS Sonoma 14.6.1 (23G93) :
> 
> * Firefox 131.0.3 (64 bits)
> * Chrome Version 130.0.6723.59 (Build officiel) (x86_64)
> * Safari Version 18.0 (19619.1.26.111.10, 19619)
> * Même Edge ^^ Version 129.0.2792.89 (Version officielle) (x86_64)

Test

**Comment by enguerranws** [comment]
Traité, j'attends la review dev et on livre au plus vite

**Comment by gargagif** [comment]
Testé en staging > OK pour moi, modulo le bug remonté sur #2397 qui se produit également lorsqu'on ouvre dans un nouvel onglet le résultat de la recherche via la map (non-bloquant)
