### ISSUE TITLE
Ajout du filtre sur les entreprise accueillant les personnes en situation de handicap - côté back

### ISSUE THREAD

**Issue by 3lodi3** [gip-inclusion/immersion-facile#2326]
### :construction: Epic

#2327

### :thinking: Contexte et problématique

Les candidats ne peuvent pas filtrer les résultats de recherche et risquent d'abandonner et de ne pas contacter d'entreprise.

### :tada: Proposition de solution

Filtrer les résultats de recherche entreprise par "accueille les personnes en situation de handicap" en back/api

**Comment by gargagif** [comment]
Non-testé, sera recetté en même temps que le front
