### ISSUE TITLE
Ajout du filtre entreprises acueillant les personnes en situation de handicap - côté front

### ISSUE THREAD

**Issue by 3lodi3** [gip-inclusion/immersion-facile#2328]
### :construction: Epic

#2327

### :thinking: Contexte et problématique

Les candidats ne peuvent pas filtrer les résultats de recherche et risquent d'abandonner et de ne pas contacter d'entreprise.

### :tada: Proposition de solution

Filtrer les résultats de recherche entreprise par "accueille les personnes en situation de handicap" en front

### :camera: Maquettes

[Proto](https://www.figma.com/proto/Z7nwSYCDH32RlQOMfMns2w/Site---UX-design-3e-trimestre-2024?page-id=0%3A1&node-id=8-7905&node-type=frame&viewport=6650%2C1377%2C0.5&t=P3fdCWVIO775BZhH-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=8%3A7630)
[Fichier txt copiable](https://www.figma.com/design/Z7nwSYCDH32RlQOMfMns2w/Site---UX-design-3e-trimestre-2024?node-id=8-8047&t=gbjMBrgolbOCdkam-1)

### Score PIC
Portée :
Impact : 
Confiance :

**Comment by gargagif** [comment]
Recette OK en staging
