### ISSUE TITLE
Refonte graphique filtres de recherche

### ISSUE THREAD

**Issue by 3lodi3** [gip-inclusion/immersion-facile#2343]

**Comment by enguerranws** [comment]
Maquette : https://www.figma.com/proto/Z7nwSYCDH32RlQOMfMns2w/Site---UX-design-3e-trimestre-2024?page-id=0%3A1&node-id=8-7905&viewport=11344%2C2191%2C0.89&t=wQCBl3mXHOeNzsHp-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=8%3A7630

**Comment by mdamourette** [comment]
J'ai l'impression que cette phrase 

> "Les résultats sont étendus aux autres métiers de la Réalisation de contenus multimédias, c’est pour cela que vous pourrez voir des métiers proches mais ne correspondant pas précisément à votre recherche dans les résultats." 

n'est pas dynamique alors que le secteur est censé s'adapter à la recherche et être cliquable.

**Comment by mdamourette** [comment]
Je me demande si cette phrase reste utile dans ce cas car l'information est en double (la partie en gras).

> 24 résultats trouvés
> **pour la recherche Boulanger / Boulangère, étendue au secteur [Boulangerie - viennoiserie]**

**Comment by gargagif** [comment]
Je confirme le commentaire de @mdamourette :
![Image](https://github.com/user-attachments/assets/0a2888fa-d1ba-495c-8a92-b66d0d0fd2fa)

@enguerranws possible de dynamiser ça ?

**Comment by gargagif** [comment]
Recette OK en staging
