### ISSUE TITLE
Bloquer les champs emails valideurs + emails conseillers

### ISSUE THREAD

**Issue by celineung** [gip-inclusion/immersion-facile#2362]
# Description

Sur le formulaire d'édition d'agence de la vue admin:
- [x] #2368
- [x] dans la modale, avoir toujours la check "pré-valideur" de visible --> fait dans #2333
- [x] #2423
- [ ] que se passe-t-il pour une structure d'accompagnement si une structure prescriptrice ferme ?

**Comment by gargagif** [comment]
Parcours de fermeture à clarifier
