### ISSUE TITLE
Regrouper les pages "Pilotage d'une convention" et "Vérification d'une demande de convention" en une seule

### ISSUE THREAD

**Issue by mdamourette** [gip-inclusion/immersion-facile#2363]
### :thinking: Contexte et problématique (et par qui est-ce remonté ?)

Ces deux pages sont approximativement les deux mêmes et affichent les mêmes données en mode lecture seule. Il faudrait harmoniser la manière d'affichage des deux pages.

Cela permettrait au passage de régler des incompréhensions de la part de nos utilisateurs : icônes sur les informations oui/non, tableaux DSFR non fermés, affichage des horaires, …

### :tada: Proposition de solution

- [Lien des maquettes](https://www.figma.com/design/zrcTVzt3An7MlXzavxh487/Convention?node-id=35-1820&node-type=frame&t=lm9cnIqLKormSFcw-0)
- [Prototype de la page de pilotage](https://www.figma.com/proto/zrcTVzt3An7MlXzavxh487/Convention?node-id=35-1820&node-type=frame&t=lm9cnIqLKormSFcw-0&scaling=min-zoom&content-scaling=fixed&page-id=0%3A1&starting-point-node-id=35%3A2802)
- [Prototype de la page de vérification](https://www.figma.com/proto/zrcTVzt3An7MlXzavxh487/Convention?node-id=5-1529&node-type=frame&t=lm9cnIqLKormSFcw-0&scaling=min-zoom&content-scaling=fixed&page-id=0%3A1&starting-point-node-id=35%3A2802)

Exemple d'une page : 
https://github.com/user-attachments/assets/cd9a43ea-9d8a-4878-96de-972d11f5585e

**À faire dans ce ticket :**
- [ ] Faire la version mobile
- [ ] Aucune alerte ne doit apparaitre dans la barre d'action. Il y aura soit des toasters pour les messages qui ne nécessite aucune action (succès de suppression, de modification, …) ou une modale quand une action est nécessaire (rediffusion SI, …)
- [ ] Deux SplitButton sont à créer : "Annuler la demande" et Gérer la synchronisation"
- [ ] Le bouton "Rediffuser dans votre Si" n'apparait que dans les conventions en erreur
- [ ] Ajouter un statut "Erreur de synchronisation" et ajouter les boutons liées à cette erreur

### 🏅 Critères de succès 
- [Taux de conversion entre l'étape "Vérifier la demande" et "Demande envoyée"](https://matomo.inclusion.beta.gouv.fr/index.php?module=CoreHome&action=index&idSite=207&period=day&date=yesterday#?idSite=207&period=day&date=yesterday&category=Funnels_Funnels&subcategory=96) (ne doit pas baisser)
- [Taux de conversion du formulaire](https://matomo.inclusion.beta.gouv.fr/index.php?module=CoreHome&action=index&idSite=207&period=day&date=yesterday#?idSite=207&period=day&date=yesterday&category=FormAnalytics_Forms&subcategory=160)
- Taux de convention en erreur (si la relecture n'est pas bien faite)

**Comment by gargagif** [comment]
@JeromeBu a des suggestion concernant la barre d'actions, à clarifier avec @mdamourette

**Comment by 3lodi3** [comment]
Je viens de voir un truc qui m'avait échappé en regardant les maquettes, désolée j'ai pas été assez attentive. Il faudrait éviter le bleu sur les titres s'ils ne sont pas cliquables @mdamourette

**Comment by mdamourette** [comment]
### Retours non bloquants
- **Dans le bloc "Information complémentaire"**, ne mettre les ":" après le "Oui" que lorsque le champ de détail a été rempli![Image](https://github.com/user-attachments/assets/560ece2c-a087-4991-8c25-b8fe8a212156)

**Comment by celineung** [comment]
Pris en compte de quasiment tous les retours ci-dessus dans cette PR: https://github.com/gip-inclusion/immersion-facile/pull/2585

Pour la remarque:
> Les adresses mail ne sont pas alignées en hauteur avec les valeurs des champs d'à côté (constaté dans tous les blocs) 
Ceci est dû à l'icone qui permet de copier qui a une taille fixe définie par le DSFR.
Je verrai avec Enguerran dans un second temps ce que l'on peut faire.
Sinon, vu avec Gaël, ce n'est pas grave si pas possible de faire ce fix.
