### ISSUE TITLE
ETQ candidat, lorsque je modifie ma demande de convention les champs département et structure d'accompagnement disparaissent

### ISSUE THREAD

**Issue by gargagif** [gip-inclusion/immersion-facile#2366]
### :bug: Le problème

Depuis la page "Vérifier la demande de convention", au retour sur le formulaire de demande après avoir cliqué sur "Modifier la convention", les champs "Département" et "Structure d'accompagnement" ne sont plus pré-remplis 

### :footprints: Étapes pour reproduire

1. Candidat > Initier une convention > Accompagné par autre structure
2. Je remplis le formulaire
3. Je valide
4. Sur la page de vérification, je clique sur "Modifier la convention"
5. Au retour sur le formulaire, les champs mentionnés ne sont plus remplis

### :dart: Comportement attendu

Faire en sorte que "Département" et "Structure d'accompagnement" conservent les données renseignées.

### Screenshots

![image](https://github.com/user-attachments/assets/66c36ee0-4d8f-4dbe-85a2-a72f0605c9f6)

**Comment by nathalie-reyre** [comment]
@gargagif tu peux mettre dans prêt à dev et le mentionner dans le thread problème. C'est une régression. On a déjà eu ce type de problèmes mais ça a été résolu il y a déjà longtemps. Il y a une repasse à faire donc

**Comment by gargagif** [comment]
OK en staging
