### ISSUE TITLE
intégrer les nouvelles illustrations sur la page de confirmation d'envoie de convention

### ISSUE THREAD

**Issue by JeromeBu** [gip-inclusion/immersion-facile#2379]

**Comment by JeromeBu** [comment]
Ajouter les nouvelles illustrations et le fond de couleur 😊
Le fond de couleur est nécessaire pour montrer qu'il y a des informations présentes sous la ligne de flottaison.


![Image](https://github.com/user-attachments/assets/792352d1-5685-4c73-8e3f-ce6086195f9e)

**Comment by gargagif** [comment]
**Recette effectuée le 18/10**

- Visuels et fond de couleur OK en desktop.
- En version mobile, le fond de couleur disparaît. Est-ce gênant ?
- Sur ma résolution (1440 x 810), je ne vois pas la suite, donc malgré le fond de couleur je peux passer à côté des infos. Proposition de réduire l'espace en haut :

![image](https://github.com/user-attachments/assets/fe4ec3ce-5cd7-4406-a0dd-e72f773cd194)

@3lodi3 @mdamourette pour avis

**Comment by 3lodi3** [comment]
Hello,
- Pour moi pas gênant que le fond de couleur disparaisse sur mobile
- Pour l'espace au-dessus du h1 il ne me paraît pas trop grand et doit de préférence rester le même sur toutes les pages et respecter le [DSFR](https://www.systeme-de-design.gouv.fr/fondamentaux/espacement) (je pense que c'est ce que @enguerranws a fait) en revanche l'espace entre le paragraphe et l'id est trop important, celui-là on peut le réduire.

**Comment by gargagif** [comment]
Nouveau ticket créé pour réduire l'espace : https://github.com/gip-inclusion/immersion-facile/issues/2393
