### ISSUE TITLE
Lorsque je clique sur "Le tuteur est différent du représentant de la structure d'accueil" les champs du tuteur ne devrait pas être pré-rempli avec ceux du représentant de la structure d'accueil

### ISSUE THREAD

**Issue by mdamourette** [gip-inclusion/immersion-facile#2383]
### :bug: Le problème

Lors de la saisie d'une demande de convention, je clique sur "Le tuteur est différent du représentant de la structure d'accueil" mais les champs du tuteur qui s'affichent sont quand même pré-remplis avec les informations du représentant de la structure.

### :dart: Comportement attendu

Ne pas pré-remplir ces champs.

### Screenshots

https://github.com/user-attachments/assets/91bda3ed-4fd9-4124-9b04-f6a782ee3c1d

**Comment by gargagif** [comment]
KO en staging : les champs sont toujours pré-remplis

![Image](https://github.com/user-attachments/assets/7b6e0fcb-8913-4d03-9600-b164a41c475a)

![Image](https://github.com/user-attachments/assets/cd8703f9-8005-4f59-b8d0-dfbbbbe1eb9f)

**Comment by clement-duport** [comment]
@gargagif Le fix est passer en staging (je n'ai pas fait de ticket car plus long que le fix lui même)

**Comment by gargagif** [comment]
Recette OK
