### ISSUE TITLE
Résultat de la recherche "tentez votre chance" incohérent avec le métier recherché

### ISSUE THREAD

**Issue by cecile-dimarco** [gip-inclusion/immersion-facile#2386]
### :bug: Le problème

1. Je recherche le métier de vendeur prêt à porter dans la ville de Thiers + 20km
2. La liste des entreprises tenez votre chance s'affiche
3. Les entreprises proposées ne correspondent pas au métier ciblé (ex. Eurolam (coutellerie) Muzard (accessoire barbier) Mairie de Thiers et DAV informatique)
4. J'effectue la même recherche sur LBB, mais ces entreprises ne ressortent pas

Recherche sur IF : https://immersion-facile.beta.gouv.fr/recherche?distanceKm=20&latitude=45.8558&longitude=3.54897&appellations=%5B%7B%22romeCode%22%3A%22D1214%22%2C%22romeLabel%22%3A%22Vente%20en%20habillement%20et%20accessoires%20de%20la%20personne%22%2C%22appellationCode%22%3A%2220613%22%2C%22appellationLabel%22%3A%22Vendeur%20%2F%20Vendeuse%20en%20pr%C3%AAt-%C3%A0-porter%22%7D%5D&sortedBy=score&place=Thiers%252C%2520Puy-de-D%25C3%25B4me%252C%2520France

Recherche sur LBB https://labonneboite.francetravail.fr/recherche?rome=D1214&citycode=63430&bbox=&distance=20&sort_by=romes.hiring_potential&sort_direction=desc&page=7&page_size=6

**Comment by gargagif** [comment]
A retester avec la V2
