### ISSUE TITLE
401 sur l'affichage d'un document de convention

### ISSUE THREAD

**Issue by enguerranws** [gip-inclusion/immersion-facile#2389]
Si j'accède à une convention depuis l'admin, pas de souci.
Lorsque je rafraichis la page, je tombe sur une 401.

Je pense qu'on doit avoir le même comportement pour tous les utilisateurs connectés.

**Comment by celineung** [comment]
plus de problème, ça a été sûrement corrigé avec le refacto des routes de conventions
