### ISSUE TITLE
Inbound parsing Brevo ne fonctionne pas correctement

### ISSUE THREAD

**Issue by gargagif** [gip-inclusion/immersion-facile#2394]
Certains utilisateurs n'arrivent pas à répondre aux discussions.
Ex d'ID de discussion :
- 4182ba08-a4fd-4dab-94b4-def8ad537dfa
- 47734144-17fa-44f8-b12f-4b53e571ccbc

@enguerranws merci de voir avec le support Brevo et de nous tenir au courant ici.

**Comment by enguerranws** [comment]
On a continué les investigations : 
- côté brevo, ils choppent (visiblement) juste une 400, sans body ni rien
- en regardant dans le code et surtout en interrogeant la staging avec différents types de payload : 
  - si le payload dépasse 800ko : 413 -> c'est pas ça
  - si le payload a un json invalide (virgule qui traine, manque des guillemets double) : 400 - Bad Request (pas de body / issues Zod) -> bon client (côté code, il semble que c'est bodyParser qui nous envoie cette erreur)
  - si le payload est ok (même avec des clés qu'on connait pas) : 200

On va préciser la gestion d'erreur pour s'assurer que c'est bien une erreur de syntaxe qui se produit au niveau de bodyParser.

Pour info, pour tout voir côté Datadog : https://app.datadoghq.eu/logs?query=service%3Aif-prod-back%20-host%3Aif-prod-back-crawler-1%20%40req.url%3A%2Finbound-email-parsing%20%40res.statusCode%3A400%20&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&event=AgAAAZKzw6YBVy8_ngAAAAAAAAAYAAAAAEFaS3p3NmFFQUFBR3hxdG9FRXdiU3dBQQAAACQAAAAAMDE5MmIzY2MtYjE4YS00NzJlLTg1OTItZjNiNTI5M2VmMjU2&fromUser=true&messageDisplay=inline&refresh_mode=sliding&saved-view-id=127962&storage=hot&stream_sort=desc&viz=stream&from_ts=1728297822660&to_ts=1729593822660&live=true
