### ISSUE TITLE
ETQ candidat, je peux revenir à la page de recherche

### ISSUE THREAD

**Issue by enguerranws** [gip-inclusion/immersion-facile#2399]
### :bug: Le problème

Remontée du support : si je consulte une offre d'immersion issue de la 3ème page de résultats de recherche et que je clique sur Retour, je reviens sur la première page de résultat de recherche

### :dart: Comportement attendu

Je devrais arriver sur la 3ème page de résultat de recherche (la page sur laquelle j'étais).

**Comment by gargagif** [comment]
Recette OK en staging
