### ISSUE TITLE
ETQ qu'entreprise, je ne devrais pas voir le bouton "Retour au pilotage des établissements"

### ISSUE THREAD

**Issue by enguerranws** [gip-inclusion/immersion-facile#2400]
### :bug: Le problème

Remontée du support : sur la fiche entreprise (tableau de bord entreprise), il y a un bouton "Retour au pilotage des établissements" qui envoie sur une vue admin (donc ça produit une erreur pour les utilisateurs non-admin).

**Comment by gargagif** [comment]
OK en recette
