### ISSUE TITLE
ETQ utilisateur, je veux pouvoir saisir une demande d'immersion sans problème malgré le changement d'heure

### ISSUE THREAD

**Issue by nathalie-reyre** [gip-inclusion/immersion-facile#2405]
![Image](https://github.com/user-attachments/assets/f411e0ad-2274-4841-9eae-9fafefc6ec34)
Il y a un problème pour saisir des jours et horaires à cheval sur le WE du changement d'heure. La veille du jour de démarrage est bloqué. On ne peut pas sélectionner ce jour et donc y attribuer des horaires. ![Image](https://github.com/user-attachments/assets/47a6cbd3-a8de-4360-85cd-e87716726e33)
Pour une durée > 1 semaine, il n'y pas de problème de sélection de jours

**Comment by gargagif** [comment]
Recette OK :
![image](https://github.com/user-attachments/assets/5f15939f-d97e-438d-ac01-b18c09ff4fa8)
