### ISSUE TITLE
Visibilité entreprise sur onglet admin

### ISSUE THREAD

**Issue by gargagif** [gip-inclusion/immersion-facile#2419]
### :bug: Le problème

La colonne "Visible" du tableau Metabase présent sur le backoffice entreprise correspond au quota (non-atteint = oui / atteint = non). Cela apporte de la confusion dans le cas d'une entreprise non-visible.

### :footprints: Étapes pour reproduire

En PROD, l'entreprise Magali Damourette est enregistrée comme "non-visible" :

![image](https://github.com/user-attachments/assets/a4924e3b-7c48-45f1-82ca-9f9a26bb9ecc)

Pourtant, lorsqu'on effectue une recherche sur le backoffice entreprise, la valeur de la colonne "Visible" est "Oui" :

![image](https://github.com/user-attachments/assets/b20b79d7-56e4-4209-a0da-dfaf35e77c43)

### :dart: Comportement attendu

~~Le champ "Visible" devrait être renommé en "Quota disponible" / "is_searchable" en BDD devient "available_quota"~~
Suite à discussions, le champ `is_searchable` est finalement nommé `is_monthly_discussion_limit_reached` et ses valeur seront retournées (oui devient non et inversement). On garde le nommage `Limite atteinte ?` à faire dans Metabase.

Pour la discussion complète  : https://discord.com/channels/864451835553513474/1310533897985196103

**Comment by nathalie-reyre** [comment]
recette impossible car metabase n'est pas branchée en staging
