### ISSUE TITLE
ETQ entreprise, je souhaite pouvoir retrouver la liste des candidats après avoir répondu à l'un d'eux (alors que j'ai accédé à mon espace directement depuis la notification par mail)

### ISSUE THREAD

**Issue by nathalie-reyre** [gip-inclusion/immersion-facile#2422]
### :bug: Le problème

j'ai répondu négativement à un candidat en allant sur mon espace entreprise à partir du mail de notification.  Une fois la réponse négative faite, j'ai souhaité voir la liste des autres candidatures à traiter. Mais le bouton retour n'est pas actif

### :dart: Comportement attendu

une fois la réponse faite, pouvoir retourner sur la liste des candidats (https://immersion-facile.beta.gouv.fr/tableau-de-bord-etablissement/discussions) quelque soit la manière dont on a accédé à une des discussions, que ce soit en se connectant directement à son espace ou que ce soit par l'intermédiaire d'une notification.
Le bouton Retour est renommé en "Retour aux candidatures"

### Screenshots

![Capture d’écran 2024-10-25 à 16 53 01](https://github.com/user-attachments/assets/f96273ae-c38e-4b91-9695-834c32e7940e)

**Comment by gargagif** [comment]
Recette OK en staging
