### ISSUE TITLE
empêcher un utilisateur d'être à la fois valideur et conseiller sur une même agence (?? à confirmer avec le métier)

### ISSUE THREAD

**Issue by JeromeBu** [gip-inclusion/immersion-facile#2423]
Les utilisateurs qui sont déjà les deux sur certaines agences ne seront plus que "validateur".

**Comment by cecile-dimarco** [comment]
Est-ce qu'un validateur pourra valider une convention si elle n'a pas été pré-validée avant? 
Ex rencontré : Dans le cas des référencements conseiller par conseiller (utilisé par les départements et certains CEP), une convention est à valider en urgence, mais le pré-validateur est absent et je n'ai pas pensé à mettre d'autres pré-validateurs.

**Comment by JeromeBu** [comment]
Non elle ne pourrait pas validé si ça n'est pas pré-validé. En fait ce que tu décris est le comportement qu'on avait avant, on a migré pour le comportement actuel. Pour l'instant la prévalidation est obligatoire.
