### ISSUE TITLE
Retirer le mail du conseiller qui doit recevoir le bilan dans les mails :  convention final validée / notification de bilan au bénéficiaire / notification de création du  bilan à l'agence

### ISSUE THREAD

**Issue by clement-duport** [gip-inclusion/immersion-facile#2426]
Retirer le mail du conseiller qui doit recevoir le bilan dans les mails : 
- convention final validée 
- notification de bilan au bénéficiaire 
- notification de création du bilan à l'agence

On fait ça ( en attendant le nouveau parcours de bilan) car pour l'instant car on n'est pas en mesure de savoir quel mail doit recevoir le bilan

**Comment by gargagif** [comment]
Recette OK
