### ISSUE TITLE
Mettre à jour la view_establishments pour afficher is_open (+ filtre metabase)

### ISSUE THREAD

**Issue by gargagif** [gip-inclusion/immersion-facile#2427]
@enguerranws merci de détailler / expliquer la provenance de la demande

**Comment by enguerranws** [comment]
Il me semble que c'est une demande de @Jessicaceleste1 , pour identifier les entreprises actives chez IF. Cette vue est utilisée pour faire des exports, de mémoire, et il n'est pas possible d'identifier les entreprises actives pour des actions bizdev.

**Comment by Jessicaceleste1** [comment]
ce n'est pas de moi ou je ne sais pas de quoi il s'agit car cette formulation view etab / open c'est plutôt un dev je pense :), je ne peux pas aider

**Comment by bbohec** [comment]
![Image](https://github.com/user-attachments/assets/c24ab64d-dc1d-48f2-bd3c-6cb12b757d98)

**Comment by gargagif** [comment]
Recette OK sur la base de staging
