### ISSUE TITLE
ETQ admin agence, je peux voir le tableau des agences sur lequelles je suis administrateur d'agence et modifier leurs infos

### ISSUE THREAD

**Issue by 3lodi3** [gip-inclusion/immersion-facile#2441]
### :tada: Proposition de solution

**On reprend les écrans de l'admin et on cache les champs avec un point d'exclamation ! Et l'admin agence ne doit pas pouvoir éditer ces champs ni en front ni via l'API.**

**Comment by gargagif** [comment]
@cecile-dimarco et @Sylvieleb merci de prévoir la doc correspondante dans le helpdesk

**Comment by gargagif** [comment]
Recette OK en staging
