### ISSUE TITLE
ETQ utilisateur de tableau de bord, je n'ai plus besoin de copier coller des ID de convention, car les lien metabase sont maintenant cliquable

### ISSUE THREAD

**Issue by JeromeBu** [gip-inclusion/immersion-facile#2442]
### :thinking: Contexte et problématique

Le champs de saisie du convention ID pour naviguer vers une page de convention n'est plus utile, car les liens sont maintenant cliquable directement.

### :tada: Proposition de solution

Supprimer le bloc de formulaire pour saisir les id de convention

### :camera: Maquettes

Le bloc "Piloter la convention" est à supprimer 

<img width="1322" alt="image" src="https://github.com/user-attachments/assets/22f372c0-6f51-478d-9c8d-c6f67dff7423">

**Comment by gargagif** [comment]
Recette OK
