### ISSUE TITLE
ETQ superAdmin, je peux voir le détail d'un utilisateur sur une page dédiée

### ISSUE THREAD

**Issue by JeromeBu** [gip-inclusion/immersion-facile#2448]
### :thinking: Contexte et problématique

Actuellement, on a pas de moyen de voir les infos d'un utilisateur, ni les agences qui lui sont liés sur une seule vue.

### :tada: Proposition de solution

Sur la recherche d'utilisateur /admin/users, dans les résultats, on a la possiblité de cliqué sur un bouton pour accéder à la page de détail.

Sur la page de détail de l'utilisateur, on a les infos de l'utilisateur et la liste des agences pour lesquels cet utilisateur a des droits. Sur ces lignes, on a également le lien vers la page d'agence correspondante.

**Comment by gargagif** [comment]
Recette OK
