### ISSUE TITLE
Documentation du processus de recette

### ISSUE THREAD

**Issue by bbohec** [gip-inclusion/immersion-facile#2452]
### :thinking: Contexte et problématique (et par qui est-ce remonté ?)

Remonté par @gargagif et discuté avec les dev pour bien clarifier le process de recette adapté.

### :tada: Proposition de solution

Comme discuté avec l'équipe dev, voici la proposition de process pour la recette :

Lorsqu'il y a une recette à faire sur une version envoyée en staging, créer un fil de discussion sur le canal mise en recette + tag Gaël
Si Gaël absent, tagguer Nathalie. Si Nathalie absente, tagguer Elodie ou Magali.
Les retours liés aux tests sont renseignés sur chaque ticket, en commentaire.
Si ticket KO, le ticket est réouvert et repassé au statut "Développement en cours"
Un résumé de la recette est envoyé sur le fil Discord de la recette avec :
OK / KO pour MEP
La liste des tickets concernés par les retours
Tag des devs concernés par les retours (les tags / notifs GitHub ne sont pas efficaces)
Si MEP OK > ce sont les devs qui lancent la MEP, car il arrive qu'il y ait des actions autres que d'appuyer sur le bouton (par ex : requête SQL à exécuter).

Cela s'accompagne de quelques remarques en lien avec le bon déroulé de la recette :

Renseigner systématiquement le numéro du ticket correspondant dans le titre de la PR et idéalement lier la PR au ticket
Lorsqu'un dev crée une PR sur une feature d'initiative personnelle il crée systématiquement un ticket lorsqu'il s'agit d'une feature à tester
Pour créer un ticket, c'est mieux de passer par le Template sauf si c'est hyper trivial. Cela permet de renseigner correctement le contexte et le comportement attendu.
Lorsqu'un ticket est retraité suite à un retour, il est important que le dev mette un commentaire en reclôturant le ticket, afin qu'on sache si le retour à été pris en compte et si non pourquoi.

- [ ] Process à intégrer ça dans la doc du repo
- [ ] Faire un lien vers cette doc dans Notion

**Comment by nathalie-reyre** [comment]
j'ai mis à jour Notion avec lien vers le ticket
