### ISSUE TITLE
ETQ que admin j'ai un mess d'erreur lors d'un ajout ou modif d'un utilisateur via agence

### ISSUE THREAD

**Issue by Jessicaceleste1** [gip-inclusion/immersion-facile#2455]
### :bug: Le problème

Depuis admin - agence

lors d'une modification de droit mais qui pourtant a fonctionné pour l'agence Agence France Travail Chateaubriant aude.roinson@francetravail.fr de lecteur à validateur
idem pour un ajout le message apparait : 325 859 270 00044 ajout de virginielaporte@missionlocale-avignon.asso.fr et ça a pourtant fonctionné
J'ai le message d'erreur suivant
![image](https://github.com/user-attachments/assets/56f5872c-965b-4d4d-af57-bb789e269131)

https://discord.com/channels/864451835553513474/1042365650359828480/1301503390404055121

**Comment by celineung** [comment]
bug déjà corrigé
