### ISSUE TITLE
Ajouter la possibilité de se déconnecter de PE connect

### ISSUE THREAD

**Issue by SlimanCA** [gip-inclusion/immersion-facile#246]

**Comment by SlimanCA** [comment]
@3lodi3 comment tu verrais les choses? ou placerais-tu le bouton pour se déco?

**Comment by 3lodi3** [comment]
La convention UX/DSFR voudrait que le bouton connexion / déconnexion soit placé dans l'En-tête avec accès rapides : https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/en-tete

**Comment by SlimanCA** [comment]
Comme je suis très visuel j'aimerais bien voir ce que ca donne mais sur le principe ca me va :)

**Comment by JeromeBu** [comment]
Suite au discussions ca devenait critique. On a mis un bouton se déconnecter en haut à droite. (pareil que pour se déconnecter de l'admin avec le texte: `Se déconnecter (PE connect)` . On peut changer l'UX bien sur. Mais comme ca au moins les agences qui étaient bloqués ne le seront plus
