### ISSUE TITLE
Modifier la signature des agences FT

### ISSUE THREAD

**Issue by gargagif** [gip-inclusion/immersion-facile#2463]
Le texte de signature des agences FT contient "Pôle Emploi".

Il faudrait remplacer en masse par "France Travail".

Contexte et détails ici : https://www.notion.so/gip-inclusion/1215f321b604801089dbea1c0e2cf5eb?v=1215f321b60481eabd81000cc44d2978&p=1225f321b604803799d2d43bd342501c&pm=s**

**Comment by clement-duport** [comment]
@gargagif Je viens de faire la modification directement en DB du coup je cloture le ticket

**Comment by gargagif** [comment]
Testé en PROD, c'est OK
