### ISSUE TITLE
ETQ 'utilsiteur connecté', je veux avoir des sessions qui dure toute une journée (12 heures)

### ISSUE THREAD

**Issue by JeromeBu** [gip-inclusion/immersion-facile#2469]
### :thinking: Contexte et problématique

La durée des sessions a beaucoup raccourci depuis le passage à pro connect. C'est pénible pour les utilisateurs (admin, agence et entreprise) de devoir se reconnecter plusieurs fois par jour.

### :tada: Proposition de solution

Passer la durée des sessions arbitrairement à 12 heures.

**Comment by gargagif** [comment]
Non-testé en recette, OK pour passage en PROD et attendre les retours utilisateurs
