### ISSUE TITLE
ETQ prescripteur l'onglet conventions synchronisées est accessible à tous

### ISSUE THREAD

**Issue by cecile-dimarco** [gip-inclusion/immersion-facile#2479]
### :bug: Le problème

Je suis prescripteur hors France Travail et Mission Locale, l'onglet convention synchronisée dans mon espace prescripteur n'est plus grisé. 

### :dart: Comportement attendu

Je n'ai pas accès à l'onglet convention synchronisée si je ne suis pas rattachée à une agence France Travail ou Mission Locale 

### Screenshots

![Image](https://github.com/user-attachments/assets/371000d1-4468-478c-8eff-e2d90c9c829a)

**Comment by clement-duport** [comment]
C'est pas une erreur c'est les données de la DB de staging qui ne sont pas cohérentes. En gros pour déterminer si on affiche ou non l'onglet on va regarder en DB si il y a une souscription d'un de nos consommateur api sur l'agence ou le type de l'agence à laquelle l'utilisateur est rattaché.
Et en staging il y a une souscription sur les structure siae ce qu'il n'y a pas en prod c'est pour ça que dans ton test l'onglet apparait.
