### ISSUE TITLE
LBBv2 Potentiel retour "undefined" non désiré au runtime

### ISSUE THREAD

**Issue by bbohec** [gip-inclusion/immersion-facile#2483]
### :bug: Le problème

```
constructorName: "TypeError"
message: "Cannot read properties of undefined (reading 'length')"
name: "TypeError"
request: {
  "path": "/immersion-offers",
  "method": "GET"
}
stack: "TypeError: Cannot read properties of undefined (reading 'length')\n    at SearchImmersion._execute (/app/back/src/domains/establishment/use-cases/SearchImmersion.js:59:36)\n    at async /app/node_modules/.pnpm/kysely@0.27.4/node_modules/kysely/dist/cjs/kysely.js:418:32\n    at async DefaultConnectionProvider.provideConnection (/app/node_modules/.pnpm/kysely@0.27.4/node_modules/kysely/dist/cjs/driver/default-connection-provider.js:12:20)\n    at async sendHttpResponse (/app/back/src/config/helpers/sendHttpResponse.js:7:31)"
```

J'ai fait un build local pour check la ligne 59

Dans le code TS on doit avoir un tableau obligatoirement or d'après cette erreur de runtime on a undefined.
On a peut être un manque de typeguard dans l'adapter LBB v2

**/app/back/src/domains/establishment/use-cases/SearchImmersion.js:59:36**
![Image](https://github.com/user-attachments/assets/c1a6ba7b-400f-4e1b-b86e-e7e9ac06a014)

### :dart: Comportement attendu

Pas de retour undefined possible afin de respecter le contrat métier du port **LaBonneBoiteGateway**

**Comment by gargagif** [comment]
Erreur non-constatée en staging. A voir à l'usage en PROD
