### ISSUE TITLE
Nom et prénom par défaut des utilisateurs sur les templates mail

### ISSUE THREAD

**Issue by gargagif** [gip-inclusion/immersion-facile#2484]
### :bug: Le problème

Lorsque les noms et prénoms des utilisateurs d'une agence ne sont pas renseignés, les mails qu'ils reçoivent contiennent "Non fourni Non fourni" en lieu et place de leur prénom nom :

Template "AGENCY_WAS_ACTIVATED" (reçu à la validation de l'agence) :
![Image](https://github.com/user-attachments/assets/3b02d19c-d3a8-4b10-8c09-ee904345dc2c)

Template "IC_USER_RIGHTS_HAS_CHANGED" (reçu au rajout de l'utilisateur)
![Image](https://github.com/user-attachments/assets/6c3db2d4-4f1a-4b30-9506-4b46790e2fcc)

### :footprints: Étapes pour reproduire

1. ETQ prescripteur je crée une nouvelle agence. Les valideurs et pré-valideurs sont ajoutés en saisissant leurs adresses mail.
2. ATQ admin je valide l'agence sans possibilité d'éditer les noms et prénoms des utilisateurs
3. Le mail envoyé aux utilisateurs de l'agence contient "Non fourni Non fourni" en lieu et place des prénoms et noms des utilisateurs (cf précédent screenshot)

### :dart: Comportement attendu

Si le prénom et/ou le nom est/sont manquant.s sur un template mail, ne rien afficher à sa/leur place.

### :exclamation: Précision

Les tests ont été effectués sur deux templates mail. Merci de vérifier et de généraliser ce comportement à l'ensemble des templates.

**Comment by clement-duport** [comment]
Bug lié a la PR de refacto 
régler par cette PR : #2488
