### ISSUE TITLE
ETQ Admin IF, la liste des utilisateurs d'agence prend trop de temps à s'afficher

### ISSUE THREAD

**Issue by bbohec** [gip-inclusion/immersion-facile#2491]
### :bug: Le problème

Environ 20s pour lister les utilisateur depuis la dernière MEP.

### :footprints: Étapes pour reproduire

Admin > Agences > choisir une agence > les utilisateurs apparaissent au bout de ~ 20s

### :dart: Comportement attendu

Affichage quasiment immédiat attendu. Problème identifié dans le code.

**Comment by gargagif** [comment]
Chargement OK en staging, mais sur des agences avec peu d'utilisateurs rattachés. Je n'ai pas trouvé d'agence avec beaucoup d'utilisateurs.
A tester en PROD.
