### ISSUE TITLE
ETQ prescripteur les filtres dans l'espace ne facilitent pas mes recherches

### ISSUE THREAD

**Issue by Jessicaceleste1** [gip-inclusion/immersion-facile#2494]
### :bug: Le problème

depuis l'espace prescripteur les filtres nom / prénom et entreprise ne fonctionnent pas. Depuis mon espace, j'ai fais un recherche prénom "thierry" en majuscule, minuscule, ça m'a dit pas de résultat. ensuite par un mot dans un nom entreprise idem non résultat

**Comment by gargagif** [comment]
@clement-duport ticket à détailler avec @Jessicaceleste1

**Comment by Jessicaceleste1** [comment]
ba j'ai pas besoin de plus, juste que ça fonctionne, mais comme je disais c'est surement lié à métabase, en fait si tu tape juste un prenom, ça ne fonctionne pas, si tu tape que un mot dans le nom de l'entreprise non plus, donc ça veut dire que lorsqu'ils effectuent une recherche les conseillers doivent connaitre le nom exact de l'entreprise indiqué sur la convention et idem pour le nom + prénom du candidat et dans le bon ordre pas simple

**Comment by Jessicaceleste1** [comment]
exemple je tape thierry et comme indiqué il y a bien une convention liée à l'agence avec le prénom thierry, elle ne ressort pas quand on active le filtre ![Image](https://github.com/user-attachments/assets/e421adaa-34af-4b92-8eac-3a3321b2099b)

**Comment by Jessicaceleste1** [comment]
idem nom de l'entreprise, ici residence ![Image](https://github.com/user-attachments/assets/dfd0ba36-0c7c-4f26-bd93-855575cce608)

**Comment by JeromeBu** [comment]
@Jessicaceleste1 je viens corriger les champs prénom + nom et entreprise. Tu peux me confirmer que c'est OK pour toi ?
