### ISSUE TITLE
ETQ Admin, mes coordonnées ne sont pas dans le formulaire

### ISSUE THREAD

**Issue by Sylvieleb** [gip-inclusion/immersion-facile#2495]
### :bug: Mon nom s'affiche dans le formulaire 

Si je dois renvoyer le lien de partage d'une convention mes coordonnées sont indiquées dans le formulaire.

### :footprints: Étapes pour reproduire
je veux envoyer le lien de partage du formulaire

- je vais dans brevo ouvrir le mail reçu par le candidat
- j’ouvre le mail
- je clique sur “compéter la demande”
- mes informations sont préremplie (car je suis connectée)

### :dart: Comportement attendu

- les coordonnées du candidats sont indiquées dans le formulaire![Image](https://github.com/user-attachments/assets/3b757602-ca02-43a6-9fd5-7e276da9b506)

**Comment by gargagif** [comment]
OK en staging
