### ISSUE TITLE
Création de la page Mon Profil

### ISSUE THREAD

**Issue by gargagif** [gip-inclusion/immersion-facile#2504]
### :construction: Epic

#1619 

### :thinking: Contexte et problématique

En guise de première étape du ticket #1812 et dans la continuité du ticket #1815 , l'objectif est de créer la page Mon Profil

### :tada: Proposition de solution

Créer la page Mon Profil et y afficher :

- un bouton permettant à l'utilisateur d'aller modifier ses informations sur Pro Connect
- la liste des agences auxquelles l'utilisateur est rattaché, avec le détail de ses droits (non-modifiables) agence par agence.

Rajouter un bouton "Mon Profil" dans le menu déroulant de l'utilisateur

### :camera: Maquettes

https://www.figma.com/proto/HYZpBJRGvsvCLTLcbWa9TC/Espace-personnel?page-id=1%3A19648&node-id=18-7157&node-type=frame&viewport=518%2C583%2C0.5&t=oZS3MPnzKAynlDem-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=18%3A7206

### Précisions par rapport à la maquette

- Les entreprises ne sont pas à prendre en compte dans la liste des organismes auxquels l'utilisateur est rattaché. Elles seront rajoutées ultérieurement (pré-requis : gestion des utilisateurs Entreprise).
- Les notifications ne sont pas modifiables dans un premier temps, cette gestion sera rajoutée ultérieurement.

**Comment by gargagif** [comment]
Recette OK en staging, par contre petite remarque : le bouton "Voir l'agence" est grisé et non-cliquable sauf si je suis admin de l'agence. Pour un utilisateur non-admin, voir ce bouton grisé / non-cliquable est peut-être source de frustration. Quid de rendre le nom de l'agence cliquable pour les admins et de faire disparaître le bouton ?
@3lodi3 @mdamourette pour avis.

![Image](https://github.com/user-attachments/assets/feacd2ae-6184-4f1d-9de6-740628b8ae5c)

**Comment by gargagif** [comment]
Proposition de Magali :

En effet, ça peut être frustrant et surtout source d'incompréhension. Je propose qu'on enlève carrément le bouton quand on n'y a pas accès.

Et si on veut éviter de garder une colonne juste pour ça, on peut le placer sous le nom de l'agence en question. En gardant le même look, d'un lien cliquable.

**Comment by JeromeBu** [comment]
J'ai une proposition ci dessous. Mais il faut noter que la page d'accès à l'agence n'est pas encore dispo (ca arrive dans l'itération). Donc j'ai mis un warning sur le lien, qui est pour l'instant, le lien réservé au admin IF. 

![Image](https://github.com/user-attachments/assets/42a8315a-138e-4311-866d-eb181df8ebc2)


Un non-admin va tomber sur ça, s'il clique :
![Image](https://github.com/user-attachments/assets/20fda5c8-666d-4ee4-911d-8ae2aeaea7fd)


Et la colonne "Actions" au bout, ne sera visible que pour les admins:
![Image](https://github.com/user-attachments/assets/d5798329-fda4-4b2e-8ab6-d5e8445b6b81)
