### ISSUE TITLE
ETQ Admin je souhaite voir la fiche d'une agence

### ISSUE THREAD

**Issue by Sylvieleb** [gip-inclusion/immersion-facile#2511]
### :bug: Le problème

La fiche d'une agence ne s'affiche pas alors qu'elle est bien référencée

### :dart: Comportement attendu

Voir la fiche

### Screenshots

![Image](https://github.com/user-attachments/assets/a98fe295-34ce-45df-a0af-9cf82a0afeab)
![Image](https://github.com/user-attachments/assets/5e990c6b-546b-41b1-8a71-fb5c2edfdd13)

**Comment by gargagif** [comment]
Lié au pb d'ajout d'utilisateur déjà rattaché à l'agence (PR https://github.com/gip-inclusion/immersion-facile/pull/2515).
Testé en staging : OK
