### ISSUE TITLE
Modifier les filtres du TBD Agence

### ISSUE THREAD

**Issue by gargagif** [gip-inclusion/immersion-facile#2518]
Dans le tableau de bord conventions Metabase des agences :
- ajouter le filtre “date de démarrage”
- retirer le filtre “ayant changé depuis”

**Comment by nathalie-reyre** [comment]
@clement-duport possible de proposer un tri par défaut en ordonnant par les dates de démarrage les plus proches ? (les conseillers voient comme ça en premier les demandes de convention les plus urgentes à valider)
