### ISSUE TITLE
ETQ bénéficiaire, je souhaite pouvoir modifier une convention

### ISSUE THREAD

**Issue by enguerranws** [gip-inclusion/immersion-facile#2538]
### :bug: Le problème

Dans le cas d'une modification de convention, les jours / horaires ne semblent pas bien remonter dans le formulaire. Pourtant, la section est indiquée comme complète.
Si l'utilisateur valide sa demande et que la section horaires n'a pas été ouverte, on a aucun feedback utilisateur.
Si on ouvre la section horaires, on voit que l'emploi du temps est vide et si on valide, les erreurs s'affichent.

Pour info, le souci a été repéré sur une convention CCI, je peux fournir un lien de prod pour reproduire le souci.

**Comment by celineung** [comment]
doublon avec https://github.com/gip-inclusion/immersion-facile/issues/2586
