### ISSUE TITLE
ETQ Bizdev, j'ai un tableau de bord des métiers en tension pour me permettre d'orienter mon travail de prospection (équilibre Offre/demande)

### ISSUE THREAD

**Issue by nathalie-reyre** [gip-inclusion/immersion-facile#2539]
### :thinking: Contexte et problématique

Un des OKR des bizdevs porte sur l'équilibre O/D "KR 2 : Un secteur sinistré quadrillé " . Les bizdevs ont donc besoin de savoir précisément quels sont les secteurs les plus "sinistrés". 
Actuellement les recherches se font sur la base des ROME (métiers) et non des NAF (secteurs d'activité), le tableau de bord va donc porter sur les ROME qu'on pourra ultérieurement rattacher à une ou plusieurs NAF. Les entreprises proposent leurs immersions également par intitulé métier (code OGR, lié à un ROME)
Le calcul des métiers/secteurs sinistrés se fait sur la base d'un ratio entre le nombre de recherches et le nombre d'entreprises proposant ce métier.

### :tada: Proposition de solution

- Ratio nombre de recherches dans le secteur dans **le département, régional, national**, et nombre de résultats par métier
- saisonnalité : mesure dans le temps

→  par métier top 1, top 2, top 3 lissé sur 12 mois avec résultats et régions, départements et national

- Une page avec le rapport national ( sans localité )
- Vue régionale, trié par ratio et groupé par métier
- Vue départementale, trié par ratio et groupé par métier

Tableaux à proposer 

<p>Filtres &gt; Ratio minimum</p>
<h3>Exemple national</h3>

Métier ROME | Ratio recherche/entreprise accueillante | Qté terrain immersion sur le même ROME | Qté recherches sur le ROME | Top NAF entreprises ( Future)
-- | -- | -- | -- | --
Développement Logiciel | 2 | 5000 | 10000 |  
Conseiller en insertion pro | 10 | 2000 | 20000 |  

<h3>Exemple régional</h3>

Métier ROME | Région | Ratio recherche/entreprise accueillante | Qté terrain immersion sur le même ROME | Qté recherches sur le ROME | Top NAF entreprises ( Future)
-- | -- | -- | -- | -- | --
Développement Logiciel | BFC | 2 | 1000 | 2000 |  
Conseiller en insertion pro | PACA | 10 | 2000 | 20000 |  
Développement Logiciel | IDF | 10 | 500 | 5000 |  

<h3>Exemple départemental</h3>
<p>Filtre Régional</p>

Métier ROME | Département | Ratio recherche/entreprise accueillante | Qté terrain immersion sur le même ROME | Qté recherches sur le ROME | Top NAF entreprises ( Future)
-- | -- | -- | -- | -- | --
Développement Logiciel | Bourgogne | 2 | 1000 | 2000 |  
Conseiller en insertion pro | Val d’Oise | 10 | 2000 | 20000 |  
Développement Logiciel | Franche Comté | 10 | 500 | 5000 |

**Comment by bbohec** [comment]
https://metabase.immersion-facile.beta.gouv.fr/dashboard/204-tableau-de-bord-secteur-sinistre?ratio_minimum=

**Comment by bbohec** [comment]
Manque colonne avec le code département dans la table search_made
