### ISSUE TITLE
ETQ entreprise, je veux voir le formulaire de modification de l'entreprise à jour

### ISSUE THREAD

**Issue by celineung** [gip-inclusion/immersion-facile#2564]
### :bug: Le problème

ETQ entreprise, lorsque je modifie ma visibilité et que je reviens sur ce formulaire après l'avoir sauvegardé, mes informations de visibilité ne sont plus à jour.

Les entreprises pensent alors que la modification n'a pas marché.

### :footprints: Étapes pour reproduire

1. Aller sur la page de modification entreprise
2. Modifier la visibilité sur la question "Êtes-vous disponible actuellement pour recevoir des personnes en immersion ?"
3. Sauvegarder
4. Revenir sur ce formulaire par la navigation sans rafraichissement de page
5. Constater que la visibilité ne s'est pas mis à jour

### Screenshots

 

📍Étape 1 
![Image](https://github.com/user-attachments/assets/ab351004-eedd-49bc-9dec-390c78b4f7da)

Je modifie ma visibilité

📍Étape 2
![Image](https://github.com/user-attachments/assets/9536fcdb-1144-4621-84b2-d937d0d10503)

J'enregistre

📍Étape 3
![Image](https://github.com/user-attachments/assets/3c612cc2-1b0a-4c9a-84b9-a7704fb292b3)

Je ne retrouve pas ma modification de visibilité

**Comment by NastassiaRodriguez** [comment]
Suggestion : ajouter un bouton volant "enregistrer mes modifications" dès le début / haut de la page pour pouvoir enregistré les modifications de visibilité sans scroller jusqu'en bas

**Comment by gargagif** [comment]
Recette OK en staging
