### ISSUE TITLE
ETQ prescripteur je ne peux me connecter à mon espace via pro connect

### ISSUE THREAD

**Issue by Jessicaceleste1** [gip-inclusion/immersion-facile#2565]
### :bug: Le problème

J'ai un message d'erreur : Accès impossible
Nous n'arrivons pas à vous connecter à votre service en ligne pour l'instant.

code erreur : Y030118

id erreur : 77cb7152-56a4-4836-9917-2210856f6aaa

message erreur : "redirect_uri did not match any of the client's registered redirect_uris (undefined)".

**Comment by gargagif** [comment]
Corrigé en prod
