### ISSUE TITLE
Form Convention - Le bouton "vérifier la demande" ne fonctionne pas sur une demande de modif

### ISSUE THREAD

**Issue by bbohec** [gip-inclusion/immersion-facile#2586]
### :bug: Le problème

Remonté par 2 utilisateurs.
Exemple de lien convention disponible dans [discord ](https://discord.com/channels/864451835553513474/1042365650359828480/1309544668752773211)

### :footprints: Étapes pour reproduire

Cliquer sur le lien magique de modif
La conv est complète
Cliquer sur Vérifier la demande > il ne se passe rien et on a une erreur dans la console voir screen

### :dart: Comportement attendu

On arrive bien sur la revue de conv avant confirmation ou bien on a un message d'erreur si la convention est mal remplie

### Screenshots

![Image](https://github.com/user-attachments/assets/f2128010-1684-46e2-aba9-26c6ea123dd1)

**Comment by gargagif** [comment]
Recette OK en staging
