### ISSUE TITLE
Uniformiser les termes MER/Candidature/Discussions

### ISSUE THREAD

**Issue by 3lodi3** [gip-inclusion/immersion-facile#2589]
### :thinking: Contexte et problématique

Les candidats qui envoient un message à une entreprise, on appelle ça selon les endroits : 
- mises en relations
- discussions
- candidatures

### :tada: Proposition de solution

Uniformiser et appeler cela partout "Candidatures"

**Comment by gargagif** [comment]
doublon #2402
