### ISSUE TITLE
ETQ admin je veux passer des pre-validateurs en lecteur

### ISSUE THREAD

**Issue by Sylvieleb** [gip-inclusion/immersion-facile#2598]
### :bug: Le problème

L'agence veut passer de 2 à 1 étape de validation, supprimer 1 pré-validateur et passer en lecteur les autres pré-validateurs
Il n'est pas possible de passer en lecteur des prévalidateurs

### :footprints: Étapes pour reproduire

1. Je vais sur la fiche établissement de la Mission Locale Le Havre Estuaire Littoral (Le Havre) 
2. il y a  3 pré validateurs : 1 reçoit les notifs, 2 ne reçoivent pas les notifs
3. Je supprime le 1er pré-validateur (celui qui reçoit les notifs)
4. je veux changer le rôle des 2 autres pré-validateurs (ceux qui ne reçoivent pas les notifs) et les passer en lecteurs
5. c'est pas possible, cette erreur s'affiche:
Problème lors de la mise à jour de l'utilisateur
L'agence a74e8cb3-172c-4782-9867-f432668a76c1 doit avoir au moins un conseiller recevant les emails.

Du coup, j'ai supprimé les 2 prévalidateurs pour que l'agence n'ai qu une étape de validation, je rajouterai es 2 pré-validateurs avec e rôle lecteur plus tard. 

### :dart: Comportement attendu

je peux modifier les rôles
trouver un autre moyen pour alerter si il faut qu'on dise qui reçoit les notif

### Screenshots
![Image](https://github.com/user-attachments/assets/c611a3c9-abbf-411d-8ade-19718b99d8f0)

**Comment by gargagif** [comment]
Règle à implémenter : s'il y a un ou plusieurs pré-validateurs définis sur l'agence, il faut qu'il y ait au moins un pré-validateur qui reçoive les notifications.

**Comment by gargagif** [comment]
Recette OK en staging
