### ISSUE TITLE
Soumission du formulaire de convention bloqué alors que tout a l'air OK

### ISSUE THREAD

**Issue by celineung** [gip-inclusion/immersion-facile#2621]
Lorsque l'on soumet le formulaire de convention, toutes les sections sont marquées comme correctement remplies mais impossible d'accéder à l'écran suivant.

![Image](https://github.com/user-attachments/assets/5b3e65b9-0099-4405-8f21-662608948fcf)
![Image](https://github.com/user-attachments/assets/060d3c37-116b-420b-b31d-073407963a9b)

**Comment by gargagif** [comment]
Recette OK en staging
