### ISSUE TITLE
ETQ qu'entreprise je ne peux pas signer ma convention

### ISSUE THREAD

**Issue by Jessicaceleste1** [gip-inclusion/immersion-facile#2622]
### :bug: Le problème

impossible de signer la convention https://immersion-facile.beta.gouv.fr/verifier-et-signer?jwt=eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJ2ZXJzaW9uIjoxLCJhcHBsaWNhdGlvbklkIjoiYmU2MjhkYjEtN2Y5Yi00YjIzLWE4MmUtZmM5MTcxOTU4YjNhIiwicm9sZSI6ImVzdGFibGlzaG1lbnQtcmVwcmVzZW50YXRpdmUiLCJpYXQiOjE3MzI2MjE0ODgsImV4cCI6MTczNTI5OTg4OCwiZW1haWxIYXNoIjoiYjA0ZjVmYWE3OGY1OTM4MjUwNTdhMDZhNDZlYThlNDgifQ._xirS2I0np_LHntCvGeuxEGz6h_MczZKD8xo8nK7SGQ3j8GaNvz-OKXlWeW820Kpast7tDHWhdndwNKtun1bFQ

message d'erreur lors de la signature de la convention
en plus il s'affiche tout en bas alors que on clique sur "signer la convention" la page remonte pas défaut tout en haut à l'identique, il faut redescendre en bas pour comprendre que ça n'a pas fonctionné

![Image](https://github.com/user-attachments/assets/3cc5fff5-1270-411c-b27a-914f2c85774d)

**Comment by enguerranws** [comment]
Alors : 
- on a remis les signatures à zéro, ce qui a permis de valider la convention, donc l'utilisateur est débloqué
- par contre : 
  - [les logs](https://app.datadoghq.eu/logs?query=host%3Aif-prod-back-web-1%20service%3Aif-prod-back%20%40req.url%3A%22%2Fauth%2Fdemandes-immersion%2Fbe628db1-7f9b-4b23-a82e-fc9171958b3a%22%20%40req.method%3APOST&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&context_event=AZNoH43gAACVLzT8X-QEWgAA&event=AwAAAZNoSciE7zDzFgAAABhBWk5vU2NtV0FBQW8yenRGZ3hWbXBnQUEAAAAkMDE5MzY4NTctYjk3Ni00N2RkLTk5NmEtMDFjMzhmYzQyMTIyAABWew&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=time%2Cdesc&viz=&from_ts=1732525851523&to_ts=1733130651523&live=true) nous indiquent que lors de la demande de modification a été soumise 3 fois : 2 fois en 400, et la dernière fois en 200
  - [le replay Sentry](https://sentry.gip-inclusion.org/organizations/gip-inclusion/replays/20fa1e760c4449f4a2adeddfedec2dd0/?n_detail_row=3&n_detail_tab=request&project=2&query=&referrer=%2Forganizations%2F%3AorgId%2Freplays%2F&statsPeriod=30d&t_main=breadcrumbs&yAxis=count%28%29) nous indique plusieurs choses intéressantes : 
    - à la récupération de la convention pour modif (avec jwt) la convention a déjà 2 signatures
    - l'utilisateur essaie de soumettre 2 fois le formulaire et se prend un loader infini, il reload
    - après une pause de 5 minutes, et après avoir changé le tuteur et le rep de l'entreprise, il soumet à nouveau avec succès (alors qu'on continue de voir les 2 signatures validées)

Suite à ça, le dernier signataire a voulu signer et s'est pris l'erreur remontée par @Jessicaceleste1
