### ISSUE TITLE
ETQ conseiller d'une agence FT, je ne dois pas recevoir par mail une notification pour un DE qui ne s'est pas FT connecté

### ISSUE THREAD

**Issue by nathalie-reyre** [gip-inclusion/immersion-facile#2623]
### :bug: Le problème

problème tel que décrit par Marion (désormais à la PDI) 
Cette convention m'a été envoyée automatiquement MAIS : je ne connais pas cette personne et je n'ai jamais été sa conseillère + je n'ai plus de portefeuille DE à FT. L'entreprise relève bien de l'agence dont je dépends mais je n'ai aucun lien avec le service entreprise ici...

mailto:ne-pas-ecrire-a-cet-email@immersion-facile.beta.gouv.fr
vendredi 8 novembre 2024 10:57 À : marion.recurt@francetravail.fr
 Une demande de convention d'immersion est déposée : Kechare, MERISIER - CAMACF - Agence France Travail MONTAUBAN NORD
Marion apparait bien comme dans la liste des conseillers de l'agence. Elle a des droits de validateur car conseillère
 
Marion SAMARANmarion.samaran@francetravail.fr | Ne reçoit pas les notifications | Validateur
mais ne reçoit pas de notification
La convention a été adressée à l'agence (boîte fonctionnelle)

de fait des notifications ont été envoyées à tous les conseillers de l"agence cf screen 
![Image](https://github.com/user-attachments/assets/3e74ce7d-e780-4c6e-9b92-615cff468b99)

### :dart: Comportement attendu

les notifications ne sont envoyées que sur la boite agence et sur les mails indiqués comme pouvant recevoir des notifications

**Comment by nathalie-reyre** [comment]
le problème date du 8 nov. Date de l'envoi en masse de notifs ?

**Comment by JeromeBu** [comment]
> le problème date du 8 nov. Date de l'envoi en masse de notifs ?

oui c'est exactement ça:

![Image](https://github.com/user-attachments/assets/05ad1f65-5059-4168-9b37-eece7e0279dd)

Pour la partie envoie à tous les validateurs. 

Mais il faut investiguer sur la partie : la convention n'a pas été envoyé au conseiller référent.
