### ISSUE TITLE
notification de rejet doit être diffusé auprès de la structure d'accompagnement 

### ISSUE THREAD

**Issue by nathalie-reyre** [gip-inclusion/immersion-facile#2624]
### :bug: Le problème

Le 26 novembre, une notification de rejet d'une structure d'accompagnement a été adressée à l'ensemble des conseillers (qui ne reçoivent en principe pas de notifs) valideurs d'une agence FT.
Ces conseillers n'auraient pas du recevoir cette notif de rejet car aucun n'a la coche "envoi de notif" en true.
![Image](https://github.com/user-attachments/assets/d58cb0d1-14ae-4b6b-b724-27153a6c3752)

Jusqu'ici, il est possible qu'on ne se soit pas aperçu de ce problème car la plupart des  rejets concernent des structures prescriptrices qui viennent d'être crées et peu d'utilisateurs y sont rattachés.
Là, il s'agit d'une structure d'accompagnement qui voulait se rattacher à une agence FT avec plus de 50 conseillers.

-->

### :dart: Comportement attendu

Les notifications de rejet ne sont transmises qu'à ceux qui doivent recevoir des notifs : l'admin de la structure prescriptrice et celui ou ceux dont on a le mail côté structure d'accompagnement.

**Comment by bbohec** [comment]
> et celui ou ceux dont on a le mail côté structure d'accompagnement.

On parle bien de ceux qui dans cette situation ont un droit de type conseiller sur la structure d'accompagnement?

**Comment by bbohec** [comment]
Proposition de solution car la discussion et la description de l'issue manque de clarté:

```diff
-SendEmailWhenAgencyIsRejected
+Usecase - SendEmailWhenAgencyIsRejected
+  -Rights paths
-  - Sends an email to validators with agency name
+    - Sends an email to all users that have notification enabled for the agency
+    - Sends an email to all agency A users that have notification enabled for the agency A and agency B admins with notification enabled of the agency B when agency A refers to agency B.
+  - Wrong paths   
-  - On missing agency
+    - Error - Not found - On missing agency
-  - On agency not rejected    
+    - Error - Not rejected - On agency not rejected
```

Si quelque chose n'est pas clair on en parle.

**Comment by nathalie-reyre** [comment]
- If the agency is not rejected then the feature raise a not rejected error.  est ce que dans le cas de  If the agency A refers to agency B, la notification d'activation est bien envoyée aux 2 ? Sinon, je fais un autre ticket

**Comment by bbohec** [comment]
> * If the agency is not rejected then the feature raise a not rejected error.  est ce que dans le cas de  If the agency A refers to agency B, la notification d'activation est bien envoyée aux 2 ? Sinon, je fais un autre ticket

Pour le coup la notification d'activation c'est une autre feature/autre bug.
Un bug par feature.
