### ISSUE TITLE
ETQ utilisateur, je ne veux pas pouvoir modifier une convention qui ne peut pas l'être

### ISSUE THREAD

**Issue by enguerranws** [gip-inclusion/immersion-facile#2646]
### :bug: Le problème

Quand on ouvre une demande de modification de convention passée (qui n'est plus en DRAFT).

### :dart: Comportement attendu

On devrait avoir un message d'erreur qui indique que la modif n'est pas possible dans cet état.

**Comment by gargagif** [comment]
Recette OK en staging
