### ISSUE TITLE
ETQ Entreprise, je n'ai pas mon entreprise ajoutée dans IF si je fourni un email en doublon

### ISSUE THREAD

**Issue by bbohec** [gip-inclusion/immersion-facile#2650]
### :bug: Le problème

Actuellement on a une erreur de DB sur un problème d'unicité de droit.
![Image](https://github.com/user-attachments/assets/7595407e-29ec-4e32-be44-a510e483aeb6)

Le problème est situé dans le code du usecase:

```typescript
   const userRights: EstablishmentUserRight[] = [
      {
        role: "establishment-admin",
        userId: establishmentAdminId,
        job: businessContact.job,
        phone: businessContact.phone,
      },
      ...establishmentContactIds.map(
        (userId): EstablishmentUserRight => ({
          role: "establishment-contact",
          userId,
        }),
      ),
    ];
```

### :footprints: Étapes pour reproduire

Je créé une entreprise avec le même email dans le contact principal et dans les copy emails

### :dart: Comportement attendu

L'entreprise est crée en retirant les emails en doublon.

**Comment by nathalie-reyre** [comment]
c'est un peu c...n de mettre le même mail en cc😅 Dans la demande de convention, on bloque les mails en doublon. On peut appliquer la même règle.

**Comment by gargagif** [comment]
Recette OK en staging
