### ISSUE TITLE
Les coordonnées du représentant légal d'un mineur ne s'affiche plus automatiquement lors d'un partage de convention

### ISSUE THREAD

**Issue by cecile-dimarco** [gip-inclusion/immersion-facile#2669]
### :bug: Le problème

Je saisie une convention de mini-stage pour un mineur
Je complète le champ coordonnées du représentant légal du jeune
Je partage la convention avec l'entreprise ou autre
ETQ qu'entreprise, j'ouvre le lien partagé, et le champ sur les coordonnées du représentant légal du jeune ne s'affiche pas. A la place, le champ personne à contacter en cas d'urgence est rempli

Il faut alors que je clique sur la date de naissance du bénéficiaire pour que le champ représentant légal du jeune s'affiche correctement.

-->

### :dart: Comportement attendu

la convention partagée affiche directement les champs renseignés représentant légal du jeune sans que je doive cliquer sur la date de naissance

**Comment by cecile-dimarco** [comment]
Lien fil discord avec l'URL d'une convention partagée https://discord.com/channels/864451835553513474/1314237896470954034

**Comment by gargagif** [comment]
Recette OK en staging mais petit point d'attention : lorsqu'on arrive sur un lien partagé, toutes les sections sont mentionnées comme étant "à compléter", même celles déjà remplies :

![Image](https://github.com/user-attachments/assets/0da3769f-a4c0-4d04-877c-67d523775b94)

Il faut cliquer sur l'une des sections pour que celles qui sont complétées s'affichent correctement :

![Image](https://github.com/user-attachments/assets/48e1a859-f196-4314-93c3-fc9051595318)

Est-il possible de faire en sorte que les informations soient à jour dès l'arrivée sur la page ?
