### ISSUE TITLE
la previsualisation de la recherche pour ajout d etablissement ne fonctionne plus

### ISSUE THREAD

**Issue by JeromeBu** [gip-inclusion/immersion-facile#267]
Ca ne se met plus à jour avec le formulaire

![Image](https://user-images.githubusercontent.com/22095555/244117137-9774233f-f04a-4d03-8d3e-72d7e670d52c.png)

**Comment by nathalie-reyre** [comment]
recette : la prévisualisation est ok mais souci au moment de l'enregistrement 
 d'un étab en recette = la 1ere fois, l'étab (siret 920 097 516 00016) est enregistré mais n'apparait pas quand je cherche pharmacien à Talant. Je saisis de nouveau son siret et je peux recreer un établissement mais erreur au moment de l'enregistrement


![Image](https://github.com/gip-inclusion/immersion-facile/assets/61510442/e649e6e7-a610-42dd-aa40-c7d6421268ea)
