### ISSUE TITLE
ETQ utilisateur je peux faire une recherche avec un métier

### ISSUE THREAD

**Issue by enguerranws** [gip-inclusion/immersion-facile#2692]
Nous avons de plus en plus d'erreurs de ce type : https://github.com/gip-inclusion/immersion-facile/pull/2655#issuecomment-2527458113

Visiblement, à certains moments (soit des interactions un peu particulières, soit retours api qui ne seraient pas conformes au contrat - ce qui semble impossible aussi, le back enverrait une erreur). On tente un petit refacto sur le fichier pour simplifier et peut être corriger l'erreur.

**Comment by gargagif** [comment]
Bug non-reproduit en staging
