### ISSUE TITLE
ETQ qu'utilisateur, je peux renouveler le lien pour voir le statut de ma convention

### ISSUE THREAD

**Issue by enguerranws** [gip-inclusion/immersion-facile#2702]
### :bug: Le problème

Remontée utilisateur depuis Crisp : un lien de statut de convention périmé (plus d'un mois) affiche une erreur.

### :footprints: Étapes pour reproduire

Étapes pour reproduire le comportement:
1. Aller sur [le lien](https://immersion-facile.beta.gouv.fr/statut-convention?jwt=eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJ2ZXJzaW9uIjoxLCJhcHBsaWNhdGlvbklkIjoiMmFhZDk0OTQtNmExMS00ZjQ4LTgxNDktNGY2MTc5YTFhYTM5Iiwicm9sZSI6ImJlbmVmaWNpYXJ5IiwiaWF0IjoxNzMwMjk2MjAzLCJleHAiOjE3MzI5NzQ2MDMsImVtYWlsSGFzaCI6IjFiODY0OGUxNWY5MDZlMTYwN2I3MjY4N2ZhZDhkNGFmIn0.2q7soAcNOFRzjqhutdyTMFI_rfF9D3bzvRWC70XYWq23aYiV-DXGRFvQCkgUGQ3wjn0Z-ih91WEOg2tD2lBYew)

### :dart: Comportement attendu

Prolonger la validité du lien : 6 mois

**Comment by JeromeBu** [comment]
ceci ne fonctionne que sur les nouveaux liens. Les anciens restent périmés....

**Comment by gargagif** [comment]
Pas testable en staging, ou alors dans 6 mois ;)
