### ISSUE TITLE
Tech - ajustements Sentry (perf)

### ISSUE THREAD

**Issue by enguerranws** [gip-inclusion/immersion-facile#2715]
@bbohec a remarqué que les appels vers Sentry (qui nous sert de monitoring d'erreurs front, en gros), a un assez gros impact sur le temps de chargement de l'app pour les utilisateurs. 

On ajuste la façon de l'appeler pour décaler cet appel et voir ce que ça donne.

**Comment by bbohec** [comment]
![Image](https://github.com/user-attachments/assets/dca5cf27-acf6-4811-9b1c-9faa74bbe269)

Le FCP a été amélioré. Il a gagné ~1.5/2s par rapport au check précédent (je n'ai pas conservé les anciennes valeurs).
Mesure faite en CPU slowdown x6 et en network throttle mode 3G. Cache activé.

**Comment by enguerranws** [comment]
![Image](https://github.com/user-attachments/assets/abbf7b4d-d513-478d-8551-bf388e38d8bf)
