### ISSUE TITLE
Le formulaire de mini-stage ne scroll pas entièrement

### ISSUE THREAD

**Issue by mdamourette** [gip-inclusion/immersion-facile#2724]
### :bug: Le problème

Le formulaire de convention pour les mini-stages ne scroll pas entièrement sur les écrans en-dessous de 990px. La partie "Détails du stage" n'est donc pas accessible.

### :dart: Comportement attendu

Le footer ne devrait pas cacher des éléments de l'interface. Il faut pouvoir scroller entièrement.

### Screenshots

https://github.com/user-attachments/assets/10086073-a1d6-4cf3-9535-fb8a5964b71f

**Comment by gargagif** [comment]
Recette OK en staging
