### ISSUE TITLE
ETQ que contact entreprise admin ou contact simple, je veux pouvoir voir les MER de l'entreprise dans le tableau de bord et pouvoir les piloter

### ISSUE THREAD

**Issue by bbohec** [gip-inclusion/immersion-facile#2736]
### :thinking: Contexte et problématique (et par qui est-ce remonté ?)

Actuellement beaucoup de demandes support de personnes qui ont les droits d'entreprise qui va bien mais erreur lorsqu'ils veulent piloter la MER et ne voient pas la MER dans le tableau de bord MER entreprise

### :tada: Proposition de solution

Suite à la refonte du système de droit entreprises, on peut maintenant techniquement:
- lister les MER dans le tableaux de bord MER entreprise
- piloter une MER parceque j'ai les droits de l'entreprise et que la MER a le bon SIRET

**Comment by Jessicaceleste1** [comment]
Ce problème est de plus en plus récurrent et impact notre OKR : le nombre de MER passe à 25% à horizon mars 2025, nous avons de plus en plus de ticket sur le sujet
En effet, il faut que chaque personne reliée à une entreprise, puisse voir les MER et les piloter. 
@nathalie-reyre est ce possible de prioriser ce ticket

**Comment by nathalie-reyre** [comment]
@Jessicaceleste1 c'est absolument une des priorités. Ca fait partie de l'epic espace entreprise  -l'accès aux MER sera défini par l'admin entreprise. ce ticket est un doublon en fait

**Comment by bbohec** [comment]
J'avais cherché dans le backlog un ticket existant sur ce sujet, tu peux indiquer l'issue existante?

**Comment by gargagif** [comment]
Doublon #2717 je clôture celui-ci
