### ISSUE TITLE
Faire une recherche normale si l'api diagoriente  ne retourne pas de résultats

### ISSUE THREAD

**Issue by celineung** [gip-inclusion/immersion-facile#2741]
### :bug: Le problème

Sur une recherche sur "taxi" par exemple, diagoriente ne retourne pas de résultats alors que l'autre méthode de recherche que nous avons en retourne:

![Image](https://github.com/user-attachments/assets/5345a49d-b0c4-42d7-b2b4-a71423067178)
![Image](https://github.com/user-attachments/assets/cb99fcc9-1f1d-4374-a254-671bdbb3c60d)

### :dart: Comportement attendu

Si pas de résultats à partir de diagorient, retourner sur la méthode de recherche initiale.

**Comment by gargagif** [comment]
Je n'ai pas réussi à reproduire le problème : la recherche "taxi" retourne les mêmes suggestions en staging et en prod, sur recherche classique et sur diagoriente
Céline pense que c'est l'api Diagoriente qui devait retourner vide quelque soit la recherche effectuée ce matin, vu que nous avions eu un paquet de recherche sans résultat. Cette PR évitera les erreurs api de notre côté les prochaines fois que Diagoriente ne nous retournera pas de résultats.
