### ISSUE TITLE
Changement de date intempestif sur le formulaire de convention

### ISSUE THREAD

**Issue by gargagif** [gip-inclusion/immersion-facile#2748]
### :bug: Le problème

Certains utilisateurs (remontée support + tests Cécile) voient les dates de début et de fin d'immersion se décaler d'une journée en amont lorsque le focus passe sur un autre champ.

Testé en live avec Cécile sur Chrome, qui rencontre en outre des erreurs sur cette page (cela n'a peut-être aucun lien) :

![Image](https://github.com/user-attachments/assets/0cae3039-6bd8-4abe-9ab3-58f942d25624)

Le problème se produit quelque soit la date (2024 ou 2025).

Gaël ne reproduit pas le bug sur Chrome et les erreurs ne s'affichent pas non-plus dans la console.

### :footprints: Étapes pour reproduire

1. Aller sur le formulaire de convention
2. Choisir une date de début d'immersion
3. Sortir du champ (aller sur un autre champ)
4. La date de début d'immersion s'est décalée d'une journée plus tôt

Idem avec la date de fin d'immersion.

### :dart: Comportement attendu

Aucun changement de date ne se produit.

**Comment by celineung** [comment]
Bug introduit par la résolution de ce ticket: https://github.com/gip-inclusion/immersion-facile/issues/2571
On faisait la conversion dû à la timezone plusieurs fois.
