### ISSUE TITLE
ETQ FT, je veux recevoir les convention dont le type de structure d'accompagnement est FT ou 'cap-emploi'

### ISSUE THREAD

**Issue by celineung** [gip-inclusion/immersion-facile#2761]
ETQ FT, je veux recevoir:
- les demandes dont le type de structure d'accompagnement est 'autre' et dont le prescripteur est 'France Travail.
- les demandes dont le type de structure d'accompagnement est 'cap-emploi'

**Comment by nathalie-reyre** [comment]
pas recettable
