### ISSUE TITLE
Contact établissement API V2

### ISSUE THREAD

**Issue by clement-duport** [gip-inclusion/immersion-facile#287]
L'objectif de l'immersion est obligatoire dans le formulaire de mise en relation par mail.  Modifier le contrat pour le contrat pour les partenaires: ajouter les nouveau champs requis dans le formulaire de mise en relation par mail (immersionObjective, phone number, resumeLink), en profiter pour retirer "contact mode"(sert à rien) et remplacer offer par le romeCode. 

Ajouter une colonne email a la table api consumer pour pour pouvoir prévenir les partenaires quand il y a un changement dans l'api

**Comment by clement-duport** [comment]
- [ ] Modifier le contrat pour le contrat pour les partenaires: ajouter les nouveau champs requis dans le formulaire de mise en relation par mail (immersionObjective, phone number, resumeLink

- [ ] remplacer offer par le romeCode.

- [ ] Ajouter une colonne email a la table api consumer pour pour pouvoir prévenir les partenaires quand il y a un changement dans l'api

- [ ]  retirer "contact mode"(sert à rien)

**Comment by Hervelallemand974** [comment]
Contact Pass emploi : 
Stephen Potyondi
stephen.potyondi@beta.gouv.fr
copie 
Isabelle Cerrutti
isabelle.cerrutti@pole-emploi.fr
