### ISSUE TITLE
Généraliser l'écriture inclusive

### ISSUE THREAD

**Issue by PierreDeNantes** [gip-inclusion/immersion-facile#294]
Faire la chasse au texte uniquement au masculin, ex : 

![Image](https://user-images.githubusercontent.com/113897423/245516295-483623b9-59f7-4578-8f69-617d52824a8d.png)

**Comment by nathalie-reyre** [comment]
attention au type d'écriture inclusive le é.e ne sont pas lus par les bots et  les malvoyants sont mis en difficulté.
