### ISSUE TITLE
Préparer une V2 de l'API  de recherche

### ISSUE THREAD

**Issue by JeromeBu** [gip-inclusion/immersion-facile#309]

**Comment by JeromeBu** [comment]
linked to #287

**Comment by nathalie-reyre** [comment]
lier les 2 API : recherche d'entreprises et mise en relation

**Comment by clement-duport** [comment]
- [ ] Ajouter appellation code en optionel
- [ ] Ajouter la possibilité de fournir des adresses dans les params de recherche en plus de la position
- [ ] Changer distance_km en distanceKm
- [ ] Bien préciser a quoi correspond volontary to immersion : case true/false/undefined 
- [ ] Mettre a jour la doc

**Comment by JeromeBu** [comment]
prévoir un boolean pour savoir si la recherche doit se faire uniquement sur le code appellation ou également sur le rome code

**Comment by JeromeBu** [comment]
stocker l'adresse dans searches_made
