### ISSUE TITLE
Correction template mail contact entreprise

### ISSUE THREAD

**Issue by Hervelallemand974** [gip-inclusion/immersion-facile#328]

**Comment by Hervelallemand974** [comment]
Plus d'info sur ce candidat:

=> texte à modifier : "Plus d'informations sur ce candidat :"

Prenez contact avec le candidat par email ou par téléphone:

=> mettre en gras et augmenter la taille

**Comment by JeromeBu** [comment]
Obsolète, avec le mail qui a changé avec les échanges
