### ISSUE TITLE
Ajouter une colonne contact_email a la table api consumer pour pour pouvoir prévenir les partenaires quand il y a un changement dans l'api

### ISSUE THREAD

**Issue by clement-duport** [gip-inclusion/immersion-facile#330]
Ajouter en commentair de cette carte les adresse des partenaire : 
-bim bam job 
-diagoriente
-un jeune une solution
-pass emploi

**Comment by clement-duport** [comment]
- [ ] Contact Diagoriente: contact@diagoriente.beta.gouv.fr

- [ ] Contact Pass emploi : Stephen Potyondi --> stephen.potyondi@beta.gouv.fr copie Isabelle Cerrutti -->isabelle.cerrutti@pole-emploi.fr

**Comment by nathalie-reyre** [comment]
Contact Bimbamjob : agnes.vincent@bimbamjob.fr ; hugo.robellaz@bimbamjob.fr

**Comment by nathalie-reyre** [comment]
Contact1jeune1solution :  julie.gallavardin@octo.com
