### ISSUE TITLE
Typo dans des mails (remonté par Arnaud)

### ISSUE THREAD

**Issue by JeromeBu** [gip-inclusion/immersion-facile#334]
Je colle ici le message mattermost d'Arnaud:

Arnaud Denoix
[12:25 PM](https://mattermost.incubateur.net/betagouv/pl/9w3yfy9ud38hugtyy7mnopb15y)

@Benjamin @Elodie Delaisement  j'ai reçu un mail nouvelle mouture ! 

j'ai repéré quelques coquilles : 

La ligne Rédigez ici votre email de motivation en suivant nos conseils. qui apparait dans le mail final
Une majuscule de trop à Confirmer
Le nom de l'entreprise est pas le bon Les services publics numériques de l'inclusion et de l'emploi au lieu de GIP Plateforme de l'inclusion
Pour paiement de mes efforts de feedback, je rajoute une suggestion pour la route : possible de mettre en gras le nom du métier dans le corps du mail ?

(lient du message mattermost : https://mattermost.incubateur.net/betagouv/pl/9w3yfy9ud38hugtyy7mnopb15y )

**Comment by celineung** [comment]
Le nom me semble correct.
Le nom affiché dans l'exemple est le champ `customized_name` de la DB.
