### ISSUE TITLE
Modification du lien vers le bilan vierge

### ISSUE THREAD

**Issue by Hervelallemand974** [gip-inclusion/immersion-facile#349]
modifier le lien par un bouton : télécharger votre modèle de bilan
dans le template de convention et dans le template de rappel à j-1

**Comment by JeromeBu** [comment]
(Dans le mail qui contient la convention)

**Comment by nathalie-reyre** [comment]
dans le mail de convention, le lien vers le bilan n'est pas visible

**Comment by enguerranws** [comment]
![Image](https://github.com/gip-inclusion/immersion-facile/assets/2190121/3d6c6868-365f-4703-a8dd-e8e4341ed824)
