### ISSUE TITLE
Mettre un champ nom/prénom du prescripteur lors de la validation de convention pour suivi par les équipes d'une agence (demande pour PMSMP & Mini stage)

### ISSUE THREAD

**Issue by bbohec** [gip-inclusion/immersion-facile#354]
- [x] ajout d'un champ text area facultatif dans une modale ouverte au clic sur btn validation
- [ ] success ou error selon sur quel bouton on clique dans la modale
- [ ] scinder l'email "Convention finale validée" en deux - 1 pour les prescripteurs avec la note, et 1 pour les autres acteurs sans la note
- [ ] Deux versions selon que la validation se fait en 1 ou 2 étapes (voir figma)

Proto Validation 1 étape : https://www.figma.com/proto/NF2TPwDkR3iUbQvYeURWes/Prod---design-d'issues?page-id=7%3A810&type=design&node-id=7-1015&viewport=-391%2C521%2C0.09&t=Qs2Vw66LrUnCJdEv-8&scaling=min-zoom&starting-point-node-id=7%3A1015&show-proto-sidebar=1&hide-ui=1

Proto Validation 2 étapes : https://www.figma.com/proto/NF2TPwDkR3iUbQvYeURWes/Prod---design-d'issues?page-id=7%3A810&type=design&node-id=7-1055&viewport=-391%2C521%2C0.09&t=e3bLGihIFrUGTmGa-8&scaling=min-zoom&starting-point-node-id=7%3A1055&show-proto-sidebar=1&hide-ui=1

Fichier (vous avez tous les droits au moins en view) : https://www.figma.com/file/NF2TPwDkR3iUbQvYeURWes/Prod---design-d'issues?type=design&mode=design&t=gjz4CFnBYBhleK9u-1

**Comment by nathalie-reyre** [comment]
A voir rapidement à ton retour car le besoin est réel mais on ne sait pas trop comment le traiter

**Comment by 3lodi3** [comment]
Proposition à discuter : https://www.figma.com/proto/O6MfTEZ1Ms8cKQHFjOYEA5/Site---UX-design?page-id=882%3A59150&type=design&node-id=882-59155&viewport=627%2C222%2C0.42&t=veJDOFuqqHP1ZtTE-8&scaling=min-zoom&starting-point-node-id=882%3A59155&hide-ui=1

**Comment by 3lodi3** [comment]
> Proposition à discuter : https://www.figma.com/proto/O6MfTEZ1Ms8cKQHFjOYEA5/Site---UX-design?page-id=882%3A59150&type=design&node-id=882-59155&viewport=627%2C222%2C0.42&t=veJDOFuqqHP1ZtTE-8&scaling=min-zoom&starting-point-node-id=882%3A59155&hide-ui=1

Mis à jour suite à notre point @JeromeBu @bbohec , j'ai ajouté l'email "Convention finale validée" car comme on donne la possibilité de mettre une note "interne" prescripteur, il faudrait le scinder en deux - pour les prescripteurs avec la note, et pour les autres acteurs sans la note.

**Comment by 3lodi3** [comment]
Nouvelle version avec 1 étape / 2 étapes + vue de la note dans le tableau de bord + l'email prescripteur : https://www.figma.com/proto/NF2TPwDkR3iUbQvYeURWes/Prod---design-d'issues?page-id=7%3A810&type=design&node-id=7-1015&viewport=0%2C422%2C0.03&t=MGGgYV2CVJTknKci-1&scaling=min-zoom&starting-point-node-id=7%3A1015&show-proto-sidebar=1&mode=design

**Comment by nathalie-reyre** [comment]
ça me va très bien. Merci @3lodi3

**Comment by 3lodi3** [comment]
@clement-duport les templates d'emails sont dans le figma : https://www.figma.com/file/NF2TPwDkR3iUbQvYeURWes/Prod---design-d'issues?type=design&node-id=7%3A1043&mode=design&t=hTs2g8H1XiIPEwQQ-1 :-)
