### ISSUE TITLE
envoyer des notifs quand une convention est annulée

### ISSUE THREAD

**Issue by bbohec** [gip-inclusion/immersion-facile#364]

**Comment by bbohec** [comment]
Identifié par la CCI.

On envoie pas de mail quand on passe une convention validée à annulée.



![Image](https://github.com/gip-inclusion/immersion-facile/assets/58432308/36c43fcf-6e40-4947-b199-e1583bda08e7)

**Comment by JeromeBu** [comment]
Contenu du mail à définir

**Comment by nathalie-reyre** [comment]
Envoyer la notification à l'ensemble des parties. 
COntenu du mail à rédiger par mes soins le 29/06

**Comment by nathalie-reyre** [comment]
Contenu : 


Identifiant de la convention : CONVENTION_ID

Bonjour ,

Nous vous informons que la demande de convention d'immersion professionnelle de BENEFICIARY_FIRST_NAME BENEFICIARY_LAST_NAME dans l'entreprise BUSINESS_NAME a été annulée par AGENCY qui devait se dérouler le DATE_ IMMERSION.

Cette demande de convention était devenue obsolète car une autre demande a déjà été traitée.

Vous pouvez vous rapprocher de votre conseiller pour en échanger ou établir une nouvelle demande si nécessaire.

Bien cordialement,SIGNATURE 
@clement-duport
