### ISSUE TITLE
Créer la page de budget

### ISSUE THREAD

**Issue by enguerranws** [gip-inclusion/immersion-facile#390]

**Comment by nathalie-reyre** [comment]
corrections proposées 
Répartition des dépenses **prévues** pour la période d’avril à septembre (en milliers d'euros)

• Développeurs : 328,4
• Chargés de déploiement : 92,6
• Designers : 230,2
• Chargés de produit : 127,8.
• Frais (fonctionnement, communication…) : 15
• Total : 794,1

Essayer de mieux distinguer les frais de personnel et les frais de fonctionnement. 
Par ex ainsi
**Frais de personnel ** 
• Développeurs : 328,4
• Chargés de déploiement : 92,6
• Designers : 230,2
• Chargés de produit : 127,8.
**Frais de fonctionnement** 
•Coûts serveurs/solutions SAAS, frais de déplacement et communication :  15 

Corriger l'intitulé Chargés de produit par Chefs de produit et coach

Supprimer (en italique)
Évolution du budget depuis 2021
_Si vous rencontrez un défaut d’accessibilité vous empêchant d’accéder à un contenu ou une fonctionnalité du site, merci de nous en faire part. Si vous n’obtenez pas de réponse rapide de notre part, vous êtes en droit de faire parvenir vos doléances ou une demande de saisine au Défenseur des droits._ 

partie **Performance budgétaire**
Le budget s’apprécie au regard de la capacité de _la startup_ (à remplacer par l'équipe) à acquérir plus d’utilisateurs et d’usagers. Ajouter  **Plus leur nombre augmente, plus le coût d'acquisition (les efforts déployés pour les acquérir) baisse. C'est le ratio CAC (coût d'acquisition)/nombre d'utilisateurs.**


- Utilisateurs
Utilisateur : visiteur effectuant une action sur le site (recherche d’entreprise, mise en relation…)



- Usagers
Usager : candidat démarrant une demande d’immersion


Je suggère qu'on supprime entreprises et prescripteurs. Cela fait trop de schémas pas faciles à lire et encore moins à comprendre.

- Entreprises
Entreprise : entreprise accueillante inscrite sur le site Immersion Facilitée

- Prescripteurs
Prescripteur : structure prescrivant des Immersions sur le site Immersion Facilitée.
