### ISSUE TITLE
Blacklist LBB / Cacher les siret déjà chez nous

### ISSUE THREAD

**Issue by PierreDeNantes** [gip-inclusion/immersion-facile#401]
2 cas : 
- Impossible de désactiver une entreprise LBB qui veut rester sur LBB mais pas sur IF
- Quand on n'a pas d'offre, on montre tous les acteurs de LBB, qu'ils soient entreprise accueillante ou pas, ce qui s'oppose un peu au principe de la limite de nombre de MER/semaine (puisque ces acteurs continuent d'être contactés par tel via la recherche Google qu'on permet)

**Comment by JeromeBu** [comment]
Closing in favor of #404
