### ISSUE TITLE
Limiter l'enregistrement d'agences PE vis le formulaire prescripteur

### ISSUE THREAD

**Issue by PierreDeNantes** [gip-inclusion/immersion-facile#406]
![Image](https://user-images.githubusercontent.com/113897423/250608989-897eb785-7300-4cab-be77-386e50b62c1d.png)

**Comment by nathalie-reyre** [comment]
trouver une solution pour empêcher les équipes PE d'inscrire leur agence comme structure prescriptrice (inclure dans cette solution une mises à jour des agences enregistrées (cf API agences PE).

**Comment by nathalie-reyre** [comment]
créer une modale façon warning NON vous êtes une agence Pôle emploi. Votre agence est déjà référencée. Pas besoin de le refaire !!!!!!!!!!!

**Comment by 3lodi3** [comment]
Proposition : erreur sur le champ qui n'empêche pas le submit (comme sur le champ email de la demande convention) : https://www.figma.com/proto/NF2TPwDkR3iUbQvYeURWes/Prod---design-d'issues?page-id=62%3A167&type=design&node-id=62-170&viewport=840%2C1060%2C0.45&t=RZ38VrPaAJNDXzWw-1&scaling=min-zoom&starting-point-node-id=62%3A170&mode=design

**Comment by nathalie-reyre** [comment]
Ça me va très bien.
Est-ce qu'on peut en profiter pour ajouter un ^sur le o de Pôle emploi (place holder et message d'erreur) ?

**Comment by 3lodi3** [comment]
C'est fait sur le figma, en vrai il faudrait mettre une variable pour changer le nom par FT ^^
