### ISSUE TITLE
MER en doublon

### ISSUE THREAD

**Issue by PierreDeNantes** [gip-inclusion/immersion-facile#423]
Discussion : https://discord.com/channels/864451835553513474/1125491653168353384

Il semble que les utilisateurs envoient souvent (10% du temps) plus d'une demande de MER au même moment pour la même entreprise, sur le même métier.

On s'oriente vers un souci UX 
Pistes : 
- confirmation d'envoi à mettre plus gros ?
- Remettre la recherche à zero (sans resultat) une fois la demande envoyée ? mais dans ce cas, dur d'envoyer plusieurs demandes...

**Comment by JeromeBu** [comment]
Closing on favor of #426
