### ISSUE TITLE
Interdire les mises en contact multiple

### ISSUE THREAD

**Issue by JeromeBu** [gip-inclusion/immersion-facile#426]
Interdire les mises en contact multiple si elle existe déjà pour le même siret et code appellation dans les X jours précédents. Le nombre de jours est à préciser (il sera configurable si besoin de changer).

@PierreDeNantes si tu veux lié ton autre issue (que je n'ai pas trouvé)
@nathalie-reyre pour le nombre de jours

**Comment by JeromeBu** [comment]
Proposition d'UI :

<img width="688" alt="image" src="https://github.com/gip-inclusion/immersion-facile/assets/22095555/9b3928cd-04a5-4e70-8098-224cea0fa185">

**Comment by nathalie-reyre** [comment]
Wording : Vous avez déjà contacté cette entreprise. Elle a bien reçu votre demande. Il n'est pas nécessaire de la contacter de nouveau.

**Comment by nathalie-reyre** [comment]
Pour moi, le nombre de jours de blocage est de 7 (une semaine). Permettre une relance une semaine après me semble correct.

**Comment by nathalie-reyre** [comment]
**Confirmation de mise en relation effectuée à mettre en plus gros.**
 A l'heure actuelle, la confirmation est en message en vert qui parait en bas à gauche, en mode subliminal. L'aficher par ex dans une modale : Votre message a bien été transmis à l'entreprise. (pour les mises en relation par mail).
Pour les mises en relation in person ou by tel, "les coordonnées de l'entreprise vous ont été transmises par mail. SI vous ne les avez pas reçues, vérifiez vos spams."

**Comment by JeromeBu** [comment]
J'ai créer une issue dédiée à ta dernière demande @nathalie-reyre 

(au passage je viens de découvrir une super fonctionnalité de gitub :

<img width="1045" alt="image" src="https://github.com/gip-inclusion/immersion-facile/assets/22095555/e271ac76-6e38-4d0c-b2d9-ff00d3a510cd">
)

**Comment by JeromeBu** [comment]
J'ai créer une issue dédiée à ta dernière demande @nathalie-reyre 

(au passage je viens de découvrir une super fonctionnalité de gitub :

<img width="1045" alt="image" src="https://github.com/gip-inclusion/immersion-facile/assets/22095555/e271ac76-6e38-4d0c-b2d9-ff00d3a510cd">
)

**Comment by celineung** [comment]
> Wording contact par mail : Vous avez déjà contacté cette entreprise. Elle a bien reçu votre demande. Il n'est pas nécessaire de la contacter de nouveau.
> 
> Wording contact par tel ou in person : Nous vous avons transmis par mail les coordonnées de cette entreprise. Vérifiez vos spams si vous ne les avez pas reçues. Si vous ne trouvez rien dans vos spams, contactez-nous pour que nous vous les renvoyons.

@nathalie-reyre 
Pour les messages: Est-ce que l'on voudrait leur suggérer d'attendre quelques jours avant de contacter à nouveau l'entreprise ?
