### ISSUE TITLE
ETQ utilisateur, le circuit de modification de la demande de convention est simple et compréhensible. Je peux faire moi-même la modification ou demander à l'une des parties prenantes de la faire

### ISSUE THREAD

**Issue by nathalie-reyre** [gip-inclusion/immersion-facile#435]
le circuit de modification est encore imparfait. 
Certains ne comprennent pas ce qu'ils ont à faire, d'autres voudraient le faire faire par une autre partie prenante.
1/ reprendre les wordings des mails 
2/ ajouter un schéma explicatif (ou mode d'emploi) en visibilité du bouton de modification
3/ permettre de choisir qui aura la main pour faire la modification

Suite au point du 26 juillet matin :
-> On priorise la demande de modification à un tiers (avec possibilité de s'envoyer la demande)
-> On ne crée par de nouveau statut lors de la modification et on repasse en DRAFT, comme actuellement
-> On verra par la suite si on fait évoluer la feature

Figma avec parcours revu + wordings emails : https://www.figma.com/proto/O6MfTEZ1Ms8cKQHFjOYEA5/Site---UX-design?page-id=3%3A20019&type=design&node-id=1132-62273&viewport=624%2C-1475%2C0.03&t=f4EXcpqazBiDFnzD-8&scaling=min-zoom&starting-point-node-id=1132%3A62273&hide-ui=1

En profiter pour revoir le parcours de signature en introduisant une modale et dans la modale, bien indiquer qu'il s'agit d'une signature électronique cf maquette figma

**Comment by nathalie-reyre** [comment]
Proposition de modification du mail envoyé une fois la modif réalisée (les modifs sont en grs)
Bonjour SIGNATORY_FIRST_NAME SIGNATORY_LAST_NAME,

La demande de convention pour l'immersion
de BENEFICIARY_FIRST_NAME BENEFICIARY_LAST_NAME au sein de BUSINESS_NAME vient d'être modifiée.

Les raisons sont :
REASON

Votre signature ~~sur la première demande de convention~~ a ~~donc~~ été annulée.

**Que devez-vous faire ? **

Action attendue 
1/ Cliquez sur le bouton ci-dessous **pour** vérifier dans l’écran qui s’ouvre si ce qui a été modifié vous convient.
2/ Si **la modification vous convient,** confirmez votre accord **avec le bouton** “Valider la demande”.
3/ Si la modification ne vous convient pas, vous pouvez relancer des modifications **avec le bouton** “Annuler les signatures et recevoir un lien de modification”.

~~Relire et signer la demande de convention~~
Bonne journée,
L'équipe Immersion Facilitée

**Comment by cecile-dimarco** [comment]
Malgré la phrase de BENEFICIARY_FIRST_NAME BENEFICIARY_LAST_NAME au sein de BUSINESS_NAME vient d'être modifiée.
 
Les raisons sont : _"Peut-être tourner cette phrase en "ce qui a été modifié" ou autre tournure qui montre bien que la modif a déjà été faite_

**Comment by 3lodi3** [comment]
Proposition de parcours en séparant la modification par soi-même et l'envoi de demande de modification à un tiers.
À discuter. 
Parcours via emails : https://www.figma.com/proto/O6MfTEZ1Ms8cKQHFjOYEA5/Site---UX-design?page-id=3%3A20019&type=design&node-id=1073-60907&viewport=2041%2C-5025%2C0.13&t=atWUqKwcBbdEL159-1&scaling=min-zoom&starting-point-node-id=1073%3A60907&show-proto-sidebar=1&mode=design
Parcours en ligne : https://www.figma.com/proto/O6MfTEZ1Ms8cKQHFjOYEA5/Site---UX-design?page-id=3%3A20019&type=design&node-id=1037-59560&viewport=2771%2C-5607%2C0.22&t=UV5ZZ1dbD3ZT1MYr-1&scaling=min-zoom&starting-point-node-id=1037%3A59560&show-proto-sidebar=1&mode=design

**Comment by 3lodi3** [comment]
Suite au point de ce matin @nathalie-reyre @clement-duport , ajout du détail dans le select du destinataire de la demande de modification :

- Si non PE connecté, on propose tous les signataires, avec 1 ligne par adresse mail liée à l'agence.
- Si PE connecté, on propose tous les signataires côté bénéficiaire et entreprise, mais seulement 1 ligne côté prescripteur avec l'adresse du conseiller PE lié au bénéficiaire.
- On masque une partie des adresses email pour éviter un contact en direct, mais en laissant assez de caractère pour les différencer (exemple 2 conseillers qui partagent les mêmes initiales, il faut pouvoir les différencier).

Proto :
