### ISSUE TITLE
**Confirmation de mise en relation effectuée à mettre en plus gros.**

### ISSUE THREAD

**Issue by JeromeBu** [gip-inclusion/immersion-facile#436]
**Confirmation de mise en relation effectuée à mettre en plus gros.**
 A l'heure actuelle, la confirmation est en message en vert qui parait en bas à gauche, en mode subliminal. L'afficher par ex dans une modale : Votre message a bien été transmis à l'entreprise. (pour les mises en relation par mail).
Pour les mises en relation in person ou by tel, "les coordonnées de l'entreprise vous ont été transmises par mail. SI vous ne les avez pas reçues, vérifiez vos spams."

_Originally posted by @nathalie-reyre in https://github.com/gip-inclusion/immersion-facile/issues/426#issuecomment-1625477669_

**Comment by JeromeBu** [comment]
@3lodi3  pour suivi

**Comment by 3lodi3** [comment]
Proposition à discuter : https://www.figma.com/proto/O6MfTEZ1Ms8cKQHFjOYEA5/Site---UX-design?page-id=882%3A59425&type=design&node-id=882-59450&viewport=753%2C868%2C0.3&t=nUYmfSDNqnjaGvte-8&scaling=min-zoom&starting-point-node-id=882%3A59450&hide-ui=1

**Comment by enguerranws** [comment]
Lié à #559
