### ISSUE TITLE
ETQ bénéficiaire, je suis informé clairement que la demande d'aide à la mobilité pour faire des immersions est sous condition de ressources

### ISSUE THREAD

**Issue by nathalie-reyre** [gip-inclusion/immersion-facile#445]
![Image](https://github.com/gip-inclusion/immersion-facile/assets/61510442/503625fb-bd1d-4056-9447-a5161ad1d2a3)

**Comment by nathalie-reyre** [comment]
à indiquer soit dans le place holder, soit sous l'intitulé du champ. Les aides sont soumises à des conditions de ressources. Renseignez-vous auprès de votre conseiller.

**Comment by JeromeBu** [comment]
Message du sous titre :

`Le bénéficiaire a-t-il besoin d'une aide matérielle pour réaliser l'immersion ? Les aides sont soumises à des conditions de ressources. Renseignez-vous auprès de votre conseiller.`
