### ISSUE TITLE
Pouvoir ajouter des pièces jointes dans les échanges d'emails entre candidats et entreprises (ex : cv)

### ISSUE THREAD

**Issue by 3lodi3** [gip-inclusion/immersion-facile#449]
- [ ] Combien de temps sont stockées les pj, 
- [ ] Quels sont les formats/poids max autorisés,
- [ ] Est-ce qu'on peut les préciser aux utilisateurs ?

**Comment by bbohec** [comment]
@3lodi3 on a déjà merge le travail pour supporter les PJ dans les mails et par rapport à tes questions:
- Le temps de stockage des PJ est pour le moment infini >>> prévoir une feature de nettoyage programmée
- Pour le poids on doit surement suivre les normes email à date 20MB de tète donc pas sûr qu'on ait à prévenir les utilisateurs car en cas de PJ trop grosse, le mail ne partira pas ou bien il aura un accusé d'erreur d'envoi

Dans les deux cas faudra surement ajouter les besoin en + sous forme de carte dans le backlog sinon on va oublier.

@nathalie-reyre & @Hervelallemand974
