### ISSUE TITLE
ENTQ candidat ou entreprise, je ne peux plus signer une demande qui a été rendue obsolète.

### ISSUE THREAD

**Issue by nathalie-reyre** [gip-inclusion/immersion-facile#482]
Actuellement,je peux toujours ouvrir ma page de signature de demande alors qu'une demande a été rendue obsolète. Mais quand je soumets ma signature, le message d'erreur n'est pas explicite et donne l'impression d'un bug.
Il faut soit bloquer l'opuverture de la page avec un message ad hoc, soit (plus simplement) indiquer que l'action est impossible quand on soumet la signature.
Message proposé : cette demande de convention a été annulée. Il n'est plus possible de la signer.

**Comment by clement-duport** [comment]
@nathalie-reyre est ce que tu veut qu'on affiche les raison de l'annulation dans le message d'erreur ou alors on les prévient juste qu'ils ont reçus un mail avec les raisons de l'annulation ?

**Comment by nathalie-reyre** [comment]
@clement-duport si on peut afficher la raison dans le message d'erreur, c'est le mieux ! Merci

**Comment by clement-duport** [comment]
@nathalie-reyre  ok parfait du coup ça donne ça : 

![Image](https://github.com/gip-inclusion/immersion-facile/assets/104081060/2210f56f-a8d4-4139-8021-0b30062f4149)
