### ISSUE TITLE
ENT bénéficiaire ou entreprise, j'ai accès facilement aux conditions réglementaires de l'immersion. Depuis la demande de convention quand je dois la confirmer et depuis la page candidat et la page entreprise (hébergement sur le helpdesk).

### ISSUE THREAD

**Issue by nathalie-reyre** [gip-inclusion/immersion-facile#494]
les conditions réglementaires sont ici : https://aide.immersion-facile.beta.gouv.fr/fr/article/quelles-sont-les-obligations-a-respecter-pour-une-immersion-1bl944v/?bust=1690274462053

A n'afficher que pour les immersions et pas pour les mini stages

**Comment by nathalie-reyre** [comment]
à ajouter sur le formulaire de demande de convention sous forme de lien dans le cartouche "étape 4/5" et/ou "cartouche 5/5"
Wording : Consulter les conditions réglementaires applicables aux immersions
A ajouter à la page de signature de la demande de convention lien à activer dans la phrase **Je, soussigné Elo Tuteur (représentant de la structure d'accueil) m'engage à avoir pris connaissance des dispositions réglementaires de la PMSMP et à les respecter *"**
Confirmer et signer
Annuler les signatures et recevoir un lien de modification

**Comment by 3lodi3** [comment]
Parcours de signature avec 2 validations successives dans la page de signature puis la modale (du coup plus besoin de coche je pense, car on doit valider 2 boutons). 
On peut mettre un scroll dans la modale donc je suggère plutôt de mettre les conditions dedans plutôt qu'un lien qui les ferait sortir du parcours de signature : https://www.figma.com/proto/NF2TPwDkR3iUbQvYeURWes/Prod---design-d'issues?page-id=46%3A923&type=design&node-id=46-2641&viewport=277%2C454%2C0.15&t=D3fEwn1cskRTwuEL-1&scaling=min-zoom&mode=design

**Comment by 3lodi3** [comment]
@clement-duport j'ai ajouté l'erreur si tu ne cliques pas sur "Je termine la signature dans la modale". Désolée je l'avais fait dans la demande de modif et pensais l'avoir fait dans la signature aussi-> https://www.figma.com/file/NF2TPwDkR3iUbQvYeURWes/Prod---design-d'issues?type=design&node-id=46%3A2641&mode=design&t=hTs2g8H1XiIPEwQQ-1
