### ISSUE TITLE
Avoir la convention imprimable (PDF) directement depuis le tableau de bord pilotage inclusion connect

### ISSUE THREAD

**Issue by Jessicaceleste1** [gip-inclusion/immersion-facile#501]

**Comment by bbohec** [comment]
![Image](https://github.com/gip-inclusion/immersion-facile/assets/58432308/2e6f4524-4c28-48d3-a7bd-6a5686d3e8f7)

**Comment by SlimanCA** [comment]
Je sur-valide ! ca nous aiderait bcp...
