### ISSUE TITLE
convention avec horaires irréguliers / dupliquer les horaires

### ISSUE THREAD

**Issue by SlimanCA** [gip-inclusion/immersion-facile#524]
Exemple d'une convention de 15 jours ou les horaires de la première semaine sont 9h 12h 14h 17h et la deuxième semaine 8h 11h30 12h30 16h30, dans ce cas il faut choisir horaires irréguliers. J'aimerais inclure un bouton " dupliquer les horaires" d'un jour à l'autre pour gagner du temps dans la saisie des horaires jour par jour. J'ai eu quelques demandes d'évolutions à ce sujet. Mercii

**Comment by 3lodi3** [comment]
https://www.notion.so/gip-inclusion/Tests-utilisateurs-septembre-2023-ca26b396e6534567920c85d74ae93a5e?pvs=4
