### ISSUE TITLE
ETQ utilisateur, je peux renouveler une fois une convention validée

### ISSUE THREAD

**Issue by nathalie-reyre** [gip-inclusion/immersion-facile#536]
Avec l'ID d'une convention validée, je peux avoir accès à une feature de renouvellement.
Cette feature permet de dupliquer la convention validée et de ne rendre éditable que les dates de l'immersion.
Le circuit de signature est le même que pour une convention initiale. Par contre, seules les dates restent modifiables si demande de modification.
Un nouvel ID de convention est créé/ Il est lié à l'ID de la première convention. 
Pour chaque couple ID renouvellement et ID convention, il est ensuite impossible de faire un renouvellement nécessaire.
La convention précise qu'il s'agit d'un renouvellement et indique l'ID de la convention initiale en plus de l'ID de la convention de renouvellement.
Le bilan se fera à l'identique pour cette immersion renouvelée.

Raison de création de cette feature : nécessaire pour publication de l'arrêté officialisant le recours à IF
A terme, permettra d'établir une typologie des immersions renouvelées et d'en comprendre les raisons

**Comment by clement-duport** [comment]
atelier à programmer

**Comment by 3lodi3** [comment]
Attention, les conditions de renouvellement vont générer de la complexité de développement :

**Durée initiale**

La durée de chaque PMSMP est d'1 mois maximum (de date à date).

Votre présence au sein de la structure d'accueil peut être continue ou discontinue.

Vous pouvez effectuer plusieurs PMSMP auprès du même employeur.

Cependant, au cours d'une période de 12 mois consécutifs, vous pouvez conclure maximum 2 conventions de mise en situation en milieu professionnel dans la même structure d'accueil.

Pour cela, ces conventions doivent :

    Comporter des objets ou des objectifs différents
    Avoir une durée totale maximale de 60 jours sur cette période de 12 mois.

À savoir  

La durée cumulée de l'ensemble de ces PMSMP effectuées par un salarié en [contrat unique d'insertion](https://www.service-public.fr/particuliers/vosdroits/F21006) ou accompagné par une structure de l'[insertion par l'activité économique](https://www.service-public.fr/particuliers/vosdroits/F2284) doit être égale au maximum à 25 % de la durée totale du contrat.

**Renouvellement**

Lorsque le ou les objectifs de la PMSMP n'ont pas été atteints, la convention peut être renouvelée une fois.

Ce renouvellement a :

    Objet identique et objectifs identiques que ceux initialement fixés
    Durée maximale d'1 mois.

 https://www.service-public.fr/particuliers/vosdroits/F14102

**Comment by 3lodi3** [comment]
A groomer jeudi 24 août 

Proposition : modifier les emails suivants -> https://www.figma.com/file/s43XSEkyYPaeGs2sxp62iq/Site---UX-design-2nd-semestre-2023?type=design&node-id=1516%3A6912&mode=design&t=C8AJU2tuYcAcUn9h-1

Pour les contraintes liées au renouvellement :
- Lorsque le ou les objectifs de la PMSMP n'ont pas été atteints, la convention peut être renouvelée une fois.
- Objet identique et objectifs identiques que ceux initialement fixés
- Durée maximale d'1 mois.

Voir comment on le fait ? 
- Tous les champs grisés à l'exception des dates et horaires ?
- Accès seulement au module dates et horaires (déjà limité à 1 mois ?) ?
- Est-ce que l'on demande une justification concernant l'objectif fixé initialement et qui n'est pas censé être atteint si on fait un renouvellement ?
- Est-ce qu'on crée un nouveau statut "convention renouvelée" pour limiter le nb de renouvellement à 1 ?
- Est-ce que la convention renouvelée a un nouvel ID ?

**Comment by enguerranws** [comment]
Dans un premier temps : 
- on peut renouveler une convention 1 fois
- la convention doit être renouvelée à l'identique, mise à part : les dates / heures

Quid du mini-stage ?

Côté UX, l'initialisation d'une demande de renouvellement est à faire (dans un premier temps) par le conseiller / validateur (bouton dans l'écran de gestion de convention, qui enverra un mail de demande de renouvellement (cf. demande de modification)).

**Comment by celineung** [comment]
- date début > date fin
- durée max de la période initialement prévue, dans la durée max de 30 jours
- pas de mail de demande de renouvellement : le conseiller/validateur saisit directement les nouvelles dates/heures sur une convention déjà validée mais pas déjà renouvelée
- mails de signatures à envoyer suite à cette demande de renouvellement

**Comment by nathalie-reyre** [comment]
prévoir saisie du motif de renouvellement, comme c'est fait dans la demande de modification. Dans un 2e temps (si nécessaire car compliqué), prévoir d'indiquer ce motif dans la convention validée (page web). Titre explicite dans la convention : renouvellement de Convention relative à la mise en œuvre d’une période de mise en situation en milieu professionnel

**Comment by 3lodi3** [comment]
Suggestion txt email suite au point d'hier avec @nathalie-reyre :

Objet : 
**Pour action : immersion en entreprise prolongée, signez la nouvelle convention**

Corps :
**Identifiant de la nouvelle convention : CONVENTION_ID  

Bonjour SIGNATORY_FIRST_NAME SIGNATORY_LAST_NAME,

L'immersion de BENEFICIARY_FIRST_NAME BENEFICIARY_LAST_NAME au sein de BUSINESS_NAME vient d'être prolongée par CONSEILLER pour la raison suivante : REASON.

Une nouvelle convention a été créée pour la seconde période d'immersion. Toutes les parties doivent la signer.**

CTA :
**Signer la nouvelle demande de convention**

**Bonne journée,
L'équipe Immersion Facilitée**

**Comment by JeromeBu** [comment]
Pour le mail, c'est beaucoup plus simple pour nous si on peut reprendre le même mail que le mail habituel. 

On pourrait éventuellement ajouter une phrase dans le cas d'un renouvellement, mais rester sur le même template. 

Ca a pas mal d'implications sinon.... (car alors il faut créer un nouvel événement, et en gros le temps de dev va tripler...)

Voilà le mail original :



![Image](https://github.com/gip-inclusion/immersion-facile/assets/22095555/40ed53ce-6fbf-423c-bfff-1b76086a4903)
