### ISSUE TITLE
Autoriser le backoffice à modifier une entreprise en API

### ISSUE THREAD

**Issue by bbohec** [gip-inclusion/immersion-facile#556]

**Comment by nathalie-reyre** [comment]
Proposer à des entreprises dont on suppose qu'elles ont des métiers support de les inscrire en tant que métiers supplémentaires sur lesquels elles peuvent accueillir en immersion.
En back, s'appuyer sur l'API existante de modification des fiches entreprise
En front, création d'une vue metabase - retirer le mode read only et autoriser le back à faire des mofifs
historiser la modif (ajout des métiers)
