### ISSUE TITLE
Page de mise en contact dédiée pour un SIRET et une appelation avec query params

### ISSUE THREAD

**Issue by bbohec** [gip-inclusion/immersion-facile#559]
+ ajout des infos de l'entreprise sur la page dédiée

**Comment by 3lodi3** [comment]
Proposition avec cartes simplifiées façon DSFR (1 seul clic sur toute la carte) + pages entreprise avec formulaire de contact : 

Desktop :
https://www.figma.com/proto/s43XSEkyYPaeGs2sxp62iq/Site---UX-design-2nd-semestre-2023?page-id=1407%3A38729&type=design&node-id=1407-39824&viewport=-610%2C351%2C0.22&t=P6HJAfiD80yin9yQ-1&scaling=min-zoom&starting-point-node-id=1407%3A38751&mode=design

https://www.figma.com/file/s43XSEkyYPaeGs2sxp62iq/Site---UX-design-2nd-semestre-2023?type=design&node-id=1407%3A38729&mode=design&t=yI4630BxE4pxfnRh-1

Easy Success & Phoenix cliquable pour exemples page entreprise IF, Adjuvoo pour exemple entreprise LBB

Mobile :
https://www.figma.com/proto/s43XSEkyYPaeGs2sxp62iq/Site---UX-design-2nd-semestre-2023?page-id=961%3A59584&type=design&node-id=1347-80894&viewport=-4705%2C363%2C0.54&t=fHpMX5fYFDvL0Sce-1&scaling=scale-down&starting-point-node-id=1186%3A62349&mode=design

https://www.figma.com/file/s43XSEkyYPaeGs2sxp62iq/Site---UX-design-2nd-semestre-2023?type=design&node-id=961%3A59584&mode=design&t=yI4630BxE4pxfnRh-1

Easy success cliquable pour l'exemple de page entreprise IF

Par rapport à nos discussions d'hier :
- je n'ai pas ajouté la distance de la position car cela donne l'impression que le classement par défaut est par proximité, or on veut plutôt un classement par pertinence (on pourrait envisage d'afficher/masquer des infos pertinentes sur les cartes selon l'odre de tri).
- J'ai plutôt ajouté une ancre qu'un accordéon dans la page entreprise car cela rend la page plus fluide et met en avant l'action principale sous forme de CTA.
