### ISSUE TITLE
Feature flag pour déactiver les v0 et v1

### ISSUE THREAD

**Issue by bbohec** [gip-inclusion/immersion-facile#567]

**Comment by JeromeBu** [comment]
on peut envisager de mettre un feature flag pour déactiver les v0 et v1.

Ca permettra de réactiver si jamais des partenaires ne sont pas prêts

**Comment by JeromeBu** [comment]
On peut renvoyer 426 https://developer.mozilla.org/fr/docs/Web/HTTP/Status/426
si on essaye d'utiliser les vielles versions.
