### ISSUE TITLE
ETQ entreprise, je suis incité à accueillir des PSH

### ISSUE THREAD

**Issue by nathalie-reyre** [gip-inclusion/immersion-facile#568]
Modifier le wording du formulaire de référencement des entreprises et du label présent sur la fiche entreprise

l'existant : 
_Mon entreprise accueille en priorité des personnes en situation de handicap

Oui_

_Non_

A MODIFIER : Mon entreprise est prêt à accueillir des personnes en situation de handicap

wording du label 
L'existant 
_PRIORITÉ AUX PERSONNES EN SITUATION DE HANDICAP_

A modifier par : Personnes en situation de handicap bienvenues

**Comment by bbohec** [comment]
PSH???? @nathalie-reyre
