### ISSUE TITLE
API Convention : autoriser l'accès aux conventions selon le consumer

### ISSUE THREAD

**Issue by nathalie-reyre** [gip-inclusion/immersion-facile#607]
préparer l'API pour autoriser l'accès aux conventions par type de prescripteur et agence
webhook pour les mises à jour

Exemples : 
- IMILO = toutes les conventions validées par les missions locales
- Dep. Cantal = toutes les conventions validées par le Conseil départemental du Cantal

Points d'entrée API :
- récupérer une convention en particulier (par ID)
- lister les conventions

Webhook de MAJ : quand une convention est mise à jour côté partenaire, possibilité de taper un webhook chez nous pour mettre à jour la convention

**Comment by nathalie-reyre** [comment]
> No description provided

**Comment by JeromeBu** [comment]
À faire :
- route pour récupérer une convention par id #617 
- route pour récupérer des conventions avec filtres #618 
- webhook #619
