### ISSUE TITLE
Page groupe et page secteur d'actitivité (+ géo) (pour mise en ligne début nov - semaine de l'agroalimentaire)

### ISSUE THREAD

**Issue by enguerranws** [gip-inclusion/immersion-facile#608]
Prévoir un atelier dev dans un premier temps.

Exemples de secteurs : 
- industrie agro-alimentaire
- restauration en Rhône Alpes
- etc.

Nécessité, par ex, de créer un contenu édito (description, etc.)

**Comment by enguerranws** [comment]
- nouvelle colonne à prévoir dans la table establishment_groups : options (JSONB)

**Comment by JeromeBu** [comment]
Et le contenu des options aura la forme suivante :

```ts
type GroupHeroHeader = {
  title: string;
  description: string;
  logoUrl: string;
  backgroundColor?: string;
};

type GroupOptions = {
  heroHeader: GroupHeroHeader;
  tintColor: string;
};
```

**Comment by JeromeBu** [comment]
Piste en cours : utiliser le site du GIP pour créer des pages à la demande.

TODO: comment afficher ces pages sur IF ?

**Comment by 3lodi3** [comment]
On fait des pages auto par NAF / SIRET ?
