### ISSUE TITLE
ETQ admin, je peux refuser le rattachement à un espace de pilotage d'un utilisateur inclusion connecté

### ISSUE THREAD

**Issue by nathalie-reyre** [gip-inclusion/immersion-facile#616]
Aujourd'hui, pour refuser le rattachement d'un utilisateur à un BO agence, nous devons aller en base et supprimer l'utilisateur manuellement (tables ongoing_oath et authenticated_users. 
Un bouton refuser depuis le bo nous permettrait de le faire plus rapidement, d'avoir une traçabilité et d'envoyer un mail à l'utilisateur pour l'informer.
ajouter un statut refusé

**Comment by JeromeBu** [comment]
Statut -> pas la peine, on va carrément virer les lignes

Il faut sans doute un input pour message qui sera transmis dans le mail (la justification du refus)

On a besoin du contenu du mail à envoyer pour signaler le refus.

**Comment by JeromeBu** [comment]
a faire également :

- [ ] Rédiger le mail de refus

**Comment by nathalie-reyre** [comment]
Contenu du mail de refus 

Bonjour, 

Votre demande d'accès au tableau de bord des conventions d'immersion a été refusée par l'administrateur d'Immersion Facilitée car il n'a pas été possible de vérifier que vous travaillez bien au sein de la structure accompagnatrice ou prescriptrice choisie.

Bien cordialement, 
l'équipe d'Immersion Facilitée

**Comment by clement-duport** [comment]
@nathalie-reyre  

J'ai modifié le mail car il ne prenais pas en compte la justification du rejet et le nom de l'agence, du coup ça donne ça :  

![Image](https://github.com/gip-inclusion/immersion-facile/assets/104081060/a075cfc6-7670-4cb3-b01b-29f0f6d90c1e)

c'est ok pour toi ?

**Comment by nathalie-reyre** [comment]
votre demande d'accès au tableau de bord a été rejetée
