### ISSUE TITLE
Mise en visibilité  dans la convention de la pré validation faite par une structure accompagnante

### ISSUE THREAD

**Issue by nathalie-reyre** [gip-inclusion/immersion-facile#638]
### Use case :
Dans le cadre de l'établissement d'une convention :
- convention avec un prescripteur qui a le droit de prescrire
- convention avec une structure qui fait de l'accompagnement de personnes mais qui n'a pas le droit de prescrire des immersions

Ex : PE prescripteur mais il y a une autre structure qui accompagne le bénéficiaire. Cette structure a son mot à dire sur la convention -> conforme à ce qui était convenu entre la structure et le bénéficiaire.

On le fait actuellement quand on a une validation en deux étapes (utilisation détournée).
Mais dans le décret qui encadre la PMSMP il faut que la structure accompagnante apparaisse dans la convention.

Il faut afficher clairement le rôle de la structure accompagnante dans la convention.

Ça veut dire qu'il y a un nouveau rôle qui apparaît : structure accompagnatrice sans être prescriptrice.

> Quels sont les rôles respectifs du prescripteur de la PMSMP et de la structure d’accompagnement ? Ces rôles sont précisés à l’article D. 5135-6 du code du travail :
• le prescripteur s’assure de la pertinence de la PMSMP, établit le projet de convention Cerfa et le présente à la signature des autres parties ;
• la structure d’accompagnement assure la mise en œuvre de la PMSMP et en réalise le bilan et l’évaluation.
De manière générale, la prescription et l’accompagnement sont réalisés par la même structure. Toutefois, il est possible au prescripteur de sous-traiter, à toute structure de son choix et sous sa seule responsabilité, la mise en œuvre, le suivi et l’évaluation de la PMSMP.
[Source : Questions/Réponses sur les PMSMP (Périodes de mise en situation en milieu professionnel) - DGEFP - n°2 du 25 juin 2015](https://travail-emploi.gouv.fr/IMG/pdf/q-r_pmsmp_n4_15122016.pdf)

### Impacts :
- Formulaire "Ajout d'organisme encadrant les PMSMP" (choix entre prescripteur ou structure d'accompagnement).
- La structure d'accompagnement ET le prescripteur final doivent apparaître sur le parcours de signature (page pilotage etc.).
- La structure d'accompagnement doit apparaître sur la convention finale.
- Dans le select de prescripteurs, ne pas faire apparaître les structures d'accompagnement.

### Formulaire "Ajout d'organisme encadrant les PMSMP"

https://www.figma.com/proto/s43XSEkyYPaeGs2sxp62iq/Site---UX-design-2nd-semestre-2023?page-id=2208%3A110&type=design&node-id=2208-112&viewport=399%2C236%2C0.25&t=by5xEaHWqXKUmOpb-1&scaling=min-zoom&starting-point-node-id=2208%3A112&mode=design

- Choix entre prescripteur et structure d'accompagnement
- Modifications de wordings (en rouge) pour éviter la confusion prescripteur / structure d'accompagement

### Parcours de signature :
https://www.figma.com/proto/NF2TPwDkR3iUbQvYeURWes/Prod---design-d'issues?page-id=7%3A810&type=design&node-id=7-1055&viewport=-158%2C158%2C0.07&t=sTqWufYOS5pIoZOO-1&scaling=min-zoom&starting-point-node-id=7%3A1055&mode=design

- On garde le parcours de validation en deux étapes en ajoutant la structure d'accompagnement (en rouge).

### Convention finale :
Faire apparaître dans les parties :
- "le prescripteur" + nom + adresse
- "la structure d'accompagnement" + nom + adresse

Faire apparaître dans les signataires :
- "Le prescripteur" + nom agence  + nom du conseiller (opt)
- "La structure d'accompagnement" + nom de la structure + nom du conseiller (opt)

### Questions en suspens :
- La structure d'accompagnement est classée dans le type "autre" ? (est-ce que ça suffit notamment pour pouvoir les sortir du select prescripteurs, envoyer le bon bilan, préciser la distinction entre le prescripteur / la structure d'accompagnement dans la convention finale, ou bien il faut créer un nouveau type) ?
- C'est la structure d'accompagnement qui est censée gérer le bilan, du coup comment fait-on pour envoyer le bilan de la structure d'accompagnement et pas celui du prescripteur lié ?
- Est-ce qu'on a besoin d'un logo + signature pour les structures d'accompagnement ? Ou bien c'est le prescripteur lié qui prend la parole ?

**Comment by nathalie-reyre** [comment]
Transmettre aux devs liste des structures existantes en mode 'accompagnement" avec ID de la structure et ID du prescripteur

**Comment by JeromeBu** [comment]
À faire en 2 fois :

1. Faire le lien dans la DB, et gérer les affichages quand le prescipteur lié existe
2. Mettre à jour le formulaire d'ajout d'agence ainsi que le selecteur dans la page convention

**Comment by enguerranws** [comment]
- [ ] Vider le refersToAgencyId si on repasse en mode prescripteur
- [ ] revoir le sélecteur de nombre d'étapes de validation
- [ ] une agence accompagnante est-elle sensé avoir des validateurs ou seulement des conseillers ?
- [ ] formulaire de convention : useEffect sur le agencyDepartment pour gérer l'appel à la agency gateway dans le cas d'un partage d'URL

**Comment by JeromeBu** [comment]
pour répondre à la question :

> * [ ]  une agence accompagnante est-elle sensé avoir des validateurs ou seulement des conseillers ?

Elle n'est sensé avoir des conseillers obligatoirement. Des valideurs aussi, mais elle n'a pas le choix de ces valideurs, ce sont ceux de la structure prescriptrice. 
On peut au choix : 
- cacher le champs valideurs
- faire apparaitre le champs valideurs en ready only
