### ISSUE TITLE
A/B test : Recherche métier par mots-clés avec l'API Diagoriente VS Recherche actuelle

### ISSUE THREAD

**Issue by 3lodi3** [gip-inclusion/immersion-facile#666]
### :construction: Epic

#1137 

### :thinking: Contexte et problématique

La recherche métier sur le code ROME n'est pas intuitive pour les candidats, nous sohaitons tester la recherche métier basée sur l'API Diagoriente.
https://www.notion.so/gip-inclusion/Am-lioration-de-la-recherche-de-terrains-d-immersion-a93934d8649445b19809fc0d2a58b9d6?pvs=4#ced62efcb8f74d73abf522eb6cd64956

API Diagoriente
https://recherche-referentiel.prod.analytics.diagotech.dev/docs#/search%20oplc/get_search_oplc_search_oplc__item_type__get

https://recherche-referentiel.prod.analytics.diagotech.dev/docs#/search%20oplc/get_search_oplc_search_oplc__item_type__get

### :tada: Proposition de solution

A/B testing entre deux versions de la recherche, identiques en terme d'UI mais différentes en terme de résults lorsqu'on recherche un métier.

**Pré-requis :** 

- [x] Construire un funnel (ou deux ?) entre l'entrée sur la recherche et l'envoi d'une demande de contact à une entreprise, pour mesurer quelle version de la recherche performe le mieux.

En effet, le taux de conversion du formulaire de recherche actuel est très bon (94%) et ce n'est pas cet indicateur qui pèche.
- Funnel 1 : du champ métier au champ no1 "contacter l'entreprise" 
- Funnel 2 : du champ métier au champ no "envoyer" 

- [ ] Donner un ID au formulaire de recherche diagoriente pour tracker finement les champs dans le module forms matomo
- [ ] Ajouter le code A/B test au site

**Objectif à améliorer :** 
Funnel MER contact submitted A/B test
Prise de contact avec une entreprise (submit du form contact)

1ère version (50%) : recherche actuelle : https://immersion-facile.beta.gouv.fr/recherche

2è version (50%) : recherche basée sur l'API Diagoriente : 

**Le test s'arrête lorsque :** 
- Il y eu minimum de 10.000 visites sur chacune des variantes
ET
- Il y a une différence significative de conversion sur le form de prise de contact entre les deux versions (à déterminer ensemble)

**Comment by bbohec** [comment]
API Diagoriente
https://recherche-referentiel.prod.analytics.diagotech.dev/docs#/search%20oplc/get_search_oplc_search_oplc__item_type__get

**Comment by nathalie-reyre** [comment]
https://recherche-referentiel.prod.analytics.diagotech.dev/docs#/search%20oplc/get_search_oplc_search_oplc__item_type__get

**Comment by bbohec** [comment]
- possibilité de fournir code OGR (attente du retour diag pour confirmation)
- selecteur de métier multiple à cocher
- mode recherche beta

**Comment by bbohec** [comment]
- API de feedback diag
- capacité à remonter un feedback directement par l'utilisateur
-

**Comment by JeromeBu** [comment]
Regex pour matcher la route /recherche sans matcher la route /recherche-diagoriente

```
immersion-facile\.beta\.gouv\.fr\/recherche($|\?.*)
```

**Comment by chaibax** [comment]
Hello, pourquoi ne pas utiliser ROMEO de FranceTravail , a base d'IA

https://francetravail.io/data/api/romeo-2

`ROMEO vous permet de rapprocher un texte libre à des savoirs / savoir-faire (/predictionCompetences) ou à des appellations métier (/predictionMetiers) du Répertoire Opérationnel des Métiers et des Emplois (ROME) de France Travail .`

Problème : 
- c'est ROMEV4
- de base, c'est un appel par seconde (mais on peut leur demander plus je pense)

**Comment by JeromeBu** [comment]
> Hello, pourquoi ne pas utiliser ROMEO de FranceTravail , a base d'IA
> 
> https://francetravail.io/data/api/romeo-2
> 

On a essayé ROMEO, avant de faire cette partie avec diagoriente. Mais le résultat n'était pas satisfaisant. C'était avec @enguerranws , je ne sais plus si on a fait une prise de note sur le sujet...

**Comment by nathalie-reyre** [comment]
c'est documenté sur Notion.

**Comment by enguerranws** [comment]
Implémenté côté Matomo (déclencheur + balise custom)
