### ISSUE TITLE
ETQ utilisateur, je peux voir le récap de ma demande de convention même une fois que je l'ai signée

### ISSUE THREAD

**Issue by nathalie-reyre** [gip-inclusion/immersion-facile#670]
donner accès à la vue de l'immersion depuis le lien magique qui permet d'avoir accès à son statut cf conventionStatusLink : [Lien vers la page](https://staging.immersion-facile.beta.gouv.fr/statut-convention?jwt=eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJ2ZXJzaW9uIjoxLCJhcHBsaWNhdGlvbklkIjoiMDg4Y2I0YmYtZTE2Ni00MjYwLWIyNmQtOTFkMjVhODU4YTk3Iiwicm9sZSI6ImJlbmVmaWNpYXJ5IiwiaWF0IjoxNjk1NjcxOTQ0LCJleHAiOjE2OTgzNTAzNDQsImVtYWlsSGFzaCI6IjNhNTFlY2QxZTZhODgyNTk1NzRjNzQ0ZmZhYmU2MTFmIn0.1K1gOS4iPFsbPIHpkA15QnPNqVtazQd9y4Au04aGZrQuFtoXkgqYPNloywJpI3rJI4wTpyRDe56TCtYLBKCcgQ)

**Comment by clement-duport** [comment]
@nathalie-reyre c'est plutôt dans le liens de signature que l'on veut que le récapitulatif apparaisse non ?
