### ISSUE TITLE
Gestion des conventions à saisir depuis le tableau de bord : prévoir de quoi cocher les conventions qu'ils régularisent dans leurs applicatifs

### ISSUE THREAD

**Issue by Jessicaceleste1** [gip-inclusion/immersion-facile#678]

**Comment by JeromeBu** [comment]
possibilité :

- voir pour une utilisation des actions metabase, pour marquer comme traité les erreurs
- ou on le fait avec une call api classique

**Comment by clement-duport** [comment]
en attente de  la réponse de métabase : https://github.com/metabase/metabase/issues/34395
