### ISSUE TITLE
Création de la page Boulanger avec création du groupe Boulanger (pour mise en ligne fin oct)

### ISSUE THREAD

**Issue by nathalie-reyre** [gip-inclusion/immersion-facile#680]
Rattacher tous les établissements Boulanger déjà existants à partir de la liste SIREN/SIRET fourni
Création du contenu édito sur le CMS + plus création page groupe pour afficher les terrains d'immersion proposés

**Comment by nathalie-reyre** [comment]
> No description provided

**Comment by 3lodi3** [comment]
@nathalie-reyre , est-ce que Hélène Verhille t'a envoyé du contenu pour la page CMS ? (présentation du groupe + présentation des principaux métiers pratiqués au sein du groupe)

Est-ce que je la relance par mail  ? (elle ne m'a pas répondu à celui envoyé le 21 sept)

**Comment by nathalie-reyre** [comment]
@3lodi3 ca y est, elle m'a répondu ce soir. Voici l'accès au doc https://docs.google.com/document/d/1StxDms1I1CN41D47sJqrE88W_hjy8i9unGpWEeEkKqY/edit?usp=sharing.  Ils finalisent les présentation des métiers demain

**Comment by 3lodi3** [comment]
Comment on rattache les entreprises du groupe Boulanger au groupement ?

- [ ] On demande aux entreprises de s'enregistrer sur IF
- [ ] On a une liste de SIRET
- [ ] Les devs rattachent à la main les SIRET concernés au groupement Boulanger

**Comment by nathalie-reyre** [comment]
Inscris-toi et décroche ton stage chez Boulanger ! 
Si tu as entre 16 et 25 ans 
Si tu es accompagné par l’un de nos 4 partenaires : Mission locale, Apprentis d'Auteuil, Ecole de la 2e Chance ou Epide)
Si tu es à la recherche de ton futur métier
Si tu souhaites découvrir les coulisses de Boulanger ?


Voici une occasion idéale de vivre une aventure inédite chez Boulanger !



BOULANGER en quelques chiffres c’est :
210 magasins partout en france que tu pourras peut-être intégrer
Plus de 150 métiers qui oeuvrent quotidiennement et que tu pourras découvrir
Près de 10 000 collaborateurs passionnés prêts à t’accueillir
69 ans d’expertise en électroménager et multimédia, un vrai plus sur notre expérience
Les immersions près de chez vous 
Choisis le magasin près de chez toi et découvre toutes les opportunités ! 🙂

Nos métiers en magasin

Conseiller.ère Service Client (hôte de caisse services clients)
En tant que conseiller service client, tu seras chargé de résoudre les demandes des clients. Ta mission ? Répondre à leurs questions, résoudre leurs problèmes techniques et les laisser avec un sourire de satisfaction. Ton expertise et ton empathie seront les clés pour créer des expériences client exceptionnelles.
Responsable Service Client (management relation clientèle)
En tant que responsable service client, tu seras le chef de la satisfaction client. Tu guideras ton équipe pour garantir un service de qualité supérieure. Ton rôle sera de superviser, d'inspirer et de t'assurer que chaque client se sente écouté et respecté.

Equipier.ère client (équipier logistique / magasinage)
En tant qu'équipier client, tu seras l'âme du magasin. Ton job ? Accueillir chaleureusement les clients, les conseiller sur les produits, et les aider à trouver exactement ce dont ils ont besoin. Ton attitude positive et ta disponibilité créeront un environnement convivial et accueillant.
Vendeur.se électromenager
En tant que vendeuse électroménager, tu deviendras une experte des cuisines et des appareils ménagers. Tu aideras les clients à choisir les équipements parfaits pour leur maison, en les guidant à travers les fonctionnalités et les avantages de chaque produit. 
Responsable Univers (chef de rayon)
En tant que responsable univers, tu auras la responsabilité de créer des espaces magiques dans le magasin. Tu sélectionnes et présentes les produits de manière attractive, tout en veillant à ce que chaque univers reflète les dernières tendances et les besoins des clients. Ton sens du style et ta créativité seront essentiels pour inspirer les acheteurs.


Animateur.trice commercial
En tant qu'animateur commercial, tu mettras de la vie dans le magasin. Tu organiseras des événements spéciaux, des démonstrations de produits et des activités interactives pour attirer les clients. Ton énergie et ton enthousiasme aideront à créer une ambiance dynamique et à renforcer les liens avec les clients.
Directeur de magasin
En tant que directeur de magasin, tu seras le capitaine du navire. Tu supervises toutes les opérations du magasin, t'assurant que chaque client reçoive un service exceptionnel. Tu seras également responsable du développement de ton équipe, de l'atteinte des objectifs de vente et de la satisfaction globale des clients.
Technicien conseil client
En tant que technicien conseil client, tu seras le roi des gadgets. Tu aideras les clients avec leurs problèmes techniques, que ce soit pour des réparations, des mises à jour ou des conseils d'utilisation. Ta passion pour la technologie et ta patience seront essentielles pour résoudre les défis techniques des clients.

Nos métiers de demain  
Tu recherches un métier de sens et impactant pour l’environnement, découvre les métiers d’avenir chez Boulanger ! 
Nous recherchons actuellement une centaine de techniciens SAV itinérants, en alternance et en CDI, partout en France !


Technicien.ne Itinérant.e Electroménager 

Grâce à ses interventions au domicile des clients, il répare les appareils électroménagers défectueux et permet ainsi de prolonger la durée de vie des appareils et ainsi satisfaire les clients rapidement et sans contrainte.


Livreur.se, installateur.trice 
Le livreur termine le processus de vente en assurant une livraison et une installation du produit directement au sein du foyer du client. C'est la touche finale de notre service !  En plus de garantir que le produit arrive en toute sécurité, tu t'assures qu'il est installé et prêt à être utilisé. C'est cette attention aux détails qui fait de Boulanger bien plus qu'un magasin - c'est une communauté où chaque geste compte. Prêt(e) à rendre chaque livraison inoubliable ? 🚚✨

**Comment by 3lodi3** [comment]
Voilà la version CMS :
https://inclusion.beta.gouv.fr/nos-services/immersion-facilitee/partenariat-boulanger-immersion-facilitee/

L'idée sera que le bouton dans le bandeau haut renvoie vers la page groupe Boulanger.

**Comment by enguerranws** [comment]
Lié à #608

**Comment by nathalie-reyre** [comment]
fichier avec les siret du groupe ici : https://docs.google.com/spreadsheets/d/11Gz2FzsZhx8n_oHDnLN6fmHWJhxkeYYMRMAUzrzBOuc/edit?usp=sharing

**Comment by nathalie-reyre** [comment]
> Voilà la version CMS @nathalie-reyre @JeromeBu : https://inclusion.beta.gouv.fr/nos-services/immersion-facilitee/partenariat-boulanger-immersion-facilitee/
> 
> L'idée sera que le bouton dans le bandeau haut renvoie vers la page groupe Boulanger.

on aurait 2 pages  ? Une sur le site de la plateforme et une chez nous ? Sur quelle url communique t on alors ?

**Comment by nathalie-reyre** [comment]
https://docs.google.com/spreadsheets/d/11Gz2FzsZhx8n_oHDnLN6fmHWJhxkeYYMRMAUzrzBOuc/edit?usp=sharing
fichier des siret Boulanger  -  le 27/10 on a 50 étabs référencés. A regrouper dans le groupe. Prévoir de faire une 2e passe fin de semaine prochaine car un appel va être fait auprès des autres étab du groupe
