### ISSUE TITLE
Investiguer la validation du formulaire de convention qui ne se fait pas lors du submit (dans le front)

### ISSUE THREAD

**Issue by JeromeBu** [gip-inclusion/immersion-facile#685]

**Comment by enguerranws** [comment]
J'ai jeté un oeil :
- avec le boulot fait sur le schedule, on reset la date de fin si l'intervalle fait plus de 30j, donc on ne voit plus passer l'erreur
- si on a plus d'heures que le nombre d'heures max autorisées, l'erreur remonte bien aussi
- sur les autres erreurs, on voit bien la validation qui se fait
- je vois rien de déconnant sur la staging

Je me suis juste permis 2 corrections cosmétiques, tant que j'étais dans le code : 
- une petite marge sous le message d'erreur en cas d'un nombre trop élevé d'heures / semaine
- le libellé de schedule quand on affiche les erreurs, changé par "Dates et heures de l'immersion (ou du stage)"
