### ISSUE TITLE
view_establishment remonte plus de lignes que la table establishment

### ISSUE THREAD

**Issue by lionelB** [gip-inclusion/immersion-facile#692]
Si on regarde le nombre de ligne de la table establishment on trouve 42905 vs 42998 pour la vue `view_establishment`
On devrait avoir le même nombre de ligne.

Piste : Un problème de jointure car on peut trouver plusieurs fois une même entreprise mais avec des infos de contact différentes. voici la [liste des doublons](https://metabase.immersion-facile.beta.gouv.fr/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjo0LCJxdWVyeSI6eyJzb3VyY2UtcXVlcnkiOnsic291cmNlLXRhYmxlIjoxMzYsImFnZ3JlZ2F0aW9uIjpbWyJjb3VudCJdXSwiYnJlYWtvdXQiOltbImZpZWxkIiwyNDI1LG51bGxdXX0sImZpbHRlciI6WyJhbmQiLFsiPiIsWyJmaWVsZCIsImNvdW50Iix7ImJhc2UtdHlwZSI6InR5cGUvSW50ZWdlciJ9XSwxXV19LCJ0eXBlIjoicXVlcnkifSwiZGlzcGxheSI6InRhYmxlIiwidmlzdWFsaXphdGlvbl9zZXR0aW5ncyI6e319)

**Comment by JeromeBu** [comment]
à vérifier mais je crois que : des conacts sont sauvegarder une deuxième fois lors des éditions, au lieu d'être mis à jour

**Comment by clement-duport** [comment]
problème probablement plus d'actualité tout les contact en doublon ont été ajoutés suite au double ajout d'établissements apparus entre 2021 et début 2022. 

Suggestion: Récupéré le contact le plus récent dans le payload d'évènement d'ajout d'agence, le comparé avec les doublon dans les contact et supprimé le plus ancien
