### ISSUE TITLE
Est-ce que c'est OK de diffuser les infos PE connect via la webhook

### ISSUE THREAD

**Issue by JeromeBu** [gip-inclusion/immersion-facile#698]
Est-ce qu'il faut garder les infos PE connect uniquement si la convention est lié à une agence PE ? ou bien on peut diffuser dans tous les cas (situation actuelle) ?

**Comment by nathalie-reyre** [comment]
A discuter avec Jess et Sliman pour voir le type d'info qu'on a pour un BRSA avec inscription PE et suivi département (par ex dans le 21)

**Comment by nathalie-reyre** [comment]
question : a t on souvent le cas d'une personne qui se PE connecte et qui choisit un autre prescripteur ?

**Comment by nathalie-reyre** [comment]
Aujourd'hui, décision humaine. 
Peut-on mettre en place un garde fou pour éviter la diffusion de données sensibles (ID DE par ex) ?
