### ISSUE TITLE
API Insee qui plante

### ISSUE THREAD

**Issue by JeromeBu** [gip-inclusion/immersion-facile#705]
Il semble qu'on a plus grand chose dans notre espace de l'insee. Or on utilise toujours l'insee pour aller chercher les établissements non diffusible. Il faut donc investiguer pour voir ce qui cloche....

Exemple de siret non diffusible : 80327462000043

**Comment by nathalie-reyre** [comment]
Question posée à l'instant via leur support

**Comment by nathalie-reyre** [comment]
Rep de l'INSEE @JeromeBu Bonjour,
Depuis le 21 mars 2023, le statut de diffusion non diffusible « N » a été remplacé par le statut de diffusion partiellement diffusible « P ». Les siren et siret concernés sont désormais accessibles par les mêmes services (GET/siren, GET/siret…) que les unités totalement diffusibles. De fait, les services GET/siren/nonDiffusibles et GET/siret/nonDiffusibles ne sont plus alimentés et renvoient un code 404 pour les unités en diffusion partielle comme en diffusion totale.
Vous pouvez donc retrouver les entreprises et établissements ayant demandé la non diffusibilité de leurs données en interrogeant l’API Sirene par les requêtes suivantes :
- Pour les unités légales, dans le service get/siren : q=statutDiffusionUniteLegale: P

- Pour les établissements, dans le service get/siret : q=statutDiffusionEtablissement : P

Cependant, certains champs de ces siren et siret demeurent non diffusibles et sont masqués lors des extractions par la valeur [ND].

Pour plus de détails, nous vous invitons à consulter la documentation des variables : https://sirene.fr/static-resources/htm/v_sommaire.htm#diffusionpartielle ainsi que la [Lettre Sirene open data actualités n° 14](https://www.insee.fr/fr/information/6683782) de décembre 2022.

 
La documentation des services est disponible sur ce lien : https://www.sirene.fr/static-resources/htm/sommaire.html


Cordialement,

Le service Diffusion Sirene et Offre API

**Comment by celineung** [comment]
Impact chez nous lors de la recherche des établissements:
![Image](https://github.com/gip-inclusion/immersion-facile/assets/11294487/ba3973b2-f37e-4c12-8ac5-a6ad77be3bb4)

Ce qu'il s'est passé du côté de l'api Insee:
- le statut de diffusion N n'existe plus (non diffusible) et est remplacé par P (partiellement diffusible)
- sur les établissements partiellement diffusible, les informations concernant l'identité de personnes physiques et les informations de localisation sont cachés par la valeur "[ND]"

**Comment by nathalie-reyre** [comment]
@JeromeBu Bonjour,

 

L’incident concernant la gestion des droits spéciaux dans l’API Sirene a été résolu par nos équipes techniques.

Les données des unités en diffusion partielle sont à nouveau accessibles pour les comptes ayant les droits correspondants.

Le renouvellement du token peut être nécessaire pour la réactivation des droits.

 
Merci de votre compréhension.


Cordialement,

 

Le service Diffusion Sirene et Offre API
