### ISSUE TITLE
Compteur du nb de conventions en erreur sur le tbd

### ISSUE THREAD

**Issue by Jessicaceleste1** [gip-inclusion/immersion-facile#710]
### :thinking: Contexte et problématique

Afin de faciliter la gestion des régularisation manuelles des conventions au sein du SI de pôle emploi qui doit maintenant être gérée par les régions, territoires ou agences, le fait d'avoir un compteur du nombre de conventions en erreur par rapport aux nombre de conventions réalisée sur IF, permettrait de piloter et d'instauré un suivi.

### :tada: Proposition de solution

Intégration du compteur lié aux filtres, ex convention des 7 derniers jours, 30 jours, mois ect... D'avoir également une courbe d'évolution de nombre de conventions en erreurs et ajouter un filtre par département, pour ceux qui sont attachés à toutes les agences d'une région, compliqué à piloter agence par agence

### :camera: Maquettes

 (la vous m'en demandé de trop lol)

**Comment by enguerranws** [comment]
@clement-duport On en est où sur cette demande ?
