### ISSUE TITLE
Sur le formulaire de demande de convention, lorsque la date de naissance détecte un mineur, il faut renseigner obligatoirement les coordonnées du représentant légal pour qu'il signe

### ISSUE THREAD

**Issue by 3lodi3** [gip-inclusion/immersion-facile#720]
Valable sur tous les formulaires (CCI et immersion)

Si via la date de naissance on détecte que le bénéficiaire est mineur à la date de début d'immersion -> l'utilisateur ne peut plus changer manuellement la réponse "Êtes-vous mineur ou majeur protégé ? *"

**Comment by JeromeBu** [comment]
L'intitulé de la question : "Êtes-vous mineur ou majeur protégé ? *" devient ""Êtes-vous majeur protégé ? *"
