### ISSUE TITLE
Faire en sorte que toutes conventions initialisées avec dates de fins dépassées depuis plus de 2 mois par exemple soit automatiquement rendues obsolètes

### ISSUE THREAD

**Issue by 3lodi3** [gip-inclusion/immersion-facile#721]
Pierre : 
Attention : On ne pourra alors plus faire de suivi de l'évolution du volume de conventions non validées (important pour voir comment on réduit le nombre de conventions en mourance) 
https://metabase.immersion-facile.beta.gouv.fr/question/859-pourcentage-de-conventions-non-validees

**Comment by 3lodi3** [comment]
Faire une tâche planifiée la nuit

**Comment by Archeveque** [comment]
A l'oral on avait dit 2 mois avant la date de fin.
C'est ce qu'on a mis dans le code en accord avec Jerome (on pourra changer pour trois si jamais c'est nécessaire)
