### ISSUE TITLE
Export des données via TBD plus visible

### ISSUE THREAD

**Issue by Jessicaceleste1** [gip-inclusion/immersion-facile#734]
### :thinking: Contexte et problématique

Ceux qui pilotent par agences, DT, DR, DG etc... nous indiquent qu'ils ne peuvent pas filtrer comme ils le souhaitent, je leur réponds que si, ils peuvent extraire le tableau et ensuite appliquer leur filtre mais en effet, la possibilité d'extraire depuis le tbd n'est pas visible, il faut passer sa souris à l'endroit prévu pour que les "..." apparaissent et permettent l'extraction 
![image](https://github.com/gip-inclusion/immersion-facile/assets/129732318/eddcdb5a-7711-4315-ac37-2bb53eecc0d9)

### :tada: Proposition de solution

Avoir un bouton "extraire"

**Comment by JeromeBu** [comment]
Le problème est que le bouton n'est pas visible ? 
Normalement il est bien disponible, quand on passe la souris.

Malheureusement c'est coté metabase donc on ne peut pas améliorer le bouton....

**Comment by JeromeBu** [comment]
Je cloture car on ne peut rien faire....
