### ISSUE TITLE
ETQ qu'utilisateurs, je visualise plus de détails sur le bloc signataire de convention avant de la signer

### ISSUE THREAD

**Issue by cecile-dimarco** [gip-inclusion/immersion-facile#748]
### :thinking: Contexte et problématique (et par qui est-ce remonté ?)
l'entreprise fait remonter une demande de modification du nom et prénom du signataire

le nom et prénom du représentant légal de l'entreprise ou tuteur n'apparaissent pas, seul le mail apparait 
### :tada: Proposition de solution
rajouter les noms des signataires et tuteur

Lien discord https://discord.com/channels/864451835553513474/1169626615492382764

**Comment by JeromeBu** [comment]
On peut avoir un screenshot stp ?

**Comment by 3lodi3** [comment]
![Image](https://github.com/gip-inclusion/immersion-facile/assets/76998405/808a4abd-c9ce-4f9b-80f8-a46785d4486e)

Effectivement on n'a pas le nom prénom du représentant / tuteur.

On pourrait faire un premier bloc :

### Signataires de la convention

#### Bénéficiaire
Nom
Prénom
Email 
Tél
Date de naissance

#### Représentant de l'entreprise
Nom
Prénom
Email 
Tél

### Tuteur en entreprise (non signataire de la convention)
Nom
Prénom
Email 
Tél

Puis iso :

### Structure d'accompagnement du candidat (validateur de la convention)
### Informations de l'entreprise d'accueil
### Conditions d'immersion
