### ISSUE TITLE
ETQ support je souhaite éviter les conventions en doublon

### ISSUE THREAD

**Issue by 3lodi3** [gip-inclusion/immersion-facile#760]
Page notion détaillée : https://www.notion.so/gip-inclusion/Eviter-les-conventions-en-doublon-0e723a4ed1b94266b9132629e76a1043?pvs=4

## Solution :

Détecter lors de la soumission de demande de convention, s’il y a déjà une convention existante avec des infos similaires, et renvoyer vers le Tally de Pierre : https://tally.so/r/nWE4oN (ou page d’aide https://aide.immersion-facile.beta.gouv.fr/fr/article/je-nai-pas-recu-la-convention-a-signer-que-faire-125bxxd/)

Idée : on peut le vérifier au moment de la vue récap et proposer de :

1. Voir la convention existante : la signer ou la modifier
2. Quand même créer une nouvelle convention
3. Si vous voulez renouveler contactez votre conseiller

## Quelles sont les infos sur lesquelles on se base pour déterminer le doublon ?

- SIRET
- Appellation métier
- Date de naissance du bénéficiaire
- Nom de famille du bénéficiaire
- (Date de démarrage à + ou - quelques jours (proche ? à définir))
- Tous les statuts jusqu’à convention validée (pour inclure les bénéficiaires qui vont tenter de renouveler leur convention en passant par le formulaire)

## De plus on nettoie les conventions initiées mais pas finalisées

- Toutes les conventions initiées mais pas validées plus de deux mois après la date de démarrage passent automatiquement en statut DEPRECATED (obsolète).

**Comment by 3lodi3** [comment]
Suggestion : commencer par modifier la 1ère page du formulaire pour détourner les personnes qui s'apprêtent à créer un doublon - cela résoudrait aussi l'issue #765 (les entreprises qui contactent le support, pensant qu'il faut avoir des id PE pour remplir la convention)
-> https://www.figma.com/proto/s43XSEkyYPaeGs2sxp62iq/Site---UX-design-2nd-semestre-2023?page-id=2269%3A16967&type=design&node-id=2274-17026&viewport=-1226%2C-795%2C0.66&t=peVJ1shLOms5iQRD-8&scaling=min-zoom&starting-point-node-id=2274%3A17026&hide-ui=1

On en parle demain

**Comment by JeromeBu** [comment]
On part sur une date de démarage a + ou - une semaine

**Comment by JeromeBu** [comment]
Message de feedback a afficher à coté des boutons de validation / modification

**Comment by JeromeBu** [comment]
> ## De plus on nettoie les conventions initiées mais pas finalisées
> * Toutes les conventions initiées mais pas validées plus de deux mois après la date de démarrage passent automatiquement en statut DEPRECATED (obsolète).

Cette partie a été traité dans un autre ticket (et déjà mis en prod)

**Comment by JeromeBu** [comment]
On va ignoré les conventions existante qui ont les status suivant :
DEPRECATED
REJECTED
CANCELED

Toutes les autres seront considéré comme doublons si les critères match
