### ISSUE TITLE
ETQ entreprise, je veux accéder directement au remplissage de la convention et je suis bloquée par la page qui demande les ID pole emploi

### ISSUE THREAD

**Issue by 3lodi3** [gip-inclusion/immersion-facile#765]

**Comment by JeromeBu** [comment]
Dans ce ticket, on fait uniquement la refonte de la page qui contient le bouton PE connect

https://www.figma.com/proto/s43XSEkyYPaeGs2sxp62iq/Site---UX-design-2nd-semestre-2023?page-id=2269%3A16967&type=design&node-id=2276-54935&viewport=-1226%2C-795%2C0.66&t=peVJ1shLOms5iQRD-8&scaling=min-zoom&starting-point-node-id=2274%3A17026

**Comment by 3lodi3** [comment]
Steuplé @JeromeBu on dit pas maquette grossière mais wireframe haha ! @LesPetitsSuisses c'est ici pour ajouter la maquette pas grossière !

**Comment by 3lodi3** [comment]
Poposition avec illustrations : https://www.figma.com/proto/s43XSEkyYPaeGs2sxp62iq/Site---UX-design-2nd-semestre-2023?page-id=2269%3A16967&type=design&node-id=2276-54935&viewport=-1071%2C-666%2C0.56&t=5daxqDhW9cbMY5Qm-1&scaling=min-zoom&starting-point-node-id=2274%3A17026&mode=design


![Image](https://github.com/gip-inclusion/immersion-facile/assets/76998405/825311bd-3c4c-42b0-929c-05bba8c3a076)
![Image](https://github.com/gip-inclusion/immersion-facile/assets/76998405/669b521c-996f-40f0-bcac-e68e0b247785)
![Image](https://github.com/gip-inclusion/immersion-facile/assets/76998405/da44f80e-0395-4174-adfd-53a68f2c748e)

**Comment by 3lodi3** [comment]
Suite au point avec @enguerranws mardi 24 octobre :

- [ ] Supprimer cette page intermédiaire lorsqu'on accède au formulaire via le menu entreprises
- [ ] Ajouter le lien rapide "Remplir la demande de convention" dans le header
- [ ] Remplacer la page d'accès au formulaire par celle-ci : https://www.figma.com/proto/s43XSEkyYPaeGs2sxp62iq/Site---UX-design-2nd-semestre-2023?page-id=2269%3A16967&type=design&node-id=2276-54935&viewport=-1071%2C-666%2C0.56&t=8e5L2bjbMlgKkNrs-1&scaling=min-zoom&starting-point-node-id=2274%3A17026&hide-ui=1 
lorsqu'on accède au formulaire par le lien d'accès rapide, ou les menus candidats / prescripteurs (j'ai viré les boutons des cartes car tu as raison, il y a déjà énormément de texte, c'est plus lisible comme ça non ?)
- [ ] Remplacer la page de partage de formulaire par celle-ci : https://www.figma.com/proto/s43XSEkyYPaeGs2sxp62iq/Site---UX-design-2nd-semestre-2023?page-id=2269%3A16967&type=design&node-id=2386-20365&viewport=-1071%2C-666%2C0.56&t=5daxqDhW9cbMY5Qm-1&scaling=min-zoom&starting-point-node-id=2274%3A17026&mode=design (proposition)

**Comment by JeromeBu** [comment]
Pour la partie `Supprimer cette page intermédiaire lorsqu'on accède au formulaire via le menu entreprises`, on a pas dit qu'on ne le faisait pas justement ? 

Car la page gère justement ce problème. On peut en tout cas repousser cette partie après que la nouvelle page soit en service (et peut-être que ça ne sera donc plus utile, si les gens n'ont plus de difficultés)

**Comment by LesPetitsSuisses** [comment]
Salut @3lodi3 @JeromeBu @enguerranws, j

Voici la maquette UI validée : https://www.figma.com/file/bYjpgeGkOTRRVKPcEkHHZi/GIP-Immersion-facilit%C3%A9e-design-S%C3%A9bastien-Hoffmann-LPS?type=design&node-id=23%3A17747&mode=design&t=hH9DbDoLzPdlPG3I-1

L'export du *.svg "J’ai déjà rempli une demande de convention mais j’ai un problème"  directement depuis Figma pose problème, je l'ai retouché sur Illustrator pour résoudre le problème : https://www.dropbox.com/scl/fo/wjp036t4xzl9ljt915ctc/h?rlkey=kgsv8zxmm5uikucxflnu96fek&dl=0

![Remplir la demande de convention-LPS](https://github.com/gip-inclusion/immersion-facile/assets/17570352/4589af16-63f6-4477-acc3-6b57c0d9b152)
![2310-im-remplir-convention-sans-i
![2310-im-remplir-convention-aide](https://github.com/gip-inclusion/immersion-facile/assets/17570352/0808446f-e60b-41b3-b2e2-4fc7f3e18da4)
d-p
![2310-im-remplir-convention-avec-id-pe](https://github.com/gip-inclusion/immersion-facile/assets/17570352/cb590e46-af85-46ff-b376-f88d2a2a102d)
e](https://github.com/gip-inclusion/immersion-facile/assets/17570352/5a69e255-6a58-494d-881b-fc892ee86ba3)

**Comment by LesPetitsSuisses** [comment]
![2310-im-remplir-convention-aide](https://github.com/gip-inclusion/immersion-facile/assets/17570352/38789330-8e00-4f7f-8093-29e2444f0810)

![2310-im-remplir-convention-avec-id-pe](https://github.com/gip-inclusion/immersion-facile/assets/17570352/263c2921-54aa-4da1-b407-07afe9531b1e)

![2310-im-remplir-convention-sans-id-pe](https://github.com/gip-inclusion/immersion-facile/assets/17570352/ddfbd8b9-9d8d-4514-a9b4-a0973f0df9d9)

**Comment by LesPetitsSuisses** [comment]
![2310-im-remplir-convention-aide](https://github.com/gip-inclusion/immersion-facile/assets/17570352/d7ed111e-d1f4-4688-9128-1d04e318dc40)

**Comment by LesPetitsSuisses** [comment]
![2310-im-remplir-convention-aide](https://github.com/gip-inclusion/immersion-facile/assets/17570352/dbd0ab47-6f91-4a24-8d8b-c475e1d2b3b9)

**Comment by LesPetitsSuisses** [comment]
![2310-im-remplir-convention-sans-id-pe](https://github.com/gip-inclusion/immersion-facile/assets/17570352/86566c3d-d756-43ab-b6d8-d17643897282)

**Comment by LesPetitsSuisses** [comment]
![2310-im-remplir-convention-avec-id-pe](https://github.com/gip-inclusion/immersion-facile/assets/17570352/7bffc027-54eb-42ba-9ce2-51778ba65ddf)

**Comment by celineung** [comment]
Hello @LesPetitsSuisses,
Pourrais-tu nous envoyer l'image utilisée dans la page de partage de convention ?
Merci :)

**Comment by LesPetitsSuisses** [comment]
@celineung J'ai appliqué un fond transparent sur toutes les illustrations pour faciliter le "mode thème sombre". Dis-moi, si cela te convient ?

Tous les fichiers sources sont disponibles ici : https://www.dropbox.com/scl/fo/wjp036t4xzl9ljt915ctc/h?rlkey=kgsv8zxmm5uikucxflnu96fek&dl=0

[2310-im-partager-convention](https://github.com/gip-inclusion/immersion-facile/assets/17570352/f6875959-1012-44b5-acf3-ed9becd627b2)
![2310-im-remplir-convention-aide](https://github.com/gip-inclusion/immersion-facile/assets/17570352/6b0d8a71-0ab9-47a5-b8f9-23275b73c4dd)
![2310-im-remplir-convention-avec-id-pe](https://github.com/gip-inclusion/immersion-facile/assets/17570352/eae27d3d-dd3c-4f77-a4b8-6fee3b27c815)
![2310-im-remplir-convention-sans-id-pe](https://github.com/gip-inclusion/immersion-facile/assets/17570352/973383f7-6778-4bc0-8c4a-61ec554ec4c8)
ey=kgsv8zxmm5uikucxflnu96fek&dl=0
