### ISSUE TITLE
Modification du mail de validation du compte inclusion connect

### ISSUE THREAD

**Issue by Jessicaceleste1** [gip-inclusion/immersion-facile#783]
### :thinking: Contexte et problématique (et par qui est-ce remonté ?)
Maintenant que nous avons déployé bien plus de fonctionnalité, il faut supprimer cette phrase ou pas mais précisé que maintenant on peut : modifier, valider, rendre obsolète et faire une demande de renouvèlement. 

### :tada: Proposition de solution

Modification du template.

**Comment by Jessicaceleste1** [comment]
https://discord.com/channels/864451835553513474/1042365650359828480/1166382433495699487

**Comment by Jessicaceleste1** [comment]
![image](https://github.com/gip-inclusion/immersion-facile/assets/129732318/9800c465-1fd1-4b80-b267-1bb69494b138)

**Comment by nathalie-reyre** [comment]
faire le wording ASAP
