### ISSUE TITLE
ETQ support, je ne souhaite plus répondre manuellement aux tickets concernant la connaissance globale PMSMP ou les suggestions d'amélioration sur le site

### ISSUE THREAD

**Issue by 3lodi3** [gip-inclusion/immersion-facile#797]
### :thinking: Contexte et problématique (et par qui est-ce remonté ?)

De nombreux tickets concernent :
- une méconnaissance de la PMSMP et pas du service Immersion Facilitée
- des suggestions d'amélioration auxquelles le support ne peut pas répondre grand chose sauf à promettre quelque choses qui ne sera jamais développé

### :tada: Proposition de solution

- Dans Tally support : soit on récupère l’ID de convention lié au ticket, soit on demande au prescripteur déclarer son type (pour pouvoir tracker le nb de ticket par type de prescripteur).
- Modifier l'entrée "infos générales PMSMP" -> faire un vrai mode d'emploi PMSMP par persona
- Ajouter une entrée "suggestion site" -> champ titre / description / type de partie prenante (entreprise, candidat, prescripteur) / coordonnées pour participer à de futurs test utilisateurs (comme ça je me fais une base). Je voulais utiliser cally.io MAIS après avoir testé la version gratuite : pas moyen de modérer les posts donc j'ai mis en stand-by.

**Comment by 3lodi3** [comment]
rdv avec Pierre le 8 nov

**Comment by 3lodi3** [comment]
- [ ] suggestions d'amélioration
- [ ] mode d'emploi PMSMP par persona

**Comment by nathalie-reyre** [comment]
@3lodi3 ? Toujours d'actu ? Si oui, à labelliser FAST
