### ISSUE TITLE
ETQ équipe IF, je souhaite suivre le taux de réponse des entreprises lors des mises en relation

### ISSUE THREAD

**Issue by 3lodi3** [gip-inclusion/immersion-facile#801]
### :thinking: Contexte et problématique

Mesure d'impact à suivre pour le prochain comité

### :tada: Proposition de solution

Ajouter cette mesure au tableau de bord : https://metabase.immersion-facile.beta.gouv.fr/dashboard/85-indicateurs-cles-objectifs

Objectif : taux de réponse des entreprises lors d'une mise en relation : 30% vs 17% à date
La réponse est comptabilisée si l'entreprise envoie au moins une réponse par email.

Pourcentage de taux de réponse regroupé par mois avec l'objectif de 30% de visibilité.

**Comment by JeromeBu** [comment]
à voir avec #771

**Comment by bbohec** [comment]
Fait & vu avec @nathalie-reyre 
https://metabase.immersion-facile.beta.gouv.fr/question/1376-mise-en-relation-taux-de-reponse-des-entreprises
