### ISSUE TITLE
ETQ entreprise qui recoit un mail de bilan, j'ai les infos de l'agence pour pouvoir leur transmettre le bilan PDF

### ISSUE THREAD

**Issue by bbohec** [gip-inclusion/immersion-facile#804]
### :thinking: Contexte et problématique (et par qui est-ce remonté ?)

Actuellement il n'y a pas d'info d'agence dans le mail à part dire qu'il faut leur transmettre le PDF.
![image](https://github.com/gip-inclusion/immersion-facile/assets/58432308/5db32dc5-0c04-4d40-beb2-42ccb954b3e8)

### :tada: Proposition de solution

Mettre un minimum d'info d'agence dans le mail ( adresse / mail / téléphone ???) pour que l'entreprise soit autonome car ils répondent au mail avec le PDF rempli et donc ça créé un ticket support IF et ça pousse le support soit à envoyer le PDF à l'agence ou à transmettre les infos d'agence à l'entreprise à chaque fois.

**Comment by bbohec** [comment]
https://discord.com/channels/864451835553513474/1042365650359828480/1167093350382440458

**Comment by nathalie-reyre** [comment]
indiquer également le mail du valideur (mail agence ou mail du conseiller valideur ) dans la convention (en plus demandé par la DGEFP car précisé dans le décret  et l'arrêté qui décrivent le contenu de la  convention)
