### ISSUE TITLE
ETQ admin un message d'erreur s'affiche lors de la suppression d'une entreprise acceuillante

### ISSUE THREAD

**Issue by cecile-dimarco** [gip-inclusion/immersion-facile#812]
### :dart: Comportement attendu

 un message devrait nous confirmer que la suppression a bien été réalisée

### Screenshots

![image](https://github.com/gip-inclusion/immersion-facile/assets/134716620/86db8570-6577-4381-b398-ccc679ecdfb7)

**Comment by JeromeBu** [comment]
(seul le feedback est mal affiché, le backend fait bien le travail)

**Comment by clement-duport** [comment]
issue shared route : https://github.com/JeromeBu/shared-routes/issues/9
