### ISSUE TITLE
ETQ 'entreprise', quand je réactive la visibilité de mon entreprise, le nombre de mises en relation maximal doit être > 0

### ISSUE THREAD

**Issue by nathalie-reyre** [gip-inclusion/immersion-facile#827]
### :bug: Le problème

 ; quand on réactive sa structure pour être de nouveau visible, le nombre de mises en relation max/semaine reste par défaut à 0 (en tout cas dans la page vue par l'utilisateur). 

### :dart: Comportement attendu

 il faudrait que le chiffre de mise en relation soit modifié et passe à 1 (a minima)

### Screenshots

 
<img width="1228" alt="Capture d’écran 2023-11-06 à 10 42 33" src="https://github.com/gip-inclusion/immersion-facile/assets/61510442/93e59675-e0da-4789-95c8-00b4b6ff3b1c">

**Comment by celineung** [comment]
Lorsque l'on arrive sur le formulaire, le champ "L'entreprise est-elle recherchable par les utilisateurs ?" est toujours cochée, même si l'entreprise l'a désactivée.
En corrigeant ce comportement, le nombre de mise en relation revient à 10 lorsque la case est cochée à nouveau.
