### ISSUE TITLE
ETQ 'entreprise', je n'ai pas la confirmation que je vais bien recevoir un mail de modification

### ISSUE THREAD

**Issue by nathalie-reyre** [gip-inclusion/immersion-facile#831]
### :bug: Le problème

quand une entreprise rentre son siret pour modifer ses informations, elle ne voit plus la confirmation d'envoi du mail de modif. La modale de saisie du numéro de siret reste figé

### :footprints: Étapes pour reproduire

1. Aller sur '.modifier mon entreprise'
2. saisir sur 'SIRET.'
3. ouverture de la modale 
4. Il y a l'erreur '.pas de message de confirmation et modale reste figée

### :dart: Comportement attendu

 un message de confirmation d'envoi du mail pour modifer les infos de l'étab

### Screenshots

<img width="671" alt="Capture d’écran 2023-11-06 à 10 52 14" src="https://github.com/gip-inclusion/immersion-facile/assets/61510442/8b4b621d-0193-4ac5-9e37-a030c8392037">

**Comment by bbohec** [comment]
Le message est bien là, surement un oubli de placement en Production
