### ISSUE TITLE
Corriger le message de confirmation de signature de la demande de convention quand il y a une structure accompagnante

### ISSUE THREAD

**Issue by nathalie-reyre** [gip-inclusion/immersion-facile#843]
![Image](https://github.com/gip-inclusion/immersion-facile/assets/61510442/cd4e4202-2588-4b43-bcf0-fb90b1cf1d50)

ce n'est pas la structure accompagnante qui peut valider la convention, mentionner la structure accompagnante et la structure prescriptrice dans l'encadré de confirmation de la signature

**Comment by clement-duport** [comment]
@enguerranws
