### ISSUE TITLE
Mise à jour des couleurs du Helpdesk Crisp

### ISSUE THREAD

**Issue by enguerranws** [gip-inclusion/immersion-facile#847]

**Comment by LesPetitsSuisses** [comment]
J'y pense maintenant @Enguerran, désolé , si la couleur de fond est modifiable également avec la CSS, opter pour un gris neutre #f6f6f6 à la place du gris-bleu #f3f6fa. Encore merci !

**Comment by enguerran** [comment]
Bonjour, c'est un plaisir de découvrir ce projet chez beta.gouv pour l'inclusion. Le ping était pour un autre @enguerranws développeur web ;-)
Bonne continuation !
