### ISSUE TITLE
[EPIC] ETQ 'prescripteur', je reçois le bilan complété par l'entreprise (assesment)

### ISSUE THREAD

**Issue by nathalie-reyre** [gip-inclusion/immersion-facile#849]
### :thinking: Contexte et problématique

nous avons actuellement près de 20 000 tuteurs qui ont complété l'assesment (immersion achevée ou abandonnée + commentaire en libre saisie). Les prescripteurs n'en sont pas destinataires et les entreprises ne comprennent pas pourquoi elles sont relancées pour fournir ce bilan

### :tada: Proposition de solution

 **Rendre accessible le bilan par l'envoi d'une notification et  via le tableau de pilotage**
la notification pointe sur la page du bilan -  cette page peut être téléchargée en PDF ou imprimée (comme la convention)
on envoie la notification à la boite agence 
on envoie la notification au validateur et aussi au conseiller (quand 2 étapes)
on envoie à l'agence accompagnatrice et à la structure prescriptrice
on envoie au bénéficiaire

**A faire avec Elodie** Le mail  actuel adressé à l'entreprise doit mieux préciser la nécessité de télécharger le support de bilan pour le compléter en plus du verbatim et indiquer précisément à quelle adresse renvoyer le support complété.
-> Fait dans story #124 

A faire : rédiger le mail de notification de mise à disposition de l'assesment (identique pour le bénéficiaire et le prescripteur
Proposition : ajouter une page à la page convention incluant le bilan - Imaginer un header commun aux 2 "pages"  pour permettre l'identification (ID immersion -  infos récap sur l'immersion : nom prénom mail bénef -  métier, siret et RS entreprise, objectif - dates)
Permettre téléchargement de la page bilan indépendamment si besoin de celui de la convention

**Comment by 3lodi3** [comment]
#889
