### ISSUE TITLE
Inbound parsing: maj politique de confidentialité pour indiquer le système de tracking par ID pour lier les échanges

### ISSUE THREAD

**Issue by nathalie-reyre** [gip-inclusion/immersion-facile#865]
https://www.notion.so/gip-inclusion/Doctrine-inbound-parsing-Brevo-suivi-des-changes-57c6969270414d37a3befaa5b8c226c6

**Comment by 3lodi3** [comment]
@nathalie-reyre relancer Osiris pour avoir le texte de la politique de confidentialité

**Comment by bbohec** [comment]
Le sujet n'est pas clair pour Osiris car le système d'inbound-parsing Brevo n'est pas un tracker au sens cookie qui peut s'activer ou non en soit mais juste un liant technique qui permet d'identifier le destinataire pour un expéditeur.

**Comment by nathalie-reyre** [comment]
relance dOsiris le 17/01

**Comment by nathalie-reyre** [comment]
Les modifications apportées par Wissem : 

Ajout de la finalité plus claire pour le suivi des échanges à des fins statistiques ;
Ajout de la durée de conservation de 6 mois ;
Suppression de Matomo du tableau des sous-traitants (puisqu'il est en mode exempté) ;
Ajout de l'adresse des bureaux du GIP pour l'exercice des droits.

**Comment by nathalie-reyre** [comment]
[17012024 - Immersion Facilitée - Politique de confidentialité v10.docx](https://github.com/gip-inclusion/immersion-facile/files/13976007/17012024.-.Immersion.Facilitee.-.Politique.de.confidentialite.v10.docx)
