### ISSUE TITLE
Inbound parsing : communication d'équipe interdisant l'accès au contenu des échanges

### ISSUE THREAD

**Issue by nathalie-reyre** [gip-inclusion/immersion-facile#879]
Mettre une entrée dans le notion : 
- détailler qui a accès à la table des échanges
- les autres s'engagent à ne pas la consulter
- sauf à la demande expresse d'un utilisateur

**Comment by 3lodi3** [comment]
@nathalie-reyre @3lodi3

**Comment by 3lodi3** [comment]
Issue a créer : AIPD = équivalent du texte en interne Notion mais doc communicable à l'extérieur : CNIL etc. @3lodi3

**Comment by bbohec** [comment]
Fiche entrée sortie IF colone Engagement respect des communicatrions privées candidat <> entreprise
https://www.notion.so/gip-inclusion/Proc-dure-d-entr-e-sortie-8bc8e0c47b1748b193a2e253368222ec

**Comment by bbohec** [comment]
@nathalie-reyre je te laisse gérer ce sujet  pour rappeler à chaque membre IF de remplir le form pour que tu puisses cloturer le sujet et communiquer à Osiris que c'est fait?
