### ISSUE TITLE
Marianne sur Crisp - Modifier CORS pour autoriser l'utilisation de fonts depuis Crisp

### ISSUE THREAD

**Issue by enguerranws** [gip-inclusion/immersion-facile#88]
Ah, apparemment voilà le pb (j'ai regardé dans l'inspecteur sur firefox) : Blocage d’une requête multiorigines (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur https://immersion-facile.beta.gouv.fr/dsfr/fonts/Marianne-Regular.woff2. Raison : l’en-tête CORS « Access-Control-Allow-Origin » est manquant. Code d’état : 200.

[15:17_]_https://developer.mozilla.org/fr/docs/Web/HTTP/CORS/Errors/CORSMissingAllowOrigin?utm_source=devtools&utm_medium=firefox-cors-errors&utm_campaign=default

**Comment by bbohec** [comment]
https://trello.com/c/VTP51q7C/72-ajout-pages-helpdesk-am%C3%A9liorer-lux-ui-pour-diminuer-les-demandes-au-support
