### ISSUE TITLE
Refuser un compte inclusion connect depuis admin

### ISSUE THREAD

**Issue by Jessicaceleste1** [gip-inclusion/immersion-facile#881]
### :bug: Le problème

 Depuis la focale (je me teste a utiliser les bons mots lol sinon j'aurais dis fenêtre, enfin si focale est le bon mot mdr) "refuser" un compte inclusion connect. Une fois que l'on valide via refuser le rattachement, même si on va chercher un nouvel utilisateur à valider, nous restons bloqué sur : 

![image](https://github.com/gip-inclusion/immersion-facile/assets/129732318/a117e14c-2531-41c6-b91c-fd317326a06f)
 il faut rafraichir la page pour en traiter un autre.

### :footprints: Étapes pour reproduire
1. Aller sur '...'https://immersion-facile.beta.gouv.fr/admin/agencies
Rapprocher un utilisateur d'une agence
2. Cliquer sur '...' Sélectionner un utilisateur (12 en attente de validation)
Refuser
Mettre un motif et refuser le rattachement

**Comment by Jessicaceleste1** [comment]
lien thread discord https://discord.com/channels/864451835553513474/1042365650359828480/1174289241564532796

**Comment by Jessicaceleste1** [comment]
PS : et penser à ton pote TOTO 
lol

**Comment by enguerranws** [comment]
@Jessicaceleste1 C'est traité, ça passe dans la prochaine MEP

**Comment by enguerranws** [comment]
ah par contre, j'avais pas vu la faute sur rejeté (rejetté).
