### ISSUE TITLE
ETQ support je veux moins de tickets liés au parcours de modif / aux refus

### ISSUE THREAD

**Issue by 3lodi3** [gip-inclusion/immersion-facile#891]
### :thinking: Contexte et problématique

Les signataires font une demande de modif en pensant relancer les gens qui n'ont pas signé

### :tada: Proposition de solution

Deux choix s'offrent au conseiller : 
- quel est le motif de votre refus ou de votre modif ? si c'est manque de signature > qui voulez-vous relancer > mailto
- si non on garde le parcours actuel

**Comment by 3lodi3** [comment]
@3lodi3 revoir le parcours

**Comment by JeromeBu** [comment]
On a bien avancé, la PR est en cours. Voilà le contenu grossièrement. Preneur de ton retour @3lodi3 



![Image](https://github.com/gip-inclusion/immersion-facile/assets/22095555/12443718-3cdf-4b8c-800b-dc6d179abc72)



![Image](https://github.com/gip-inclusion/immersion-facile/assets/22095555/c9b6525f-a7d1-43c9-b537-9aeb7d101fe0)

ou bien si tout le monde à déjà signé

![Image](https://github.com/gip-inclusion/immersion-facile/assets/22095555/e5ff3489-d037-4201-ac38-5c300723a109)

Le mail to :


![Image](https://github.com/gip-inclusion/immersion-facile/assets/22095555/17903f3a-734e-4f6a-9a7b-ff3b0a556c88)
