### ISSUE TITLE
ETQ support je veux que tous les tickets passent par le form Tally

### ISSUE THREAD

**Issue by 3lodi3** [gip-inclusion/immersion-facile#895]
Supprimer toutes les mentions directes à l'email [contact@immersion-facile.beta.gouv.fr](https://aide.immersion-facile.beta.gouv.fr/fr/) et renvoyer vers le support

**Comment by clement-duport** [comment]
@3lodi3  je viens de retiré les derniers liens vers le mail de contact sur le site. tu t'occupe de retirer les dernières références dans le helpdesk ?

**Comment by 3lodi3** [comment]
Yes @clement-duport c'est bon !
