### ISSUE TITLE
ETQ entreprise, je souhaite mettre en pause les mer pendant un temps donné

### ISSUE THREAD

**Issue by 3lodi3** [gip-inclusion/immersion-facile#901]
### :thinking: Contexte et problématique (et par qui est-ce remonté ?)

ETQ entreprise, je peux être amenée à vouloir mettre en pause les mer (par ex : vacances de Noël). Cela éviterait les entreprises qui désactivent les mer puis oublient de les réactiver.

### :tada: Proposition de solution

Proposer aux entreprises de pouvoir mettre en pause les mer pendant une période donnée.
Au terme de cette période, les mer sont réactivées en reprenant le nombre de mer définies par l'entreprise avant la pause.

**Comment by bbohec** [comment]
Prévoir également d'ajouter dans les mails de mise en relation la possibilité de mettre en pause avec un lien. (peut être le lien de modif d'établissement?)

**Comment by enguerranws** [comment]
@3lodi3 

![Image](https://github.com/gip-inclusion/immersion-facile/assets/2190121/c7fe022d-cd5b-4c1c-9d5b-02ad011a1fab)

**Comment by 3lodi3** [comment]
Hello, suite à notre point de cet aprem, j'ai tenté la version "on casse tout" :-) 
-> https://www.figma.com/proto/O6MfTEZ1Ms8cKQHFjOYEA5/Site---UX-design-1er-semestre-2023?page-id=1722%3A8169&type=design&node-id=1729-14420&viewport=-1288%2C-1313%2C0.32&t=zMpEM94lQwnFGS0l-1&scaling=min-zoom&starting-point-node-id=1729%3A14420&mode=design

Aussi, il me semble qu'on avait ajouté à un moment avec @enguerranws une prévisualisation de la carte qui apparaît sur l'annuaire, et je ne la vois plus, je ne sais pas pourquoi on l'a retirée ? 

N'hésitez pas si vous voulez en discuter, j'essaie de me rendre dispo demain même si au jeudi de l'inclusion (dans l'aprem plutôt car le matin j'ai un entretien avec un candidate designeuse + rex octo) 

la version mvp pour rappel : https://www.figma.com/proto/O6MfTEZ1Ms8cKQHFjOYEA5/Site---UX-design-1er-semestre-2023?page-id=1722%3A8169&type=design&node-id=1722-8172&viewport=78%2C357%2C0.16&t=7GZKODwgzQ4NFKBY-1&scaling=min-zoom&starting-point-node-id=1722%3A8172&mode=design
