### ISSUE TITLE
ETQ bizdev IF je souhaite que la page Boulanger soit mise en avant

### ISSUE THREAD

**Issue by 3lodi3** [gip-inclusion/immersion-facile#903]
### :thinking: Contexte et problématique (et par qui est-ce remonté ?)

La page https://immersion-facile.beta.gouv.fr/groupe/boulanger est cachée

### :tada: Proposition de solution

- Mettre le macaron "Décathlon" mais avec Boulanger sur la home de IF
- Comment peut-on améliorer le référencement de ces pages ?
- Mettre en avant ces opé spé sur LinkedIn, site du GIP... @LesPetitsSuisses ? à voir avec les bizdev @Jessicaceleste1 @NastassiaRodriguez

**Comment by LesPetitsSuisses** [comment]
Suggestions :
- Revoir le texte (problèmes d'espaces après la ponctuation)
- Champs filtre : wording à modifier / raccourcir : "Filtrer par métier ou localisation" (intitulé trop long sur mobile)
- Rajouter le logo BOULANGER (logo entreprise, pas le logo 1000 jeunes/1000 stages) sur toutes les cartes de résultat (le nom/titre "boulanger" est très confusant : est-ce le nom de l'entreprise ou le nom d'un métier ?)
- Le logo "1000 jeunes/1000 stages" ne s'affiche pas sur mobile, on est d'accord ?
- Le bandeau texte qui inclut le CTA "trouver une immersion" ne s'adapte pas en dark mode (évolution possible ?)

**Comment by LesPetitsSuisses** [comment]
Ajouter le logo Boulanger dans chacune des cartes de résultats.
![boulanger-ss-baseline](https://github.com/gip-inclusion/immersion-facile/assets/17570352/a8e3a463-53fe-4f93-9d10-28efa5a6e5b6)

**Comment by LesPetitsSuisses** [comment]
Dark mode : le bandeau du haut ne suit pas le changement de paramètre (cf. capture ci-dessous)
<img width="1473" alt="Capture d’écran 2023-11-23 à 09 46 08" src="https://github.com/gip-inclusion/immersion-facile/assets/17570352/448d684f-5e28-48ec-8c2b-cd975a82f328">

**Comment by LesPetitsSuisses** [comment]
Mise en avant de l'étiquette type Décathlon sous cette forme : 
https://www.figma.com/file/bYjpgeGkOTRRVKPcEkHHZi/GIP-Immersion-facilit%C3%A9e-design-S%C3%A9bastien-Hoffmann-LPS?type=design&node-id=584%3A26913&mode=design&t=PYhGxWwagibVutXp-1
<img width="697" alt="Capture d’écran 2023-11-23 à 11 14 43" src="https://github.com/gip-inclusion/immersion-facile/assets/17570352/fffa766e-7999-4dba-babc-1d2f55090c93">

Dans un deuxième temps, ce serait peut-être intéressant d'envisager une mise en avant mieux intégrée à notre site / au DSFR sous la forme de 3 cartes "brandées" au nom du/des partenaires.

Maquette Figma : https://www.figma.com/file/bYjpgeGkOTRRVKPcEkHHZi/GIP-Immersion-facilit%C3%A9e-design-S%C3%A9bastien-Hoffmann-LPS?type=design&node-id=584%3A27784&mode=design&t=PYhGxWwagibVutXp-1

<img width="697" alt="Capture d’écran 2023-11-23 à 11 16 50" src="https://github.com/gip-inclusion/immersion-facile/assets/17570352/f5277f0e-d017-4a7a-a7df-881247659f12">

**Comment by LesPetitsSuisses** [comment]
Dans un deuxième temps, ce serait peut-être intéressant d'envisager une mise en avant mieux intégrée à notre site / au DSFR sous la forme de 3 cartes "brandées" au nom du/des partenaires.

Maquette Figma : https://www.figma.com/file/bYjpgeGkOTRRVKPcEkHHZi/GIP-Immersion-facilit%C3%A9e-design-S%C3%A9bastien-Hoffmann-LPS?type=design&node-id=584%3A27784&mode=design&t=PYhGxWwagibVutXp-1

<img width="697" alt="Capture d’écran 2023-11-23 à 11 16 50" src="https://github.com/gip-inclusion/immersion-facile/assets/17570352/f5277f0e-d017-4a7a-a7df-881247659f12">

**Comment by Jessicaceleste1** [comment]
attention au wording : priorité aux personnes RQTH, ce n'est pas ce que nous utilisons pour le référencement des entreprises
