### ISSUE TITLE
ETQ UX IF, je souhaite que l'on puisse ajouter un fil d'Ariane DSFR sur toutes les pages du site IF (hors Home)

### ISSUE THREAD

**Issue by 3lodi3** [gip-inclusion/immersion-facile#905]
### :thinking: Contexte et problématique (et par qui est-ce remonté ?)

Manque d'accessibilité lié à l'absence de fil d'Ariane.
Les fonds de couleurs actuels en header ne permettent pas d'ajouter un fil d'Ariance accessible en light et dark mode

### :tada: Proposition de solution

Proposer une UI qui intègre le fil d'Ariane sur toutes les pages hors Home, et vérifier que ce fil est accessible en light + dark mode (vérifier le contraste).

**Comment by enguerranws** [comment]
Doublon : https://github.com/gip-inclusion/immersion-facile/issues/1989
