### ISSUE TITLE
Formulaire de convention avec étapes

### ISSUE THREAD

**Issue by enguerranws** [gip-inclusion/immersion-facile#91]
https://www.figma.com/proto/O6MfTEZ1Ms8cKQHFjOYEA5/Site---UX-design?page-id=0%3A1&node-id=3-5293&viewport=468%2C183%2C0.07&scaling=min-zoom&starting-point-node-id=3%3A5293

**Comment by nathalie-reyre** [comment]
modifier le wording de l'en tête de l'écran de vérif

**Comment by enguerranws** [comment]
Modifs apportées en staging : 
- wording bouton de soumission du form
- wording titre en mode vérif
- règles d'affichage des badges de statuts (sur les étapes)
- emploi du temps (schedule) initialisé avec des horaires vides
- remise à zéro de showSummary
