### ISSUE TITLE
Mail IF bloqués chez les boites mail Microsoft

### ISSUE THREAD

**Issue by bbohec** [gip-inclusion/immersion-facile#913]
Mails bloqués sur toutes les adresses (live/outlook/hotmail).

Le blockage semble lié à un problème d'envois de mail trop important depuis fin octobre.

**Comment by bbohec** [comment]
https://discord.com/channels/864451835553513474/1173908690970091520

**Comment by enguerranws** [comment]
Ticket lié : https://github.com/orgs/gip-inclusion/projects/10/views/2?pane=issue&itemId=45397247

**Comment by bbohec** [comment]
Mails envoyés à Microsoft débloqués après avoir relancé Microsoft suite au processus de demande de déblocage sur https://olcsupport.office.com/
