### ISSUE TITLE
Expérimentation recherche naturelle avec l'API ROMEO

### ISSUE THREAD

**Issue by 3lodi3** [gip-inclusion/immersion-facile#922]
### :thinking: Contexte et problématique (et par qui est-ce remonté ?)

Améliorer la recherche de terrains d'immersion sur IF (sortir des restrictions liées au ROME/code OGR).
État de l'xp en cours : https://www.notion.so/gip-inclusion/Am-lioration-de-la-recherche-de-terrains-d-immersion-a93934d8649445b19809fc0d2a58b9d6?pvs=4

### :tada: Proposition de solution

Test recherche en langage naturel / IA avec l'API ROMEO.

**Comment by JeromeBu** [comment]
La doc de ROMEO : https://pole-emploi.io/data/api/romeo?tabgroup-api=documentation&doc-section=api-doc-section-caracteristiques

**Comment by enguerranws** [comment]
Suite à mes tests, voilà ce que je vois : 
- pour chaque requête, il faut fournir obligatoirement 3 choses : 
  - l'intitule : c'est la query (texte libre) -> "faire le pain"
  - le contexte : alors lui me pose problème, pour un intitulé libre, il faut quand même préciser obligatoirement le secteur -> "boulangerie". Dans notre cas, je trouve qu'on perd complètement l'intérêt de la recherche en langage naturel.
  - un identifiant à fournir : je trouve ça pas mal, ça permet de récupérer le résultat précédemment trouvé. On pourrait imaginer un id `${contexte-intitule}`

**Comment by enguerranws** [comment]
Pour la partie test OpenAI : #947
