### ISSUE TITLE
ETQ équipe IF, je souhaite toujours recevoir les tickets dans Crisp

### ISSUE THREAD

**Issue by 3lodi3** [gip-inclusion/immersion-facile#946]
### :thinking: Contexte et problématique

Si n8n tombe, le support ne reçoit plus les tickets dans Crisp.

### :tada: Proposition de solution

**Proposition retenue : 
Depuis n8n voir s'il n'y a pas de soumission dans Tally depuis plus d'1h (entre 7h et 20h) et si c'est le cas envoyer une notif discord.**

- [ ] Surveiller que les webhooks sont bien actifs et sinon envoyer une alerte au bout d’1 heure (par ex sur discord).
- [ ] Prévenir sur discord que le workflow tourne.
- [ ] Notif à chaque nouveau ticket sur un chan discord.
- [ ] Etre prévenu si un workflow qui pète dans n8n
- [ ] Scheduler est remis en service, pour récupérer les ratés (si certains messages n’ont pas été envoyés sur crisp).
- [ ] Pierre donne les droits admin sur airtable à Tuka par ex. + passation Pierre/Tuka (arrive le 11/12).
- [ ] Pierre fait une vue notion des tickets à traiter pour le support.
- [ ] À terme, rapatrier l’xp dans le code.

### :camera: Maquettes

Si besoin

**Comment by Master-Touks** [comment]
Gestion des erreur dans n8n : https://blog.n8n.io/creating-error-workflows-in-n8n/

**Comment by Master-Touks** [comment]
Les workflow actif : https://n8n.inclusion.beta.gouv.fr/workflow/52, https://n8n.inclusion.beta.gouv.fr/workflow/53

**Comment by celineung** [comment]
Outils actuellement utilisés au support:
- Tally
- Airtable
- n8n
- Crisp

Problèmes:
- Airtable pas RGPD compliant
- on veut aussi se détacher de n8n dont on ne sait pas si le workflow est actif ou tombé

Next step:
prévoir une discussion pour revoir le process actuel

**Comment by chaibax** [comment]
Dispo pour regarder ça à deux @celineung  .
On pourrait passer directement et uniquement par Crisp

**Comment by chaibax** [comment]
Bon, on a regardé avec @3lodi3 , c'est plus compliqué que prévu de tout faire sur Crisp.
La doc est pas tres explicite. 
 J'ai demandé a avoir accès au bot de jeveuxaider pour voir commen ils ont fait . 
De son coté , @Master-Touks cherche une ressource externe
