### ISSUE TITLE
ETQ agent PE, quand je me connecte pour la première fois avec inclusion connect, j'ai accès directement au tableau de bord de mon agence de rattachement

### ISSUE THREAD

**Issue by nathalie-reyre** [gip-inclusion/immersion-facile#953]
s'appuyer sur le SSO PE/inclusion connect pour définir directement l'agence de rattachement d'un conseiller Pôle emploi (code azur est maintenant transmis par Inclusion connect).
Gérer dans un 2e temps les demandes émanant des agents localisés en DT et en DR --> comment récupérer les codes azur ? et comment rattacher à chaque DT  et chaque DR les agences qui dépendent de ce territoire ?

**Comment by nathalie-reyre** [comment]
Aujourd'hui, plus de 90 conseillers PE en attente de validation   et modification en base nécessaire à chaque fois qu'un conseiller change d'agence.

**Comment by bbohec** [comment]
Surement à faire dans la séquence de connexion Inclusion Connect pour ajouter les droit une fois les infos IC avec code AZUR fournies
