### ISSUE TITLE
ETQ utilisateur du helpdesk, au clic sur le logo du centre d'aide, je devrais arriver sur le centre d'aide

### ISSUE THREAD

**Issue by enguerranws** [gip-inclusion/immersion-facile#955]

**Comment by 3lodi3** [comment]
Done, pour info c'est dans les paramètres Crisp, j'ai créé une page doc notion ici : https://www.notion.so/gip-inclusion/Personnalisation-du-helpdesk-crisp-7758753c28574360ab46dbf33a82317d?pvs=4
