### ISSUE TITLE
Déclaration et activation/désactivation des cookies

### ISSUE THREAD

**Issue by bbohec** [gip-inclusion/immersion-facile#958]
Référencer les divers cookies et capacité d'activer desactiver un cookie

**Comment by nathalie-reyre** [comment]
https://www.cnil.fr/fr/cookies-et-autres-traceurs/regles/cookies/comment-mettre-mon-site-web-en-conformite

**Comment by 3lodi3** [comment]
- [ ] référencement des cookies
- [ ] implémentation du bandeau cookie en front + modification des CGU
