### ISSUE TITLE
ETQ équipe IF je souhaite rapatrier les expérimentations nocode en dur

### ISSUE THREAD

**Issue by 3lodi3** [gip-inclusion/immersion-facile#968]
### :thinking: Contexte et problématique

- [ ] Relance après la mer : rapatrier l'expérimentation nocode en dur dans le dev.

Liste des expés : 
https://www.notion.so/gip-inclusion/Catalogue-des-exp-rimentations-et-prototypes-442c3bea3de64d8e8ea2af6a95bcb3ee?pvs=4

**Comment by nathalie-reyre** [comment]
https://www.notion.so/gip-inclusion/Catalogue-des-exp-rimentations-et-prototypes-442c3bea3de64d8e8ea2af6a95bcb3ee

**Comment by nathalie-reyre** [comment]
1ere à rapatrier est la relance des entreprise pour répondre aux mises en relation

**Comment by clement-duport** [comment]
closed in favor of #1078 and #1079
