### ISSUE TITLE
ETQ candidat je souhaite pouvoir distinguer mes différentes mer

### ISSUE THREAD

**Issue by 3lodi3** [gip-inclusion/immersion-facile#972]
### :thinking: Contexte et problématique (et par qui est-ce remonté ?)

Les candidats ne peuvent pas distinguer les différentes candidatures qu'ils ont faites.
https://discord.com/channels/864451835553513474/1181535358178054214/1181535361101467659

- Le 1er email et les échanges suivants n'apparaissent pas dans une même conversation dans le client mail
- L'objet n'est pas pré-rempli lorsque l'entreprise répond au candidat (bouton répondre du client email ou CTA)

### :tada: Proposition de solution

Si possible : 
~~- Remettre le 1er email dans le reply lorsqu'on répond via le CTA~~
~~- et/ou remplir l'objet du reply : BUSINESS_NAME vous répond au sujet d'une demande d'immersion sur le métier de APPELLATION_LABEL~~
- et/ou remettre dans l'échange d'email (dans le texte en gris ajouté via le serveur) : 

```
##- Veuillez répondre au-dessus de cette ligne -##

Cet email vous a été envoyé via le service Immersion Facilitée, vous pouvez répondre directement à cet email, il sera transmis à votre interlocuteur.

Pour rappel, voici les informations liées à cette mise en relation :

- Candidat : POTENTIAL_BENEFICIARY_FIRST_NAME POTENTIAL_BENEFICIARY_LAST_NAME 
- Métier : APPELLATION_LABEL
- Entreprise : BUSINESS_NAME (BUSINESS_ADDRESS)

-----------------------------
```

**Comment by JeromeBu** [comment]
On va avoir quelque chose comme ça : 

![Image](https://github.com/gip-inclusion/immersion-facile/assets/22095555/1b752110-a515-4041-9142-c068fa4b98e1)
