### ISSUE TITLE
ETQ admin IF, j'ai besoin d'un dashboard pour traiter plus facilement les ajouts/refus de structures prescriptrices

### ISSUE THREAD

**Issue by 3lodi3** [gip-inclusion/immersion-facile#975]
### :thinking: Contexte et problématique

[#732](https://github.com/gip-inclusion/immersion-facile/issues/732)

### :tada: Proposition de solution

Dashboard metabase pour Nathalie pour traiter les ajouts d'agences.

**Comment by nathalie-reyre** [comment]
Proposition de mail de rejet d'une agence 

Objet : rejet de  AGENCY_NAME  comme structure prescriptrice
 
Bonjour,

La demande d'activation  de : AGENCY_NAME  sur Immersion Facilitée comme prescripteur a été refusée pour les raisons suivantes : REASON. 

Pour toute question concernant ce rejet, il est possible de nous contacter : contact@immersion-facile.beta.gouv.fr
Bonne journée,L'équipe Immersion Facilitée |

**Comment by clement-duport** [comment]
- [ ] Ajouter un dashboard pour visualiser les agences en review avec possibilité de filtré par kind 
- [ ] Remplacer le select par un champ input d'id d'agence qui affiche le resumé de l'agence
- [ ] Ajouter une modale dans le cas du refus pour renseigner les justifications
- [ ] Envoyer un mail avec les justification dans le cas du refus
