### ISSUE TITLE
ETQ salarié MILO, j'ai besoin que ma MILO ne soit pas créée en doublon pour avoir accès au bon dashboard IC

### ISSUE THREAD

**Issue by 3lodi3** [gip-inclusion/immersion-facile#976]
### :thinking: Contexte et problématique

#732 

### :tada: Proposition de solution

Pour éviter les doublons : vérifier type + adresse + active : si les deux sont identiques, on refuse la création du doublon et on donne le nom de l'agence identifiée comme doublon à l'utilisateur pour qu'il puisse la retrouver. 
On vérifie : 
- à l'ajout d'une structure, si on crée uns structure en doublon.
- à la modification d'une structure, si on crée un doublon en modifiant une structure existante.

**Comment by celineung** [comment]
@3lodi3 la base de comparaison se fait sur type + adresse ou sur type + adresse + active ?

**Comment by celineung** [comment]
Pour info, doublons actuel en prod: https://metabase.immersion-facile.beta.gouv.fr/question/1426-agences-en-doublons
