### ISSUE TITLE
Offre temporaire Semaine des métiers du numérique

### ISSUE THREAD

**Issue by bbohec** [gip-inclusion/immersion-facile#981]
- [x]  Logo format SVG déposé sur clever
- [x] Text alternatif logo
- [x] Text sous-titre
- [x] Lien vers la page

**Comment by bbohec** [comment]
Composant FixedStamp à modifier dans HomePage.tsx

**Comment by 3lodi3** [comment]
- logo svg : 

![Image](https://github.com/gip-inclusion/immersion-facile/assets/76998405/6befcbf5-da91-4755-a96b-d0834ff3fb39)

- text alt : 
Illustration d'une développeuse informatique

- Text sous-titre : 
Découvrez les métiers du numérique en faisant une immersion en entreprise !

- Lien vers la page : 
https://inclusion.beta.gouv.fr/nos-services/immersion-facilitee/22-26-janvier-2024-semaine-des-metiers-du-numerique/

**Comment by bbohec** [comment]
URL LOGO >>> https://immersion.cellar-c2.services.clever-cloud.com/logo_semaine_du_numerique.svg
