### ISSUE TITLE
ETQ entreprise, je choisis d'accueillir tout public, public scolaire ou tout public sauf scolaire - back

### ISSUE THREAD

**Issue by nathalie-reyre** [gip-inclusion/immersion-facile#990]
### 🚧 : Epic
#1036 

### :thinking: Contexte et problématique

l'annuaire et le moteur de recherche vont être utilisé par 1J/1solution et par les CCI/CMA pour permettre à des publics scolaire ou jeune étudiant de faire des stages de découverte (stage 3" et 2nde et mini stage. Par ailleurs, le ministère de l'Education nationale et le ministère de l'économie ont recensé 200 000 entreprises prêtes à accueillir des jeunes scolarisés. Ces entreprises vont être encouragées à se référencer comme entreprise accueillante via le formulaire hébergé sur 1J/1S qui alimente la base des entreprises accueillantes. 

Il faut permettre à ces entreprises de choisir d'être contactées par le public de leur choix  : 
- soit tout public (IF, 1J/1S CCI/CMA),
- soit uniquement public  scolaire (1J/1 solution et CCI/CMA),
- soit uniquement pour des PMSMP (IF).

### :tada: Proposition de solution

 

- [ ]  back - création du champ/table ad hoc dans la base,
- [ ] back - catégorisation présente dans l'API pour permettre d'appeler le bon type d'entreprises en fonction de l'objectif du site utilisateur de l'AP.

L'idéal serait d'avoir en prod ces solutions fin janv/début février afin d'être en phase avec l'exposition sur 1J/1S.
On peut faire un rattrapage des entreprises déjà enregistrées via un mailing pour les informer et leur préciser que leur choix peut être précisé en mettant à jour leur fiche. En l'absence de mise à jour, les entreprises sont exposées partout.

**Comment by nathalie-reyre** [comment]
Grooming à programmer rapidement. Enjeu pol !

**Comment by 3lodi3** [comment]
https://www.1jeune1solution.gouv.fr/immersions/referencer-mon-entreprise

**Comment by 3lodi3** [comment]
Proposition d'ajout du choix des types de candidats que l'entreprise souhaite recevoir en front : https://www.figma.com/proto/6msAgGCn4id2P3OjI4NRxP/Site---UX-design-1er-semestre-2024?page-id=6%3A303&type=design&node-id=6-1171&viewport=941%2C518%2C0.4&t=tfqnSteuVKVtNF4P-1&scaling=min-zoom&mode=design

En le mettant en front, je trouve que ça brouille le message pour les utilisateurs qui viennent sur notre site : on se présente comme un site facilitant l'immersion et puis dans le form d'inscription on propose aussi des stages pour publics scolaires : les entreprises vont se demander ce que ça implique, où elles vont apparaître etc.

Si c'est possible, est-ce qu'on pourrait ajouter ce choix uniquement en back et les partenaires se débrouillent pour faire un front de leur côté en appelant notre API :
- Si les entreprises s'inscrivent sur 1J1J CCI/CMA -> elles rentrent dans la cat. publics scolaires
- Si les entreprises s'inscrivent sur IF -> elles rentrent dans la cat. immersions

A défaut, s'il faut absolument ajouter le choix en front pour les entreprises, je propose qu'on crée une page distincte pour le moteur de recherche, à reprendre en iframe côté partenaire, sinon on va devoir changer l'intégralité de la page qui ne parle que d'immersion + intégrer un nouveau type de candidat scolaire qui n'a rien à voir avec les candidats immersion, déjà que les utilisateurs sont perdus actuellement...
Par ex on leur fournit ça et c'est tout :
<img width="1440" alt="Capture d’écran 2024-01-17 à 18 24 55" src="https://github.com/gip-inclusion/immersion-facile/assets/76998405/f5c8ea40-b990-4a9e-b49a-7cebbd207bbe">


Sinon, il va falloir très vite s'appeller France Stages 😄 
On en rediscute !

**Comment by nathalie-reyre** [comment]
En réalité, un stage de découverte et une immersion, c'est la même chose.  Le terme d'immersion est tout autant pertinent pour des PMSMP que pour les stages de 3 ou de 2nde que pour les mini stages. La seule différence, c'est le type de convention.  On peut travailler avec 1J/1solution pour expliquer aux entreprises les similitudes et les différences mais l'objectif recherché est bien de faire  croître l'annuaire des **entreprises. accueillantes.** et de les inciter à etre exposées partout , quelque soit le public qui recherche. Si on catégorise d'emblée en fonction de l'origine du référencement, on limite drastiquement le nombre de terrains d'immersion proposés. 
Les mises en relation passent également par nous. 
et oui, un jour on sera sûrement France stages de découverte ou France immersion !

**Comment by nathalie-reyre** [comment]
On ne peut pas proposer de "rechercher mon stage "car c'est la porte ouverte pour des recherches de stage d'application et pour le coup, les entreprises ne se sont pas référencées pour ça (gratification, déclaration Urssaf, encadrement renforcé, tâches à confier ...)

**Comment by 3lodi3** [comment]
Suite à la discussion de ce matin avec @nathalie-reyre voici un petit schéma du parcours attendu 
![Parcours annuaire d'entreprises 1J1S - CCI_CMA - IF - Flow](https://github.com/gip-inclusion/immersion-facile/assets/76998405/56d4b48a-917b-44a1-8c37-c84ade113c66)

Pour le front on ne changerait pour l'instant que le parcours de référencement/modification entreprises qui serait repris tel quel en iframe chez nos partenaires : https://www.figma.com/proto/6msAgGCn4id2P3OjI4NRxP/Site---UX-design-1er-semestre-2024?page-id=6%3A303&type=design&node-id=6-1171&viewport=901%2C343%2C0.16&t=67eiWBeuxvoHMcX4-1&scaling=min-zoom&mode=design

**Comment by enguerranws** [comment]
Récap :
- moteur de recherche :
  - pas de changement front
  - changement back : on ne présente que les entreprises qui accueillent "jobSeekers"
  - API : assignation de préférence de public selon la source (ex: 1jeune1solution)
- MER : rien de prévu pour le moment
